 SELECT
     biview."BOOKING_ID",biview."NAME",biview."CENTER_ID",biview."ACTIVITY_ID",biview."COLOR",biview."START_DATE_TIME",biview."STOP_DATE_TIME",
     biview."CREATION_DATE_TIME",biview."STATE",biview."CLASS_CAPACITY",biview."WAITING_LIST_CAPACITY",biview."CANCEL_DATE_TIME",biview."CANCEL_REASON",
     biview."MAX_CAPACITY_OVERRIDE",biview."MAIN_BOOKING_ID",biview."DESCRIPTION",biview."COMMENT",biview."ETS"
 FROM
     BI_BOOKINGS biview
 WHERE
     biview."ETS" BETWEEN
    CASE
        WHEN $$offset$$=-1
        THEN 0
        ELSE CAST((CURRENT_DATE-$$offset$$-to_date('1-1-1970','MM-DD-YYYY')) AS BIGINT)*24*3600*1000
    END
    AND CAST((CURRENT_DATE+1-to_date('1-1-1970','MM-DD-YYYY'))AS BIGINT)*24*3600*1000    
 union all
 SELECT
 null AS BOOKING_ID,null AS NAME,null AS CENTER_ID,null AS ACTIVITY_ID,null AS COLOR,null AS START_DATE_TIME,null AS STOP_DATE_TIME,null AS CREATION_DATE_TIME,null AS STATE,null AS CLASS_CAPACITY,null AS WAITING_LIST_CAPACITY,null AS CANCEL_DATE_TIME,null AS CANCEL_REASON,null AS MAX_CAPACITY_OVERRIDE,null AS MAIN_BOOKING_ID,null AS DESCRIPTION,null AS "COMMENT",null AS ETS 
