-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT
     ccc.PERSONCENTER || 'p' || ccc.PERSONID AS MEMBER,
     ccc.AMOUNT,
     ccc.STARTDATE,
         ccc.CURRENTSTEP_DATE,
     ccc.CURRENTSTEP,
     CASE ccc.CURRENTSTEP WHEN 0 THEN 'MESSAGE' WHEN 1 THEN 'BLOCK' WHEN 2 THEN 'MESSAGE' WHEN 3 THEN 'MESSAGE' WHEN 4 THEN 
     'WAIT' WHEN 5 THEN 'REMINDER' WHEN 6 THEN 'CASHCOLLECTION' WHEN 7 THEN 'REQUESTBUYOUTANDSTOP' WHEN 8 THEN 'PUSH' ELSE 'Undefined' END AS
     CURRENTSTEP_DESCRIPTION,
         ccc.NEXTSTEP_DATE,
     ccc.NEXTSTEP_TYPE,
     CASE ccc.NEXTSTEP_TYPE WHEN 0 THEN 'MESSAGE' WHEN 1 THEN 'BLOCK' WHEN 2 THEN 'MESSAGE' WHEN 3 THEN 'MESSAGE' WHEN 4 THEN 
     'WAIT' WHEN 5 THEN 'REMINDER' WHEN 6 THEN 'CASHCOLLECTION' WHEN 7 THEN 'REQUESTBUYOUTANDSTOP' WHEN 8 THEN 'PUSH' ELSE 'Undefined' END AS
     NEXSTEP_DESCRIPTION
 FROM
     CASHCOLLECTIONCASES ccc
 WHERE
    /* ccc.closed = 0
 AND ccc.missingpayment = 1
 AND ccc.NEXTSTEP_DATE IS NOT NULL
 AND */ccc.CENTER IN (2004)
