SELECT CENTER, period, SUM ( DEBT ) FROM (

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT , 'before '
|| ADD_MONTHS( :reportDate ,-12)  as period FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 ( AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-12)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION 

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-11)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 ( AR_TRANS.AMOUNT >= 0 OR DUE_DATE < ADD_MONTHS( :reportDate ,-11) )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION 

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-10)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-10) )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION 

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-9)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-9) )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-8)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-8)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-7)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-7)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-6)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-6) )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-5)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-5)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-4) as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-4) )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-3)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-3)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-2)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-2)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,-1)  as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,-1) )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'before '
|| ADD_MONTHS( :reportDate ,0) as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate AND
 (  AR_TRANS.AMOUNT >= 0 OR  DUE_DATE < ADD_MONTHS( :reportDate ,0)  )
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT  , 'after '
|| :reportDate as period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT, 'other' as
period  FROM AR_TRANS , ACCOUNT_RECEIVABLES
WHERE 
 AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 1 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) < 0

) GROUP BY CENTER,period

