SELECT * FROM ( SELECT  ACCOUNT_TRANS.CENTER, ACCOUNT_TRANS.ID, ACCOUNT_TRANS.SUBID ,TRANS_TIME/(24*3600*1000) + TO_DATE('01-01-1970','dd-mm-yyyy ') as BOOKDATE,  ENTRY_TIME/(24*3600*1000) + TO_DATE('01-01-1970','dd-mm-yyyy ') as ENTRYDATE, 
ACCOUNT_TRANS.AMOUNT,  debacc.GLOBALID as DEBITACCOUNT, debacc.EXTERNAL_ID as DEBITACCOUNTID, 
credacc.GLOBALID as CREDITACCOUNT, credacc.EXTERNAL_ID as CREDITACCOUNTID, ACCOUNT_TRANS.TEXT, ACCOUNT_TRANS.EXPORT_FILE , MAIN_TRANSSUBID 
FROM ACCOUNT_TRANS JOIN ACCOUNTS  debacc ON ACCOUNT_TRANS.DEBIT_ACCOUNTCENTER = debacc.CENTER AND ACCOUNT_TRANS.DEBIT_ACCOUNTID = debacc.ID
JOIN ACCOUNTS  credacc ON ACCOUNT_TRANS.CREDIT_ACCOUNTCENTER = credacc.CENTER AND ACCOUNT_TRANS.CREDIT_ACCOUNTID = credacc.ID
WHERE  

/* ### UNCOMMENT THE FOLLOWING LINE TO FILTER BY EXPORT FILE */
 EXPORT_FILE = :export_file

ORDER BY  ACCOUNT_TRANS.CENTER, ACCOUNT_TRANS.ID, ACCOUNT_TRANS.SUBID ) 
/* ### Limitation to avoid getting too many rows */
WHERE ROWNUM  BETWEEN  1 AND 10000
