SELECT * FROM PERSONS P , PERSON_EXT_ATTRS A, ACCOUNT_RECEIVABLES AR 
WHERE 
A.PERSONCENTER = P.CENTER AND A.PERSONID = P.ID  AND P.SEX = 'C' AND 
AR.CUSTOMERCENTER  = P.CENTER AND AR.CUSTOMERID = P.ID  AND 
AR.BALANCE <> 0 AND AR.AR_TYPE = 4 AND
A.NAME = '_eClub_InvoiceSpecification' AND A.TXTVALUE = 'UNSPECIFIED_INVOICES' 
AND P.CENTER < 200
