SELECT CENTER, period, SUM ( DEBT ) FROM (

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT, 'positive Payment AR' as
period  FROM ECLUB2.AR_TRANS , ECLUB2.ACCOUNT_RECEIVABLES
WHERE 
 AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 4 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) > 0

UNION

SELECT ACCOUNT_RECEIVABLES.CUSTOMERCENTER as CENTER,
ACCOUNT_RECEIVABLES.CUSTOMERID as ID  , SUM(AR_TRANS.AMOUNT) as DEBT, 'positive Cash AR' as
period  FROM ECLUB2.AR_TRANS , ECLUB2.ACCOUNT_RECEIVABLES
WHERE 
 AR_TRANS.CENTER =  ACCOUNT_RECEIVABLES.CENTER AND 
AR_TRANS.ID =  ACCOUNT_RECEIVABLES.ID AND 
ACCOUNT_RECEIVABLES.AR_TYPE = 1 AND
TO_DATE('01-01-1970','dd-mm-yyyy') + ENTRY_TIME/(24*3600*1000) <
:reportDate
GROUP BY ACCOUNT_RECEIVABLES.CUSTOMERCENTER, ACCOUNT_RECEIVABLES.CUSTOMERID
HAVING SUM(AR_TRANS.AMOUNT) > 0

) GROUP BY CENTER,period
