SELECT ACT.CENTER, ACT.ID, ACT.SUBID, ART.TEXT,ART.AMOUNT, AR.CUSTOMERCENTER || 'p' || AR.CUSTOMERID as MemberId, '' as Rien FROM ECLUB2.ACCOUNT_TRANS ACT, ECLUB2.AR_TRANS  ART, ECLUB2.ACCOUNT_RECEIVABLES AR
 WHERE ACT.DEBIT_ACCOUNTID = ACT.CREDIT_ACCOUNTID 
 AND ACT.DEBIT_ACCOUNTCENTER = ACT.CREDIT_ACCOUNTCENTER 
AND ACT.TEXT NOT LIKE 'Balance trans%' AND ACT.TEXT NOT LIKE 'Transfer of cred%'
AND ACT.ENTRY_TIME BETWEEN :from
AND :to
AND ACT.CENTER = ART.ACCOUNT_TRANS_CENTER
AND ACT.ID = ART.ACCOUNT_TRANS_ID
AND ACT.SUBID = ART.ACCOUNT_TRANS_SUBID
AND ART.CENTER = AR.CENTER
AND ART.ID = AR.ID
