select CO.NAME as COUNTRY, RE.NAME as REGION, CEST.NAME as CENTER, 
CREATOR.FIRSTNAME || ' ' || CREATOR.LASTNAME || ' (' || CREATOR.CENTER || 'emp'
|| CREATOR.ID || ')' as CREATOR,
OWNER.FIRSTNAME || ' ' || OWNER.LASTNAME || ' (' || OWNER.CENTER || 'p' ||
OWNER.ID || ')' as OWNER,
CASE 
  WHEN Owner.PersonType = 0 THEN 'Private'
   WHEN Owner.PersonType = 1 THEN 'Student'
   WHEN Owner.PersonType = 2 THEN 'Staff'
   WHEN Owner.PersonType = 3 THEN 'Friend'
   WHEN Owner.PersonType = 4 THEN 'Corporate'
   WHEN Owner.PersonType = 5 THEN 'OneManCorporate'
   WHEN Owner.PersonType = 6 THEN 'Family'
   WHEN Owner.PersonType = 7 THEN 'Senior'
END AS OwnerType,
S.CREATION_DATE, 
PST.NAME as SUBSCRIPTION_NAME 
from SUBSCRIPTIONS S 
join SUBSCRIPTIONTYPES ST on S.SUBSCRIPTIONTYPE_CENTER=ST.CENTER and
S.SUBSCRIPTIONTYPE_ID=ST.ID
join CENTERS CEST on ST.CENTER=CEST.ID
join REGIONS RE on CEST.REGION=RE.ID
join COUNTRIES CO on RE.COUNTRY=CO.ID
join PRODUCTS PST on ST.CENTER=PST.CENTER and ST.ID=PST.ID
join EMPLOYEES E on S.CREATOR_CENTER=E.CENTER and S.CREATOR_ID=E.ID
join PERSONS CREATOR on E.PERSONCENTER=CREATOR.CENTER and E.PERSONID=CREATOR.ID
join PERSONS OWNER on S.OWNER_CENTER=OWNER.CENTER and S.OWNER_ID=OWNER.ID
where 
S.START_DATE > S.CREATION_DATE AND
CO.ID =
:country AND

S.CREATION_DATE>= :Minimum AND

S.CREATION_DATE<= :Maximum AND 
S.STATE <> 5 AND
OWNER.STATUS <> 4 AND OWNER.STATUS <> 5 AND 
 (S.CENTER,S.ID) NOT IN 
(select SS.SUBSCRIPTION_CENTER, SS.SUBSCRIPTION_ID 
FROM SUBSCRIPTION_SALES SS 
WHERE 
SALES_DATE >= :Minimum AND

 SALES_DATE <= :Maximum 
)

order by CO.NAME, RE.NAME, CEST.NAME, S.CREATOR_CENTER,
S.CREATOR_ID,S.CREATION_DATE, PST.NAME
