SELECT
    act.TEXT,
    act.CENTER,
    act.AMOUNT + act2.AMOUNT PRICE,
    act.AMOUNT VAT
FROM
    ACCOUNT_TRANS act
JOIN VAT_TYPES vatt
ON
    vatt.CENTER = act.VAT_TYPE_CENTER
    AND vatt.ID = act.VAT_TYPE_ID
LEFT JOIN ACCOUNT_TRANS act2
ON
    act2.CENTER = act.MAIN_TRANSCENTER
    AND act2.id = act.MAIN_TRANSID
    AND act2.SUBID = act.MAIN_TRANSSUBID
LEFT JOIN INVOICELINES invl
ON
    invl.ACCOUNT_TRANS_CENTER = act2.CENTER
    AND invl.ACCOUNT_TRANS_ID = act2.id
    AND invl.ACCOUNT_TRANS_SUBID = act2.SUBID
LEFT JOIN CREDIT_NOTE_LINES cnl
ON
    cnl.ACCOUNT_TRANS_CENTER = act2.CENTER
    AND cnl.ACCOUNT_TRANS_ID = act2.id
    AND cnl.ACCOUNT_TRANS_SUBID = act2.SUBID
WHERE
    ROUND((act2.amount+act.AMOUNT)/act2.amount,2) = 1.17
    AND act.AMOUNT != 0
    AND vatt.GLOBALID = 'vatonsale_17'
    AND act.TRANS_TIME > 1325372400000
    AND act.CENTER IN ( :scope)