select
C.OWNER_CENTER||'p'||C.OWNER_ID as PERSONID,
P.FIRSTNAME as Firstname,
p.LASTNAME as Lastname, 
EMAIL.TXTVALUE as PERSONEMAIL,
mob.TXTVALUE as mobile_phone,
to_char(LONGTODATE(C.VALID_FROM), 'yyyy-MM-dd') as CLIPCARDSTARTDATE,
PRO.NAME as CLIPCARDNAME
from CLIPCARDS C
JOIN PRODUCTS PRO on PRO.CENTER = C.CENTER and PRO.ID = C.ID
join PERSONS P on C.OWNER_CENTER = P.CENTER and C.OWNER_ID = P.ID
left join PERSON_EXT_ATTRS EMAIL ON P.CENTER = EMAIL.PERSONCENTER and P.ID = EMAIL.PERSONID and EMAIL.NAME = '_eClub_Email'
LEFT JOIN PERSON_EXT_ATTRS mob
ON
    P.CENTER = mob.PERSONCENTER
    AND P.ID = mob.PERSONID
    AND mob.NAME = '_eClub_PhoneSMS'
where C.VALID_FROM > DATETOLONG('2013-01-01 00:00')
and C.CANCELLED = 0