SELECT
    DECODE(par.USER_INTERFACE_TYPE, 0,'OTHER', 1,'CLIENT',2,'WEB',3,'KIOSK',4,'SCRIPT','UNKNOWN') AS USER_INTERFACE_TYPE ,
    COUNT(par.BOOKING_CENTER)
FROM
    SATS.PARTICIPATIONS par
WHERE
    par.USER_INTERFACE_TYPE IS NOT NULL
    AND par.CREATION_TIME BETWEEN :fromDate AND :toDate
	and par.center in (:scope)
GROUP BY
    par.USER_INTERFACE_TYPE