SELECT
p.CENTER,
p.ID,
cen.NAME as CENTER,
p.FULLNAME,
p.ADDRESS1,
p.ADDRESS2,
p.ADDRESS3,
p.ZIPCODE, 
longToDate(inv.TRANS_TIME) used_time,
prg.NAME campaign_name,
longToDate(cc.CREATION_TIME) codes_created,
longToDate(prg.STARTTIME) campaign_start_time,
prod.NAME,
invl.TOTAL_AMOUNT,
invl.QUANTITY,
prg.NAME AS "Campaign"
FROM
SATS.INVOICES inv
JOIN SATS.PERSONS p
ON
p.CENTER = inv.PAYER_CENTER
AND p.ID = inv.PAYER_ID
JOIN SATS.INVOICELINES invl
ON
inv.CENTER = invl.CENTER
AND inv.ID = invl.ID
JOIN SATS.PRODUCTS prod
ON
invl.PRODUCTID = prod.ID
AND invl.PRODUCTCENTER = prod.CENTER
JOIN SATS.PRIVILEGE_USAGES pu
ON
pu.TARGET_SERVICE = 'InvoiceLine'
AND pu.PRIVILEGE_TYPE = 'PRODUCT'
AND pu.TARGET_CENTER = invl.CENTER
AND pu.TARGET_ID = invl.ID
AND pu.TARGET_SUBID = invl.SUBID
JOIN SATS.CAMPAIGN_CODES cc
ON
pu.CAMPAIGN_CODE_ID = cc.ID
AND cc.CAMPAIGN_TYPE = 'RECEIVER_GROUP'
JOIN SATS.PRIVILEGE_RECEIVER_GROUPS prg
ON
prg.ID = cc.CAMPAIGN_ID
left join CENTERS cen
on cen.ID = p.CENTER
WHERE
inv.TRANS_TIME BETWEEN :from_date AND :to_date
and cc.CODE = :code
and prod.CENTER in (:scope)