SELECT 'BI2_CRM_TASK' AS EXPORT, count(*) FROM BI2_CRM_TASK WHERE "ETS" is null union all
SELECT 'BI2_PERSON' AS EXPORT, count(*) FROM BI2_PERSON WHERE "ETS" is null union all
SELECT 'BI2_PERSON_EXT_ATTR' AS EXPORT, count(*) FROM BI2_PERSON_EXT_ATTR WHERE "ETS" is null union all
SELECT 'BI2_PERSON_TYPE_LOG' AS EXPORT, count(*) FROM BI2_PERSON_TYPE_LOG WHERE "ETS" is null union all
SELECT 'BI2_ANSWER_SUBMISSION' AS EXPORT, count(*) FROM BI2_ANSWER_SUBMISSION WHERE "ETS" is null union all
SELECT 'BI2_CENTER_EXT_ATTR' AS EXPORT, count(*) FROM BI2_CENTER_EXT_ATTR WHERE "ETS" is null union all
SELECT 'BI2_DEBT_CASE' AS EXPORT, count(*) FROM BI2_DEBT_CASE WHERE "ETS" is null union all
SELECT 'BI2_SUBSCRIPTION_STATE_LOG' AS EXPORT, count(*) FROM BI2_SUBSCRIPTION_STATE_LOG WHERE "ETS" is null union all
SELECT 'BI2_SUBSCRIPTION_CHANGE_LOG' AS EXPORT, count(*) FROM BI2_SUBSCRIPTION_CHANGE_LOG WHERE "ETS" is null union all
SELECT 'BI2_VISIT' AS EXPORT, count(*) FROM BI2_VISIT WHERE "ETS" is null union all
SELECT 'BI2_BOOKING' AS EXPORT, count(*) FROM BI2_BOOKING WHERE "ETS" is null union all
SELECT 'BI2_HOME_CENTER_LOG' AS EXPORT, count(*) FROM BI2_HOME_CENTER_LOG WHERE "ETS" is null union all
SELECT 'BI2_INVENTORY_TRANSACTION_LOG' AS EXPORT, count(*) FROM BI2_INVENTORY_TRANSACTION_LOG WHERE "ETS" is null union all
SELECT 'BI2_MEMBER_STATE_LOG' AS EXPORT, count(*) FROM BI2_MEMBER_STATE_LOG WHERE "ETS" is null union all
SELECT 'BI2_SUBSCRIPTION_ADDON' AS EXPORT, count(*) FROM BI2_SUBSCRIPTION_ADDON WHERE "ETS" is null