
SELECT
    p.CENTER || 'p' ||    p.ID pid,
    DECODE ( p.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') AS PERSONTYPE,
   DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED',8, 'ANONYMIZED', 9, 'CONTACT', 'UNKNOWN') AS STATUS,
   decode(p.SEX,'M','MALE','F','FEMATE','C','COMPANY','UNKNOWN') PERSON_SEX,
   ch.NAME CLEARING_HOUSE,
   chc.CREDITOR_NAME,
   pc.NAME PAYMENT_CYCLE,
   max(pr.REQ_DATE) latest_deduction_date
FROM
    PAYMENT_AGREEMENTS pa
JOIN
    PAYMENT_ACCOUNTS pac
ON
    pac.ACTIVE_AGR_CENTER = pa.CENTER
    AND pac.ACTIVE_AGR_ID = pa.ID
    AND pac.ACTIVE_AGR_SUBID = pa.SUBID
JOIN
    ACCOUNT_RECEIVABLES ar
ON
    ar.CENTER = pac.CENTER
    AND ar.ID = pac.ID
JOIN
    CLEARINGHOUSES ch
ON
    ch.ID = pa.CLEARINGHOUSE
LEFT JOIN
    CLEARINGHOUSE_CREDITORS chc
ON
    chc.CLEARINGHOUSE = ch.ID
    AND chc.CREDITOR_ID = pa.CREDITOR_ID
LEFT JOIN
    PAYMENT_CYCLE_CONFIG pc
ON
    pc.ID = pa.PAYMENT_CYCLE_CONFIG_ID
left join PAYMENT_REQUESTS pr on pr.CENTER = pa.CENTER and pr.ID = pa.ID and pr.AGR_SUBID = pa.SUBID
LEFT JOIN
    PERSONS p
ON
    p.CENTER = ar.CUSTOMERCENTER
    AND p.ID = ar.CUSTOMERID
    where p.STATUS not in (7,8,4)
    and p.CENTER in ($$scope$$)
group by 
   p.CENTER,p.ID,
    p.PERSONTYPE,
   p.STATUS,
   p.SEX,
   ch.NAME,
   chc.CREDITOR_NAME,
   pc.NAME    
  