SELECT
    p.CENTER,
    c.NAME,
    c.COUNTRY,
    COUNT(p.CENTER)
FROM
    PERSONS p
JOIN
    CASHCOLLECTIONCASES cc
ON
    cc.PERSONCENTER = p.CENTER
    AND cc.PERSONID = p.ID
    AND cc.MISSINGPAYMENT = 1
    AND cc.CLOSED = 0
JOIN
    CENTERS c
ON
    c.ID = p.CENTER
WHERE
    p.SEX = 'C'
GROUP BY
    p.CENTER,
    c.NAME,
    c.COUNTRY