WITH
    params AS
    (
        SELECT
            (TRUNC(SYSDATE)-5-to_date('1-1-1970 00:00:00','MM-DD-YYYY HH24:Mi:SS'))*24*3600*1000 AS FROMDATE,
            (TRUNC(SYSDATE)-to_date('1-1-1970 00:00:00','MM-DD-YYYY HH24:Mi:SS'))*24*3600*1000 AS TODATE
        FROM
            dual
    )
SELECT
    sl.SALES_LINE_ID
  , sl.CENTER_ID
  , sl.SALES_TYPE
  , sl.PERSON_ID
  , sl.COMPANY_ID
  , sl.IS_COMPANY
  , sl.SALES_PERSON_ID
  , sl.ENTRY_DATE_TIME
  , sl.BOOK_DATE_TIME
  , sl.PRODUCT_CENTER
  , sl.PRODUCT_ID
  , sl.PRODUCT_NORMAL_PRICE
  , sl.QUANTITY
  , sl.NET_AMOUNT
  , sl.VAT_AMOUNT
  , sl.TOTAL_AMOUNT
  , sl.SPONSOR_LINE_ID
  , sl.GL_DEBIT_ACCOUNT
  , sl.GL_CREDIT_ACCOUNT
  , sl.TTS
  , sl.ETS
FROM
    BI_SALES_Log sl
CROSS JOIN
    PARAMS
WHERE
    sl.CENTER_ID IN ($$scope$$)
    AND sl.ETS >= PARAMS.FROMDATE
    AND sl.ETS < PARAMS.TODATE