Select

PERSONS.CENTER as "Center",
PERSONS.ID as "ID",
PERSONS.FIRSTNAME as "First Name",
PERSONS.LASTNAME as "Last Name" ,
PERSONS.FULLNAME as "Full Name",
PERSONS.CO_NAME as "Company name",
PERSONS.ADDRESS1,
PERSONS.ADDRESS2,
PERSONS.ZIPCODE as "Zipcode", 
PERSONS.CITY as "City",
DECODE (STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED','UNKNOWN') AS PERSON_STATUS,
DECODE (PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') AS PersonType


FROM SATS.PERSONS 


where COUNTRY = 'XX'
and STATUS != 8
