SELECT
    c.ID CLUB_ID,
    c.SHORTNAME,
    c.COUNTRY,
    ch.NAME CLEARING_HOUSE,
    chc.CREDITOR_NAME,
    pcc.NAME payment_cycle,
    pa.NOTIFY_PAYMENT,
    DECODE(p.SEX,'C','COMPANY','PRIVATE') TYPE,
    COUNT(1)
FROM
    PAYMENT_AGREEMENTS pa
JOIN
    PAYMENT_ACCOUNTS pac
ON
    pac.ACTIVE_AGR_CENTER = pa.CENTER
    AND pac.ACTIVE_AGR_ID = pa.ID
    AND pac.ACTIVE_AGR_SUBID = pa.SUBID
JOIN
    CLEARINGHOUSES ch
ON
    ch.ID = pa.CLEARINGHOUSE
JOIN
    CLEARINGHOUSE_CREDITORS chc
ON
    chc.CLEARINGHOUSE = ch.ID
    AND chc.CREDITOR_ID = pa.CREDITOR_ID
JOIN
    PAYMENT_CYCLE_CONFIG pcc
ON
    pcc.ID = pa.PAYMENT_CYCLE_CONFIG_ID
    AND pcc.PAY_REQ_NOTIFICATION_MODE = 'OPTIONAL'
JOIN
    ACCOUNT_RECEIVABLES ar
ON
    ar.CENTER = pac.CENTER
    AND ar.ID = pac.ID
JOIN
    PERSONS p
ON
    p.CENTER = ar.CUSTOMERCENTER
    AND p.ID = ar.CUSTOMERID
JOIN
    CENTERS c
ON
    c.ID = p.CENTER
WHERE
    pa.CENTER NOT IN (148,212)
    --AND pa.CREDITOR_ID in ('AG Elixia Nordic','HFN Norway EFT Person','S.A.T.S Norge Avtale')
    --AND pa.NOTIFY_PAYMENT = 0
    AND p.STATUS IN (0,1,2,3,6,9)
GROUP BY
    c.ID ,
    c.SHORTNAME,
    c.COUNTRY,
    ch.NAME ,
    chc.CREDITOR_NAME,
    pcc.NAME ,
    pa.NOTIFY_PAYMENT,
    DECODE(p.SEX,'C','COMPANY','PRIVATE')
ORDER BY
    c.ID