select CENTER,	ID,	STATE, 	AMOUNT,	PRODUCT_CENTER,	PRODUCT_ID,	INVOICELINE_CENTER,	INVOICELINE_ID,	INVOICELINE_SUBID,	EXPIRATIONDATE,	LongToDate(USE_TIME)

 from GIFT_CARDS where center = :centernr
and id = :id