SELECT
    '-->' TODAY_START
  ,sa.USE_INDIVIDUAL_PRICE
  ,sa.INDIVIDUAL_PRICE_PER_UNIT
  ,'<--' TODAY_END
  ,'FROM SECURE COPY -->' SECURE_COPY_START
  ,i1.ADDON_ID
  , i1.PID
  , i1.SSID
  , i1.PERSONTYPE
  , i1.CENTER_ID
  , i1.SHORTNAME
  , i1.LIST_PRICE_MASTER
  , i1.FROM_DATE
  , i1.TO_DATE
  , i1.MONTHS_BETWEEN
  , i1.PAID_AMOUNT
  , i1.NO_DISCOUNT_AMOUNT
  , i1.SPONSORED_AMOUNT
  , i1.SPONS_NO_DISCOUNT_AMOUNT
  , i1.TOTAL_AMOUNT
  , i1.AMOUNT_EXPLAINED
  , i1.ADDON_NAME
  , i1.SUBSCRIPTION_NAME
  , i1.CALCULATED_MONTHLY_PRICE
  , i1.PRICE_MODIFICATION_NAME
  , i1.PRICE_MODIFICATION_AMOUNT
  , i1.REF_TYPE
  , i1.DISCOUNTED_PRODUCT_GROUP
  , i1.GRANTER_SERVICE
  , i1.GRANTER_DETAILS
  , i1.FINAL_EXPLANATION
FROM
    (
        SELECT
            *
        FROM
            ST_1980_FI
        UNION
        SELECT
            *
        FROM
            ST_1980_NO
        UNION
        SELECT
            *
        FROM
            ST_1980_SE 
)i1
LEFT JOIN
    SUBSCRIPTION_ADDON sa
ON
    sa.ID = i1.addon_id
where i1.CENTER_ID in ($$scope$$)