WITH t AS 
(
   SELECT 
      CAST(dateToLong(TO_CHAR(CURRENT_TIMESTAMP-365*4, 'YYYY-MM-dd HH24:MI')) AS BIGINT) as fouryears_ts,
      CURRENT_TIMESTAMP-365*4 AS fouryears_dt
)
SELECT 
  p.CENTER||'p'||p.ID as Member_ID, 
  p.FULLNAME, 
  CASE  p.persontype  WHEN 0 THEN 'Private'  WHEN 1 THEN 'Student'  WHEN 2 THEN 'Staff'  WHEN 3 THEN 'Friend'  WHEN 4 THEN 'Corporate'  WHEN 5 THEN 'Onemancorporate'  WHEN 6 THEN 'Family'  WHEN 7 THEN 'Senior'  WHEN 8 THEN 'Guest' ELSE 'Unknown' END AS PERSON_TYPE,
  CASE  p.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE'  WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' WHEN 8 THEN  'ANONYMIZED'  WHEN 9 THEN  'CONTACT'  ELSE 'UNKNOWN' END AS PERSON_STATUS,
  art.UNSETTLED_AMOUNT,
  TO_CHAR(longtodate(art.ENTRY_TIME),'YYYY-MM-DD HH24:MI') AS ENTRY_TIME,
  TO_CHAR(longtodate(art.TRANS_TIME),'YYYY-MM-DD HH24:MI') AS TRANS_TIME,
  TO_CHAR(art.DUE_DATE, 'YYYY-MM-DD') As Due_Date, 
  art.STATUS AS PAYMENT_STATUS,
  CASE ar.AR_TYPE WHEN 1 THEN 'Cash' WHEN 4 THEN 'Payment' WHEN 5 THEN 'Debt' WHEN 6 THEN 'installment' END AS ACCOUNT_TYPE
FROM
  t, AR_TRANS art
JOIN
  ACCOUNT_RECEIVABLES ar
ON
  ar.CENTER = art.CENTER AND ar.ID = art.ID 
JOIN
  PERSONS p
ON    
  p.CENTER = ar.CUSTOMERCENTER AND p.ID = ar.CUSTOMERID 
WHERE 
  p.PERSONTYPE <> 4 AND 
  art.STATUS in ('NEW','OPEN') AND
  (art.DUE_DATE < t.fouryears_dt OR art.due_DATE is null ) AND
  art.REF_TYPE in ('INVOICE','ACCOUNT_TRANS') AND
  p.CENTER in (:Scope) AND
  art.ENTRY_TIME < t.fouryears_ts  AND
  art.UNSETTLED_AMOUNT < 0


