-- The extract is extracted from Exerp on 2026-02-08
-- https://clublead.atlassian.net/browse/ST-2477
Lists all company debt that is older than 2 years BUT below 10 000 SEK, 10 000 NOK and 1 000 EUR
-- all corparate debt that is older than 2 years but less then 10.000 SEK, 10.000 NOK or 1000 EUR
WITH t AS 
(
   SELECT 
      CAST(dateToLong(TO_CHAR(CURRENT_TIMESTAMP-365*4, 'YYYY-MM-dd HH24:MI')) AS BIGINT) as fouryears_ts,
      current_timestamp-365*4 AS fouryears_dt
)
SELECT
  Member_ID, FULLNAME, PERSON_TYPE, PERSON_STATUS, SUM(UNSETTLED_AMOUNT) AS TOTAL_DEBT,ACCOUNT_TYPE   
FROM
(
SELECT 
  p.CENTER||'p'||p.ID as Member_ID, 
  p.FULLNAME, 
  CASE  p.persontype  WHEN 4 THEN 'Corporate'  ELSE 'Private' END AS PERSON_TYPE,
  CASE  p.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE'  WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' WHEN 8 THEN  'ANONYMIZED'  WHEN 9 THEN  'CONTACT'  ELSE 'UNKNOWN' END AS PERSON_STATUS,
  art.UNSETTLED_AMOUNT,
  TO_CHAR(longtodate(art.ENTRY_TIME),'YYYY-MM-DD HH24:MI') AS ENTRY_TIME,
  TO_CHAR(longtodate(art.TRANS_TIME),'YYYY-MM-DD HH24:MI') AS TRANS_TIME,
  TO_CHAR(art.DUE_DATE, 'YYYY-MM-DD') As Due_Date, 
  art.STATUS ,
  CASE ar.AR_TYPE WHEN 1 THEN 'Cash' WHEN 4 THEN 'Payment' WHEN 5 THEN 'Debt' WHEN 6 THEN 'installment' END AS ACCOUNT_TYPE,
  CASE c.COUNTRY 
    WHEN 'FI' THEN -1000
  ELSE -10000 END AS MAX_LIMIT
FROM
  t, AR_TRANS art
JOIN
  ACCOUNT_RECEIVABLES ar
ON
  ar.CENTER = art.CENTER AND ar.ID = art.ID 
JOIN
  PERSONS p
ON    
  p.CENTER = ar.CUSTOMERCENTER AND p.ID = ar.CUSTOMERID 
JOIN
  CENTERS c
ON
  p.CENTER = c.ID
WHERE 
  p.PERSONTYPE = 4 AND  
  art.STATUS in ('NEW','OPEN') AND
  (art.DUE_DATE < t.fouryears_dt - 365*4 OR art.due_DATE is null ) AND
  art.REF_TYPE in ('INVOICE','ACCOUNT_TRANS') AND
  p.CENTER in (:Scope) AND
  art.ENTRY_TIME < t.fouryears_ts AND
  art.UNSETTLED_AMOUNT < 0
) t1
GROUP BY Member_ID, FULLNAME, PERSON_TYPE, PERSON_STATUS,ACCOUNT_TYPE 
HAVING SUM(UNSETTLED_AMOUNT) >= AVG(MAX_LIMIT)