-- The extract is extracted from Exerp on 2026-02-08
-- https://clublead.atlassian.net/browse/ST-2477
Lists all positive balances for corporate that are older than 2 years BUT below 10 000 SEK, 10 000 NOK and 1 000 EUR
-- all corparate positive balance that is older than 2 years but less then 10.000 SEK, 10.000 NOK or 1000 EUR
WITH t AS 
(
   SELECT 
      CAST(dateToLong(TO_CHAR(CURRENT_TIMESTAMP-365*4, 'YYYY-MM-dd HH24:MI')) AS BIGINT) as fouryears_ts,
      CURRENT_TIMESTAMP-365*4 AS fouryears_dt
)
SELECT
  Member_ID, FULLNAME, PERSON_TYPE, PERSON_STATUS, ACCOUNT_TYPE, SUM(BALANCE) AS BALANCE
FROM
(
SELECT 
  p.CENTER||'p'||p.ID as Member_ID, 
  p.FULLNAME, 
  CASE  p.persontype  WHEN 4 THEN 'Corporate'  ELSE 'Private' END AS PERSON_TYPE,
  CASE  p.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE'  WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' WHEN 8 THEN  'ANONYMIZED'  WHEN 9 THEN  'CONTACT'  ELSE 'UNKNOWN' END AS PERSON_STATUS,
  ar.BALANCE,
  TO_CHAR(longtodate(ar.LAST_ENTRY_TIME),'YYYY-MM-DD HH24:MI') AS LAST_ENTRY_TIME,
  CASE ar.AR_TYPE WHEN 1 THEN 'Cash' WHEN 4 THEN 'Payment' WHEN 5 THEN 'Debt' WHEN 6 THEN 'installment' END AS ACCOUNT_TYPE,
  CASE c.COUNTRY 
    WHEN 'FI' THEN 1000
  ELSE 10000 END AS MAX_LIMIT
FROM
  t, ACCOUNT_RECEIVABLES ar
JOIN
  PERSONS p
ON    
  p.CENTER = ar.CUSTOMERCENTER AND p.ID = ar.CUSTOMERID 
JOIN
  CENTERS c
ON
  p.CENTER = c.ID
WHERE 
  p.PERSONTYPE = 4 AND  
  ar.BALANCE > 0 AND
  ar.LAST_ENTRY_TIME < t.fouryears_ts  AND
  p.CENTER in (:Scope) 
) t1
GROUP BY Member_ID, FULLNAME, PERSON_TYPE, PERSON_STATUS, ACCOUNT_TYPE
HAVING SUM(BALANCE) <= AVG(MAX_LIMIT)
