select CE.NAME as SALESPERSON_CENTER,
E.CENTER || 'emp' || E.ID as SALESPERSON_ID, 
PE.FIRSTNAME || ' ' || PE.LASTNAME as SALESPERSON, 
CI.NAME as SALES_CENTER, 
TO_DATE('01011970', 'DDMMYYYY') + I.TRANS_TIME/(24*3600*1000) + 1/24 as SALES_DAY,
PP.CENTER || 'p' || PP.ID as CUSTOMER_ID, 
PP.FIRSTNAME || ' ' || PP.LASTNAME as CUSTOMER, 
CP.NAME as CUSTOMER_CENTER,
P.NAME as PRODUCT, 
P.PRICE as PRICE

from INVOICES I 
join INVOICELINES IL on I.CENTER=IL.CENTER and I.ID=IL.ID 
join PRODUCTS P on IL.PRODUCTCENTER=P.CENTER and IL.PRODUCTID=P.ID 
join EMPLOYEES E on I.EMPLOYEE_CENTER=E.CENTER and I.EMPLOYEE_ID=E.ID
join PERSONS PE on E.PERSONCENTER=PE.CENTER and E.PERSONID=PE.ID
join CENTERS CE on PE.CENTER=CE.ID
join CLIPCARDS C on IL.CENTER=C.INVOICELINE_CENTER and IL.ID=C.INVOICELINE_ID and IL.SUBID=C.INVOICELINE_SUBID
join PERSONS PP on C.OWNER_CENTER=PP.CENTER and C.OWNER_ID=PP.ID
join CENTERS CP on PP.CENTER=CP.ID
join CENTERS CI on I.CENTER=CI.ID

where P.PTYPE=4 
and E.CENTER>= :cfrom and 
 e.center <= :cto
and I.TRANS_TIME>=
:From_date
and I.TRANS_TIME<
:To_date_(exclusive)