WITH
        params AS
        (
                SELECT
                        /*+ materialize */
                        TO_DATE('2020-03-26', 'YYYY-MM-dd')   AS CUT_DATE,
                        TO_DATE('2020-05-01', 'YYYY-MM-dd')   AS START_MAY
                FROM
                        DUAL
        )
SELECT 
        s.OWNER_CENTER || 'p' || s.OWNER_ID MEMBER_ID, 
        s.CENTER || 'ss' || s.ID AS SUBSCRIPTION_ID,
        DECODE(s.STATE,2,'Active',3,'Ended',4,'Frozen',7,'Window',8,'Created','Undefined') AS SUBSCRIPTION_STATE,
        TO_CHAR(s.START_DATE,'YYYY-MM-DD') AS SUB_START_DATE,
        TO_CHAR(s.BILLED_UNTIL_DATE,'YYYY-MM-DD') AS SUB_BILLED_UNTIL_DATE,
        TO_CHAR(s.END_DATE,'YYYY-MM-DD') AS SUB_END_DATE,
        TO_CHAR(sa.START_DATE,'YYYY-MM-DD') AS ADDON_START_DATE, 
        TO_CHAR(sa.END_DATE,'YYYY-MM-DD') AS ADDON_END_DATE,
        sa.INDIVIDUAL_PRICE_PER_UNIT  AS ADD_ON_PRICE,
        (CASE
                WHEN s.BILLED_UNTIL_DATE IS NULL THEN 'CANCEL ADDON'
                WHEN s.BILLED_UNTIL_DATE IS NOT NULL AND sa.START_DATE > s.BILLED_UNTIL_DATE THEN 'CANCEL ADDON'
                WHEN sa.END_DATE < SYSDATE THEN 'OLD ADDONS FREECREDIT'
                WHEN sa.END_DATE < PARAMS.START_MAY THEN 'FREECREDIT'
                WHEN sa.START_DATE < PARAMS.START_MAY THEN 'SET END DATE 30/4'    
                ELSE 'INVESTIGATE'
        END) AS TO_DO
FROM SUBSCRIPTIONS s
JOIN CENTERS c
        ON c.ID = s.CENTER AND c.COUNTRY = 'SE'
CROSS JOIN PARAMS
JOIN SUBSCRIPTION_ADDON sa
        ON s.center = sa.SUBSCRIPTION_CENTER AND s.id = sa.SUBSCRIPTION_ID
JOIN MASTERPRODUCTREGISTER mpr
        ON mpr.ID = sa.ADDON_PRODUCT_ID
WHERE       
        mpr.GLOBALID = 'CHILD_CARE_2019'   
        AND (sa.END_DATE IS NULL OR sa.END_DATE >= PARAMS.CUT_DATE)
        AND sa.CANCELLED = 0
        AND sa.USE_INDIVIDUAL_PRICE = 1
AND sa.INDIVIDUAL_PRICE_PER_UNIT > 0