SELECT
        s.CENTER || 'ss' || s.ID AS "Subscription key",
        sa.ID AS "Subscription add-on key",
        s.OWNER_CENTER || 'p' || s.OWNER_ID AS PERSON_ID,
        s.CENTER || 'ss' || s.ID AS SUBSCRIPTION_ID,
        pr.GLOBALID AS SUBSCRIPTION_GLOBAL_ID,       
        (CASE st.ST_TYPE 
                WHEN 0 THEN 'CASH'
                WHEN 1 THEN 'EFT'
        END) AS SUBSCRIPTION_TYPE,
        s.START_DATE AS SUBSCRIPTION_START_DATE,
        s.BILLED_UNTIL_DATE,
        s.END_DATE AS SUBSCRITPION_END_DATE,
        mpr.GLOBALID AS ADDON_GLOBAL_ID,
        (CASE
                WHEN sa.INDIVIDUAL_PRICE_PER_UNIT > 0 THEN 'NO'
                ELSE 'YES'
        END) IS_PRICE_0,
        sa.INDIVIDUAL_PRICE_PER_UNIT AS ADDON_PRICE,
        sa.START_DATE AS ADDON_START_DATE,
        sa.END_DATE AS ADDON_END_DATE,
        --TO_DATE('2020-08-31','YYYY-MM-DD') AS NEW_END_DATE,
        mpr.CACHED_PRODUCTNAME AS ADDON_NAME
FROM
        SATS.SUBSCRIPTIONS s
JOIN
        SATS.CENTERS c
                ON c.ID = s.CENTER
JOIN 
        SATS.SUBSCRIPTIONTYPES st
                ON s.SUBSCRIPTIONTYPE_CENTER = st.CENTER AND s.SUBSCRIPTIONTYPE_ID = st.ID
JOIN 
        SATS.PRODUCTS pr 
                ON pr.CENTER = st.CENTER AND pr.ID = st.ID
JOIN 
        SATS.SUBSCRIPTION_ADDON sa
                ON sa.SUBSCRIPTION_CENTER = s.CENTER AND sa.SUBSCRIPTION_ID = s.ID
JOIN
        SATS.MASTERPRODUCTREGISTER mpr
                ON mpr.ID = sa.ADDON_PRODUCT_ID
WHERE 
		s.CENTER IN (:Scope)
        AND pr.GLOBALID IN ('2CLUB_DAYTIME_BND_GX','2CLUB_DAYTIME_BND_CON','2CLUB_DAYTIME_CASH_CON','2CLUB_DAYTIME_NOBND_CON','2CLUB_DAYTIME_CASH_GX','2CLUB_DAYTIME_NOBND_GX','2CLUB_DAYTIME_BND_FIT','2CLUB_DAYTIME_CASH_FIT','2CLUB_DAYTIME_NOBND_FIT','2CLUB_ALLDAY_BND_GX','2CLUB_ALLDAY_BND_CON','2CLUB_ALLDAY_CASH_CON','2CLUB_ALLDAY_NOBND_CON','2CLUB_ALLDAY_CASH_GX','2CLUB_ALLDAY_NOBND_GX','2CLUB_ALLDAY_BND_FIT','2CLUB_ALLDAY_CASH_FIT','2CLUB_ALLDAY_NOBND_FIT')
        AND (s.END_DATE IS NULL OR s.END_DATE > TO_DATE('2020-08-31','YYYY-MM-DD'))
        AND s.STATE IN (2,4,8)
        --AND c.COUNTRY = 'FI'  
        AND (sa.END_DATE IS NULL OR sa.END_DATE > TO_DATE('2020-08-31','YYYY-MM-DD'))         
        AND sa.CANCELLED = 0
        --AND mpr.GLOBALID IN ('FITNESS_ONE_CLUB','FITNESS_TO_SENTER_KVELD','SATS_CLUB_DOUBLE_AUTOGIRO','SECOND_CLUB_DAYTIME_GRO','SECOND_CLUB_DAYTIME_GRO_1','SECOND_CLUB_DAYTIME_GYM','SECOND_CLUB_DAYTIME_GYM_1','SECOND_CLUB_GROUP_TRAININ','SECOND_CLUB_GROUP_TRAININ_1','SECOND_CLUB_GROUP_TRAININ_2','SECOND_CLUB_GYM_TRAINING','SECOND_CLUB_GYM_TRAINING_')
ORDER BY mpr.CACHED_PRODUCTNAME
        
        