SELECT
    s.OWNER_CENTER||'p'||s.OWNER_ID "Member_ID"
FROM
    SUBSCRIPTIONS s
JOIN
    SUBSCRIPTIONTYPES st
ON
    st.CENTER = s.SUBSCRIPTIONTYPE_CENTER
    AND st.id = s.SUBSCRIPTIONTYPE_ID
WHERE
    st.FREEZEPERIODPRODUCT_CENTER IS NULL
    AND EXISTS (SELECT 1 FROM SUBSCRIPTION_FREEZE_PERIOD sf WHERE sf.SUBSCRIPTION_CENTER = s.CENTER AND sf.SUBSCRIPTION_ID = s.ID AND sf.STATE = 'ACTIVE' AND sf.TYPE = 'CONTRACTUAL' AND s.BILLED_UNTIL_DATE < sf.END_DATE)
