 WITH
     params AS
     (
         SELECT
             cast(datetolongC(TO_CHAR(cast(:date_start as date),'YYYY-MM-DD HH24:MI'),id) as bigint)                                          AS StartDate,
             cast(datetolongC(TO_CHAR(cast(:date_end as date),'YYYY-MM-DD HH24:MI'),id) as bigint) + 86400 * 1000 -1          AS EndDate,
             id                                                                                                  AS center
         FROM
             CENTERS
     )
 SELECT
     pp.NAME   AS "Product Name",
     pp.ID     AS "Product ID",
     pp.CENTER AS "Product Center",
     invl.QUANTITY "Quanity sold",
     invl.TOTAL_AMOUNT "Product price",
     (
         CASE
             WHEN p.SEX = 'C'
             THEN invl.PERSON_CENTER||'p'||invl.PERSON_ID
             ELSE NULL
         END) AS "CompanyID",
     (
         CASE
             WHEN p.SEX != 'C'
             THEN invl.PERSON_CENTER||'p'||invl.PERSON_ID
             ELSE NULL
         END) AS "PayerID",
     (
         CASE
             WHEN p.SEX = 'C'
             THEN p.LASTNAME
             ELSE NULL
         END)                   AS "Companyname",
     longtodateC(inv.TRANS_TIME, inv.center) AS "invoice_date"
 FROM
     PRODUCTS pp
 JOIN
     INVOICE_LINES_MT invl
 ON
     invl.PRODUCTCENTER = pp.center
     AND invl.productid = pp.ID
 JOIN
     PERSONS p
 ON
     invl.PERSON_CENTER =p.CENTER
     AND invl.PERSON_ID = p.ID
 JOIN
     INVOICES inv
 ON
     invl.center = inv.center
     AND invl.ID = inv.ID
 JOIN
     PARAMS
 ON
     PARAMS.center = inv.center
 WHERE
   (EXISTS
             (
                 SELECT
                     1
                 FROM
                     PRODUCT_AND_PRODUCT_GROUP_LINK prlink,
                     product_group pg
                 WHERE
                     prlink.PRODUCT_CENTER = pp.center
                     AND prlink.product_id = pp.id
                     AND prlink.product_group_id = pg.id
                     AND pg.name IN ('Corporate report EC-1085'))
     OR
     (pp.GLOBALID IN ('PTDUO60_LEVEL_3_10_CLIPS', 'PTDUO60_LEVEL_1_1_CLIP', 'PT60_LEVEL_2_10_CLIPS', 'PTDUO60_LEVEL_4_50_CLIPS', 'PT60_LEVEL_2_1_CLIP_HK', 'PT60_LEVEL_3_3_CLIPS', 'PT60LEVEL1_1_CLIP_HK', 'PT30LEVEL1_1_CLIP_HK', 'PT30LEVEL3_24_CLIPS', 'PT60LEVEL4_8_CLIPS', 'RENT_OF_GYM_INVASIVE_2', 'PT30_LEVEL_5_25_CLIPS', 'PTDUO60_LEVEL5_25_CLIPS', 'PT60_LEVEL5_1_CLIP', 'TEAMSPORT', 'SMALL_GROUP_LEVEL_4_FREE_CLIPS', 'RENT_STUDIO_CORPMEMBER', 'PT60LEVEL4_MONTHLY', 'PT60LEVEL2_MONTHLY', 'PT60LEVEL1_3_CLIPS_FREE_', 'CORPORATE_ONELINE_TRAINING_4', 'FÖRETAGSKLASS_ONLINE_2', 'CORPORATE_LIVESTREAM_1', 'REHAB_FOOT_6_CLIPS', 'PTDUO60_LEVEL_4_10_CLIPS', 'PT60_LEVEL_3_1_CLIP_HK', 'PT30_LEVEL_2_50_CLIPS', 'PT30_LEVEL_2_3_CLIPS', 'PT30_LEVEL_1_10_CLIPS', 'PT30_LEVEL_3_1_CLIP', 'PT60_DUO_LEVEL2_1_CLIP_FREE', 'PT30_LEVEL_1_3_CLIPS', 'PT30_LEVEL_1_25_CLIPS', 'SMALL_GROUP_PT_LEVEL_1', 'PT60_LEVEL_1_25_CLIPS', 'PT60_LEVEL_3_50_CLIPS', 'PRGROUPLEVEL2_NEW', 'PT60_LEVEL_5_25_CLIPS', 'PTDUO60_LEVEL5_1_CLIP', 'PT30LEVEL3_1_CLIP_HK', 'SMALL_GROUP_LEVEL_3_FREE_CLIPS', 'PT30CAMPAIGNLEVEL3', 'PTDUO60CAMPAIGNLEVEL4', 'PT60LEVEL3_LOYALTY_CLIP', 'SAMARBETSAVTAL_3_ONLINE', 'SAMARBETSAVTAL_4_ONLINE', 'PT60LEVEL2_3_CLIPS_FREE', 'PT60LEVEL2_3_CLIPS_FREE_', 'CORPORATE_LIVESTREAM_4', 'WAKEUP_ONLINE_3', 'CORPORATE_ONELINE_TRAINING_1', 'CORPORATE_LIVESTREAM_2', 'GRUPPTRNING_5000_KR', 'PT60_LEVEL_4_1_CLIP_HK', 'PT30_LEVEL_4_25_CLIPS', 'PTDUO60_LEVEL_3_50_CLIPS', 'PT30_LEVEL_4_1_CLIP', 'PTDUO60_LEVEL_4_25_CLIPS', 'PT60_LEVEL_4_10_CLIPS', 'PT30_LEVEL_3_10_CLIPS', 'PT30_LEVEL2_1_CLIP', 'PT60LEVEL2_16_CLIPS', 'PT60_LEVEL_5_50_CLIPS', 'PTGROUPLEVEL5_NEW', 'PT60LEVEL3_MONTHLY', 'PT60CAMPAIGNLEVEL5', 'PT30CAMPAIGNLEVEL2', 'PT60LEVEL2_LOYALTY_CLIP', 'SAMARBETSAVTAL_1_ONLINE', 'CORPORATE_TRAINER_PILOT_3MND', 'CORPORATE_TRAINER_PILOT_10MND', 'CORPORATE_ONELINE_TRAINING_2', 'WAKEUP_ONLINE_2', 'WAKEUP_ONLINE_4', 'REHAB_KLIPP_1_0KR', 'PRIS_MED_LILLA_PAKETET_4000', 'PT60_LEVEL_4_1_CLIP', 'PTDUO60_LEVEL_4_3_CLIPS', 'PT60_LEVEL_4_3_CLIPS', 'PT60_LEVEL_1_50_CLIPS', 'SMALL_GROUP_PT_LEVEL_4', 'PT60_LEVEL2_10_CLIPS_FREE', 'PT60_LEVEL4_10_CLIPS_FREE', 'PT60_LEVEL3_10_CLIPS_FREE', 'PT30_LEVEL_5_10_CLIPS', 'PT_60_LEVEL_5_3_CLIPS', 'SMALL_GROUP_LEVEL_1_FREE_CLIPS', 'PTDUO60CAMPAIGNLEVEL3', 'PT30CAMPAIGNLEVEL5', 'PTDUO60CAMPAIGNLEVEL1', 'PT60LEVEL1_LOYALTY_CLIP', 'PT60LEVEL4_FOOD_COUNSELING', 'SAMARBETSAVTAL_6_ONLINE', 'SAMARBETSAVTAL_2_ONLINE', 'PT60LEVEL4_3_CLIPS_FREE', 'CORPORATE_LIVESTREAM_3', 'CORPORATE_ONELINE_TRAINING_5', 'REHAB_KIG_3_CLIPS', 'REHAB_POST_REHAB_10_CLIPS', 'REHAB_20_CLIPS', 'PTDUO60_LEVEL_2_1_CLIP', 'PT60_LEVEL_3_25_CLIPS', 'PTDUO60_LEVEL_2_3_CLIPS', 'PTDUO60_LEVEL_1_50_CLIPS', 'PT60_LEVEL_4_50_CLIPS', 'PT60_LEVEL_2_1_CLIP', 'PT30_LEVEL_3_50_CLIPS', 'SMALL_GROUP_PT_LEVEL_3', 'PT30_LEVEL_1_1_CLIP', 'PTDUO60_LEVEL_1_25_CLIPS', 'PT30_LEVEL_4_50_CLIPS', 'PT30_LEVEL_3_25_CLIPS', 'PT60_LEVEL_2_50_CLIPS', 'PT30LEVEL3_48_CLIPS', 'PT30LEVEL1_24_CLIPS', 'RENT_GXSTUDIO_W_INSTR_PRIVATE', 'PTDUO_LEVEL5_50_CLIPS', 'PTDUO60_LEVEL5_3_CLIPS', 'PRGROUPLEVEL1_NEW', 'PRGROUPLEVEL3_NEW', 'TEAMSPORT_360', 'SMALL_GROUP_LEVEL_5_FREE_CLIPS', 'PT60CAMPAIGNLEVEL4', 'PT60LEVEL4_LOYALTY_CLIP', 'SAMARBETSAVTAL_KLASS', 'WAKEUP_ONLINE_1', 'RENT_STUDIO_CORPNOMEMBER', 'PRIS_MED_MELLANSTORA_PAKETET', 'PT60_LEVEL_1_1_CLIP', 'PT30_LEVEL_3_3_CLIPS', 'PT30_LEVEL_2_1_CLIP', 'PTDUO60_LEVEL_3_1_CLIP', 'PT60_LEVEL_1_3_CLIPS', 'PT30_LEVEL_4_10_CLIPS', 'PTDUO60_LEVEL_2_25_CLIPS', 'PT60_LEVEL_3_1_CLIP', 'PT30_LEVEL_2_10_CLIPS', 'PT30_LEVEL_2_25_CLIPS', 'PT60DUO_LEVEL3_1_CLIP_FREE', 'PTDUO60_LEVEL_2_10_CLIPS', 'PT60DUO_LEVEL4_1_CLIP_FREE', 'PT30_LEVEL_1_50_CLIPS', 'PT60DUO_LEVEL_1_1CLIP_FREE', 'HYRA_AV_SAL', 'PT60LEVEL4_16_CLIPS', 'PT60LEVEL2_8_CLIPS', 'PT30LEVEL4_24_CLIPS', 'RENT_PART_OF_GYM_NON_INVASIVE', 'PTGROUPLEVEL4_NEW', 'SMALL_GROUP_LEVEL_2_FREE_CLIPS', 'PT60LEVEL1_MONTHLY', 'SATS_CORPORATE_GX4', 'SAMARBETSAVTAL_5_ONLINE', 'PT60LEVEL3_3_CLIPS_FREE', 'FÖRETAGSKLASS_ONLINE_4', '10_GRUPPTRANINGAR_FRISKVARD', 'PTDUO60_LEVEL_1_3_CLIPS', 'PT30LEVEL4_1_CLIP_HK', 'SMALL_GROUP_PT_LEVEL_2', 'PT60_LEVEL_4_25_CLIPS', 'PTDUO60_LEVEL_3_25_CLIPS', 'PTDUO60_LEVEL_1_10_CLIPS', 'PT30LEVEL1_48_CLIPS', 'PT30LEVEL2_48_CLIPS', 'PT30LEVEL2_24_CLIPS', 'PT30LEVEL4_48_CLIPS', 'RENT_PART_OF_GYM_INVASIVE', 'PT30_LEVEL5_1_CLIP', 'BOOTCAMP2', 'PT30CAMPAIGNLEVEL1', 'PT60CAMPAIGNLEVEL1', 'SATS_CORPORATE_GX2', 'PTDUO60CAMPAIGNLEVEL2', 'PT30LEVEL4_FOOD_COUNSELING', 'SAMARBETSAVTAL_FORELASNING', 'PT60LEVEL5_MONTHLY', 'CORPORATE_TRAINER_PILOT_6MND', 'CORPORATE_LIVESTREAM_5', 'FÖRETAGSKLASS_ONLINE_3', 'CORPORATE_ONELINE_TRAINING_3', 'WAKEUP_ONLINE_5', 'REHAB_1_CLIP', 'PTDUO60_LEVEL_2_50_CLIPS', 'PT60_LEVEL_2_3_CLIPS', 'PTDUO60_LEVEL_3_3_CLIPS', 'PTDUO60_LEVEL_4_1_CLIP', 'PT60_LEVEL_1_10_CLIPS', 'PT60_LEVEL_3_10_CLIPS', 'PT60_LEVEL_2_25_CLIPS', 'PT30_LEVEL_4_3_CLIPS', 'PT60LEVEL3_8_CLIPS', 'PT60LEVEL3_16_CLIPS', 'RENT_OF_GYM_NON_INVASIVE_2', 'PTDUO60_LEVEL5_10_CLIPS', 'PT30_LEVEL_5_50_CLIPS', 'PT_60_LEVEL_5_10_CLIPS', 'PT60_LEVEL_5_1_CLIP_HK', 'PT30CAMPAIGNLEVEL4', 'PT60CAMPAIGNLEVEL2', 'PT60CAMPAIGNLEVEL3', 'PTDUO60CAMPAIGNLEVEL5', 'SATS_CORPORATE_GX1', 'SATS_CORPORATE_GX3', 'SAMARBETSAVTAL_WAKE_UP', 'FÖRETAGSKLASS_ONLINE_1', 'RENT_GXSTUDIO_NO_INSTR_PRIVATE')))
 AND pp.CENTER in(:scope)
 AND inv.TRANS_TIME BETWEEN PARAMS.StartDate AND PARAMS.EndDate
