SELECT
    s.owner_center || 'p'|| s.owner_ID AS member,
    p.EXTERNAL_ID,
    s.owner_center                                  AS MEMBER_CENTER,
    sfp.start_date                                  AS FREEZE_START_DATE,
    sfp.END_DATE                                    AS FREEZE_END_DATE,
    sfp.TEXT                                        AS FREEZE_REASON_CURRENT,
    sfp.EMPLOYEE_CENTER || 'emp' || sfp.employee_id AS APPLIED_BY,
    c.country
FROM
    SUBSCRIPTION_FREEZE_PERIOD sfp
JOIN
    centers c
ON
    c.id = sfp.SUBSCRIPTION_CENTER
JOIN
    subscriptions s
ON
    s.id = sfp.SUBSCRIPTION_ID
AND s.center = sfp.SUBSCRIPTION_CENTER
JOIN
  persons p
ON
    p.center = s.owner_center
AND p.id = s.owner_id
AND sfp.text IN ('Club renovation',
                 '(EC-1417) COVID19 Lockdown',
                 'Caovid-19 frys',
                 'Corona-19',
                 'Covid -19 (EC - 1012)',
                 'Covid -19 (EC - 1013)',
                 'Covid -19 (EC - 1014)',
                 'Covid -19 (EC - 1056)',
                 'Covid -19 (EC - 1057)',
                 'Covid -19 (EC - 1069)',
                 'Covid -19 (EC - 1070)',
                 'Covid -19 (EC - 1352)',
                 'Covid -19 (EC - 1353)',
                 'Covid -19 (EC - 1417)',
                 'Covid -19 (EC - 650)',
                 'Covid -19 (EC-1186)',
                 'Covid -19 (EC-1207)',
                 'Covid -19 (EC-1232)',
                 'Covid -19 (EC-1344)',
                 'Covid -19 (EC-1399)',
                 'Covid -19 (EC-1495)',
                 'Covid-10 freeze',
                 'Covid-19',
                 'COVID19 (ST-13806)',
                 'Covid-19 (ST-13806)',
                 'Covid-19 freeze',
                 'Covid-19- freeze',
                 'Covid-19 frys',
                 'COVID-19 measures (EC-755)',
                 'COVID-19 measures (EC-776)',
                 'COVID-19 measures (ST-11299)',
                 'COVID-19 measures (ST-11562)',
                 'Covid-19(EC-1002)',
                 'Covid-19(EC-1187)',
                 'Covid-19(EC-1195)',
                 'Covid-19(EC-1220)',
                 'Covid-19(EC-1237)',
                 'Covid-19(EC-1254)',
                 'Covid-19(EC-1370)',
                 'Covid-19(EC-1417)',
                 'Covid-19(EC-1491)',
                 'Covid-19(EC-867)',
                 'Covid-19(EC-894)',
                 'Covid-19(EC-895)',
                 'korona',
                 'ovid-19 freeze',
                 'FF frys',
                 'Frys via epost',
                 'Fryst via epost (Nina Johansen)',
                 'jääd',
                 'Jäädytys',
                 'jäädytys (poikkeus)',
                 'jäädytys 2kk',
                 'jäädytys/digi',
                 'Jäädytys/dok ok',
                 'jäädytys/ok',
                 'jäädytys-dok ok',
                 'Jäädytys-dok.ok',
                 'Jäädytys-muutto Kanada',
                 'Jäädytys-opiskelut Norjassa-dok.ok',
                 'tak jäädytys',
                 'Illness/injury',
                 'Kritisk sygdom',
                 'Sjukdom/Skada',
                 'Sykdom eller skade',
                 'Sykdom/skade',
                 '-',
                 '.',
                 'al',
                 'Annet',
                 'army',
                 'Bero ordinær',
                 'BLOCKED',
                 'dok ok',
                 'Dok ok, viivi',
                 'Fejlrettelse',
                 'Loyalty program',
                 'Mi',
                 'No binding',
                 'OK',
                 'Ok.',
                 'Resa',
                 'ST-13857',
                 'Varusmiespalvelus',
                 'Graviditet',
                 'Komplikationer ved graviditet',
                 'Raskaus',
                 'Raskaus T. Ainu',
                 'Svangerskap',
                 'Save desk',
                 'Save desk freeze',
                 'Save desk frys',
                 'Savedesk',
                 'Savedesk bero',
                 'Savedesk freeze',
                 'Savedesk frys',
                 'Savesesk frys',
                 'pensjonist bor i utlandet',
                 'Senior',
                 'Arbete på annan ort',
                 'Armeija alkaa 6.7.2020, dokumentti palveluunastumismääräyksestä näytetty.',
                 'Armeijassa',
                 'Armeijassa.',
                 'E student i Harstad.',
                 'Førstegangstjeneste',
                 'militæret.',
                 'Militärtjänstgöring',
                 'Posted for work or study',
                 'Studerer',
                 'Studier på annan ort',
                 'työkomennus ulkomailla!',
                 'Utstasjonering',
                 'Arbetslös' )
ORDER BY
    s.owner_center || 'p'|| s.owner_ID, c.country