SELECT cc.* , TO_DATE('01-01-1970','dd-mm-yyyy') + TRANSTIME/(24*3600*1000) + 1/24 as TRANS_TIME , CE.external_id
FROM CREDITCARDTRANSACTIONS CC
join CENTERS CE on cc.CENTER=CE.ID
WHERE 
cc.TRANSTIME BETWEEN  :from AND 
:to
AND cc.CENTER BETWEEN :FromCenter AND :ToCenter