SELECT 
p.CENTER||'p'||p.ID  AS "MEMBERID",
CASE p.STATUS WHEN 0 THEN 'LEAD' WHEN 1 THEN 'ACTIVE' WHEN 2 THEN 'INACTIVE' WHEN 3 THEN 'TEMPORARYINACTIVE' WHEN 4 THEN 'TRANSFERRED' WHEN 5 THEN 'DUPLICATE' WHEN 6 THEN 'PROSPECT' WHEN 7 THEN 'DELETED' WHEN 8 THEN 'ANONYMIZED' WHEN 9 THEN 'CONTACT' ELSE 'Undefined' END AS PERSON_STATUS,
p.last_active_end_date
 FROM persons p 
WHERE p.blacklisted = 1
AND p.last_active_end_date <= CURRENT_DATE - INTERVAL '5' YEAR
AND p.CENTER in (:Scope)
and p.status NOT IN (4,5,8)