-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 
    center,
    name,
    price,
    requiredrole,
    globalid,
    primary_product_group_id,
    CASE 
        WHEN p.center >= 700 THEN 'Portugal'
        ELSE 'Spain'
    END AS country,
    CASE p.requiredrole
        WHEN '5868'  THEN 'old product access'
        WHEN '8673'  THEN 'Sell Staff Subscriptions'
        WHEN '4250'  THEN 'Admin support'
        WHEN '3243'  THEN 'HQ ATC'
        WHEN '11284' THEN 'MKT Offeer'
        WHEN '11283' THEN 'Assign invitations with permissions'
        WHEN '539'   THEN 'Exerp'
        WHEN '7269'  THEN 'ExtAtt_Gympass'
        WHEN '4251'  THEN 'Sales Secretary'
        WHEN '14498' THEN 'Join Journey Visibility'
        ELSE p.requiredrole::text
    END AS requiredrole_match,
    CASE p.product_account_config_id
        WHEN '4404' THEN 'Seguro de accidentes add-on'
        WHEN '1'    THEN 'Subscription DD'
        WHEN '1001' THEN 'Joining Fee SP'
        WHEN '4401' THEN 'Subscription ONE'
        WHEN '4601' THEN 'Subscription FLEX'
        WHEN '4801' THEN 'Subscription PRIME'
        WHEN '201'  THEN 'Subscriptions Cash'
        WHEN '601'  THEN 'Subscripciones mensuales'
        WHEN '602'  THEN 'Subscripciones prepago 6 M'
        WHEN '603'  THEN 'Freezers'
        WHEN '604'  THEN 'Pase de día'
        WHEN '605'  THEN 'Seguro de accidentes'
        WHEN '801'  THEN 'Subscripciones prepago 3 M'
        WHEN '802'  THEN 'Subscripciones prepago 12 M'
        WHEN '803'  THEN 'Merchandising SP'
        WHEN '1002' THEN 'Taquillas'
        WHEN '1201' THEN 'Subscripciones Premium'
        WHEN '1401' THEN 'Cargos de devolución'
        WHEN '1402' THEN 'Otros servicios'
        WHEN '1601' THEN 'Clipcards - Personal Training'
        WHEN '1801' THEN 'Servicios de Personal Training'
        WHEN '2001' THEN 'Rejeição DD'
        WHEN '2201' THEN 'Clipcards'
        WHEN '2401' THEN 'Bring a friend'
        WHEN '2601' THEN 'Merchandising PT'
        WHEN '2801' THEN 'Yanga'
        WHEN '3001' THEN 'Candados Alquiler'
        WHEN '3201' THEN 'Yanga - Clipcard'
        WHEN '3401' THEN 'Otros Servicios (add-on)'
        WHEN '3601' THEN 'Ingresos cambio subscripcion'
        WHEN '3802' THEN 'Subscripcion Platino'
        WHEN '3803' THEN 'Subscripcion Zone'
        WHEN '4001' THEN 'Drink'
        WHEN '4201' THEN 'Subscripcion Club'
        WHEN '4202' THEN 'Subscripcion Iberia'
        WHEN '4402' THEN 'LevelUp Sesiones'
        WHEN '4403' THEN 'Passaporte Canarias'
        WHEN '4602' THEN 'Vivabox'
        WHEN '4802' THEN 'Cuota Boxeo Senior'
        WHEN '4803' THEN 'One Experience Plus'
        WHEN '4804' THEN 'PT EXPERIENCE'
        WHEN '5001' THEN 'Cuota Boxeo Junior'
        WHEN '5002' THEN 'Passaporte 200'
        WHEN '5201' THEN 'Joining Fee Boxeo'
        WHEN '5202' THEN 'PT Sesiones'
        WHEN '5401' THEN 'Parking'
        WHEN '5601' THEN 'PT Basic'
        WHEN '5801' THEN 'PT Basic Service'
        WHEN '6001' THEN 'Squash'
        WHEN '6002' THEN '7 Days passes'
        WHEN '6201' THEN 'Subscripcion One <18'
        WHEN '6401' THEN 'Subscripcion One Disc'
        WHEN '6601' THEN 'Subscripcion One +65'
        WHEN '6801' THEN 'Taquillas - Service'
        WHEN '7001' THEN 'Drink Pack'
		WHEN '7201' THEN 'Merchandising Boxeo'
        WHEN '7401' THEN 'Boxer - King of the ring'
        WHEN '7601' THEN 'Boxer - Padwork Boxing'
		WHEN '7801' THEN 'Freezer Bocer (INC)'
		WHEN '8003' THEN 'Boxer - ADDON HIIT 2Días (INC)'
		WHEN '8201' THEN 'Boxer - Cuota Adulto Ilim (INC)'
		WHEN '8401' THEN 'Boxer - Cuota Adulto 2d (INC)'
		WHEN '8402' THEN 'Pasaporte Algarve'
		WHEN '8601' THEN 'Boxer - Cuota Junior (INC)'
		WHEN '8602' THEN 'Boxer - Cuota HIIT 2Días (INC)'
		WHEN '8801' THEN 'Boxer - Cuota HIIT 3Días (INC)'
		WHEN '9001' THEN 'Boxer - ADDON HIIT 3Días (INC)'
		WHEN '9201' THEN 'Boxer - Daypass'
		WHEN '9401' THEN 'Drink'
		WHEN '10001' THEN 'Pro-rata Cuota Iberia (INC)'
		WHEN '10001' THEN 'Pro-rata Cuota Iberia (INC)'
		WHEN '10201' THEN 'Pro-rata Cuota ONE (INC)'
		WHEN '10401' THEN 'Pro-rata Cuota FLEX (INC)'
		WHEN '10402' THEN 'Pro-rata Cuota PRIME (INC)'
		WHEN '9601' THEN 'Pro-rata Cuota Club (INC)'
		WHEN '9801' THEN 'Pro-rata Cuota Zone (INC)'
		WHEN '8002' THEN 'Pro-rata Cuota BoxerKid (INC)'
		WHEN '10404' THEN 'Pro-rata Cuota Platino (INC)'
		WHEN '10403' THEN 'Pro-rata Cuota Premium (INC)'
		WHEN '9402' THEN 'Pro-rata Cuota Montlhy (INC)'
		WHEN '8001' THEN 'Pro-rata Cuota BoxerClub (INC)'
		WHEN '10601' THEN 'Pro-rata Cuota Adulto Boxing (INC)'
		WHEN '10801' THEN 'Pro-rata Cuota HIIT Boxing (INC)'
		WHEN '9802' THEN 'Pro-rata Cuota Junior Boxing (INC)'
        ELSE p.product_account_config_id::text
    END AS product_account_config_match
FROM products AS p
ORDER BY p.center, p.name;
