SELECT (CURRENT_DATE - INTERVAL '4 months') AS FECHA_LIMITE_ACTUAL, P.LAST_ACTIVE_START_DATE, P.EXTERNAL_ID, P.CURRENT_PERSON_CENTER, P.STATUS, P.MEMBER_STATUS
FROM PERSONS P
WHERE P.CURRENT_PERSON_CENTER >= 700
  AND P.LAST_ACTIVE_START_DATE <= (CURRENT_DATE - INTERVAL '4 months')
  AND P.LAST_ACTIVE_START_DATE > (CURRENT_DATE - INTERVAL '12 months')
--  AND P.CURRENT_PERSON_CENTER IN (112,108)
--  AND P.CURRENT_PERSON_CENTER IN (
--    SELECT center
--    FROM products
--    WHERE globalid IN (
      --'CL_ONE_EXEPRIENCE'
      --'CL_ONE_EXPERIENCE_PLUS',
      --'CL_ONE_EXPERIENCE',
--      'CL_ONE_EXPERIENCE_PLUS_PT'
--      )
--      AND blocked = false
--      AND show_on_web = true
--)

  AND P.STATUS = 1;

--  AND P.STATUS = 2
--  AND P.EXTERNAL_ID = '100284459';