SELECT 
s.CENTER as "CENTERID",
s.OWNER_CENTER ||'p'|| s.OWNER_ID AS "PERSONKEY",
s.CENTER ||'ss'||s.ID as "SUBSCRIPTIONKEY",
s.START_DATE,
s.END_DATE,
CASE s.STATE
	WHEN 2 THEN 'ACTIVE'
	WHEN 3 THEN 'ENDED'
	WHEN 4 THEN 'FROZEN'
	WHEN 7 THEN 'WINDOW' 
	WHEN 8 THEN 'CREATED'
	ELSE 'OTHER'
END AS "SUBSCRIPTION STATE",
s.SUB_COMMENT AS "Legacy name",
PR.NAME AS "Exerp name",
s.subscription_price as "Price",
PR.GLOBALID


FROM 
SUBSCRIPTIONS s
JOIN
PRODUCTS PR
ON
S.SUBSCRIPTIONTYPE_ID = PR.ID
AND
S.SUBSCRIPTIONTYPE_CENTER = PR.CENTER
-- AND 
-- S.STATE in (2,4)
AND
(s.OWNER_CENTER,S.OWNER_ID) IN (:Members)

