-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
    SU.CENTER AS SU_CENTER,
    PR.GLOBALID AS PR_GLOBALID,
    MPR.CACHED_PRODUCTNAME AS PR_GLOBAL_NAME,
    PR.NAME AS PR_LOCAL_NAME,
    DECODE(ST.ST_TYPE, 0, 'CASH', 1, 'DD', 'ERROR') AS ST_ST_TYPE,
    ST.BINDINGPERIODCOUNT BindingPeriod,
    DECODE(ST.PERIODUNIT, 0, 'WEEK', 1, 'DAY', 2, 'MONTH', 3, 'YEAR', 'ERROR') BindingUnit,
    TO_CHAR(SU.START_DATE, 'YYYY-MM-DD') START_DATE,
    COUNT(*) ACTIVATED
FROM
    SUBSCRIPTIONS SU
INNER JOIN
    SUBSCRIPTIONTYPES ST
ON
    (
        SU.SUBSCRIPTIONTYPE_CENTER = ST.CENTER
        AND SU.SUBSCRIPTIONTYPE_ID = ST.ID )
INNER JOIN
    PRODUCTS PR
ON
    (
        ST.CENTER = PR.CENTER
        AND ST.ID = PR.ID )
INNER JOIN
    HP.MASTERPRODUCTREGISTER MPR
ON
    PR.GLOBALID = MPR.GLOBALID
    AND MPR.DEFINITION_KEY = MPR.ID
INNER JOIN
    STATE_CHANGE_LOG SCL1
ON
    (
        SCL1.CENTER = SU.CENTER
        AND SCL1.ID = SU.ID
        AND SCL1.ENTRY_TYPE = 2
        AND SCL1.STATEID = 8 )
JOIN
    STATE_CHANGE_LOG SCL2
ON
    (
        SU.CENTER = SCL2.CENTER
        AND SU.ID = SCL2.ID
        AND SCL2.ENTRY_TYPE = 2
        AND SCL2.ENTRY_START_TIME = SCL1.ENTRY_END_TIME
        AND SCL2.STATEID = 2 )
WHERE
    (
        SCL2.ENTRY_START_TIME > :FromStartDate
        AND SCL2.ENTRY_START_TIME < :ToStartDate + (1000*60*60*24) )
GROUP BY
    SU.CENTER,
    PR.GLOBALID,
    MPR.CACHED_PRODUCTNAME,
    PR.NAME,
    ST.ST_TYPE,
    ST.BINDINGPERIODCOUNT,
    DECODE(ST.PERIODUNIT, 0, 'WEEK', 1, 'DAY', 2, 'MONTH', 3, 'YEAR', 'ERROR') ,
    SU.START_DATE