-- The extract is extracted from Exerp on 2026-02-08
-- List of members with all Corona Comps chosen and given
SELECT
		p.center || 'p' || p.id AS PersonId,
		p.EXTERNAL_ID,
     p.FIRSTNAME,
     p.LASTNAME,
     c.Shortname        AS "Club",
     c.Id          AS "Center ID",
     email.TXTVALUE      AS "email",
      CASE p.STATUS
        WHEN 0 THEN 'LEAD'
        WHEN 1 THEN 'ACTIVE'
        WHEN 2 THEN 'INACTIVE'
        WHEN 3 THEN 'TEMPORARY INACTIVE'
        WHEN 4 THEN 'TRANSFERRED'
        WHEN 5 THEN 'DUPLICATE'
        WHEN 6 THEN 'PROSPECT'
        WHEN 7 THEN 'DELETED'
        WHEN 8 THEN 'ANONYMIZED'
        WHEN 9 THEN 'CONTACT'
        ELSE 'UNKNOWN'
    END AS "STATUS",
     
     CASE p.persontype
        WHEN 0 THEN 'PRIVATE'
        WHEN 1 THEN 'STUDENT'
        WHEN 2 THEN 'STAFF'
        WHEN 3 THEN 'FRIEND'
        WHEN 4 THEN 'CORPORATE'
        WHEN 5 THEN 'ONEMANCORPORATE'
        WHEN 6 THEN 'FAMILY'
        WHEN 7 THEN 'SENIOR'
        WHEN 8 THEN 'GUEST'
        WHEN 9 THEN 'CHILD'
        WHEN 10 THEN 'EXTERNAL_STAFF'
        ELSE 'UNKNOWN'
    END AS "PERSONTYPE",
COMPENSATION.TXTVALUE AS "Apr20Chosen",
COMPENSATIONGIVENAT.TXTVALUE AS "Apr20Given",
Compensation2.TXTVALUE AS "May20Chosen",
Compensation2Given.TXTVALUE AS "May20Given",
COMPENSATION3.TXTVALUE AS "Nov-MayChosen",
COMPENSATION3GIVENAT.TXTVALUE AS "Nov20Given",
COMPENSATION4.TXTVALUE AS "Dec20Given",
COMPENSATION5.TXTVALUE AS "Jan21Given",
COMPENSATION6.TXTVALUE AS "Feb21Given",
COMPENSATION7.TXTVALUE AS "Mar21Given",
COMPENSATION8.TXTVALUE AS "Apr21Given",
COMPENSATION9.TXTVALUE AS "May21Admin",
COMPENSATION10.TXTVALUE AS "May21firsthalfGiven",
COMPENSATION11.TXTVALUE AS "May/JunChosen",
COMPENSATION11GIVENAT.TXTVALUE AS "May/JunGvien",
COMPENSATION12.TXTVALUE AS "DEC21Chosen",
COMPENSATION12GIVEN.TXTVALUE AS "DEC21Given"

 
FROM
             PERSONS p
         JOIN
             CENTERS c
         ON
             c.id = p.CENTER
         
              
 LEFT JOIN
     PERSON_EXT_ATTRS email
 ON
     p.center=email.PERSONCENTER
     AND p.id=email.PERSONID
     AND email.name='_eClub_Email'
 LEFT JOIN
     PERSON_EXT_ATTRS mobile
 ON
     p.center=mobile.PERSONCENTER
     AND p.id=mobile.PERSONID
     AND mobile.name='_eClub_PhoneSMS'
 LEFT JOIN
     PERSON_EXT_ATTRS home
 ON
     p.center=home.PERSONCENTER
     AND p.id=home.PERSONID
     AND home.name='_eClub_PhoneHome'

LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION
 ON
     p.center=compensation.PERSONCENTER
     AND p.id=compensation.PERSONID
     AND compensation.name='COMPENSATION'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATIONGIVENAT
 ON
     p.center=COMPENSATIONGIVENAT.PERSONCENTER
     AND p.id=COMPENSATIONGIVENAT.PERSONID
     AND COMPENSATIONGIVENAT.name='COMPENSATIONGIVENAT'
 LEFT JOIN
     PERSON_EXT_ATTRS Compensation2
 ON
     p.center=Compensation2.PERSONCENTER
     AND p.id=Compensation2.PERSONID
     AND Compensation2.name='Compensation2'
 LEFT JOIN
     PERSON_EXT_ATTRS Compensation2Given
 ON
     p.center=Compensation2Given.PERSONCENTER
     AND p.id=Compensation2Given.PERSONID
     AND Compensation2Given.name='Compensation2Given'
LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION3
 ON
     p.center=COMPENSATION3.PERSONCENTER
     AND p.id=COMPENSATION3.PERSONID
     AND COMPENSATION3.name='COMPENSATION3'
LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION3GIVENAT
 ON
     p.center=COMPENSATION3GIVENAT.PERSONCENTER
     AND p.id=COMPENSATION3GIVENAT.PERSONID
     AND COMPENSATION3GIVENAT.name='COMPENSATION3GIVENAT'

 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION4
 ON
     p.center=compensation4.PERSONCENTER
     AND p.id=compensation4.PERSONID
     AND compensation4.name='COMPENSATION4'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION5
 ON
     p.center=COMPENSATION5.PERSONCENTER
     AND p.id=COMPENSATION5.PERSONID
     AND COMPENSATION5.name='COMPENSATION5'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION6
 ON
     p.center=COMPENSATION6.PERSONCENTER
     AND p.id=COMPENSATION6.PERSONID
     AND COMPENSATION6.name='COMPENSATION6'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION7
 ON
     p.center = COMPENSATION7.PERSONCENTER
     AND p.id = COMPENSATION7.PERSONID
     AND COMPENSATION7.name = 'COMPENSATION7'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION8
 ON
     p.center = COMPENSATION8.PERSONCENTER
     AND p.id = COMPENSATION8.PERSONID
     AND COMPENSATION8.name = 'COMPENSATION8'
 
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION9
 ON
     p.center=COMPENSATION9.PERSONCENTER
     AND p.id=COMPENSATION9.PERSONID
     AND COMPENSATION9.name='COMPENSATION9'
 
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION10
 ON
     p.center=COMPENSATION10.PERSONCENTER
     AND p.id=COMPENSATION10.PERSONID
     AND COMPENSATION10.name='COMPENSATION10'

 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION11
  ON
     p.center=COMPENSATION11.PERSONCENTER
     AND p.id=COMPENSATION11.PERSONID
     AND COMPENSATION11.name='COMPENSATION11'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION11GIVENAT
 ON
     p.center=COMPENSATION11GIVENAT.PERSONCENTER
     AND p.id=COMPENSATION11GIVENAT.PERSONID
     AND COMPENSATION11GIVENAT.name='COMPENSATION11GIVENAT'
LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION12
 ON
     p.center=COMPENSATION12.PERSONCENTER
     AND p.id=COMPENSATION12.PERSONID
     AND COMPENSATION12.name='COMPENSATION12'
 
LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATION12GIVEN
 ON
     p.center=COMPENSATION12GIVEN.PERSONCENTER
     AND p.id=COMPENSATION12GIVEN.PERSONID
     AND COMPENSATION12GIVEN.name='COMPENSATION12GIVEN'

where p.center in(:scope)AND p.status in (:status)

