SELECT
		p.center || 'p' || p.id AS PersonId,
		p.EXTERNAL_ID,
     p.FIRSTNAME,
     p.LASTNAME,
     c.Shortname        AS "Club",
     c.Id          AS "Center ID",
     email.TXTVALUE      AS "email",
      CASE p.STATUS
        WHEN 0 THEN 'LEAD'
        WHEN 1 THEN 'ACTIVE'
        WHEN 2 THEN 'INACTIVE'
        WHEN 3 THEN 'TEMPORARY INACTIVE'
        WHEN 4 THEN 'TRANSFERRED'
        WHEN 5 THEN 'DUPLICATE'
        WHEN 6 THEN 'PROSPECT'
        WHEN 7 THEN 'DELETED'
        WHEN 8 THEN 'ANONYMIZED'
        WHEN 9 THEN 'CONTACT'
        ELSE 'UNKNOWN'
    END AS "STATUS",
     
     CASE p.persontype
        WHEN 0 THEN 'PRIVATE'
        WHEN 1 THEN 'STUDENT'
        WHEN 2 THEN 'STAFF'
        WHEN 3 THEN 'FRIEND'
        WHEN 4 THEN 'CORPORATE'
        WHEN 5 THEN 'ONEMANCORPORATE'
        WHEN 6 THEN 'FAMILY'
        WHEN 7 THEN 'SENIOR'
        WHEN 8 THEN 'GUEST'
        WHEN 9 THEN 'CHILD'
        WHEN 10 THEN 'EXTERNAL_STAFF'
        ELSE 'UNKNOWN'
    END AS "PERSONTYPE",
EGYMID.TXTVALUE AS "EGYMID",
EGYMIDAT.TXTVALUE AS "EGYMIDAT",
EGYMIDCH.TXTVALUE AS "EGYMIDAT",
ENABLEEGYM.TXTVALUE AS "ENABLEEGYM",
EGYMAGG.TXTVALUE AS "EGYMAGG",
AGGREGATOR.TXTVALUE AS "AGGREGATOR",
EGYMNONMEMBER.TXTVALUE AS "EGYMNONMEMBER",
ENABLEEGYMAT.TXTVALUE AS "ENABLEEGYMAT"


 
FROM
             PERSONS p
         JOIN
             CENTERS c
         ON
             c.id = p.CENTER
         
              
 LEFT JOIN
     PERSON_EXT_ATTRS email
 ON
     p.center=email.PERSONCENTER
     AND p.id=email.PERSONID
     AND email.name='_eClub_Email'
 LEFT JOIN
     PERSON_EXT_ATTRS mobile
 ON
     p.center=mobile.PERSONCENTER
     AND p.id=mobile.PERSONID
     AND mobile.name='_eClub_PhoneSMS'
 LEFT JOIN
     PERSON_EXT_ATTRS home
 ON
     p.center=home.PERSONCENTER
     AND p.id=home.PERSONID
     AND home.name='_eClub_PhoneHome'

LEFT JOIN
     PERSON_EXT_ATTRS EGYMID
 ON
     p.center=EGYMID.PERSONCENTER
     AND p.id=EGYMID.PERSONID
     AND EGYMID.name='EGYMID'
 LEFT JOIN
     PERSON_EXT_ATTRS EGYMIDAT
 ON
     p.center=EGYMIDAT.PERSONCENTER
     AND p.id=EGYMIDAT.PERSONID
     AND EGYMIDAT.name='EGYMIDAT'
 LEFT JOIN
     PERSON_EXT_ATTRS EGYMIDCH
 ON
     p.center=EGYMIDCH.PERSONCENTER
     AND p.id=EGYMIDCH.PERSONID
     AND EGYMIDCH.name='EGYMIDCH'
 LEFT JOIN
     PERSON_EXT_ATTRS ENABLEEGYM
 ON
     p.center=ENABLEEGYM.PERSONCENTER
     AND p.id=ENABLEEGYM.PERSONID
     AND ENABLEEGYM.name='ENABLEEGYM'
 LEFT JOIN
     PERSON_EXT_ATTRS EGYMAGG
 ON
     p.center=EGYMAGG.PERSONCENTER
     AND p.id=EGYMAGG.PERSONID
     AND EGYMAGG.name='EGYMAGG'
 LEFT JOIN
     PERSON_EXT_ATTRS EGYMNONMEMBER
 ON
     p.center=EGYMNONMEMBER.PERSONCENTER
     AND p.id=EGYMNONMEMBER.PERSONID
     AND EGYMNONMEMBER.name='EGYMNONMEMBER'
 LEFT JOIN
     PERSON_EXT_ATTRS ENABLEEGYMAT
 ON
     p.center = ENABLEEGYMAT.PERSONCENTER
     AND p.id = ENABLEEGYMAT.PERSONID
     AND ENABLEEGYMAT.name = 'ENABLEEGYMAT'
 LEFT JOIN
     PERSON_EXT_ATTRS ENABLEEGYMATCH
 ON
     p.center = ENABLEEGYMATCH.PERSONCENTER
     AND p.id = ENABLEEGYMATCH.PERSONID
     AND ENABLEEGYMATCH.name = 'ENABLEEGYMATCH'
 
 LEFT JOIN
     PERSON_EXT_ATTRS AGGREGATOR
 ON
     p.center=AGGREGATOR.PERSONCENTER
     AND p.id=AGGREGATOR.PERSONID
     AND AGGREGATOR.name='AGGREGATOR'
 
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATIONGIVEN6
 ON
     p.center=compensationgiven6.PERSONCENTER
     AND p.id=compensationgiven6.PERSONID
     AND compensationgiven6.name='COMPENSATIONGIVEN6'

 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATIONGIVEN7
  ON
     p.center=compensationgiven7.PERSONCENTER
     AND p.id=compensationgiven7.PERSONID
     AND compensationgiven7.name='COMPENSATIONGIVEN7'
 LEFT JOIN
     PERSON_EXT_ATTRS COMPENSATIONGIVEN8
 ON
     p.center=compensationgiven8.PERSONCENTER
     AND p.id=compensationgiven8.PERSONID
     AND compensationgiven8.name='COMPENSATIONGIVEN8'
 
LEFT JOIN
     PERSON_EXT_ATTRS CORONACOMP
 ON
     p.center=CORONACOMP.PERSONCENTER
     AND p.id=CORONACOMP.PERSONID
     AND CORONACOMP.name='CORONACOMP'

where p.center in(:scope)AND p.status in (:status)

