SELECT distinct
    p2.EXTERNAL_ID,
    ch.CHECKIN_CENTER,
    TO_CHAR(longtodate(ch.CHECKIN_TIME),'yyyy-MM-dd HH24:MI') AS CHECKIN_TIME
FROM
    HP.CHECKINS ch
JOIN
    HP.PERSONS p
ON
    p.CENTER = ch.PERSON_CENTER
    AND p.id = ch.PERSON_ID
JOIN
    HP.PERSONS p2
ON
    p2.center = p.CURRENT_PERSON_CENTER
    AND p2.id = p.CURRENT_PERSON_ID
WHERE
    p2.STATUS NOT IN (4,5,7,8)
    AND p2.PERSONTYPE != 2
    AND ch.CHECKIN_TIME BETWEEN datetolong(TO_CHAR(SYSDATE -5, 'YYYY-MM-DD HH24:MM')) AND datetolong(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MM'))