-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT
    s.CENTER||'ss'||s.id AS Subscription_ID,
    pr.NAME              AS Addon,
    sa.START_DATE,
    sa.END_DATE,
    emp.FULLNAME
FROM
    HP.SUBSCRIPTION_ADDON sa
JOIN
    HP.SUBSCRIPTIONS s
ON
    sa.SUBSCRIPTION_CENTER=s.CENTER
    AND sa.SUBSCRIPTION_ID = s.id
JOIN
    HP.SUBSCRIPTIONTYPES st
ON
    st.CENTER = s.SUBSCRIPTIONTYPE_CENTER
    AND st.id = s.SUBSCRIPTIONTYPE_ID
JOIN
    HP.PERSONS emp
ON
    emp.CENTER = sa.EMPLOYEE_CREATOR_CENTER
    AND emp.id = sa.EMPLOYEE_CREATOR_ID
JOIN
    HP.MASTERPRODUCTREGISTER mpr
ON
    mpr.ID = sa.ADDON_PRODUCT_ID
JOIN
    HP.PRODUCTS pr
ON
    pr.GLOBALID = mpr.GLOBALID
    AND pr.CENTER = sa.CENTER_ID
JOIN
    HP.PERSONS p
ON
    p.CENTER = s.OWNER_CENTER
    AND p.id = s.OWNER_ID
JOIN
    HP.PERSONS p2
ON
    p2.CENTER = p.CURRENT_PERSON_CENTER
    AND p2.id = p.CURRENT_PERSON_ID
WHERE
    s.STATE !=5
    AND p2.STATUS NOT IN (4,5,7,8)
    AND p2.PERSONTYPE != 2
    AND sa.CANCELLED = 0