SELECT DISTINCT
    p.EXTERNAL_ID,
    DECODE(r.RTYPE,1,p3.EXTERNAL_ID,NULL)   AS "Friend of",
    DECODE(r2.RTYPE,2,p5.EXTERNAL_ID,NULL)  AS "My Company",
    DECODE(r.RTYPE,4,p3.EXTERNAL_ID,NULL)   AS "My Head of Family",
    DECODE(r.RTYPE,13,p3.EXTERNAL_ID,NULL)  AS "My referrer",
    DECODE(r2.RTYPE,12,p5.EXTERNAL_ID,NULL) AS "My payer"
FROM
    HP.PERSONS p
LEFT JOIN
    HP.RELATIVES r
ON
    r.CENTER = p.CENTER
    AND r.id = p.ID
    AND r.RTYPE IN (1,4,13)
    AND r.STATUS =1
LEFT JOIN
    HP.PERSONS p2
ON
    p2.CENTER = r.RELATIVECENTER
    AND p2.id = r.RELATIVEID
LEFT JOIN
    HP.PERSONS p3
ON
    p3.CENTER = p2.CURRENT_PERSON_CENTER
    AND p3.id = p2.CURRENT_PERSON_ID
LEFT JOIN
    HP.RELATIVES r2
ON
    r2.RELATIVECENTER = p.CENTER
    AND r2.RELATIVEID = p.ID
    AND r2.RTYPE IN (2,12)
    AND r2.STATUS = 1
LEFT JOIN
    HP.PERSONS p4
ON
    p4.CENTER = r2.CENTER
    AND p4.id = r2.ID
LEFT JOIN
    HP.PERSONS p5
ON
    p5.CENTER = p4.CURRENT_PERSON_CENTER
    AND p5.id = p4.CURRENT_PERSON_ID
WHERE
    p.STATUS NOT IN (4,5,7,8)
    AND p.PERSONTYPE != 2
    AND (
        r.CENTER IS NOT NULL
        OR r2.CENTER IS NOT NULL)