-- The extract is extracted from Exerp on 2026-02-08
--  

SELECT
    PERSON_EXT_ATTRS.TXTVALUE,
    COUNT(PERSON_EXT_ATTRS.NAME)
FROM
    HP.PERSON_EXT_ATTRS
WHERE
    PERSON_EXT_ATTRS.NAME = '_eClub_Email'

GROUP BY
    PERSON_EXT_ATTRS.TXTVALUE
HAVING
    (
        COUNT(PERSON_EXT_ATTRS.NAME) > 1 )

	 