-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 'bi2_accepted_material' AS EXPORT, count(*) FROM bi2_accepted_material WHERE "ETS" is null union all
SELECT 'bi2_access_privilege_usage' AS EXPORT, count(*) FROM bi2_access_privilege_usage WHERE "ETS" is null union all
SELECT 'bi2_agreement_case' AS EXPORT, count(*) FROM bi2_agreement_case WHERE "ETS" is null union all
SELECT 'bi2_answer_submission' AS EXPORT, count(*) FROM bi2_answer_submission WHERE "ETS" is null union all
SELECT 'bi2_attend' AS EXPORT, count(*) FROM bi2_attend WHERE "ETS" is null union all
SELECT 'bi2_booking' AS EXPORT, count(*) FROM bi2_booking WHERE "ETS" is null union all
SELECT 'bi2_booking_resource_usage' AS EXPORT, count(*) FROM bi2_booking_resource_usage WHERE "ETS" is null union all
SELECT 'bi2_center_ext_attr' AS EXPORT, count(*) FROM bi2_center_ext_attr WHERE "ETS" is null union all
SELECT 'bi2_clipcard' AS EXPORT, count(*) FROM bi2_clipcard WHERE "ETS" is null union all
SELECT 'bi2_clipcard_usage' AS EXPORT, count(*) FROM bi2_clipcard_usage WHERE "ETS" is null union all
SELECT 'bi2_company' AS EXPORT, count(*) FROM bi2_company WHERE "ETS" is null union all
SELECT 'bi2_crm_action' AS EXPORT, count(*) FROM bi2_crm_action WHERE "ETS" is null union all
SELECT 'bi2_crm_task' AS EXPORT, count(*) FROM bi2_crm_task WHERE "ETS" is null union all
SELECT 'bi2_daily_member_state' AS EXPORT, count(*) FROM bi2_daily_member_state WHERE "ETS" is null union all
SELECT 'bi2_debt_case' AS EXPORT, count(*) FROM bi2_debt_case WHERE "ETS" is null union all
SELECT 'bi2_document' AS EXPORT, count(*) FROM bi2_document WHERE "ETS" is null union all
SELECT 'bi2_entity_identifier' AS EXPORT, count(*) FROM bi2_entity_identifier WHERE "ETS" is null union all
SELECT 'bi2_freeze_period' AS EXPORT, count(*) FROM bi2_freeze_period WHERE "ETS" is null union all
SELECT 'bi2_home_center_log' AS EXPORT, count(*) FROM bi2_home_center_log WHERE "ETS" is null union all
SELECT 'bi2_inventory_transaction_log' AS EXPORT, count(*) FROM bi2_inventory_transaction_log WHERE "ETS" is null union all
SELECT 'bi2_kpi_log' AS EXPORT, count(*) FROM bi2_kpi_log WHERE "ETS" is null union all
SELECT 'bi2_member_state_log' AS EXPORT, count(*) FROM bi2_member_state_log WHERE "ETS" is null union all
SELECT 'bi2_message' AS EXPORT, count(*) FROM bi2_message WHERE "ETS" is null union all
SELECT 'bi2_participation' AS EXPORT, count(*) FROM bi2_participation WHERE "ETS" is null union all
SELECT 'bi2_person' AS EXPORT, count(*) FROM bi2_person WHERE "ETS" is null union all
SELECT 'bi2_person_attribute_log' AS EXPORT, count(*) FROM bi2_person_attribute_log WHERE "ETS" is null union all
SELECT 'bi2_person_detail' AS EXPORT, count(*) FROM bi2_person_detail WHERE "ETS" is null union all
SELECT 'bi2_person_ext_attr' AS EXPORT, count(*) FROM bi2_person_ext_attr WHERE "ETS" is null union all
SELECT 'bi2_person_status_log' AS EXPORT, count(*) FROM bi2_person_status_log WHERE "ETS" is null union all
SELECT 'bi2_person_type_log' AS EXPORT, count(*) FROM bi2_person_type_log WHERE "ETS" is null union all
SELECT 'bi2_product' AS EXPORT, count(*) FROM bi2_product WHERE "ETS" is null union all
SELECT 'bi2_product_privilege_usage' AS EXPORT, count(*) FROM bi2_product_privilege_usage WHERE "ETS" is null union all
SELECT 'bi2_relation_state_log' AS EXPORT, count(*) FROM bi2_relation_state_log WHERE "ETS" is null union all
SELECT 'bi2_sale_employee_log' AS EXPORT, count(*) FROM bi2_sale_employee_log WHERE "ETS" is null union all
SELECT 'bi2_sale_log' AS EXPORT, count(*) FROM bi2_sale_log WHERE "ETS" is null union all
SELECT 'bi2_staff_usage' AS EXPORT, count(*) FROM bi2_staff_usage WHERE "ETS" is null union all
SELECT 'bi2_subscription_addon' AS EXPORT, count(*) FROM bi2_subscription_addon WHERE "ETS" is null union all
SELECT 'bi2_subscription' AS EXPORT, count(*) FROM bi2_subscription WHERE "ETS" is null union all
SELECT 'bi2_subscription_period' AS EXPORT, count(*) FROM bi2_subscription_period WHERE "ETS" is null union all
SELECT 'bi2_subscription_price' AS EXPORT, count(*) FROM bi2_subscription_price WHERE "ETS" is null union all
SELECT 'bi2_subscription_sale' AS EXPORT, count(*) FROM bi2_subscription_sale WHERE "ETS" is null union all
SELECT 'bi2_subscription_state_log' AS EXPORT, count(*) FROM bi2_subscription_state_log WHERE "ETS" is null union all
SELECT 'bi2_visit_log' AS EXPORT, count(*) FROM bi2_visit_log WHERE "ETS" is null