CREATE TABLE 
    booking_time_configs 
    ( 
        id int4 NOT NULL, 
        name       text(2147483647) NOT NULL, 
        scope_type text(2147483647) NOT NULL, 
        scope_id int4 NOT NULL, 
        STATE text(2147483647) NOT NULL, 
        book_start_value int4, 
        book_start_unit int4, 
        book_start_round text(2147483647), 
        book_start_role int4, 
        book_stop_value int4, 
        book_stop_unit int4, 
        book_stop_round text(2147483647), 
        book_cancel_stop_value int4, 
        book_cancel_stop_unit int4, 
        book_cancel_stop_round text(2147483647), 
        book_cancel_stop_role int4, 
        part_start_value int4, 
        part_start_unit int4, 
        part_start_round text(2147483647), 
        part_start_role int4, 
        part_stop_staff_value int4, 
        part_stop_staff_unit int4, 
        part_stop_staff_round text(2147483647), 
        part_stop_cus_value int4, 
        part_stop_cus_unit int4, 
        part_stop_cus_round text(2147483647), 
        part_cancel_stop_staff_value int4, 
        part_cancel_stop_staff_unit int4, 
        part_cancel_stop_staff_round text(2147483647), 
        part_cancel_stop_staff_role int4, 
        part_cancel_stop_cus_value int4, 
        part_cancel_stop_cus_unit int4, 
        part_cancel_stop_cus_round text(2147483647), 
        part_showup_start_value int4, 
        part_showup_start_unit int4, 
        part_showup_start_round text(2147483647), 
        part_showup_stop_staff_value int4, 
        part_showup_stop_staff_unit int4, 
        part_showup_stop_staff_round text(2147483647), 
        part_showup_stop_cus_value int4, 
        part_showup_stop_cus_unit int4, 
        part_showup_stop_cus_round text(2147483647), 
        waitinglist_run_value int4, 
        waitinglist_run_unit int4, 
        waitinglist_run_round text(2147483647), 
        normal_misuse_id      text(2147483647), 
        waiting_misuse_id     text(2147483647), 
        part_recurrence_in_past_value int4, 
        part_recurrence_in_past_unit int4, 
        part_recurrence_in_past_round text(2147483647), 
        part_rec_in_past_requiredrole int4, 
        showup_membercard bool DEFAULT FALSE NOT NULL, 
        showup_membercard_requiredrole int4, 
        booking_time_configs bool DEFAULT FALSE NOT NULL, 
        allow_auto_showup bool DEFAULT FALSE NOT NULL, 
        part_cancel_sanc_start_value int4, 
        part_cancel_sanc_start_unit int4, 
        part_cancel_sanc_start_round text(2147483647), 
        part_cancel_sanc_start_role int4, 
        head_count_window_value int4, 
        head_count_window_unit int4, 
        head_count_window_round text(2147483647), 
        threshold_percentage int4, 
        threshold_action text(2147483647), 
        review_part_stop_value int4, 
        review_part_stop_unit int4, 
        review_part_stop_round text(2147483647), 
        flag_substitution_start_value int4, 
        flag_substitution_start_unit int4, 
        flag_substitution_start_round text(2147483647), 
        flag_substitution_stop_value int4, 
        flag_substitution_stop_unit int4, 
        flag_substitution_stop_round text(2147483647), 
        program_cancel_stop_role int4, 
        program_cancel_stop_round VARCHAR(20), 
        program_cancel_stop_unit int4, 
        program_cancel_stop_value int4, 
        program_signup_role int4, 
        program_signup_round VARCHAR(20), 
        program_signup_unit int4, 
        program_signup_value int4, 
        book_stop_role int4, 
        part_showup_start_role int4, 
        part_communication_stop_round VARCHAR(20), 
        part_communication_stop_unit int4, 
        part_communication_stop_value int4, 
        program_latest_start_value int4, 
        program_latest_start_unit int4, 
        program_latest_start_round VARCHAR(20), 
        program_latest_start_role int4, 
        program_early_start_value int4, 
        program_early_start_unit int4, 
        program_early_start_round VARCHAR(20), 
        program_early_start_role int4, 
        stop_sanction_window_value int4, 
        stop_sanction_window_unit int4, 
        stop_sanction_window_round text(2147483647), 
        PRIMARY KEY (id) 
    );
