CREATE TABLE 
    startup_campaign 
    ( 
        id int4 NOT NULL, 
        scope_type text(2147483647) NOT NULL, 
        scope_id int4 NOT NULL, 
        STATE       text(2147483647) NOT NULL, 
        name        text(2147483647) NOT NULL, 
        plugin_name text(2147483647), 
        plugin_config bytea, 
        starttime int8 NOT NULL, 
        endtime int8 NOT NULL, 
        period_type text(2147483647) NOT NULL, 
        period_unit int4 DEFAULT 1, 
        period_value int4, 
        period_round bool, 
        period_start      DATE, 
        period_end        DATE, 
        web_text          text(2147483647), 
        available_scopes  text(2147483647), 
        plugin_codes_name text(2147483647), 
        plugin_codes_config bytea, 
        free_period_unit int4, 
        free_period_value int4, 
        free_period_type text(2147483647), 
        free_period_extends_binding bool DEFAULT FALSE, 
        campaign_apply_for            VARCHAR(50) DEFAULT 'NEW_SALE'::character VARYING NOT NULL, 
        privilege_change_binding_type VARCHAR(50) DEFAULT 'NONE'::character VARYING NOT NULL, 
        relative_to_start_date_value int4, 
        relative_to_start_date_unit int4, 
        relative_to_start_date_round bool, 
        fixed_binding_end_date DATE, 
        PRIMARY KEY (id) 
    );
