 SELECT CENTER, ID, SUBID,DEBIT_ACCOUNTCENTER, DEBIT_ACCOUNTID, CREDIT_ACCOUNTCENTER, CREDIT_ACCOUNTID, TEXT, INFO, AMOUNT, longtodatec(trans_time, ACCOUNT_TRANS.CENTER) AS TRANS_TIME,
 longtodatec(entry_time, ACCOUNT_TRANS.CENTER) AS ENTRY_TIME FROM ACCOUNT_TRANS
   WHERE CENTER = 105 and
 longtodatec(trans_time, ACCOUNT_TRANS.CENTER) >= TO_DATE('2016/04/24 12:00:00','yyyy/mm/dd hh24:mi:ss')
 AND DEBIT_ACCOUNTID = 125
 AND CREDIT_ACCOUNTID = 84
LIMIT 100