Select owner,object_name,object_type 
from all_objects 
WHERE object_type = $$object_type$$
ORDER BY owner DESC
-- WHERE object_type = 'PROCEDURE'
-- WHERE object_type = 'EDITION'
-- WHERE object_type = 'CONSUMER GROUP'
-- WHERE object_type = 'SEQUENCE'
-- WHERE object_type = 'SCHEDULE'
-- WHERE object_type = 'PROCEDURE'
-- WHERE object_type = 'OPERATOR'
-- WHERE object_type = 'DESTINATION'
-- WHERE object_type = 'SCHEDULER GROUP'
-- WHERE object_type = 'WINDOW'
-- WHERE object_type = 'PACKAGE'
-- WHERE object_type = 'PROGRAM'
-- WHERE object_type = 'LOB'
-- WHERE object_type = 'JAVA RESOURCE'
-- WHERE object_type = 'XML SCHEMA'
-- WHERE object_type = 'JOB CLASS'
-- WHERE object_type = 'TABLE'
-- WHERE object_type = 'SYNONYM'
-- WHERE object_type = 'VIEW'
-- WHERE object_type = 'FUNCTION'
-- WHERE object_type = 'JAVA CLASS'
-- WHERE object_type = 'INDEXTYPE'
-- WHERE object_type = 'INDEX'
-- WHERE object_type = 'TYPE'
-- WHERE object_type = 'EVALUATION CONTEXT'