-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT p.CENTER, p.ID, p.FULLNAME, pa.CENTER, pa.ID, pa.SUBID, pa.BANK_NAME,  pa.BANK_CONTROL_DIGITS,pa.BANK_ACCNO, pa.BANK_ACCOUNT_HOLDER, pa.IBAN, pa.BIC, pa.EXAMPLE_REFERENCE, pa.REF, pa.NOTIFY_PAYMENT
    FROM PERSONS p
 LEFT JOIN
         ACCOUNT_RECEIVABLES ar
 ON
     ar.CUSTOMERCENTER = p.CENTER
     AND ar.CUSTOMERID = p.ID
     AND ar.AR_TYPE = 4
 LEFT
         JOIN PAYMENT_ACCOUNTS pac
 ON
     pac.CENTER = ar.CENTER
     AND pac.ID = ar.ID
 LEFT JOIN
         PAYMENT_AGREEMENTS pa
 ON
     pa.CENTER = pac.ACTIVE_AGR_CENTER
     AND pa.ID = pac.ACTIVE_AGR_ID
         AND pa.SUBID = pac.ACTIVE_AGR_SUBID
 WHERE p.CENTER  IN (select c.ID from CENTERS c where  c.COUNTRY = 'IT' )
 AND pa.CLEARINGHOUSE = 803
