-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT s.* FROM SUBSCRIPTIONS S LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID LEFT JOIN PRODUCTS PR ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID WHERE P.CENTER IN (select c.ID from CENTERS c where  c.COUNTRY = 'IT')
  AND S.SUB_STATE IN(1,9)
AND PR.PRIMARY_PRODUCT_GROUP_ID NOT IN(5404,5405,5406)
AND S.END_DATE  BETWEEN TRUNC(SYSDATE +1) AND TRUNC(SYSDATE +30)
--AND ROWNUM < 20 