-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT S.CENTER, S.ID, P.ID AS PERSONID, P.FIRSTNAME, P.LASTNAME,P.CENTER AS PERSON_CENTER,  
DECODE (STATE, 2,'Active', 3,'Ended', 4,'Frozen', 7,'Window', 8,'Created','Unknown') as STATE,
 DECODE (SUB_STATE, 1,'None', 6, 'Transferred', 9,'Blocked') AS SUB_STATE, S.SUBSCRIPTIONTYPE_CENTER, S.BINDING_END_DATE, S.SUBSCRIPTION_PRICE, S.START_DATE, S.END_DATE, 
 PR.NAME
 FROM SUBSCRIPTIONS S LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER 
 AND P.ID = S.OWNER_ID
 LEFT JOIN PRODUCTS PR
 ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID
 LEFT OUTER JOIN
(SELECT PERSONID, PERSONCENTER from  CASHCOLLECTIONCASES cc
INNER JOIN CENTERS C 
on c.ID = cc.PERSONCENTER
WHERE

 c.COUNTRY = 'IT'
   AND cc.CLOSED = 0
   AND CC.MISSINGPAYMENT = 1
	

GROUP BY PERSONID, PERSONCENTER) cc
ON cc.PERSONCENTER = p.CENTER AND cc.PERSONID = p.ID
 WHERE P.CENTER IN (select c.ID from CENTERS c where  c.COUNTRY = 'IT')
  AND S.SUB_STATE IN(1,9)
AND PR.PRIMARY_PRODUCT_GROUP_ID NOT IN(5404)

AND S.END_DATE  BETWEEN ADD_MONTHS(TRUNC(SYSDATE),-1) AND ADD_MONTHS(TRUNC(SYSDATE),+1)
AND (P.PERSONTYPE NOT IN(2,4) OR PR.NAME Like '%Partnership%')
AND PR.NAME NOT LIKE 'Tessera%'
AND PR.NAME NOT LIKE 'JOIN%'
AND PR.NAME NOT LIKE 'Ditte Esterne%'
AND PR.NAME NOT LIKE 'Staff Family%'
AND cc.PERSONID IS NULL