-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT p.CENTER, p.ID, p.FULLNAME, pa.BIC, pa.IBAN,  pa.BANK_NAME, pa.BANK_CONTROL_DIGITS,pa.BANK_ACCNO, pa.BANK_ACCOUNT_HOLDER, pa.IBAN, pa.BIC
   FROM PERSONS p

LEFT JOIN 
	ACCOUNT_RECEIVABLES ar
ON
    ar.CUSTOMERCENTER = p.CENTER
    AND ar.CUSTOMERID = p.ID
    AND ar.AR_TYPE = 4
LEFT 
	JOIN PAYMENT_ACCOUNTS pac
ON
    pac.CENTER = ar.CENTER
    AND pac.ID = ar.ID
LEFT JOIN 
	PAYMENT_AGREEMENTS pa
ON
    pa.CENTER = pac.ACTIVE_AGR_CENTER
    AND pa.ID = pac.ACTIVE_AGR_ID
	AND pa.SUBID = pac.ACTIVE_AGR_SUBID
LEFT JOIN 
	PAYMENT_AGREEMENTS pa1
on 
 	pa1.CENTER = pa.PREV_CENTER
    AND pa1.ID = pa.PREV_ID
	AND pa1.SUBID = pa.PREV_SUBID
   


WHERE 
-- pa.BANK_ACCOUNT_HOLDER IS NOT NULL 
AND (pa.BIC IS  NULL or trim(pa.BIC) = '')
--p.CENTER  IN( select c.ID from CENTERS c where  c.COUNTRY = 'IT'  )
 --and pa.IBAN IS NOT  NULL 