-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT p.CENTER, p.ID, pa.NOTIFY_PAYMENT,  pa.CENTER, pa.ID, pa.SUBID,  pa.CREATION_TIME as CREATIONAGREEMENT
   FROM PERSONS p

LEFT JOIN 
	ACCOUNT_RECEIVABLES ar
ON
    ar.CUSTOMERCENTER = p.CENTER
    AND ar.CUSTOMERID = p.ID
    AND ar.AR_TYPE = 4
LEFT 
	JOIN PAYMENT_ACCOUNTS pac
ON
    pac.CENTER = ar.CENTER
    AND pac.ID = ar.ID
LEFT JOIN 
	PAYMENT_AGREEMENTS pa
ON
    pa.CENTER = pac.ACTIVE_AGR_CENTER
    AND pa.ID = pac.ACTIVE_AGR_ID


   


WHERE p.CENTER  IN(select c.ID from CENTERS c where  c.COUNTRY = 'IT' )