-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT p.CENTER, p.ID, p.FULLNAME,TO_DATE('1970/01/01 00:00:00','yyyy/mm/dd hh24:mi:ss') + (pa.CREATION_TIME/86400/1000) as CREATION_DATE,  pa.BANK_NAME, pa.BANK_CONTROL_DIGITS,pa.BANK_ACCNO, pa.BANK_ACCOUNT_HOLDER, pa.IBAN, pa.BIC
   FROM PERSONS p

LEFT JOIN 
	ACCOUNT_RECEIVABLES ar
ON
    ar.CUSTOMERCENTER = p.CENTER
    AND ar.CUSTOMERID = p.ID
   
LEFT 
	JOIN PAYMENT_ACCOUNTS pac
ON
    pac.CENTER = ar.CENTER
    AND pac.ID = ar.ID
LEFT JOIN 
	PAYMENT_AGREEMENTS pa
ON
    pa.CENTER = pac.ACTIVE_AGR_CENTER
    AND pa.ID = pac.ACTIVE_AGR_ID

   


WHERE p.CENTER  IN( select c.ID from CENTERS c where  c.COUNTRY = 'IT'  )
-- and pa.IBAN IS NOT  NULL 
ORDER BY p.CENTER, p.ID, p.FULLNAME, pa.CREATION_TIME