SELECT
    p.PERSON_ID
  , p.HOME_CENTER_ID
  , p.HOME_CENTER_PERSON_ID
  , p.FULL_NAME
  , p.COUNTRY_ID
  , p.POSTAL_CODE
  , p.CITY
  , p.DATE_OF_BIRTH
  , p.GENDER
  , p.PERSON_TYPE
  , p.PERSON_STATUS
  , p.CREATION_DATE
  , p.PAYER_PERSON_ID
  , p.COMPANY_ID
  , p.ETS
FROM
    BI_PERSONS p
WHERE
    p.HOME_CENTER_ID in ($$scope$$)
    AND TO_DATE(p.CREATION_DATE,'YYYY-MM-DD') >= :StartDate
    AND TO_DATE(p.CREATION_DATE,'YYYY-MM-DD') < :EndDate
