-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
cen.SHORTNAME,
    SS.SALES_DATE,
    p.CENTER || 'p' || p.ID personId,
    SS.SUBSCRIPTION_CENTER || 'ss' || SS.SUBSCRIPTION_ID subId,
    p.FULLNAME,
    pr.NAME subscription,
    prg.NAME productGroup,
    SS.TYPE salesType,
    longtodateC(SU.CREATION_TIME, SU.CENTER) created
FROM
    SUBSCRIPTION_SALES SS
JOIN
    SUBSCRIPTIONS SU
ON
    SUBSCRIPTION_CENTER = SU.CENTER
    AND SUBSCRIPTION_ID = SU.ID
INNER JOIN
    SUBSCRIPTIONTYPES ST
ON
    (
        SS.SUBSCRIPTION_TYPE_CENTER = ST.CENTER
        AND SS.SUBSCRIPTION_TYPE_ID = ST.ID)
INNER JOIN
    PRODUCTS PR
ON
    (
        SS.SUBSCRIPTION_TYPE_CENTER = PR.CENTER
        AND SS.SUBSCRIPTION_TYPE_ID = PR.ID)
INNER JOIN
    PERSONS p
ON
    p.center = SS.OWNER_CENTER
    AND p.ID = ss.OWNER_ID
INNER JOIN
    CENTERS cen
ON
    cen.ID = p.CENTER
LEFT JOIN
    PRODUCT_GROUP prg
ON
    prg.ID = pr.PRIMARY_PRODUCT_GROUP_ID
WHERE
    (
        SS.SUBSCRIPTION_TYPE_CENTER IN ($$Scope$$)
        AND SS.SALES_DATE >= $$SalesFromDate$$
        AND SS.SALES_DATE <= $$SalesToDate$$ )
	AND  PRG.ID IN (5406,5407,20019)