SELECT
    DISTINCT TRIM(r.EXTERNAL_ID) AS EXTERNAL_ID FROM BOOKING_RESOURCES r
INNER JOIN CENTERS c

ON r.CENTER = c.ID

WHERE c.COUNTRY = 'IT' AND r.TYPE IN('STUDIO', 'SWIMHALL')
ORDER BY TRIM(r.EXTERNAL_ID)
