-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT

c.EXTERNAL_ID,
BOOK_DATE,
act.TEXT,
 act.AMOUNT,
 act.INFO

 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER




WHERE EXTRACT(month FROM agr.BOOK_DATE) = 5 
--AND c.COUNTRY = 'IT'
AND act.CENTER = 105


ORDER BY c.EXTERNAL_ID, agr.BOOK_DATE