SELECT DISTINCT P.CENTER AS CENTER, P.ID AS ID, P.FULLNAME AS FULLNAME, 
        CE.NAME AS CENTER, P.FIRSTNAME AS FIRSTNAME, P.LASTNAME AS 
        LASTNAME, P.ADDRESS1 AS ADDRESS1, P.ADDRESS2 AS ADDRESS2, P.COUNTRY AS 
        COUNTRY, P.ZIPCODE AS ZIPCODE, P.CITY AS CITY, PEA2.TXTVALUE AS EMAIL, P.NAME from PERSONS P LEFT 
    join SUBSCRIPTIONS S ON (P.CENTER = S.OWNER_CENTER AND P.ID = 
        S.OWNER_ID) LEFT 
    join CENTERS CE ON P.CENTER = CE.ID LEFT 
    join ENTITYIDENTIFIERS EI1 ON (P.CENTER = EI1.REF_CENTER AND P.ID = 
        EI1.REF_ID AND EI1.IDMETHOD = 1 AND EI1.ENTITYSTATUS = 1) LEFT 
    join ENTITYIDENTIFIERS EI2 ON (P.CENTER = EI2.REF_CENTER AND P.ID = 
        EI2.REF_ID AND EI2.IDMETHOD = 2 AND EI2.ENTITYSTATUS = 1) LEFT 
    join ENTITYIDENTIFIERS EI3 ON (P.CENTER = EI3.REF_CENTER AND P.ID = 
        EI3.REF_ID AND EI3.IDMETHOD = 4 AND EI3.ENTITYSTATUS = 1) LEFT 
    join ENTITYIDENTIFIERS EI4 ON (P.CENTER = EI4.REF_CENTER AND P.ID = 
        EI4.REF_ID AND EI4.IDMETHOD = 5 AND EI4.ENTITYSTATUS = 1) LEFT 
    join RELATIVES RL ON (P.CENTER = RL.RELATIVECENTER AND P.ID = 
        RL.RELATIVEID AND RL.RTYPE = 2 AND RL.STATUS <> 3) LEFT 
    join PERSONS PE1 ON (PE1.CENTER = RL.CENTER AND PE1.ID = RL.ID) LEFT 
    join PERSONS PE2 ON (PE2.CENTER = P.CURRENT_PERSON_CENTER AND PE2.ID = 
        P.CURRENT_PERSON_ID) LEFT 
    join PERSON_EXT_ATTRS PEA1 ON (PEA1.PERSONCENTER = P.CENTER AND 
        PEA1.PERSONID = P.ID AND PEA1.NAME = '_eClub_PhoneHome') LEFT 
    join PERSON_EXT_ATTRS PEA2 ON (PEA2.PERSONCENTER = 
        P.CURRENT_PERSON_CENTER AND PEA2.PERSONID = P.CURRENT_PERSON_ID 
        AND PEA2.NAME = '_eClub_Email') LEFT 
    join PERSON_EXT_ATTRS PEA3 ON (PEA3.PERSONCENTER = 
        P.CURRENT_PERSON_CENTER AND PEA3.PERSONID = P.CURRENT_PERSON_ID 
        AND PEA3.NAME = '_eClub_PhoneSMS')  WHERE P.CENTER IN (205,204,207,206,201,203,202,220,221,222,223,216,217,218,219,212,213,214,215,208,209,210,211,102,103,100,101,108,106,107,225,104,224,105) AND (P.CENTER,P.ID) IN (:members)
