SELECT

c.EXTERNAL_ID,
BOOK_DATE,
act.TEXT,
 act.AMOUNT,
 NULL AS VAT,
 act.INFO

 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER
JOIN BILLLINES bl
ON bl.ACCOUNT_TRANS_CENTER = act.CENTER
AND
bl.ACCOUNT_TRANS_ID = act.ID
AND
bl.ACCOUNT_TRANS_SUBID = act.SUBID




WHERE 
--EXTRACT(month FROM agr.BOOK_DATE) = 5 
--AND c.COUNTRY = 'IT'
 act.CENTER = 223
AND ACT.id = 181816



ORDER BY c.EXTERNAL_ID, agr.BOOK_DATE


