SELECT

c.EXTERNAL_ID,
p.center,
p.id,
p.FULLNAME,
BOOK_DATE,
act.TEXT,
 act.AMOUNT,
 NULL AS VAT,
ar.AMOUNT AS TRANSaMOUNT, 
 act.INFO


 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER


INNER JOIN AR_TRANS ar
ON ar.REF_CENTER = act.CENTER
AND ar.REF_ID = act.ID
AND ar.REF_SUBID = act.SUBID

INNER JOIN PAYMENT_REQUESTS pr ON
pr.CENTER = ar.PAYREQ_SPEC_CENTER
AND pr.ID = ar.PAYREQ_SPEC_ID
AND pr.SUBID = ar.PAYREQ_SPEC_SUBID

INNER JOIN
    ACCOUNT_RECEIVABLES ar
ON pr.CENTER = ar.CENTER
    AND pr.ID = ar.ID

INNER JOIN PERSONS p
ON p.CENTER = ar.CUSTOMERCENTER AND p.ID = ar.CUSTOMERID





 






WHERE EXTRACT(month FROM agr.BOOK_DATE) = 5 
--AND c.COUNTRY = 'IT'
AND act.CENTER = 105
AND ACT.TRANS_TYPE = 2
AND ar.PAYREQ_SPEC_CENTER IS NOT NULL




