SELECT

c.EXTERNAL_ID,
p.center,
p.id,
p.FULLNAME,
BOOK_DATE,
act.TEXT,
 act.AMOUNT,
 NULL AS VAT,
 act.INFO

 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER
JOIN CREDIT_NOTE_LINES crl
ON crl.ACCOUNT_TRANS_CENTER = act.CENTER
AND
crl.ACCOUNT_TRANS_ID = act.ID
AND
crl.ACCOUNT_TRANS_SUBID = act.SUBID
INNER JOIN PERSONS p
ON p.CENTER = crl.PERSON_CENTER
AND p.ID = crl.PERSON_ID




WHERE EXTRACT(month FROM agr.BOOK_DATE) = 5 
--AND c.COUNTRY = 'IT'
AND act.CENTER = 105
AND ACT.TRANS_TYPE = 5
AND act.MAIN_TRANSCENTER IS  NULL


ORDER BY c.EXTERNAL_ID, p.FULLNAME, agr.BOOK_DATE


