-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT

c.EXTERNAL_ID,
P.CENTER,
P.ID,
p.FULLNAME,
BOOK_DATE,
act.TEXT,
 act.AMOUNT,
 NULL AS VAT,
 act.INFO

 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER
LEFT OUTER  JOIN
 INVOICELINES invl
ON invl.ACCOUNT_TRANS_CENTER = act.CENTER
AND
invl.ACCOUNT_TRANS_ID = act.ID
AND
invl.ACCOUNT_TRANS_SUBID = act.SUBID
LEFT OUTER JOIN PERSONS p
ON invl.PERSON_CENTER = p.CENTER
AND invl.PERSON_ID = p.ID



WHERE EXTRACT(month FROM agr.BOOK_DATE) = 5 
--AND c.COUNTRY = 'IT'
AND act.CENTER = 105
AND ACT.TRANS_TYPE = 4
AND act.MAIN_TRANSCENTER IS  NULL


ORDER BY c.EXTERNAL_ID, p.FULLNAME, agr.BOOK_DATE


