SELECT

c.EXTERNAL_ID,
BOOK_DATE,
act.TEXT,
 NULL as AMOUNT,
 act.AMOUNT AS VAT,
 act.INFO

 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER
INNER JOIN
ACCOUNT_TRANS act1
ON act.MAIN_TRANSCENTER = act1.CENTER
AND
act.MAIN_TRANSID = act1.ID
AND
act.MAIN_TRANSSUBID = act1.SUBID 
JOIN BILLLINES bl
ON bl.ACCOUNT_TRANS_CENTER = act1.CENTER
AND
bl.ACCOUNT_TRANS_ID = act1.ID
AND
bl.ACCOUNT_TRANS_SUBID = act1.SUBID




WHERE EXTRACT(month FROM agr.BOOK_DATE) = 5 
--AND c.COUNTRY = 'IT'
AND act.CENTER = 105
AND ACT.TRANS_TYPE = 6
AND act.MAIN_TRANSCENTER IS NOT NULL


ORDER BY c.EXTERNAL_ID, agr.BOOK_DATE
