-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT

C.SHORTNAME,
p.CENTER,
p.ID,
p.FULLNAME,
ac.EXTERNAL_ID as creditAccount,
ad.EXTERNAL_ID as debitAccount,
invl.TEXT,
invl.TOTAL_AMOUNT as AMOUNT


 FROM ACCOUNT_TRANS act

INNER JOIN AGGREGATED_TRANSACTIONS agr
ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
AND
act.AGGREGATED_TRANSACTION_ID = agr.ID
INNER JOIN CENTERS c
ON c.ID = agr.CENTER
INNER  JOIN
 INVOICELINES invl
ON invl.ACCOUNT_TRANS_CENTER = act.CENTER
AND
invl.ACCOUNT_TRANS_ID = act.ID
AND
invl.ACCOUNT_TRANS_SUBID = act.SUBID
INNER JOIN PERSONS p
ON invl.PERSON_CENTER = p.CENTER
AND invl.PERSON_ID = p.ID

INNER JOIN ACCOUNTS ac
ON ac.CENTER = act.CREDIT_ACCOUNTCENTER AND
ac.ID = act.CREDIT_ACCOUNTID

INNER JOIN ACCOUNTS ad
ON ad.CENTER = act.DEBIT_ACCOUNTCENTER AND
ad.ID = act.DEBIT_ACCOUNTID



WHERE EXTRACT(month FROM agr.BOOK_DATE) = 6 AND EXTRACT(day FROM agr.BOOK_DATE) = 1
AND c.COUNTRY = 'IT'
--AND act.CENTER = 105
AND ACT.TRANS_TYPE = 4
AND ac.EXTERNAL_ID  IN('04000', '04005', '04094')
AND ad.EXTERNAL_ID  = '11705'




ORDER BY c.SHORTNAME, p.FULLNAME


