-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT
 COUNT(*), c.SHORTNAME
 , act.TRANS_TYPE
  FROM ACCOUNT_TRANS act
 INNER JOIN AGGREGATED_TRANSACTIONS agr
 ON act.AGGREGATED_TRANSACTION_CENTER = agr.CENTER
 AND
 act.AGGREGATED_TRANSACTION_ID = agr.ID
 INNER JOIN CENTERS c
 ON c.ID = agr.CENTER
 WHERE EXTRACT(month FROM agr.BOOK_DATE) = 5
 AND c.COUNTRY = 'IT'
 --AND act.CENTER = 105
 GROUP BY c.SHORTNAME,  act.TRANS_TYPE
 ORDER BY c.SHORTNAME, act.TRANS_TYPE
