select

concat(concat(cast(p.center as varchar(4)),'p'),cast(p.ID as varchar(6))) as PersonId,
c.SHORTNAME as Club, p.FULLNAME as Nominativo,
DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5, 'DUPLICATE', 6,'PROSPECT', 7,'DELETED',8, 'ANONYMIZED', 9, 'CONTACT', 'UNKNOWN') AS STATUS,
longToDate(MIN(CL.BOOK_START_TIME)) CREATED_DATE,
e.LAST_LOGIN,
CASE WHEN R.ID IS NOT NULL THEN 1 ELSE 0 END AS SUPERUSER


-- CASE WHEN cl.Longtodate() < TO_DATE('01/01/2016','dd/mm/YYYY') THEN TO_DATE('01/01/2016','dd/mm/YYYY') ELSE --p.LAST_ACTIVE_START_DATE END DataInizio, p.LAST_ACTIVE_END_DATE as DataFine

FROM 

PERSONS P

INNER JOIN EMPLOYEES E
ON P.CENTER = E.PERSONCENTER
AND P.ID = E.PERSONID
INNER JOIN CENTERS C
ON E.CENTER = C.ID
INNER JOIN 
STATE_CHANGE_LOG CL
ON
CL.CENTER = p.CENTER AND
CL.ID = p.ID AND 
cl.ENTRY_TYPE = 1
LEFT OUTER JOIN
(SELECT CENTER, ID FROM EMPLOYEESROLES
WHERE ROLEID IN(394,395) GROUP BY  CENTER, ID) r
ON R.CENTER = P.CENTER
AND R.ID = P.ID

WHERE C.COUNTRY= 'IT'

--AND p.LAST_ACTIVE_START_DATE IS NOT NULL
group by 
c.SHORTNAME, p.FULLNAME, DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5, 'DUPLICATE', 6,'PROSPECT', 7,'DELETED',8, 'ANONYMIZED', 9, 'CONTACT', 'UNKNOWN'), p.id, p.center, e.LAST_LOGIN,CASE WHEN R.ID IS NOT NULL THEN 1 ELSE 0 END
ORDER BY 
c.SHORTNAME, p.FULLNAME