-- The extract is extracted from Exerp on 2026-02-08
--  
 select
 CONCAT(CONCAT(cast(p.CENTER as char(3)),'p'),  cast(p.ID as varchar(8))) as personId,pr.NAME, p.FULLNAME,  sp.PRICE AS CURRENT_PRICE, COALESCE(ss.PRICE_PERIOD,s.BINDING_PRICE) AS INITIAL_PRICE, s.START_DATE
 FROM PERSONS p
 INNER JOIN
 CENTERS c
 ON
 p.CENTER = C.ID
 INNER JOIN
 SUBSCRIPTIONS s
 ON
 s.OWNER_CENTER = p.CENTER
 AND
 s.OWNER_ID = p.ID
 INNER JOIN
 SUBSCRIPTION_PRICE sp
 ON
 sp.SUBSCRIPTION_ID = s.ID
 AND
 sp.SUBSCRIPTION_CENTER = s.CENTER
 INNER JOIN
 (SELECT MIN(ID) AS ID, SUBSCRIPTION_CENTER, SUBSCRIPTION_ID FROM SUBSCRIPTION_PRICE WHERE SUBSCRIPTION_CENTER = $$club$$
  AND (TO_DATE IS NULL OR TO_DATE > TRUNC(CURRENT_TIMESTAMP))
  GROUP BY SUBSCRIPTION_CENTER, SUBSCRIPTION_ID) sp1
 ON sp.ID = sp1.ID
 INNER JOIN PRODUCTS pr
 ON s.SUBSCRIPTIONTYPE_CENTER = pr.CENTER
 and s.SUBSCRIPTIONTYPE_ID = pr.ID
 LEFT OUTER JOIN
 SUBSCRIPTION_SALES ss
 ON ss.SUBSCRIPTION_CENTER = s.CENTER
 AND ss.SUBSCRIPTION_ID = s.ID
 WHERE
 p.CENTER = $$club$$
 --AND sp.FROM_DATE <= TRUNC(SYSDATE)
 AND (sp.TO_DATE IS NULL OR sp.TO_DATE > TRUNC(CURRENT_TIMESTAMP))
 AND (s.END_DATE IS NULL OR s.END_DATE > TRUNC(CURRENT_TIMESTAMP))
 AND p.PERSONTYPE !=2
 AND (sp.APPLIED = 1 or sp.PENDING = 1)
 --AND p.ID = 905
 GROUP BY p.ID, p.CENTER, sp.PRICE, p.FULLNAME, pr.NAME, sp.TO_DATE, s.END_DATE,sp.PRICE, ss.PRICE_PERIOD, s.START_DATE, s.BINDING_PRICE
 ORDER BY p.FULLNAME
