SELECT
c.SHORTNAME,
CONCAT(CONCAT(cast(p.CENTER as char(3)),'p'), cast(p.ID as varchar(8))) as JuniorId,
p.FULLNAME as JuniorName,
CONCAT(CONCAT(cast(rel.CENTER as char(3)),'p'), cast(rel.ID as varchar(8))) as PayerId,
rel.FULLNAME as PayerName
,NVL(s.BINDING_END_DATE, s.END_DATE) as JuniorEndDate 
,NVL(sr.BINDING_END_DATE, sr.END_DATE) AS PayerEndDate
, sr.OWNER_CENTER
FROM SUBSCRIPTIONS S

LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID
LEFT JOIN PRODUCTS P ON P.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND P.ID = S.SUBSCRIPTIONTYPE_ID
LEFT JOIN CENTERS c ON c.ID = p.CENTER
LEFT JOIN RELATIVES R
on 
r.CENTER = p.CENTER 
AND
r.ID = p.ID
LEFT JOIN PERSONS rel
on rel.ID = r.RELATIVEID
AND rel.CENTER = r.RELATIVECENTER

LEFT OUTER JOIN 
(
select OWNER_CENTER, OWNER_ID, END_DATE, BINDING_END_DATE FROM SUBSCRIPTIONS sr
INNER JOIN CENTERS C
ON sr.OWNER_CENTER = c.ID 
WHERE 
C.country = 'IT' AND SR.STATE IN(3,7)
) sr
on sr.OWNER_CENTER = r.RELATIVECENTER
AND sr.OWNER_ID = r.RELATIVEID
WHERE 
c.COUNTRY = 'IT' AND
--c.ID = 102 AND
p.NAME like 'Junior%' 

AND r.RTYPE = 4
AND s.STATE IN(2,4)
--GROUP BY p.ID, P.CENTER
AND sr.OWNER_CENTER IS NULL
AND r.STATUS = 2 --STATO RELAZIONE
AND rel.STATUS not in(0,9) --STATO PERSON IN RELAZIONE -0 E 9 STANNO PER LEAD E CONTATTO (CAPIRE SE SSERVONO)
ORDER BY  c.SHORTNAME, p.FULLNAME
