SELECT
    ci.ID "ATTENDANCEID",
    p.EXTERNAL_ID "PERSONID",
    ci.CHECKIN_CENTER "SITEID",
    p.CENTER "HOMESITEID",
    longToDate(ci.CHECKIN_TIME) "ATTENDANCEDATE",
    'OK' "STATUS",
    'N/A' "DENIEDREASON",
    'N/A' "DUPLICATE",
    '?' "VASOURCESYSTEM",
    'EXERP' "SOURCESYSTEM",
    '?' "EXTREF"
FROM
    CHECKINS ci
JOIN PERSONS oldP
ON
    oldP.CENTER = ci.PERSON_CENTER
    AND oldP.ID = ci.PERSON_ID
JOIN PERSONS p
ON
    p.CENTER = oldP.CURRENT_PERSON_CENTER
    AND p.ID = oldP.CURRENT_PERSON_ID
