SELECT
    par.CENTER || 'par' || par.ID "BOOKINGID",
    p.EXTERNAL_ID "PERSONID",
    par.BOOKING_CENTER || 'book' || par.BOOKING_ID "BOOKINGPRODUCTID",
    par.STATE "Status",
    longToDate(par.START_TIME) "BOOKINGSTART",
    longToDate(par.STOP_TIME) "BOOKINGEND",
    longToDate(par.CREATION_TIME) "BOOKINGDATE",
    DECODE(par.USER_INTERFACE_TYPE, 0,'OTHER', 1,'CLIENT',2,'WEB',3,'KIOSK',4,'SCRIPT','UNKNOWN') "BOOKINGMETHOD",
    'Need example' "INDUCTION",
    'Need example' "FIRSTMEETING",
    'EXERP' "SOURCESYSTEM",
    '?' "EXTREF"
FROM
    PARTICIPATIONS par
JOIN PERSONS oldP
ON
    oldP.CENTER = par.PARTICIPANT_CENTER
    AND oldP.ID = par.PARTICIPANT_ID
JOIN PERSONS p
ON
    p.CENTER = oldP.CURRENT_PERSON_CENTER
    AND p.ID = oldP.CURRENT_PERSON_ID
