SELECT
    ei.ID "CARDID",
    p.EXTERNAL_ID "PERSONID",
    ei.IDENTITY "CARDNO",
    '?' "ISSUENO",
    longToDate(ei.START_TIME) "ISSUEDATE",
    'N/A' "EXPIRYDATE",
    'EXERP' "SOURCESYSTEM",
    'N/A' "EXTREF"
FROM
    ENTITYIDENTIFIERS ei
JOIN PERSONS oldP
ON
    oldP.CENTER = ei.REF_CENTER
    AND oldP.ID = ei.REF_ID
JOIN PERSONS p
ON
    p.CENTER = oldP.CURRENT_PERSON_CENTER
    AND p.ID = oldP.CURRENT_PERSON_ID
WHERE
    ei.ENTITYSTATUS = 1
    AND ei.REF_TYPE = 1
