/* PERSON */
SELECT
    'EXERP' "SOURCESYSTEM" ,
    pv.UNIQUE_KEY "EXTREF",
    pv.UNIQUE_KEY "PERSONID",
    pv.UNIQUE_KEY "HOMEADDRESSID",
    'N/A' "WORKADDRESSID",
    pv.CENTER "SITEID",
    pv.CREATION_TIME "CREATEDDATE",
    'N/A' "MODIFIEDDATE",
    '?' "SOURCE",
    '?' "ENQUIRYTYPE",
    pv.SALUTATION "TITLE",
    pv.FIRST_NAME "FORENAME",
    pv.LAST_NAME "SURNAME",
    pv.DATE_OF_BIRTH "DOB",
    'N/A' "JOBTITLE",
    pv.GENDER "GENDER",
    'N/A' "MARITALSTATUS",
    '?' "ACCOUNTSTATUS",
    '?' "CREDITLIMIT",
    '?' "ACCOUNTENABLED",
    '?' "PROMOTION",
    '?' "DEBTBALANCE",
    pv.CREATED_BY_FIRST_NAME || ' ' || pv.CREATED_BY_LAST_NAME "CREATEDBY",
    'N/A' "EDITEDBY",
    'N/A' "COMPETITOR",
    'N/A' "CORPORATECONTACT",
    comp.EXTERNAL_ID "COMPANYID",
    'Do VA use referrers?' "REFERREDBYID",
    'ID or name?' "HEADOFFAMILY",
    '?' "STATUSDATE",
    'Person status?' "STATUS",
    '?' "SECKEY1",
    '?' "SECKEY2"
FROM
    PERSONS_VW pv
LEFT JOIN RELATIVES rel
ON
    rel.CENTER = pv.CENTER
    AND rel.ID = pv.ID
    AND rel.RTYPE = 3
    AND rel.STATUS = 1
LEFT JOIN PERSONS comp
ON
    comp.CENTER = rel.RELATIVECENTER
    AND comp.ID = rel.RELATIVEID
