SELECT
    p.EXTERNAL_ID "PERSONEMAILID",
    p.EXTERNAL_ID "PERSONID",
    'N/A' "EMAILTYPE",
    atts.TXTVALUE "EMAILADDRESS",
    'N/A' "EMAILADDRESS_CLEAN",
    '?' "LASTSEENDATE",
    '?' "LATESTSOURCESYSTEM",
    '?' "SECKEY"
FROM
    PERSON_EXT_ATTRS atts
JOIN PERSONS pOld
ON
    pOld.CENTER = atts.PERSONCENTER
    AND pOld.ID = atts.PERSONID
JOIN PERSONS p
ON
    p.CENTER = pOld.CURRENT_PERSON_CENTER
    AND p.ID = pOld.CURRENT_PERSON_ID
    /*LEFT JOIN MESSAGES m
    ON
    m.CENTER = p.CENTER
    AND m.id = p.id
    AND m.DELIVERYMETHOD = 1
    */
WHERE
    atts.NAME = '_eClub_Email'
