SELECT
    p.EXTERNAL_ID "PERSONPHONEID",
    p.EXTERNAL_ID "PERSONID",
    DECODE(atts.NAME,'_eClub_PhoneHome','HOME','_eClub_PhoneSMS','CELLULAR','UNDEFINED') "PHONETYPE",
    atts.TXTVALUE "PHONENUMBER",
    atts.TXTVALUE "PHONENUMBER_CLEAN",
    '?' "LASTSEENDATE",
    '?' "LATESTSOURCESYSTEM",
    '?' "SECKEY"
FROM
    PERSON_EXT_ATTRS atts
JOIN PERSONS pOld
ON
    pOld.CENTER = atts.PERSONCENTER
    AND pOld.ID = atts.PERSONID
JOIN PERSONS p
ON
    p.CENTER = pOld.CURRENT_PERSON_CENTER
    AND p.ID = pOld.CURRENT_PERSON_ID
WHERE
    atts.NAME IN ('_eClub_PhoneHome','_eClub_PhoneSMS')
