-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT  c.personId, CASE WHEN c1.CONSENSO IS NULL THEN c.CONSENSO ELSE c1.CONSENSO END as consenso FROM (
SELECT p.EXTERNAL_ID as personId, p.FULLNAME, 
CASE  WHEN atts.TXTVALUE = 'false' THEN 0 ELSE 1 END as consenso
FROM
    PERSON_EXT_ATTRS atts
JOIN PERSONS p
ON
    p.CENTER = atts.PERSONCENTER
    AND p.ID = atts.PERSONID
JOIN CENTERs C
ON C.ID = P.CENTER

WHERE
    atts.NAME IN ('_eClub_IsAcceptingThirdPartyOffers')
and p.SEX != 'C'
and C.COUNTRY = 'IT'
AND P.status in(2,3)) C
left outer join

(

select CONCAT(CONCAT(cast(QUN.CENTER as char(3)),'p'), cast(QUN.ID as varchar(8))) as personId, CASE WHEN qa.NUMBER_ANSWER = 1 then 1 else 0 END as consenso
from   QUESTIONNAIRE_ANSWER QUN
LEFT JOIN 
    QUESTION_ANSWER QA
 
ON
    QA.ANSWER_CENTER = QUN.CENTER
    AND QA.ANSWER_ID = QUN.ID
    AND QA.ANSWER_SUBID = QUN.SUBID

inner join
(select ANSWER_CENTER, ANSWER_ID, MAX(ANSWER_SUBID) as ANSWER_SUBID
FROM QUESTION_ANSWER QA
INNER JOIN CENTERS C
on c.ID = QA.ANSWER_CENTER
WHERE C.COUNTRY= 'IT'
AND C.ID = 101
group by ANSWER_center, ANSWER_id ) qa1
ON qa1.ANSWER_CENTER = QA.ANSWER_CENTER
AND qa1.ANSWER_ID = QA.ANSWER_ID
AND qa1.ANSWER_SUBID  = QA.ANSWER_SUBID
LEFT JOIN
    QUESTIONNAIRE_CAMPAIGNS QC
ON
    QC.ID = QUN.QUESTIONNAIRE_CAMPAIGN_ID
    --AND QC.TYPE = 3
   -- AND longToDate(qun.LOG_TIME) BETWEEN S.START_DATE AND S.END_DATE
   -- AND QC.SCOPE_TYPE = 'A'
LEFT JOIN
    QUESTIONNAIRES Q
ON
    q.ID = QC.QUESTIONNAIRE

INNER JOIN CENTERS C
ON QUN.CENTER = C.ID

where 
c.country = 'IT'

AND QA.QUESTION_ID = 3
AND QUN.CENTER = 101
--AND QUN.ID = 43
) c1
ON c.personId = c1.personId
