-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 
NVL(c3.SHORTNAME,NVL(c2.SHORTNAME,NVL(c1.SHORTNAME, c.SHORTNAME))) AS club, nvl(E2.TXTVALUE,nvl(e1.TXTVALUE,nvl(e.TXTVALUE,CONCAT(CONCAT(cast(p.CENTER as char(3)),'p'), cast(p.ID as varchar(8)))))) as personId, 
p.FULLNAME as nominativo, pr.NAME, ar.amount as importo, art.AMOUNT as importoSaldato, 
LongToDate(ar.TRANS_TIME) AS dataPagamento,ar1.TEXT,
DECODE(art.USED_RULE, 1, 'BATCH', 2, 'AMOUNT', 5, 'OLDEST', 11, 'COLLECTED', 12, 'MATCH_AMOUNT_COLLECTED') "Regola", ar1.STATUS
FROM AR_TRANS ar
LEFT OUTER JOIN ART_MATCH art
ON
art.ART_PAYING_SUBID = ar.SUBID
AND
art.ART_PAYING_ID = ar.ID
AND
art.ART_PAYING_CENTER = ar.CENTER
AND art.ART_PAYING_CENTER IS NOT NULL
LEFT OUTER JOIN AR_TRANS ar1
ON
art.ART_PAID_SUBID = ar1.SUBID
AND
art.ART_PAID_ID = ar1.ID
AND
art.ART_PAID_CENTER = ar1.CENTER
AND art.ART_PAID_CENTER IS NOT NULL
and ar1.REF_TYPE = 'INVOICE'
INNER JOIN INVOICELINES invl
ON ar1.REF_CENTER = invl.CENTER
AND ar1.REF_ID = invl.id
INNER JOIN PRODUCTS pr
ON pr.CENTER = invl.PRODUCTCENTER
AND pr.ID = invl.PRODUCTID
AND pr.PTYPE = 10
INNER JOIN CENTERS C
ON ar.CENTER = C.id
INNER JOIN ACCOUNT_RECEIVABLES A
ON a.CENTER = AR.CENTER
AND A.ID = AR.ID
INNER JOIN 
PERSONS p
ON p.ID = a.CUSTOMERID
AND
p.CENTER = a.CUSTOMERCENTER
LEFT JOIN
PERSON_EXT_ATTRS e
ON p.ID = e.PERSONID
AND p.CENTER = e.PERSONCENTER
AND e.NAME = '_eClub_TransferredToId'
LEFT JOIN CENTERS c1
on c1.id = SUBSTR(e.TXTVALUE, 1, 3)
LEFT JOIN PERSONS p1
ON CONCAT(CONCAT(cast(p1.CENTER as char(3)),'p'), cast(p1.ID as varchar(8))) = e.TXTVALUE
LEFT JOIN
PERSON_EXT_ATTRS e1
ON p1.ID = e1.PERSONID
AND p1.CENTER = e1.PERSONCENTER
AND e1.NAME = '_eClub_TransferredToId'
LEFT JOIN CENTERS c2
on c2.id = SUBSTR(e1.TXTVALUE, 1, 3)
LEFT JOIN PERSONS p2
ON CONCAT(CONCAT(cast(p2.CENTER as char(3)),'p'), cast(p2.ID as varchar(8))) = e1.TXTVALUE
LEFT JOIN
PERSON_EXT_ATTRS e2
ON p2.ID = e2.PERSONID
AND p2.CENTER = e2.PERSONCENTER
AND e2.NAME = '_eClub_TransferredToId'
LEFT JOIN CENTERS c3
on c3.id = SUBSTR(e2.TXTVALUE, 1, 3)


WHERE
c.COUNTRY = 'IT'

AND
Extract(MONTH FROM LongToDate(ar.TRANS_TIME)) = Extract(MONTH FROM ADD_MONTHS(SYSDATE,-1))
--Extract(MONTH FROM LongToDate(ar.TRANS_TIME)) IN(10,11,12)
AND
Extract(YEAR FROM LongToDate(ar.TRANS_TIME)) = Extract(YEAR FROM ADD_MONTHS(SYSDATE,-1))
--Extract(YEAR FROM LongToDate(ar.TRANS_TIME))= 2016
--AND p.CENTER = 101
AND ar.TEXT = 'Payment into account'
--AND p.CENTER = 101
--AND p.ID = 10017
AND ar1.TEXT NOT LIKE 'Rimb%' and ar1.TEXT NOT LIKE 'Insoluto%'
AND ar1.TEXT NOT LIKE 'Payment into account' AND ar1.TEXT NOT LIKE 'Payment revoked by clearing house%'
AND ar1.TEXT NOT LIKE 'Transfer to cash collection account%'
AND art.USED_RULE IN(2,5)
AND ar1.STATUS = 'CLOSED'

ORDER BY NVL(c3.SHORTNAME,NVL(c2.SHORTNAME,NVL(c1.SHORTNAME, c.SHORTNAME))), p.FULLNAME