SELECT
i.IDENTITY, i.REF_GLOBALID, r.CACHED_EXTERNAL_ID, r.STATE

FROM ENTITYIDENTIFIERS i
INNER JOIN
MASTERPRODUCTREGISTER r
ON i.REF_GLOBALID = r.GLOBALID
WHERE 
--ROWNUM < 100 
--AND IDMETHOD = 1 
--AND REF_CENTER = 101 
--AND
 i.REF_TYPE = 4
AND 
i.SCOPE_ID = 24
GROUP BY i.IDENTITY, i.REF_GLOBALID, r.CACHED_EXTERNAL_ID, r.STATE

ORDER BY CACHED_EXTERNAL_ID, i.REF_GLOBALID, i.IDENTITY, r.STATE