-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT c.SHORTNAME AS CLUB, CONCAT(CONCAT(cast(P.CENTER AS CHAR(3)),'p'), CAST(P.ID AS varchar(6))) as personId, P.FULLNAME AS SOCIO, 
          CASE P.STATUS  WHEN 1 THEN  'ACTIVE' WHEN 3 THEN 'TEMPORARY INACTIVE' END AS 
        STATUS, CASE P.PERSONTYPE WHEN 0 THEN 'PRIVATE' WHEN 1 THEN 'STUDENT' WHEN 2 THEN 'STAFF' WHEN 3 THEN 'FRIEND' WHEN 4 THEN 'CORPORATE' WHEN 5 THEN 'ONE MAN CORPORATE' WHEN 6  THEN 'FAMILY' WHEN 7 THEN 'SENIOR' WHEN 8 THEN 'GUEST' WHEN 9 THEN 'UNKNOWN' END AS PERSONTYPE, 
		TRIM(PEA3.TXTVALUE) as Email, UPPER(TRIM(PEA3.TXTVALUE)) ~* '^[A-Z0-9._%-]+@[A-Z0-9._%-]+\.[A-Z]{2,64}$' AS isValidEmail
    from PERSONS P LEFT 
  
    join PERSON_EXT_ATTRS PEA3 ON PEA3.PERSONCENTER = 
        P.CURRENT_PERSON_CENTER AND PEA3.PERSONID = P.CURRENT_PERSON_ID 
        AND PEA3.NAME = '_eClub_Email'  
	JOIN CENTERS C ON p.CENTER = C.ID
	WHERE c.COUNTRY = 'IT'
	AND P.STATUS IN(1,3)
	AND p.PERSONTYPE IN(0,1,2,3,4,5,6,7,8,9)
	AND LENGTH(TRIM(PEA3.TXTVALUE)) > 0 
	ORDER BY c.SHORTNAME,CONCAT(CONCAT(cast(P.CENTER AS CHAR(3)),'p'), CAST(P.ID AS varchar(6))) 