SELECT

DISTINCT  CONCAT(CONCAT(cast(p1.CENTER as char(3)),'p'), cast(p1.ID as varchar(8))) as personId,
art.TEXT,
CASE WHEN pr.CLEARINGHOUSE_ID = 803 THEN '99' ELSE '02' END as PAYMENT_METHOD,
c.EXTERNAL_ID,
agr.TEXT,
ROUND(art.AMOUNT * -1,2) as OPEN_AMOUNT,
pr.REQ_DATE AS DUE_DATE,
longtodate(art.ENTRY_TIME) as BOOK_DATE,
vat.EXTERNAL_ID AS VAT_TYPE,
vat.RATE AS VAT_RATE

 FROM 


	PERSONS p1


JOIN 
ACCOUNT_RECEIVABLES ar
on
 ar.CUSTOMERCENTER = p1.CENTER
    AND ar.CUSTOMERID = p1.ID
AND ar.AR_TYPE = 4

LEFT 
	JOIN PAYMENT_ACCOUNTS pac
ON
    pac.CENTER = ar.CENTER
    AND pac.ID = ar.ID
  
LEFT JOIN
    PAYMENT_REQUESTS pr
ON
  pr.CENTER = ar.CENTER
    AND pr.ID = ar.id  


LEFT JOIN
    PAYMENT_REQUEST_SPECIFICATIONS prs
ON
    pr.INV_COLL_CENTER = prs.CENTER
    AND pr.INV_COLL_ID = prs.ID
    AND pr.INV_COLL_SUBID = prs.SUBID
LEFT JOIN
 
 AR_TRANS  art
ON 
art.PAYREQ_SPEC_CENTER = prs.CENTER
AND
art.PAYREQ_SPEC_ID = prs.ID
AND
art.PAYREQ_SPEC_SUBID = prs.SUBID

LEFT JOIN ACCOUNT_TRANS act
    ON act.CENTER = art.REF_CENTER
	AND act.ID = art.REF_ID
	AND act.SUBID = art.REF_SUBID
LEFT JOIN AGGREGATED_TRANSACTIONS agr
	ON agr.CENTER = act.AGGREGATED_TRANSACTION_CENTER
    AND agr.ID = act.AGGREGATED_TRANSACTION_ID

LEFT JOIN

ART_MATCH am
ON 
am.ART_PAID_CENTER = art.CENTER
AND
am.ART_PAID_ID = art.ID
AND
am.ART_PAID_SUBID = art.SUBID
LEFT JOIN
AR_TRANS art1
ON 
am.ART_PAYING_CENTER = art1.CENTER
AND
am.ART_PAYING_ID = art1.ID
AND
am.ART_PAYING_SUBID = art1.SUBID
LEFT JOIN ACCOUNT_TRANS act1
    ON act1.CENTER = art1.REF_CENTER
	AND act1.ID = art1.REF_ID
	AND act1.SUBID = art1.REF_SUBID
LEFT JOIN AGGREGATED_TRANSACTIONS agr1
	ON agr1.CENTER = act1.AGGREGATED_TRANSACTION_CENTER
    AND agr1.ID = act1.AGGREGATED_TRANSACTION_ID


INNER JOIN
CENTERS c ON
art.CENTER = c.ID

LEFT JOIN INVOICELINES invl
 on invl.ID = art1.REF_ID
AND invl.CENTER = art1.REF_CENTER

LEFT JOIN ACCOUNT_TRANS act2
    ON act2.CENTER = invl.VAT_ACC_TRANS_CENTER

	AND act2.ID = invl.VAT_ACC_TRANS_ID
	AND act2.SUBID = invl.VAT_ACC_TRANS_SUBID
LEFT JOIN VAT_TYPES vat
	ON vat.CENTER = act2.VAT_TYPE_CENTER
    AND vat.ID = act2.VAT_TYPE_ID

WHERE 

art.DUE_DATE <= LAST_DAY(ADD_MONTHS(SYSDATE,-2))


AND
EXTRACT(MONTH FROM LongToDate(art.ENTRY_TIME)) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))
AND
EXTRACT(YEAR FROM LongToDate(art.ENTRY_TIME)) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1))
AND c.COUNTRY = 'IT'



