WITH
    params AS
    (
        SELECT
            DECODE($$offset$$,-1,0,(TRUNC(SYSDATE)-$$offset$$-to_date('1-1-1970 00:00:00','MM-DD-YYYY HH24:Mi:SS'))*24*3600*1000) AS FROMDATE,
            (TRUNC(SYSDATE+1)-to_date('1-1-1970 00:00:00','MM-DD-YYYY HH24:Mi:SS'))*24*3600*1000                                 AS TODATE
        FROM
            dual
    )
SELECT
SUB_STATE_CHANGE_ID,
SUBSCRIPTION_CENTER_ID,
SUSBCRIPTION_ID,
STATE,
SUB_STATE,
ENTRY_START_TIME,
ENTRY_END_TIME,
NEXT_SUB_STATE_CHANGE_ID,
CENTER_ID
FROM
    params,
    BI_SUBSCRIPTION_STATE_LOG biview
WHERE
    biview.ETS BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE