-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT c.SHORTNAME as club, CONCAT(CONCAT(cast(p.CENTER as char(3)),'p'), cast(p.ID as varchar(8))) as personId, p.FULLNAME as nominativo, pr.NAME as abbonamentoConcluso, pr1.NAME AS nuovoAbbonamento, s1.START_DATE as dataInizioNuovoAbbonamento, s.END_DATE as dataFineVecchioAbbonamneto, ss.SALES_DATE as dataVendita from 
SUBSCRIPTIONS s
INNER JOIN PERSONS p
on
s.owner_center = p.CENTER AND s.owner_id = p.ID
INNER JOIN CENTERS c
ON c.ID = p.CENTER
INNER JOIN PRODUCTS PR 
ON
PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID
INNER  JOIN
PRODUCT_AND_PRODUCT_GROUP_LINK ppgl


on pr.CENTER  = ppgl.product_center
and pr.id = ppgl.product_id
INNER JOIN PRODUCT_GROUP PG
on pg.ID = ppgl.PRODUCT_GROUP_ID

INNER JOIN SUBSCRIPTIONS s1
ON s1.owner_center = p.CENTER AND s1.owner_id = p.ID
INNER JOIN SUBSCRIPTION_SALES ss
ON ss.SUBSCRIPTION_ID = s1.ID
AND
ss.SUBSCRIPTION_CENTER = s1.CENTER
INNER JOIN PRODUCTS PR1 
ON
PR1.CENTER = S1.SUBSCRIPTIONTYPE_CENTER AND PR1.ID = S1.SUBSCRIPTIONTYPE_ID
INNER  JOIN (
SELECT
ppgl.product_center, ppgl.product_id
FROM
PRODUCT_AND_PRODUCT_GROUP_LINK ppgl
INNER JOIN PRODUCT_GROUP pg
ON
pg.ID = ppgl.PRODUCT_GROUP_ID
GROUP BY
ppgl.product_center, ppgl.product_id
HAVING MAX(EXCLUDE_FROM_MEMBER_COUNT) = 0) ppgl1


on pr1.CENTER  = ppgl1.product_center
and pr1.id = ppgl1.product_id



 
WHERE 
pg.EXCLUDE_FROM_MEMBER_COUNT = 1


AND ((
EXTRACT(YEAR FROM s.END_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-2)) 
AND
EXTRACT(MONTH FROM s.END_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-2)))
OR
(
EXTRACT(YEAR FROM s.END_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1)) 
AND
EXTRACT(MONTH FROM s.END_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))) 
AND c.COUNTRY = 'IT'

AND 
EXTRACT(YEAR FROM ss.SALES_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,-1)) 
AND
EXTRACT(MONTH FROM ss.SALES_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)) 
AND  ss.SALES_DATE <= TRUNC(S.END_DATE) + INTERVAL '30' DAY
AND c.COUNTRY = 'IT'




ORDER BY c.SHORTNAME,  p.FULLNAME