-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 
 "ID EXERP SOCIO" as PersonId,
 "CAUSALE DROP" as DropMotivazione,
"DATA RICHIESTA CANCELLAZIONE" as DropDataRichiesta,
  "DATA FINE ABBONAMENTO" as DropData
 FROM(
  SELECT 
DISTINCT 
cc.center, cc.id,
concat(concat(cast(s.center as varchar(4)),'ss'),cast(s.ID as varchar(6))) as NUMEROABBONAMENTO,
p.FIRSTNAME AS NOME,
P.LASTNAME AS COGNOME,
 FLOOR((TRUNC(SYSDATE) - P.BIRTHDATE) /365.242199) AS ETA,
  PR.NAME AS PRODOTTO, 
  S.SUBSCRIPTION_PRICE AS "PREZZO ABBONAMENTO",
 S.START_DATE AS "DATA INIZIO ABBONAMENTO", 
 S.END_DATE AS "DATA FINE ABBONAMENTO",
DECODE (s.STATE, 2,'ACTIVE', 3,'ENDED', 4,'FROZEN', 7,'WINDOW', 8,'CREATED','UNKNOWN') AS STATE,
DECODE (s.SUB_STATE, 1,'NONE', 2,'AWAITING_ACTIVATION', 3,'UPGRADED', 4,'DOWNGRADED', 5,'EXTENDED', 6, 'TRANSFERRED',7,'REGRETTED',8,'CANCELLED',9,'BLOCKED','UNKNOWN') AS SUB_STATE,
 CASE WHEN CK.ID IS NULL THEN NULL ELSE CK.CHECKINS END AS INGRESSI,
  CASE WHEN CK.ID IS NULL THEN NULL ELSE CK.LAST_CHECKIN END AS "ULTIMO INGRESSO",
 concat(concat(cast(P.CENTER as char(3)),'p'), cast(P.ID as varchar(10))) as "ID EXERP SOCIO",
email.TXTVALUE as EMAIL,
home.TXTVALUE as TELEFONO,
mobile.TXTVALUE as CELLULARE,
LEAVING_REASON as "CAUSALE DROP",
 q.ANSWER_DATE as "DATA RICHIESTA CANCELLAZIONE", 
 case when op.ID IS NOT NULL THEN cc2.AMOUNT ELSE cc.AMOUNT END AS INSOLUTO,
  CASE
                WHEN salesPersonOverride.CENTER IS NOT NULL
                    AND (salesPersonOverride.CENTER <> salesperson.CENTER
                        OR salesPersonOverride.ID <> salesperson.ID)
                THEN salesPersonOverride.FULLNAME
                ELSE salesperson.FULLNAME
            END MC,
			payer.FULLNAME as TITOLARE,
			 concat(concat(cast(Payer.CENTER as char(3)),'p'), cast(Payer.ID as varchar(10))) as "ID EXERP TITOòLARE"
FROM SUBSCRIPTIONS S
LEFT JOIN
    INVOICELINES invl
ON
    invl.CENTER = s.INVOICELINE_CENTER
    AND invl.ID = s.INVOICELINE_ID
	AND invl.SUBID = s.INVOICELINE_SUBID
LEFT JOIN
    INVOICES inv
ON
    inv.CENTER = invl.CENTER
    AND inv.ID = INVL.id
 LEFT JOIN
            PERSON_EXT_ATTRS email
        ON
            s.owner_center = email.PERSONCENTER
            AND s.owner_id = email.PERSONID
            AND email.name = '_eClub_Email'
LEFT JOIN
            PERSON_EXT_ATTRS home
        ON
            s.owner_center = home.PERSONCENTER
            AND s.owner_id = home.PERSONID
            AND home.name = '_eClub_PhoneHome'
        LEFT JOIN
            PERSON_EXT_ATTRS mobile
        ON
            s.owner_center = mobile.PERSONCENTER
            AND s.owner_id = mobile.PERSONID
            AND mobile.name = '_eClub_PhoneSMS'
LEFT JOIN PERSONS Payer
ON inv.PAYER_CENTER =  payer.CENTER
AND inv.PAYER_ID = payer.ID

LEFT JOIN SUBSCRIPTION_SALES SS
on S.ID = SS.SUBSCRIPTION_ID AND S.CENTER = SS.SUBSCRIPTION_CENTER
LEFT JOIN
            EMPLOYEES emp
        ON
            ss.EMPLOYEE_CENTER = emp.CENTER
            AND ss.EMPLOYEE_ID = emp.ID
LEFT JOIN
            PERSONS salesperson
        ON
            salesperson.CENTER = emp.PERSONCENTER
            AND salesperson.ID = emp.PERSONID
        LEFT JOIN
            PERSON_EXT_ATTRS salesPersonOverrideExt
        ON
            s.owner_center = salesPersonOverrideExt.PERSONCENTER
            AND s.owner_id = salesPersonOverrideExt.PERSONID
            AND salesPersonOverrideExt.name = 'MC_IT'
        LEFT JOIN
            PERSONS salesPersonOverride
        ON
            salesPersonOverride.CENTER || 'p' || salesPersonOverride.ID = salesPersonOverrideExt.TXTVALUE
LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID
LEFT JOIN CENTERS c
ON c.ID = p.CENTER
LEFT JOIN
    RELATIVES rel
ON
    rel.RTYPE = 12
    AND rel.STATUS = 1
    AND rel.RELATIVECENTER = p.CENTER
    AND rel.RELATIVEID = p.ID
LEFT JOIN
    PERSONS op
ON
    op.CENTER = rel.CENTER
    AND op.ID = rel.ID
LEFT JOIN PRODUCTS PR ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID
LEFT  JOIN
PRODUCT_AND_PRODUCT_GROUP_LINK ppgl

on pr.CENTER  = ppgl.product_center
and pr.id = ppgl.product_id


LEFT JOIN
    CASHCOLLECTIONCASES
 cc
ON
    cc.PERSONCENTER = p.CENTER
    AND cc.PERSONID = p.id
	AND cc.MISSINGPAYMENT = 1 AND cc.CLOSED = 0
 
LEFT JOIN
    CASHCOLLECTIONCASES cc2
ON
    cc2.PERSONCENTER = op.CENTER
    AND cc2.PERSONID = op.ID
    AND cc2.CLOSED = 0
    AND cc2.MISSINGPAYMENT = 1
	
LEFT JOIN
(
SELECT Q2.* FROM(
(SELECT MAX(QUN.SUBID) AS SUBID, QUN.CENTER, QUN.ID  FROM    QUESTIONNAIRE_ANSWER QUN
INNER JOIN CENTERS
c
ON c.ID = qun.CENTER
INNER JOIN SUBSCRIPTIONS S
ON S.OWNER_CENTER = QUN.CENTER AND S.OWNER_ID = QUN.ID
LEFT JOIN 
    QUESTION_ANSWER QA
ON
    QA.ANSWER_CENTER = QUN.CENTER
    AND QA.ANSWER_ID = QUN.ID
    AND QA.ANSWER_SUBID = QUN.SUBID
LEFT JOIN
    QUESTIONNAIRE_CAMPAIGNS QC
ON
    QC.ID = QUN.QUESTIONNAIRE_CAMPAIGN_ID
    AND QC.TYPE = 3
    AND exerpro.longToDate(qun.LOG_TIME) BETWEEN S.START_DATE AND S.END_DATE
    AND QC.SCOPE_TYPE = 'A'
LEFT JOIN
    QUESTIONNAIRES Q
ON
    q.ID = QC.QUESTIONNAIRE
WHERE
 c.COUNTRY = 'IT'  
 
 and q.questions is not null
AND S.END_DATE >= TRUNC(SYSDATE) - 30 AND S.END_DATE IS NOT NULL
AND S.SUB_STATE IN(1,9)
GROUP BY  QUN.CENTER, QUN.ID) Q1
INNER JOIN 
(select concat(concat(cast(qun.center as char(3)),'p'),cast(qun.id as varchar(10))) as PERSONID, QC.STARTDATE, QC.STOPDATE, exerpro.longToDate(qun.LOG_TIME) as answerDate, case when q.QUESTIONS IS NOT NULL AND qa.QUESTION_ID IS NOT NULL AND qa.NUMBER_ANSWER IS NOT NULL then EXTRACTVALUE(xmltype(
            CASE
            WHEN length(q.QUESTIONS) < 2001 
            THEN UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(q.QUESTIONS, 4000,1), 'UTF8') 
            ELSE UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(q.QUESTIONS, 2000,1), 'UTF8') || UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(q.QUESTIONS, 2000,2001), 'UTF8') 
            END
            ), '//question[id/text()='||TO_CHAR(qa.QUESTION_ID)||']/options/option[id/text()='||TO_CHAR(qa.NUMBER_ANSWER)||']/optionText') end
as LEAVING_REASON, QUN.ID, QUN.CENTER, QUN.SUBID, exerpro.longToDate(qun.LOG_TIME) AS ANSWER_DATE
from   QUESTIONNAIRE_ANSWER QUN
INNER JOIN CENTERS c
ON
c.ID = qun.CENTER
INNER JOIN SUBSCRIPTIONS S
ON S.OWNER_CENTER = QUN.CENTER AND S.OWNER_ID = QUN.ID
LEFT JOIN 
    QUESTION_ANSWER QA
ON
    QA.ANSWER_CENTER = QUN.CENTER
    AND QA.ANSWER_ID = QUN.ID
    AND QA.ANSWER_SUBID = QUN.SUBID
LEFT JOIN
    QUESTIONNAIRE_CAMPAIGNS QC
ON
    QC.ID = QUN.QUESTIONNAIRE_CAMPAIGN_ID
    AND QC.TYPE = 3
    AND exerpro.longToDate(qun.LOG_TIME) BETWEEN S.START_DATE AND S.END_DATE
    AND QC.SCOPE_TYPE = 'A'
LEFT JOIN
    QUESTIONNAIRES Q
ON
    q.ID = QC.QUESTIONNAIRE


	

where   
c.COUNTRY = 'IT' 
and q.questions is not null
AND S.END_DATE >= TRUNC(SYSDATE)-30 AND S.END_DATE IS NOT NULL
AND S.SUB_STATE IN(1,9)) Q2
ON Q1.ID = Q2.ID AND Q1.SUBID = Q2.SUBID AND Q1.CENTER = Q2.CENTER)



) Q
ON Q.ID = P.ID AND Q.CENTER = P.CENTER
LEFT OUTER JOIN 
(
SELECT COUNT(*) AS CHECKINS, MAX(CHECKIN_TIME) AS LAST_CHECKIN,
CENTER, ID
FROM(
SELECT  
 P.ID, P.CENTER,  EXERPRO.LONGTODATE(CHECKIN_TIME) AS CHECKIN_TIME

FROM 
persons p
INNER JOIN
CENTERS ce
ON ce.ID = p.CENTER
INNER JOIN 
 subscriptions s
ON S.OWNER_CENTER = P.CENTER AND S.OWNER_ID = P.ID
INNER JOIN 
CHECKINS C
ON P.ID = C.PERSON_ID AND P.CENTER = C.PERSON_CENTER
AND EXERPRO.LONGTODATE(C.CHECKIN_TIME) >= S.START_DATE 
where 
ce.COUNTRY= 'IT'
AND S.END_DATE >= TRUNC(SYSDATE) -30 AND S.END_DATE IS NOT NULL

and CHECKIN_RESULT = 1

GROUP BY P.ID, P.CENTER, EXERPRO.LONGTODATE(CHECKIN_TIME)) P
GROUP  BY CENTER, ID
) CK

ON P.CENTER = CK.CENTER AND P.ID = CK.ID


--AND ppgl.PRODUCT_GROUP_ID  = 7601
WHERE 

C.COUNTRY = 'IT' 
AND S.END_DATE >= TRUNC(SYSDATE) -30 AND S.END_DATE IS NOT NULL
AND S.SUB_STATE IN(1,9) AND (Q.ANSWER_DATE IS NULL OR Q.ANSWER_DATE BETWEEN S.START_DATE AND S.END_DATE)
AND (pr.NAME LIKE 'Open%'
 OR ppgl.PRODUCT_GROUP_ID  IN(7601,5409)
OR pr.NAME LIKE 'Corporate%'
 OR pr.NAME LIKE 'DT%'
 OR pr.NAME LIKE 'Partnership%'
 OR pr.NAME LIKE 'Senior%'
 OR pr.NAME LIKE 'Young%'
  OR pr.NAME LIKE 'Flexi%'
   OR pr.NAME LIKE 'Active%'
)
AND S.END_DATE >= TRUNC(SYSDATE) -30 AND S.END_DATE IS NOT NULL) p
GROUP BY 
"DATA FINE ABBONAMENTO",
"ID EXERP SOCIO",
"CAUSALE DROP",
"DATA RICHIESTA CANCELLAZIONE"