	SELECT p.PERSONID, p.ANSWER, p.CAMPAIGN_ID, p.QUESTION_ID from (
SELECT CONCAT(CONCAT(CAST(qa.CENTER as CHAR(3)),'p'), CAST(qa.ID as VARCHAR(6))) as personId, qa.SUBID, CASE WHEN SUBSTR(qa.RESULT_CODE,1,1) IN('Y','S') THEN 'Sì' ELSE 'No' END  as ANSWER, qa.QUESTIONNAIRE_CAMPAIGN_ID as CAMPAIGN_ID, 1 as QUESTION_ID FROM    
QUESTIONNAIRE_ANSWER qa
INNER JOIN
QUESTIONNAIRE_CAMPAIGNS
 qc
ON qa.QUESTIONNAIRE_CAMPAIGN_ID
 = qc.ID

 WHERE
qa.QUESTIONNAIRE_CAMPAIGN_ID IN(1001, 1401, 2001, 2401)

UNION ALL

SELECT CONCAT(CONCAT(CAST(qa.CENTER as CHAR(3)),'p'), CAST(qa.ID as VARCHAR(6))) as personId,qa.SUBID, CASE WHEN SUBSTR(qa.RESULT_CODE,2,1) IN('Y','S')  THEN 'Sì' ELSE 'No' END  as ANSWER, qa.QUESTIONNAIRE_CAMPAIGN_ID as CAMPAIGN_ID, 2 as QUESTION_ID FROM    
QUESTIONNAIRE_ANSWER qa
INNER JOIN
QUESTIONNAIRE_CAMPAIGNS
 qc
ON qa.QUESTIONNAIRE_CAMPAIGN_ID
 = qc.ID

 WHERE
qa.QUESTIONNAIRE_CAMPAIGN_ID IN(1001, 1401, 2001, 2401)

UNION ALL

SELECT CONCAT(CONCAT(CAST(qa.CENTER as CHAR(3)),'p'), CAST(qa.ID as VARCHAR(6))) as personId,qa.SUBID, CASE WHEN SUBSTR(qa.RESULT_CODE,3,1) IN('Y','S')  THEN 'Sì' ELSE 'No' END  as ANSWER, qa.QUESTIONNAIRE_CAMPAIGN_ID as CAMPAIGN_ID, 3 as QUESTION_ID FROM    
QUESTIONNAIRE_ANSWER qa
INNER JOIN
QUESTIONNAIRE_CAMPAIGNS
 qc
ON qa.QUESTIONNAIRE_CAMPAIGN_ID
 = qc.ID

 WHERE
qa.QUESTIONNAIRE_CAMPAIGN_ID IN(1001, 1401, 2001, 2401)

UNION ALL

SELECT CONCAT(CONCAT(CAST(qa.CENTER as CHAR(3)),'p'), CAST(qa.ID as VARCHAR(6))) as personId,qa.SUBID, CASE WHEN SUBSTR(qa.RESULT_CODE,4,1) IN('Y','S')  THEN 'Sì' ELSE 'No' END  as ANSWER, qa.QUESTIONNAIRE_CAMPAIGN_ID as CAMPAIGN_ID, 4 as QUESTION_ID FROM    
QUESTIONNAIRE_ANSWER qa
INNER JOIN
QUESTIONNAIRE_CAMPAIGNS
 qc
ON qa.QUESTIONNAIRE_CAMPAIGN_ID
 = qc.ID

 WHERE
qa.QUESTIONNAIRE_CAMPAIGN_ID IN(2001, 2401)

UNION ALL

SELECT CONCAT(CONCAT(CAST(qa.CENTER as CHAR(3)),'p'), CAST(qa.ID as VARCHAR(6))) as personId, qa.SUBID,CASE WHEN SUBSTR(qa.RESULT_CODE,5,1) IN('Y','S')  THEN 'Sì' ELSE 'No' END  as ANSWER, qa.QUESTIONNAIRE_CAMPAIGN_ID as CAMPAIGN_ID, 5 as QUESTION_ID FROM    
QUESTIONNAIRE_ANSWER qa
INNER JOIN
QUESTIONNAIRE_CAMPAIGNS
 qc
ON qa.QUESTIONNAIRE_CAMPAIGN_ID
 = qc.ID

 WHERE
qa.QUESTIONNAIRE_CAMPAIGN_ID IN(2001, 2401)) p
INNER JOIN

(select CONCAT(CONCAT(CAST(CENTER as CHAR(3)),'p'), CAST(ID as VARCHAR(6))) as personId, QUESTIONNAIRE_CAMPAIGN_ID, MAX(SUBID) as SUBID
FROM QUESTIONNAIRE_ANSWER
where QUESTIONNAIRE_CAMPAIGN_ID  IN(1001, 1401, 2001, 2401)
GROUP BY CONCAT(CONCAT(CAST(CENTER as CHAR(3)),'p'), CAST(ID as VARCHAR(6))), QUESTIONNAIRE_CAMPAIGN_ID)
q
ON p.personid =q.personId AND p.CAMPAIGN_ID = q.QUESTIONNAIRE_CAMPAIGN_ID AND p.SUBID = q.SUBID


