SELECT
STAFF_USAGE_ID,
BOOKING_ID,
CENTER_ID,
PERSON_ID,
STATE,
START_DATE_TIME,
STOP_DATE_TIME,
SALARY
FROM
    BI_STAFF_USAGE biview
WHERE
    (to_date('19700101', 'YYYYMMDD') 
+ ( 1 / 24 / 60 / 60 / 1000) 
* biview.ETS) BETWEEN $$FROMDATE$$ AND $$TODATE$$
	and biview.CENTER_ID in ($$scope$$)