SELECT
VISIT_ID,
CENTER_ID,
PERSON_ID,
HOME_CENTER_ID,
CHECK_IN_DATE,
CHECK_IN_TIME,
CHECK_OUT_DATE,
CHECK_OUT_TIME,
CHECK_IN_RESULT,
CARD_CHECKED_IN

FROM
    BI_VISIT_LOG biview
WHERE
    biview.ETS BETWEEN $$FROMDATE$$ AND $$TODATE$$
    and biview.CENTER_ID in ($$scope$$)