-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT P.CENTER as "OLDPERSONCENTER", P.ID as "OLDPERSONID", TRANSFERS_CURRENT_PRS_CENTER as "NEWPERSONCENTER", TRANSFERS_CURRENT_PRS_ID as "NEWPERSONID", s.END_DATE AS "END_DATE" FROM SUBSCRIPTIONS S LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID
 LEFT JOIN CENTERS c
 ON c.ID = P.CENTER
  WHERE
 c.COUNTRY = 'IT'
  AND S.END_DATE >= TRUNC(CURRENT_TIMESTAMP) - 30 AND S.END_DATE <= TRUNC(CURRENT_TIMESTAMP)
  AND P.STATUS = 4 AND S.STATE = 3
