SELECT
PARTICIPATION_ID,
BOOKING_ID,
CENTER_ID,
PERSON_ID,
CREATION_DATE_TIME,
STATE,
USER_INTERFACE_TYPE,
SHOW_UP_TIME,
SHOW_UP_INTERFACE_TYPE,
SHOWUP_USING_CARD,
CANCEL_TIME,
CANCEL_INTERFACE_TYPE,
CANCEL_REASON,
WAS_ON_WAITING_LIST

FROM
	BI_PARTICIPATIONS biview
WHERE
    biview.ETS BETWEEN $$FROMDATE$$ AND $$TODATE$$
	and biview.CENTER_ID in ($$scope$$)