SELECT

COMPANY_ID,
HOME_CENTER_ID,
NAME,
COUNTRY_ID,
POSTAL_CODE,
CITY,
ACCOUNT_MANAGER_ID,
STATUS,
COUNTY,
STATE

FROM
    BI_COMPANIES biview
WHERE
    (to_date('19700101', 'YYYYMMDD') 
+ ( 1 / 24 / 60 / 60 / 1000) 
* biview.ETS) BETWEEN $$FROMDATE$$ AND $$TODATE$$
	and biview.COUNTRY_ID = 'GB'