SELECT ex.* FROM(
SELECT CONCAT(CONCAT(CAST(prod.CENTER as CHAR(3)),'p'),CAST(prod.ID as VARCHAR(10))) as productId, prod.NAME FROM  SUBSCRIPTIONTYPES st
JOIN PRODUCTS prod
        ON
            prod.CENTER = st.CENTER
            AND prod.ID = st.ID
INNER
JOIN CENTERS c 
ON st.CENTER = c.ID
INNER JOIN

PRODUCT_AND_PRODUCT_GROUP_LINK ppl
ON ppl.PRODUCT_ID = prod.ID
AND
ppl.PRODUCT_CENTER = prod.CENTER
 

INNER JOIN PRODUCT_GROUP pg
ON pg.ID = ppL.PRODUCT_GROUP_ID
WHERE c.COUNTRY = 'IT'
AND pg.EXCLUDE_FROM_MEMBER_COUNT = 1
GROUP BY CONCAT(CONCAT(CAST(prod.CENTER as CHAR(3)),'p'),CAST(prod.ID as VARCHAR(10))), prod.NAME) ex
LEFT OUTER JOIN (
SELECT CONCAT(CONCAT(CAST(prod.CENTER as CHAR(3)),'p'),CAST(prod.ID as VARCHAR(10))) as productId, prod.NAME  FROM  SUBSCRIPTIONTYPES st
JOIN PRODUCTS prod
ON
            prod.CENTER = st.CENTER
            AND prod.ID = st.ID
INNER
JOIN CENTERS c 
ON st.CENTER = c.ID
INNER JOIN
PRODUCT_AND_PRODUCT_GROUP_LINK ppl
ON ppl.PRODUCT_ID = prod.ID
AND
ppl.PRODUCT_CENTER = prod.CENTER
INNER JOIN PRODUCT_GROUP pg
ON pg.ID = ppL.PRODUCT_GROUP_ID
WHERE c.COUNTRY = 'IT'
AND (pg.NAME = 'Corporate')
GROUP BY CONCAT(CONCAT(CAST(prod.CENTER as CHAR(3)),'p'),CAST(prod.ID as VARCHAR(10))), prod.NAME) corp
ON ex.productId = corp.productId
WHERE corp.productId IS NULL
and ex.NAME NOT LIKE 'Ospite%'



