-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT
 c.SHORTNAME as Club,
 CONCAT(CONCAT(cast(p.CENTER as char(3)),'p'), cast(p.ID as varchar(8))) as persondId, p.FULLNAME as nominativo,
 pa.BANK_ACCNO,
 pa.BANK_ACCOUNT_DETAILS,
 pa.BANK_ACCOUNT_HOLDER,
 pa.BANK_BRANCH_NO,
 pa.BANK_CONTROL_DIGITS,
 pa.BANK_NAME,
 pa.BANK_REGNO,
 pa.IBAN,
 pa.BIC,
 pa.REF
 FROM
         PERSONS p
 INNER JOIN
 ACCOUNT_RECEIVABLES ar
 on
  ar.CUSTOMERCENTER = p.CENTER
     AND ar.CUSTOMERID = p.ID
 AND ar.AR_TYPE = 4
 INNER JOIN PAYMENT_ACCOUNTS pac
 ON
     pac.CENTER = ar.CENTER
     AND pac.ID = ar.ID
 INNER JOIN
         PAYMENT_AGREEMENTS pa
 ON
     pa.CENTER = pac.ACTIVE_AGR_CENTER
     AND pa.ID = pac.ACTIVE_AGR_ID
         AND pa.SUBID = pac.ACTIVE_AGR_SUBID
 INNER JOIN CENTERS c
 ON p.CENTER = c.ID
 WHERE
 c.COUNTRY = 'IT'
 AND
 pa.CLEARINGHOUSE != 803
 AND
 p.CENTER = 102
 AND
 p.ID = 3130
 ORDER BY c.SHORTNAME, p.FULLNAME
