-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT CONCAT(CONCAT(cast(s.CENTER as char(3)),'p'), cast(s.ID as varchar(8))) as personId, s.FULLNAME, prod.Name as subName,  s.NSub, s1.START_DATE, s1.END_DATE, s1.BINDING_END_DATE
 FROM (
 select
 p.CENTER, p.ID, p.EXTERNAL_ID, p.FULLNAME, count(*) as nSub
  from
 SUBSCRIPTIONS s
         JOIN PERSONS p ON
  p.CENTER = S.OWNER_CENTER
  AND
  p.ID = s.OWNER_ID
 JOIN PRODUCTS prod
 ON
 prod.CENTER = s.SUBSCRIPTIONTYPE_CENTER
 AND prod.ID = s.SUBSCRIPTIONTYPE_ID
 join SUBSCRIPTIONTYPES st on st.CENTER = s.SUBSCRIPTIONTYPE_CENTER and st.ID = s.SUBSCRIPTIONTYPE_ID
 join PRODUCT_GROUP pg on pg.ID = prod.PRIMARY_PRODUCT_GROUP_ID
 join CENTERS c
 ON  s.CENTER = c.ID
 WHERE
 --ROWNUM < 10
 c.COUNTRY = 'IT'
 and s.STATE = 2
 and (s.SUB_STATE = 1 OR s.SUB_STATE IS NULL)
 --and prod.PRICE > 0
 --and p.FULLNAME = 'Andrea Sanna'
 GROUP BY p.EXTERNAL_ID, p.FULLNAME, p.CENTER, p.ID
 HAVING COUNT(*) > 1) s
 INNER JOIN
 SUBSCRIPTIONS s1
 ON
 s1.OWNER_CENTER = s.CENTER
 AND
 s1.OWNER_ID = s.ID
 JOIN PRODUCTS prod
 ON
 prod.CENTER = s1.SUBSCRIPTIONTYPE_CENTER
 AND prod.ID = s1.SUBSCRIPTIONTYPE_ID
 AND s1.STATE = 2
 AND (s1.SUB_STATE = 1 OR s1.SUB_STATE IS NULL)
 ORDER BY S.FULLNAME, s1.START_DATE
