-- The extract is extracted from Exerp on 2026-02-08
--  
 SELECT  c.SHORTNAME,  p.NAME as Prodotto, p.EXTERNAL_ID AS "Codice Ma", p.COST_PRICE as "Prezzo acquisto", invl.TOTAL_AMOUNT as "Prezzo vendita", invl.TOTAL_AMOUNT - p.COST_PRICE as "Delta", invl.PRODUCT_COST, longToDate(inv.ENTRY_TIME)
 FROM
 INVOICES inv INNER JOIN
 INVOICELINES invl
 ON inv.CENTER = invl.CENTER AND inv.ID = invl.ID
 INNER JOIN PERSONS payer
 ON payer.CENTER = inv.PAYER_CENTER AND payer.ID = inv.PAYER_ID
 INNER JOIN PERSONS person
 ON person.CENTER = invl.PERSON_CENTER AND person.ID = invl.PERSON_ID
 INNER JOIN EMPLOYEES empl
 ON empl.CENTER = inv.EMPLOYEE_CENTER AND empl.ID = inv.EMPLOYEE_ID
 INNER JOIN PERSONS empl1
 ON empl1.CENTER = empl.PERSONCENTER AND empl1.ID = empl.PERSONID
 INNER JOIN (select DISTINCT  CENTER, ID, NAME, EXTERNAL_ID, COST_PRICE FROM  PRODUCTS) p
 ON p.ID = invl.PRODUCTID and p.CENTER = invl.PRODUCTCENTER
 INNER JOIN CENTERS c
 ON inv.CENTER = c.id
 INNER JOIN
 (SELECT PRODUCT_CENTER, PRODUCT_ID FROM PRODUCT_AND_PRODUCT_GROUP_LINK WHERE PRODUCT_GROUP_ID IN(5245, 5616) GROUP BY PRODUCT_CENTER, PRODUCT_ID) prodgrp
 on prodgrp.PRODUCT_CENTER = p.CENTER AND prodgrp.PRODUCT_ID = p.ID
 WHERE
  longToDate(inv.ENTRY_TIME) BETWEEN  $$dataDa$$ AND $$dataA$$ + 1
 and c.COUNTRY = 'IT'
 --and p.COST_PRICE > 0
 ORDER BY c.SHORTNAME, P.NAME
