-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT S.CENTER, s.CENTER || 'ss' || s.ID "Subscription ID", 
CASE  s.STATE  WHEN 2 THEN 'Active'  WHEN 3 THEN 'Ended'  WHEN 4 THEN 'Frozen'  WHEN 7 THEN 'Window'  WHEN 8 THEN 'Created' ELSE 'Unknown' END as STATE, 
CASE  s.SUB_STATE  WHEN 1 THEN 'None'  WHEN 6 THEN  'Transferred'  WHEN 9 THEN 'Blocked' END AS SUB_STATE, 
S.SUBSCRIPTIONTYPE_CENTER, 
S.BINDING_END_DATE, 
S.SUBSCRIPTION_PRICE, 
S.START_DATE, S.END_DATE, 
S.TRANSFERRED_CENTER, PR.NAME, p.CENTER || 'p' || p.ID "Membership Number" 

FROM SUBSCRIPTIONS S 

LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID 
LEFT JOIN PRODUCTS PR ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID WHERE P.CENTER IN ($$scope$$) AND S.END_DATE >= :End_Date_From AND S.END_DATE <= :End_Date_To
  AND P.STATUS IN ( :PersonStatus ) AND S.STATE IN ( :Subscription_state )
