 SELECT
 REPLACE(CAST(ad.ID  AS VARCHAR(20)),'.', '') as "ADDONID",
 CONCAT(CONCAT(cast(s.CENTER AS VARCHAR(4)),'ss'),CAST(s.ID as VARCHAR(10))) as "MEMBERSHIPID",
 CONCAT(CONCAT(cast(P.CENTER AS VARCHAR(4)),'p'),CAST(P.ID as VARCHAR(10))) as "PERSONID",
 prod.NAME AS "NAME",
 LongToDate(ad.CREATION_TIME) as "DATAACQUISTO",
 ad.START_DATE as "DATAINIZIO",
 ad.END_DATE as "DATAFINE"
 FROM
 SUBSCRIPTIONS s
 INNER JOIN
 PERSONS p
 ON
 p.CENTER = s.OWNER_CENTER
 AND p.ID = s.OWNER_ID
 INNER JOIN
 SUBSCRIPTION_ADDON ad
 ON
 s.CENTER = ad.SUBSCRIPTION_CENTER
 AND
 s.ID = ad.SUBSCRIPTION_ID
 JOIN
     MASTERPRODUCTREGISTER mpr
 ON
     mpr.ID = ad.ADDON_PRODUCT_ID
         INNER JOIN PRODUCTS prod
         ON
             prod.CENTER = s.CENTER
     AND prod.GLOBALID = mpr.GLOBALID
 INNER JOIN
 CENTERS c
 ON c.ID = ad.CENTER_ID
 WHERE
 c.COUNTRY = 'IT'
 AND
 ad.CANCELLED = 0
