-- Started writing this, then realised that it's just a copy of 'MarketingSubscriptions'
-- Left here as someone might find it useful. Both BI_xxx are views which makes it s-l-o-w
SELECT 
	s.PERSON_ID,
	s.SUBSCRIPTION_ID,
	s.SUBSCRIPTION_CENTER,
	s.STATE,
	s.SUB_STATE,
	s.RENEWAL_TYPE,
	s.PRODUCT_ID,
	s.START_DATE,
	s.STOP_DATE,
	s.END_DATE,
	s.BILLED_UNTIL_DATE,
	s.BINDING_END_DATE,
	s.CREATION_DATE,
	s.SUBSCRIPTION_PRICE,
	s.BINDING_PRICE,
	s.REQUIRES_MAIN,
	s.SUB_PRICE_UPDATE_EXCLUDED,
	s.TYPE_PRICE_UPDATE_EXCLUDED,
	s.FREEZE_PERIOD_PRODUCT_ID,
	s.TRANSFERRED_TO,
	s.EXTENDED_TO,
	s.PERIOD_UNIT,
	s.PERIOD_COUNT,
	s.CENTER_ID,
	p.PRODUCT_GROUP_ID,
	p.MASTER_PRODUCT_ID,
	p.NAME as PRODUCT_NAME,
	p.SALES_PRICE AS PRODUCT_SALES_PRICE,
	p.MINIMUM_PRICE AS PRODUCT_MINIMUM_PRICE,
	p.COST_PRICE AS PRODUCT_COST_PRICE		
FROM 
	BI_SUBSCRIPTIONS s
INNER JOIN 
	BI_PRODUCTS p
		ON p.PRODUCT_ID = s.PRODUCT_ID
WHERE ROWNUM < 100