SELECT  PERSON_ID,
SUBSCRIPTION_ID,
SUBSCRIPTION_CENTER,
STATE,
SUB_STATE,
RENEWAL_TYPE,
PRODUCT_ID,
START_DATE,
STOP_DATE,
END_DATE,
BILLED_UNTIL_DATE,
BINDING_END_DATE,
CREATION_DATE,
SUBSCRIPTION_PRICE,
BINDING_PRICE,
REQUIRES_MAIN,
SUB_PRICE_UPDATE_EXCLUDED,
TYPE_PRICE_UPDATE_EXCLUDED,
FREEZE_PERIOD_PRODUCT_ID,
TRANSFERRED_TO,
EXTENDED_TO,
PERIOD_UNIT,
PERIOD_COUNT,
CENTER_ID
FROM BI_SUBSCRIPTIONS
WHERE START_DATE BETWEEN '1987-01-01'
AND '1987-12-31'
AND SUBSCRIPTION_CENTER = 405

