-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT CONCAT(CONCAT(CAST(s.CENTER as CHAR(3)),'ss'),CAST(s.ID as VARCHAR(10))) as membershipId, invl.TOTAL_AMOUNT as AF  from 
SUBSCRIPTIONS s
INNER JOIN
INVOICELINES invl
on s.INVOICELINE_CENTER = invl.CENTER
AND
s.INVOICELINE_ID = invl.ID
AND
s.INVOICELINE_SUBID = invl.SUBID

INNER JOIN PRODUCTS p
 ON invl.PRODUCTCENTER = p.CENTER
AND
invl.PRODUCTID = p.ID
INNER JOIN CENTERS c
ON 
c.ID = p.CENTER

WHERE  
 c.COUNTRY = 'IT'
AND p.NAME LIKE 'Creation%'
AND TOTAL_AMOUNT > 0