 select
 act.CENTER, act.ID, act.SUBID, p.NAME, act.AMOUNT, crt.AMOUNT as cashAmount,
 CONCAT(CONCAT(CAST(act.AGGREGATED_TRANSACTION_CENTER as CHAR(3)),'agt'), CAST(act.AGGREGATED_TRANSACTION_ID as VARCHAR(6))) as AGGREGATED_TRANSACTION,
 CONCAT(CONCAT(CAST(usr.CENTER as CHAR(3)),'p'), CAST(usr.ID as VARCHAR(6))) as userId
 FROM GIFT_CARDS g
 INNER JOIN
 GIFT_CARD_USAGES u
 ON
 g.ID = u.GIFT_CARD_ID
 AND
 g.CENTER = u.GIFT_CARD_CENTER
 INNER JOIN PRODUCTS giftProd
 ON
 giftProd.ID = g.PRODUCT_ID
 AND
 giftProd.CENTER = g.PRODUCT_CENTER
 INNER JOIN
 ACCOUNT_TRANS act
 ON
 act.SUBID = u.TRANSACTION_SUBID
 AND
 act.ID = u.TRANSACTION_ID
 AND
 act.CENTER = u.TRANSACTION_CENTER
 INNER JOIN
 CASHREGISTERTRANSACTIONS
  crt
 ON
 crt.GLTRANSCENTER = act.CENTER
 AND
 crt.GLTRANSID = act.ID
 AND
 crt.GLTRANSSUBID = act.SUBID
 INNER JOIN
 PERSONS usr
 ON
 crt.CUSTOMERCENTER = usr.CENTER
 AND
 crt.CUSTOMERID = usr.ID
 INNER JOIN
 CASHREGISTERS cr
 ON
 cr.CENTER = crt.CENTER
 AND cr.ID = crt.ID
 INNER JOIN INVOICES inv
 ON
  crt.PAYSESSIONID = inv.PAYSESSIONID
     AND crt.CRCENTER = inv.CASHREGISTER_CENTER
     AND crt.CRID = inv.CASHREGISTER_ID
 INNER JOIN INVOICELINES invl
 ON invl.CENTER = inv.CENTER
 AND
 invl.ID = inv.ID
 INNER JOIN
 PRODUCTS p
 ON
 p.CENTER = invl.PRODUCTCENTER
 AND
 p.ID = invl.PRODUCTID
 INNER JOIN PERSONS payer
 ON payer.ID = g.PAYER_ID
 AND
 payer.CENTER = g.PAYER_CENTER
 INNER JOIN
 CENTERS c
 ON
 c.ID = g.CENTER
 WHERE
 c.COUNTRY = 'IT'
 AND extract(month from LongToDate(u.TIME)) = EXTRACT(month FROM  ADD_MONTHS(CURRENT_TIMESTAMP,0))
 AND extract(year from  LongToDate(u.TIME)) = extract(YEAR FROM ADD_MONTHS(CURRENT_TIMESTAMP,0))
 UNION ALL
 select
 act.CENTER, act.ID, act.SUBID,'Accredito' AS NAME,  act.AMOUNT,crt.AMOUNT as cashAmount,
 CONCAT(CONCAT(CAST(act.AGGREGATED_TRANSACTION_CENTER as CHAR(3)),'agt'), CAST(act.AGGREGATED_TRANSACTION_ID as VARCHAR(6))) as AGGREGATED_TRANSACTION,
 CONCAT(CONCAT(CAST(usr.CENTER as CHAR(3)),'p'), CAST(usr.ID as VARCHAR(6))) as userId
 FROM GIFT_CARDS g
 INNER JOIN
 GIFT_CARD_USAGES u
 ON
 g.ID = u.GIFT_CARD_ID
 AND
 g.CENTER = u.GIFT_CARD_CENTER
 INNER JOIN PRODUCTS giftProd
 ON
 giftProd.ID = g.PRODUCT_ID
 AND
 giftProd.CENTER = g.PRODUCT_CENTER
 INNER JOIN
 ACCOUNT_TRANS act
 ON
 act.SUBID = u.TRANSACTION_SUBID
 AND
 act.ID = u.TRANSACTION_ID
 AND
 act.CENTER = u.TRANSACTION_CENTER
 INNER JOIN
 CASHREGISTERTRANSACTIONS
  crt
 ON
 crt.GLTRANSCENTER = act.CENTER
 AND
 crt.GLTRANSID = act.ID
 AND
 crt.GLTRANSSUBID = act.SUBID
 INNER JOIN
 PERSONS usr
 ON
 crt.CUSTOMERCENTER = usr.CENTER
 AND
 crt.CUSTOMERID = usr.ID
 INNER JOIN
 CASHREGISTERS cr
 ON
 cr.CENTER = crt.CENTER
 AND cr.ID = crt.ID
 INNER JOIN AR_TRANS art
 ON art.CENTER = crt.ARTRANSCENTER
 AND
 art.ID = crt.ARTRANSID
 AND
 art.SUBID = crt.ARTRANSSUBID
 INNER JOIN ACCOUNT_RECEIVABLES ar
 ON ar.ID = art.ID
 AND ar.CENTER = art.CENTER
 INNER JOIN PERSONS payer
 ON payer.ID = g.PAYER_ID
 and
 payer.CENTER = g.PAYER_CENTER
 INNER JOIN CENTERS c
 ON c.ID = payer.CENTER
 WHERE
 c.COUNTRY = 'IT'
 AND extract(month from LongToDate(u.TIME)) = EXTRACT(month FROM  ADD_MONTHS(CURRENT_TIMESTAMP,0))
 AND extract(year from  LongToDate(u.TIME)) = extract(YEAR FROM ADD_MONTHS(CURRENT_TIMESTAMP,0))
