select 

e1.IDENTITY,
e1.ID AS EI_ID1,
e2.ID as EI_ID2,
e1.REF_CENTER||'p'||e1.REF_ID as MEMBER_1,
e2.REF_CENTER||'p'||e2.REF_ID as MEMBER_2,
e1.ASSIGN_EMPLOYEE_CENTER||'emp'||e1.ASSIGN_EMPLOYEE_ID as ASSIGNING_EMPLOYEE,
DECODE(e1.IDMETHOD, 1, 'BARCODE', 2, 'MAGNETIC_CARD', 3, 'SSN', 4, 'RFID_CARD', 5, 'PIN', 6, 'ANTI DROWN', 7, 'QRCODE', 'UNKNOWN') as "IDMETHOD"

from VA.ENTITYIDENTIFIERS e1

join VA.ENTITYIDENTIFIERS e2 on e1.IDENTITY = e2.IDENTITY and e1.ID <> e2.ID and e1.ENTITYSTATUS = 1 and e2.ENTITYSTATUS = 1 and e1.IDMETHOD = e2.IDMETHOD