-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT c.SHORTNAME as club, p.CENTER || 'p' || p.ID as personIdMinore, CONCAT(CONCAT(p.FIRST_NAME, ' '), p.LAST_NAME) as nominativoMinore, p1.CENTER || 'p' || p1.ID as personIdGenitore,CONCAT(CONCAT(p1.FIRSTNAME, ' '), p1.LASTNAME) as nominativoGenitore, r.STATUS, p.DATE_OF_BIRTH FROM PERSONS_VW P
INNER JOIN RELATIVES r
ON p.CENTER = r.RELATIVECENTER
AND
p.ID = r.RELATIVEID
INNER JOIN CENTERS c
ON c.ID = p.CENTER
INNER JOIN PERSONS p1
ON p1.CENTER = r.CENTER
AND
p1.ID = r.id
 WHERE 
c.COUNTRY = 'IT'
AND p.STATUS IN('ACTIVE','TEMPORARYINACTIVE')
AND r.RTYPE = 12
AND (p.SSN IS NULL or LENGTH(p.SSN) = 0)
AND r.STATUS = 1

AND p.DATE_OF_BIRTH >  ADD_MONTHS(TRUNC(SYSDATE), -216) 
ORDER by c.SHORTNAME,  CONCAT(CONCAT(p.FIRST_NAME, ' '), p.LAST_NAME)