-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT EXTERNAL_ID, sum(nAcquistiTot) as nAcquistiTot, sum(nAcquisti90) as nAcquisti90, max(dataUltimoAcquisto) as dataUltimoAcquisto
FROM (

SELECT  person.EXTERNAL_ID, COUNT(*) AS nAcquistiTot, 0 as nAcquisti90, max(LongToDate(inv.ENTRY_TIME)) as dataUltimoAcquisto


FROM 
INVOICES inv INNER JOIN
INVOICELINES invl
ON inv.CENTER = invl.CENTER AND inv.ID = invl.ID


INNER JOIN PERSONS person
ON person.CENTER = invl.PERSON_CENTER AND person.ID = invl.PERSON_ID
INNER JOIN CENTERS c
ON c.ID = person.CENTER

INNER JOIN 
(SELECT PRODUCT_CENTER, PRODUCT_ID FROM PRODUCT_AND_PRODUCT_GROUP_LINK WHERE PRODUCT_GROUP_ID IN(5245, 5616) GROUP BY PRODUCT_CENTER, PRODUCT_ID) prodgrp
on prodgrp.PRODUCT_CENTER = invl.PRODUCTCENTER AND prodgrp.PRODUCT_ID = invl.PRODUCTID

WHERE
c.COUNTRY = 'IT'
GROUP  BY person.EXTERNAL_ID
UNION ALL

SELECT  person.EXTERNAL_ID, 0 AS nAcquistiTot, COUNT(*) as nAcquisti90, max(LongToDate(inv.ENTRY_TIME)) as dataUltimoAcquisto


FROM 
INVOICES inv INNER JOIN
INVOICELINES invl
ON inv.CENTER = invl.CENTER AND inv.ID = invl.ID


INNER JOIN PERSONS person
ON person.CENTER = invl.PERSON_CENTER AND person.ID = invl.PERSON_ID
INNER JOIN CENTERS c
ON c.ID = person.CENTER

INNER JOIN 
(SELECT PRODUCT_CENTER, PRODUCT_ID FROM PRODUCT_AND_PRODUCT_GROUP_LINK WHERE PRODUCT_GROUP_ID IN(5245, 5616) GROUP BY PRODUCT_CENTER, PRODUCT_ID) prodgrp
on prodgrp.PRODUCT_CENTER = invl.PRODUCTCENTER AND prodgrp.PRODUCT_ID = invl.PRODUCTID

WHERE
c.COUNTRY = 'IT'
and LongToDate(inv.ENTRY_TIME) > TRUNC(SYSDATE) -30
GROUP  BY person.EXTERNAL_ID) m
WHERE EXTERNAL_ID IS NOT NULL
GROUP BY EXTERNAL_ID