-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT S.CENTER, S.ID, DECODE (S.STATE, 2,'Active', 3,'Ended', 4,'Frozen', 7,'Window', 8,'Created','Unknown') as STATE, DECODE (SUB_STATE, 1,'None', 6, 'Transferred', 9,'Blocked') AS SUB_STATE, S.SUBSCRIPTIONTYPE_CENTER, S.BINDING_END_DATE, S.SUBSCRIPTION_PRICE, S.START_DATE, S.END_DATE, S.TRANSFERRED_CENTER, PR.NAME, az.FULLNAME FROM SUBSCRIPTIONS S LEFT JOIN PERSONS P ON P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID
INNER JOIN RELATIVES rel
ON
rel.CENTER = p.center
AND
rel.ID = p.ID
INNER JOIN PERSONS az
ON
az.CENTER = rel.RELATIVECENTER
AND
az.ID = rel.RELATIVEID
 LEFT JOIN PRODUCTS PR ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID WHERE P.CENTER = :Club AND S.END_DATE >= :End_Date_From AND S.END_DATE <= :End_Date_To
 AND P.STATUS IN ( :PersonStatus ) AND S.STATE IN ( :Subscription_state ) AND rel.RTYPE = 3