 select
  per.EXTERNAL_ID AS "EXTERNAL_ID", TRUNC(LongToDate(b.STARTTIME)) as "DATA", TO_CHAR(longtodateTZ(b.STARTTIME, 'Europe/Rome'), 'HH24:MI') as "ORA", c.SHORTNAME as "CLUB",  a.NAME AS "NAME",
 CASE
 WHEN p.USER_INTERFACE_TYPE = 1 THEN 'Staff'
 WHEN p.USER_INTERFACE_TYPE = 2 THEN 'WEB'
 WHEN p.USER_INTERFACE_TYPE = 6 THEN 'Mobile API'
 WHEN p.USER_INTERFACE_TYPE = 0 THEN 'Altro'
 END as "INTERFACCIA"
 FROM BOOKINGS b
 INNER JOIN
 PARTICIPATIONS p
 ON
 p.BOOKING_CENTER = b.CENTER
 AND
 p.BOOKING_ID = b.ID
 INNER JOIN
 CENTERS c
 ON c.ID = b.CENTER
 INNER JOIN PERSONS per
 ON
 per.ID = p.PARTICIPANT_ID
 AND
 per.CENTER = p.PARTICIPANT_CENTER
 INNER JOIN ACTIVITY a
 on
 a.ID = b.ACTIVITY
 WHERE
 c.COUNTRY  = 'IT'
 AND TRUNC(LongToDate(b.STARTTIME)) >= TRUNC(CURRENT_TIMESTAMP) -1
 and b.STATE = 'ACTIVE'
 and p.STATE = 'PARTICIPATION'
