SELECT 
	STATE,
	CONCAT(CENTER,CONCAT('ss',ID)) AS SUB_ID, 
	CONCAT(OWNER_CENTER,CONCAT('p',OWNER_ID)) AS MEMBER_ID,
	OWNER_CENTER,
	SUB_COMMENT
FROM Subscriptions
WHERE 
	SUB_COMMENT like '%nameID=Ind Mth Select;%'


