SELECT
    inv.CENTER || 'inv' || inv.ID "TRANSACTIONID",
    p.EXTERNAL_ID "PERSONID",
    longToDate(inv.TRANS_TIME) "TRANSACTIONDATE",
    '?' "TRANSACTIONSTATUS",
    '?' "TRANSACTIONCATEGORY",
    '?' "TRANSACTIONTYPEID",
    inv.CENTER "SITEID",
    'If > 1 credit note for one invoice? ' "REFUNDREASON",
    '?' "ANALYSISCODE",
    'EXERP' "SOURCESYSTEM",
    inv.CENTER || 'inv' || inv.ID "EXTREF"
FROM
    INVOICES inv
JOIN INVOICELINES invl
ON
    invl.CENTER = inv.CENTER
    AND invl.ID = inv.ID
LEFT JOIN CREDIT_NOTE_LINES cnl
ON
    cnl.INVOICELINE_CENTER = invl.CENTER
    AND cnl.INVOICELINE_ID = invl.ID
    AND cnl.INVOICELINE_SUBID = invl.SUBID
LEFT JOIN PERSONS op
ON
    op.CENTER = inv.PAYER_CENTER
    AND op.ID = inv.PAYER_ID
LEFT JOIN PERSONS p
ON
    p.CENTER = op.CURRENT_PERSON_CENTER
    AND p.ID = op.CURRENT_PERSON_ID
LEFT JOIN AR_TRANS art
ON
    art.REF_TYPE = 'INVOICE'
    AND art.REF_CENTER = inv.CENTER
    AND art.REF_ID = inv.ID
LEFT JOIN ACCOUNT_RECEIVABLES ar
ON
    ar.CENTER = art.CENTER
    AND ar.ID = art.ID
LEFT JOIN PAYMENT_ACCOUNTS pac
ON
    pac.CENTER = ar.CENTER
    AND pac.ID = ar.ID
LEFT JOIN PAYMENT_AGREEMENTS pagr
ON
    pagr.CENTER = pac.ACTIVE_AGR_CENTER
    AND pagr.ID = pac.ACTIVE_AGR_ID
    AND pagr.SUBID = pac.ACTIVE_AGR_SUBID
LEFT JOIN CLEARINGHOUSES ch
ON
    ch.id = pagr.CLEARINGHOUSE
WHERE
    inv.PAYSESSIONID IS NOT NULL
GROUP BY
    p.EXTERNAL_ID ,
    inv.CENTER ,
    inv.TRANS_TIME,
    inv.CENTER,
    inv.ID