 SELECT
     p.center||'p'||p.id                                                                                                                                                                  AS MEMBER_ID,
     p.EXTERNAL_ID                                                                                                                                                                        AS EXTERNAL_ID,
     SUBSTR(pr.NAME, 10, 100)                                                                                                                                                             AS SUBSCRIPTION_SUB_NAME,
     CASE  s.STATE  WHEN 2 THEN 'ACTIVE'  WHEN 3 THEN 'ENDED'  WHEN 4 THEN 'FROZEN'  WHEN 7 THEN 'WINDOW'  WHEN 8 THEN 'CREATED' ELSE 'UNKNOWN' END                                                                                               AS SUBSCRIPTION_STATE,
     CASE  s.SUB_STATE  WHEN 1 THEN 'NONE'  WHEN 2 THEN 'AWAITING_ACTIVATION'  WHEN 3 THEN 'UPGRADED'  WHEN 4 THEN 'DOWNGRADED'  WHEN 5 THEN 'EXTENDED'  WHEN 6 THEN  'TRANSFERRED' WHEN 7 THEN 'REGRETTED' WHEN 8 THEN 'CANCELLED' WHEN 9 THEN 'BLOCKED' WHEN 10 THEN 'CHANGED' ELSE 'UNKNOWN' END AS SUBSCRIPTION_SUB_STATE,
     s.SUBSCRIPTION_PRICE                                                                                                                                                                 AS SUBSCRIPTION_PRICE,
     mpr.CACHED_PRODUCTNAME                                                                                                                                                               AS ADD_ON_NAME,
     CASE
         WHEN mpr.CACHED_PRODUCTNAME IN ('Roaming Home - Collection Open 12',
                                         'Roaming Home - Collection Open 24',
                                         'Roaming Home - Collection Open 3',
                                         'Roaming Premium - Collection Open 12',
                                         'Roaming Premium - Collection Open 24',
                                         'Roaming Premium - Collection Open 3',
                                         'Roaming Premium Plus - Collection Open 12',
                                         'Roaming Premium Plus - Collection Open 24',
                                         'Roaming Premium Plus - Collection Open 3',
                                         'Roaming Reg/Bar - Collection Open 12',
                                         'Roaming Reg/Bar - Collection Open 24',
                                         'Roaming Reg/Bar - Collection Open 3')
         THEN 'COLLECTION'
         WHEN mpr.CACHED_PRODUCTNAME IN ('Accesso Executive Staff',
                                         'Acqua AGE',
                                         'Acqua Pack',
                                         'ANNUALE GYM TRAINING CASH',
                                         'ANNUALE GYM TRAINING SEPA',
                                         'Away club - Deposito Borsa Mensile',
                                         'Away Club - GYM TRAINING 12.90',
                                         'Away Club - GYM TRAINING 14.90',
                                         'Away Club - GYM TRAINING 16.90',
                                         'Away Club - GYM TRAINING 19.90',
                                         'Away Club - Noleggio Armadietto Mensile',
                                         'Away Club - PT Rental Annual',
                                         'Away Club - Spogliatoio Executive Mese',
                                         'Away Club-PT AF RID Operating Club 4 Mesi',
                                         'Away Club-PT EX GI Nuovi Club',
                                         'Away Club-PT EX GI Operating Club',
                                         'Away Club-PT Nuovi Club',
                                         'Away Club-PT Operating Club',
                                         'Body & Mind AGE',
                                         'Body & Mind Pack',
                                         'Cardio & Tone AGE',
                                         'Cardio & Tone Pack',
                                         'Cycle AGE',
                                         'Cycle Pack',
                                         'Deposito Borsa Mensile',
                                         'Fitness AGE',
                                         'Fitness Pack',
                                         'GYM TRAINING',
                                         'GYM TRAINING CASH',
                                         'GYM TRAINING FREE',
                                         'Home Club - AF RID PT Nuovi Club',
                                         'Home Club - AF RID PT Nuovi Club 4 Mesi',
                                         'Home Club - AF RID PT Nuovi Club Residuo',
                                         'Home Club - AF RID PT Operating Club',
                                         'Home Club - AF RID PT Operating Club 4 Mesi',
                                         'Home Club - AF RID PT Operating Club 6 Mesi',
                                         'Home Club - AF RID PT Operating Club Residuo',
                                         'Karate Annuale',
                                         'Neonatale Bisettimanale Annuale RID',
                                         'Neonatale Bisettimanale Quadrimestrale RID',
                                         'Neonatale Monosettimanale Annuale RID',
                                         'Neonatale Monosettimanale Quadrimestrale RID',
                                         'Neonatale Quadrimestrale',
                                         'Noleggio Armadietto Annuale Promo 199 euro',
                                         'Noleggio Armadietto Mensile',
                                         'Noleggio Armadietto Mensile Long',
                                         'Noleggio Armadietto Mensile Promo 19 euro',
                                         'Noleggio Armadietto Mensile Short',
                                         'Noleggio Armadietto Staff Mese',
                                         'NS Karate Annuale',
                                         'NS Neonatale Quadrimestrale',
                                         'NS Nuoto 4 Mesi Bis',
                                         'NS Nuoto 4 Mesi Mono',
										 'NS Nuoto 8 Mesi Bis',
                                         'NS Nuoto 8 Mesi Mono',
                                         'NS Scuola Danza Bis Annuale',
                                         'NS Scuola Danza Mon Annuale'
                                         'Nuoto 4 Mesi Bis',
                                         'Nuoto 4 Mesi Mono',
										 'Nuoto 8 Mesi Bis',
										 'Nuoto 8 Mesi Mono',
                                         'Off Peak Day Collection',
                                         'Off Peak Night Collection',
                                         'Scuola Danza Bis Annuale',
										 'Scuola Danza Mon Annuale',
                                         'Scuola Nuoto Bisettimanale Annuale RID',
                                         'Scuola Nuoto Bisettimanale Quadrimestrale RID',
                                         'Scuola Nuoto Monosettimanale Annuale RID',
                                         'Scuola Nuoto Monosettimanale Auadrimestrale RID',
                                         'Servizio Towel',
                                         'Spogliatoio Executive Mese',
                                         'Spogliatoio Executive VIP',
                                         'Trattati Con Cura',
                                         'Trattati Con Cura 3mesi',
                                         'Trattati Con Cura Saldo Totale',
                                         'Young 3 Mesi Collection')
         THEN 'NO_CHANGE'
         WHEN mpr.CACHED_PRODUCTNAME IN ('Roaming Home - Premium Open 12/3',
                                         'Roaming Home - Premium Open 24',
                                         'Roaming Reg/Bar - Premium Open 12/3',
                                         'Roaming Reg/Bar - Premium Open 24')
         THEN 'PREMIUM'
         WHEN mpr.CACHED_PRODUCTNAME IN ('Roaming Home - Premium Plus Open 12/3',
                                         'Roaming Home - Premium Plus Open 24',
                                         'Roaming Premium - Premium Plus Open 12/3',
                                         'Roaming Premium - Premium Plus Open 24',
                                         'Roaming Reg/Bar - Premium Plus Open 12/3',
                                         'Roaming Reg/Bar - Premium Plus Open 24')
         THEN 'PREMIUM PLUS'
         WHEN mpr.CACHED_PRODUCTNAME is null
         THEN 'NO ADD-ON'
         ELSE 'NO MATCH'
     END         AS ADD_ON_TIER,
     sa.END_DATE AS ADD_ON_END_DATE,
     CASE
         WHEN SUBSTR(pr.NAME, 10, 100) IN ('Alter Ego Classic',
                                           'Alter Ego Collection',
                                           'Corporate 1 Mese Classic',
                                           'Corporate 1 Mese Classic Cash',
                                           'Corporate 12 Mesi Classic ',
                                           'Corporate 12 Mesi Classic Cash ',
                                           'Corporate 3 Mesi Classic',
                                           'Corporate 3 Mesi Classic Cash',
                                           'Corporate 5 Mesi Classic Cash',
                                           'Diplomatico Open 12 Classic ',
                                           'Diplomatico Open 12 Collection',
                                           'Diplomatico Open 12 Collection Cash',
                                           'Diplomatico Open 3 Mesi Collection',
                                           'Diplomatico Open 3 Mesi Collection Cash',
                                           'One Month Classic',
                                           'Open 12 Classic',
                                           'Open 12 Classic Cash',
                                           'Open 12 Classic Special ',
                                           'Open 12 Classic Special Cash',
                                           'Open 12 Collection',
                                           'Open 12 Collection AlterEgo',
                                           'Open 12 Collection AlterEgo Cash',
                                           'Open 12 Collection Cash',
                                           'Open 24 Collection',
                                           'Open 24 Collection Cash',
                                           'Open 3 Collection',
                                           'Open 3 Collection Cash',
                                           'Open 36 Classic',
                                           'Open 36 Classic Cash',
                                           'Partnership Open 12 Classic',
                                           'Partnership Open 12 Classic Cash',
                                           'Partnership Open 12 Collection ',
                                           'Partnership Open 12 Collection Cash',
                                           'Partnership Open 3 Collection',
                                           'Partnership Open 3 Collection Cash ',
                                           'Partnership Special Collection ',
                                           'Partnership Special Collection Cash')
         THEN 'COLLECTION'
         WHEN SUBSTR(pr.NAME, 10, 100) IN ('Open 12 Cash',
                                           'Open 12 Home Club',
                                           'Open 12 Home club',
                                           'Open 12 Home Club AlterEgo ',
                                           'Open 12 Home Club AlterEgo Cash',
                                           'Open 12 Home Club Cash',
                                           'Open 12 Multiactive Cash Legacy',
                                           'Open 12 Presales ',
                                           'Open 24 Home Club',
                                           'Open 24 Home Club Cash',
                                           'Open 24 Home Club Rinnovo',
                                           'Open 24 Home Club Rinnovo Cash',
                                           'Open 3',
                                           'Open 3 Cash',
                                           'Open 3 Home Club',
                                           'Open 3 Home Club Cash',
                                           'Open 36',
                                           'Open 36 Cash',
                                           'Open 36 Multiactive',
                                           'Open 36 Multiactive Cash',
                                           'Open Mese',
                                           'Open Mese Cash',
                                           'Partnership Open 12 Home Club',
                                           'Partnership Open 12 Home Club Cash',
                                           'Partnership Open 3',
                                           'Partnership Open 3 Cash',
                                           'Partnership Open 3 Home Club',
                                           'Partnership Open 3 Home Club Cash ',
                                           'Partnership Open Mese',
                                           'Partnership Open Mese Cash',
                                           'Partnership Special Home Club',
                                           'Partnership Special Home Club Cash',
                                           'Partnership Villaggi Fitness Open 12',
                                           'Partnership Villaggi Fitness Open 12 Cash')
         THEN 'LIFE'
         WHEN SUBSTR(pr.NAME, 10, 100) IN ('Alter Ego Fascia 3',
                                           'Alter Ego Premium',
                                           'Corporate 1 Mese Fascia 2',
                                           'Corporate 1 Mese Fascia 2 Cash',
                                           'Corporate 1 Mese Fascia 3',
                                           'Corporate 1 Mese Fascia 3 Cash',
                                           'Corporate 1 Mese Premium ',
                                           'Corporate 1 Mese Premium Cash',
                                           'Corporate 12 Mesi Fascia 2',
                                           'Corporate 12 Mesi Fascia 2 Cash',
                                           'Corporate 12 Mesi Fascia 3',
                                           'Corporate 12 Mesi Fascia 3 Cash',
                                           'Corporate 12 Mesi Premium ',
                                           'Corporate 12 Mesi Premium Cash',
                                           'Corporate 3 Mesi Fascia 2',
                                           'Corporate 3 Mesi Fascia 2 Cash',
                                           'Corporate 3 Mesi Fascia 3',
                                           'Corporate 3 Mesi Fascia 3 Cash',
                                           'Corporate 3 Mesi Premium ',
                                           'Corporate 3 Mesi Premium Cash',
                                           'Diplomatico Open 12 Mesi (Fascia 2) ',
                                           'Diplomatico Open 12 Mesi (Fascia 2) Cash',
                                           'Diplomatico Open 12 Mesi (Fascia 3) ',
                                           'Diplomatico Open 12 Mesi (Fascia 3) Cash',
                                           'Diplomatico Open 12 Premium',
                                           'Diplomatico Open 12 Premium Cash',
                                           'Diplomatico Open 3 Mesi Premium',
                                           'Diplomatico Open 3 Mesi Premium Cash',
                                           'Open 12 Fascia 2',
                                           'Open 12 Fascia 2 Cash',
                                           'Open 12 Fascia 3',
                                           'Open 12 Fascia 3 Cash',
                                           'Open 12 Premium',
                                           'Open 12 Premium AlterEgo',
                                           'Open 12 Premium AlterEgo Cash',
                                           'Open 12 Premium Cash',
                                           'Open 12 Premium Presales',
                                           'Open 12 Premium Presales Cash',
                                           'Open 12 Premium Rinnovo',
                                           'Open 12 Premium Rinnovo Cash',
                                           'Open 24 Premium',
                                           'Open 24 Premium Cash',
                                           'Open 3 Premium',
                                           'Open 3 Premium Cash',
                                           'Open 36 Fascia 2',
                                           'Open 36 Fascia 2 Cash ',
                                           'Open 36 Fascia 3',
                                           'Open 36 Fascia 3 Cash ',
                                           'Open 36 Premium',
                                           'Open 36 Premium Cash ',
                                           'Partnership Open 12 Fascia 2',
                                           'Partnership Open 12 Fascia 2 Cash',
                                           'Partnership Open 12 Fascia 3',
                                           'Partnership Open 12 Fascia 3 Cash',
                                           'Partnership Open 12 Premium',
                                           'Partnership Open 12 Premium Cash',
                                           'Partnership Open 3 Fascia 2',
                                           'Partnership Open 3 Fascia 2 Cash ',
                                           'Partnership Open 3 Fascia 3',
                                           'Partnership Open 3 Fascia 3 Cash ',
                                           'Partnership Open 3 Premium',
                                           'Partnership Open 3 Premium Cash ',
                                           'Partnership Premium Open 12 ',
                                           'Partnership Premium Open 12 Cash',
                                           'Partnership Special Premium',
                                           'Partnership Special Premium Cash')
         THEN 'PREMIUM'
         WHEN SUBSTR(pr.NAME, 10, 100) IN ('Corporate 1 Mese Premium Plus',
                                           'Corporate 1 Mese Premium Plus Cash',
                                           'Corporate 12 Mesi Premium Plus',
                                           'Corporate 12 Mesi Premium Plus Cash',
                                           'Corporate 3 Mesi Premium Plus',
                                           'Corporate 3 Mesi Premium Plus Cash',
                                           'Diplomatico Open 12 Premium Plus',
                                           'Diplomatico Open 12 Premium Plus Cash',
                                           'Diplomatico Open 3 Mesi Premium Plus',
                                           'Diplomatico Open 3 Mesi Premium Plus Cash',
                                           'Open 12 Premium Plus',
                                           'Open 12 Premium Plus AlterEgo',
                                           'Open 12 Premium Plus AlterEgo Cash',
                                           'Open 12 Premium Plus Cash',
                                           'Open 24 Premium Plus',
                                           'Open 24 Premium Plus Cash',
                                           'Open 3 Premium Plus',
                                           'Open 3 Premium Plus Cash',
                                           'Open 36 Premium Plus',
                                           'Open 36 Premium Plus Cash ',
                                           'Partnership Open 12 Premium Plus  ',
                                           'Partnership Open 12 Premium Plus Cash',
                                           'Partnership Open 3 Premium Plus  ',
                                           'Partnership Open 3 Premium Plus Cash ',
                                           'Partnership Special Premium Plus  ',
                                           'Partnership Special Premium Plus Cash ')
         THEN 'PREMIUM PLUS'
         WHEN SUBSTR(pr.NAME, 10, 100) IN ('Accompagnatore Junior',
                                           'Accompagnatore Junior Cash ',
                                           'Active',
                                           'Active Cash',
                                           'Active Diplomatico',
                                           'Active Diplomatico Cash',
                                           'Alter Ego',
                                           'Alter Ego Fascia 1',
                                           'Ancillary by DD base subscription',
                                           'Away Collection Member',
                                           'Cambio Merce',
                                           'Cambio Merce Corporate Cash',
                                           'Cambio Merce Locale',
                                           'Corporate 1 Mese Fascia 1 ',
                                           'Corporate 1 Mese Fascia 1 Cash',
                                           'Corporate 12 Mesi Fascia 1 Cash',
                                           'Corporate 12 Mesi Fascia 1 Cash ',
                                           'Corporate 12 Mesi Junior ',
                                           'Corporate 12 Mesi Young',
                                           'Corporate 3 Mesi',
                                           'Corporate 3 Mesi Cash',
                                           'Corporate 3 Mesi Fascia 1',
                                           'Corporate 3 Mesi Fascia 1 Cash',
                                           'Corporate 3 Mesi Young ',
                                           'Corporate 6 Mesi',
                                           'Corporate 6 Mesi Cash',
                                           'Corporate Domenica Cash',
                                           'Corporate Giovedì Cash',
                                           'Corporate Mensile Cash',
                                           'Corporate Off Peak Day 12 Mesi',
                                           'Corporate Off Peak Night 12 Mesi ',
                                           'Corporate Part Sponsored Cash',
                                           'Dipendente',
                                           'Diplomatico Off Peak Cash',
                                           'Diplomatico Off Peak Day 12 Mesi',
                                           'Diplomatico Off Peak Night 12 Mesi',
                                           'Diplomatico Open 12 Home Club',
                                           'Diplomatico Open 12 Home Club Cash',
                                           'Diplomatico Open 3 Mesi Home Club',
                                           'Diplomatico Open 3 Mesi Home Club Cash',
                                           'Diplomatico Open Mese ',
                                           'Diplomatico Open Mese Cash',
                                           'Diplomatico Senior ',
                                           'Diplomatico Senior Cash',
                                           'Diplomatico Week End Cash',
                                           'Diplomatico WeekEnd',
                                           'Diplomatico Young 12 Open',
                                           'Diplomatico Young 12 Open Cash',
                                           'Diplomatico Young 3 Mesi ',
                                           'Diplomatico Young 3 Mesi Cash',
                                           'Ditte Esterne',
                                           'DT Off Peak ',
                                           'DT Off Peak  Cash',
                                           'DT Open',
                                           'DT Open Cash',
                                           'DT Vip',
                                           'DT Vip Cash',
                                           'DT Young',
                                           'DT Young Cash',
                                           'Dummy ',
                                           'Flexi',
                                           'Flexi Cash',
                                           'Flexi Diplomatico',
                                           'Flexi Diplomatico Cash',
                                           'Flexi Student',
                                           'Flexi Student Cash',
                                           'Freelance',
                                           'Freelance Cash',
                                           'JOIN 5',
                                           'JOIN PROMO',
                                           'Junior 12',
                                           'Junior 12 Cash',
                                           'Junior 12 Classic',
                                           'Junior Mese',
                                           'Junior Mese Cash',
                                           'Junior Mese Classic',
                                           'Junior Mese Classic Cash',
                                           'Junior Multiactive',
                                           'Junior Multiactive Cash',
                                           'Junior Omaggio',
                                           'Junior Omaggio Cash',
                                           'Junior Open 12 10A-13A',
                                           'Junior Open 12 10A-13A Cash',
                                           'Junior Open 12 10A-13A Cash Diplomatico',
                                           'Junior Open 12 10A-13A Diplomatico',
                                           'Junior Open 12 18M-9A',
                                           'Junior Open 12 18M-9A Cash',
                                           'Junior Open 12 18M-9A Cash Diplomatico',
                                           'Junior Open 12 18M-9A Diplomatico',
                                           'Junior Open 3 10A-13A',
                                           'Junior Open 3 10A-13A Cash ',
                                           'Junior Open 3 10A-13A Cash Diplomatico',
                                           'Junior Open 3 10A-13A Diplomatico',
                                           'Junior Open 3 18M-9A',
                                           'Junior Open 3 18M-9A Cash',
                                           'Junior Open 3 18M-9A Cash Diplomatico',
                                           'Junior Open 3 18M-9A Diplomatico',
                                           'Junior Open 3 Mesi 3A-9A',
                                           'Junior Open 3 Mesi Cash 3A-9A',
                                           'Junior Open Mese 10A-13A',
                                           'Junior Open Mese 10A-13A Cash',
                                           'Junior Open Mese 10A-13A Cash Diplomatico',
                                           'Junior Open Mese 10A-13A Diplomatico',
                                           'Junior Open Mese 18M-9A',
                                           'Junior Open Mese 18M-9A Cash',
                                           'Junior Open Mese 18M-9A Cash Diplomatico',
                                           'Junior Open Mese 18M-9A Diplomatico',
                                           'Junior Open Mese 3A-9A',
                                           'Junior Open Mese Cash 3A-9A',
                                           'Junior Pool',
                                           'Junior Pool 10 Ingressi',
                                           'Junior Pool 18M-13A',
                                           'Junior Pool 18M-13A Cash',
                                           'LETS MOVE',
                                           'Nuoto Legacy',
                                           'Nuoto Legacy Cash',
                                           'Off Peak A Cash Legacy',
                                           'Off Peak A Legacy',
                                           'Off Peak B Cash Legacy',
                                           'Off Peak B Legacy',
                                           'Off Peak Day',
                                           'Off Peak Day Cash',
                                           'Off Peak Night',
                                           'Off Peak Night Cash',
                                           'Off Peak Promo',
                                           'Off Peak Promo Cash',
                                           'Open 12',
                                           'Open 12 - Ch',
                                           'Open 12 BLACK FRIDAY ',
                                           'Open 12 BLACK FRIDAY CASH',
                                           'Open 12 Cash - Ch',
                                           'Open 12 Fascia 1',
                                           'Open 12 Fascia 1 Cash',
                                           'Open 12 Home Club Rinnovo',
                                           'Open 12 Home Club Rinnovo Cash',
                                           'Open 12 Mesi OLD',
                                           'Open 36 Fascia 1',
                                           'Open 36 Fascia 1 Cash ',
                                           'Open 6',
                                           'Open 6 Cash',
                                           'Open Mensile OLD',
                                           'Ospite Corsi',
                                           'Ospite Pilates - Yoga',
                                           'Ospite Pranzo',
                                           'Ospite Pranzo Gift',
                                           'Partnership Open 12 Fascia 1',
                                           'Partnership Open 12 Fascia 1 Cash',
                                           'PT Ex GI Fee 11 Mesi ',
                                           'PT Ex GI Fee 12 Mesi ',
                                           'PT Ex GI Fee Reformer 11 Mesi ',
                                           'PT Ex GI Fee Reformer 12 Mesi ',
                                           'PT EX GI Nuovi Club ',
                                           'PT EX GI Nuovi Club Cash',
                                           'PT EX GI Operating Club ',
                                           'PT EX GI Operating Club Cash',
                                           'PT Family',
                                           'PT Family Cash',
                                           'PT Fee 11 Mesi ',
                                           'PT Fee 12 Mesi ',
                                           'PT Fee Cash',
                                           'PT Fee Reformer 11 Mesi ',
                                           'PT Fee Reformer 12 Mesi ',
                                           'PT Fee Reformer Cash',
                                           'PT Nuovi Club ',
                                           'PT Nuovi Club Cash',
                                           'PT Operating Club',
                                           'PT Operating Club Cash ',
                                           'PT Week End Ex GI Fee 11 Mesi ',
                                           'PT Week End Ex GI Fee 12 Mesi ',
                                           'PT Week End Fee 11 Mesi ',
                                           'PT Week End Fee 12 Mesi ',
                                           'PT Week End Fee Cash',
                                           'Senior ',
                                           'Senior Cash',
                                           'Special Adult ',
                                           'Speciale Junior',
                                           'Speciale Junior Cash',
                                           'Specialist Academy',
                                           'Staff Family',
                                           'Staff Family Senior ',
                                           'Staff Family Young',
                                           'Staff Friends',
                                           'Staff Friends Cash',
                                           'Tessera Adulto 10 Ingressi',
                                           'Tessera Adulto Collection 10 Ingressi',
                                           'Tessera Young 10 Ingressi',
                                           'Titolare',
                                           'Vip',
                                           'Vip Classic',
                                           'Vip Senior',
                                           'Vip Senior Collection',
                                           'Vip Young',
                                           'Vip Young Collection',
                                           'Week End',
                                           'Week End Active',
                                           'Week End Active Cash',
                                           'Week End Cash',
                                           'Week End Giovedi',
                                           'Week End Giovedi Cash',
                                           'Week End Lunedi',
                                           'Week End Lunedi Cash',
                                           'Week End Martedi',
                                           'Week End Martedi Cash',
                                           'Week End Mercoledi',
                                           'Week End Mercoledi Cash',
                                           'Week End Venerdi',
                                           'Week End Venerdi Cash',
                                           'Young 12 Day',
                                           'Young 12 Day Cash',
                                           'Young 12 Mesi',
                                           'Young 12 Night',
                                           'Young 12 Night Cash',
                                           'Young 12 Open',
                                           'Young 12 Open Cash',
                                           'Young 12 Promo',
                                           'Young 12 Promo Cash',
                                           'Young 3 Day',
                                           'Young 3 Day Cash',
                                           'Young 3 Night  ',
                                           'Young 3 Night Cash',
                                           'Young 3 Open   ',
                                           'Young 3 Open  ',
                                           'Young 3 Open',
                                           'Young 3 Open ',
                                           'Young 3 Open Cash',
                                           'Young 3 Open Cash Old',
                                           'Young 3 Open Old',
                                           'Young 3 Promo',
                                           'Young 3 Promo Cash',
                                           'Young Free 12 Open',
                                           'Young Free 12 Open Cash',
                                           'Young30 12 Open',
                                           'Young30 12 Open Cash',
                                           'Partnership Open 12',
                                           'Open 12 Fascia 2 Legacy',
                                           'NS Nuoto 4 Mesi Mono',
                                           'Alter Ego Fascia 2',
                                           'Carnet Classic Adulto',
                                           'Corporate 12 Mesi Fascia 1 ',
                                           'Diplomatico Off Peak 12 Mesi',
                                           'Diplomatico Open 12 Mesi (Fascia 1) ',
                                           'Corporate 12 Mesi Fascia 1',
                                           'Carnet Adulto',
                                           'One Month Classic ')
         THEN 'NO CHANGES'
         ELSE 'NO MATCH'
     END          AS TIER ,
     pea.TXTVALUE AS MWC_TOKEN
 FROM
     persons p
 JOIN
     centers c
 ON
     c.id = p.center
 LEFT JOIN
     SUBSCRIPTIONS s
 ON
     s.OWNER_CENTER = p.center
     AND s.OWNER_ID = p.id
 LEFT JOIN
     SUBSCRIPTIONTYPES st
 ON
     st.CENTER = s.SUBSCRIPTIONTYPE_CENTER
     AND st.id = s.SUBSCRIPTIONTYPE_ID
 LEFT JOIN
     PRODUCTS pr
 ON
     pr.center = st.PRODUCTNEW_CENTER
     AND pr.id = st.PRODUCTNEW_ID
 LEFT JOIN
     SUBSCRIPTION_ADDON sa
 ON
     sa.SUBSCRIPTION_CENTER = s.center
     AND sa.SUBSCRIPTION_ID = s.id
     AND sa.CANCELLED = 0
     AND (
         sa.END_DATE IS NULL
         OR sa.END_DATE > CURRENT_TIMESTAMP)
 LEFT JOIN
     PERSON_EXT_ATTRS pea
 ON
     pea.NAME = '_eClub_WellnessCloudUserPermanentToken'
     AND pea.PERSONCENTER = p.center
     AND pea.PERSONID = p.id
 LEFT JOIN
     MASTERPRODUCTREGISTER mpr
 ON
     mpr.ID = sa.ADDON_PRODUCT_ID
 WHERE
     p.STATUS IN (1,3)
     AND c.COUNTRY = 'IT'
     AND s.state IN (2,7,8)
