select
longtodate(prs.LAST_MODIFIED) as ultimaModifica, CONCAT(CONCAT(cast(p1.CENTER as char(3)),'p'), cast(p1.ID as varchar(8))) as perosndId, p1.FULLNAME as nominativo,
DECODE(pr.STATE, 1, 'PS_NEW', 2, 'PS_SENT', 3, 'PS_DONE', 5, 'PS_REJECTED_BY_CLEARINGHOUSE', 12, 'PS_FAIL_NO_CREDITOR', 17,'PS_FAIL_REJ_DEB_REVOKED') "Stato",
 prs.REQUESTED_AMOUNT as importoRichiesto, PRS.open_amount as IMPORTOAPERTO, pr.REQ_DATE as scadenza, longtodate(prs.LAST_MODIFIED) as DataPagamento,
pr.XFR_INFO as motivo

FROM 

	PERSONS p1


JOIN 
ACCOUNT_RECEIVABLES ar
on
 ar.CUSTOMERCENTER = p1.CENTER
    AND ar.CUSTOMERID = p1.ID
AND ar.AR_TYPE = 4

LEFT 
	JOIN PAYMENT_ACCOUNTS pac
ON
    pac.CENTER = ar.CENTER
    AND pac.ID = ar.ID
  
LEFT JOIN
    PAYMENT_REQUESTS pr
ON
  pr.CENTER = ar.CENTER
    AND pr.ID = ar.id  


LEFT JOIN
    PAYMENT_REQUEST_SPECIFICATIONS prs
ON
    pr.INV_COLL_CENTER = prs.CENTER
    AND pr.INV_COLL_ID = prs.ID
    AND pr.INV_COLL_SUBID = prs.SUBID

LEFT JOIN AR_TRANS art
	ON art.PAYREQ_SPEC_SUBID = prs.SUBID
	and art.PAYREQ_SPEC_ID = prs.ID
	and art.PAYREQ_SPEC_CENTER = prs.CENTER
LEFT JOIN INVOICELINES invl
 on invl.ID = art.REF_ID
AND invl.CENTER = art.REF_CENTER
INNER JOIN CENTERS c
ON C.ID = PR.CENTER


WHERE 
pr.center IN (205,204,207,206,201,203,202,220,221,222,223,216,217,218,219,212,213,214,215,208,209,210,211,102,103,100,101,108,106,107,225,104,224,105,226,227,228) 
--c.country = 'IT'
and pr.STATE IN(5,12,17)

and extract(day from pr.req_date) <= 4

AND pr.REQ_DATE between $$dataDaScadenza$$ AND $$dataAScadenza$$
AND pr.STATE IS NOT NULL
AND ART.REF_TYPE = 'INVOICE'

--AND ar.CUSTOMERID = 7338
AND art.COLLECTED_AMOUNT <> 0
--AND prs.OPEN_AMOUNT < prs.REQUESTED_AMOUNT


Order by P1.CENTER, P1.FULLNAME