 SELECT
                 bi."PERSON_ID",
 --              p.CURRENT_PERSON_CENTER,
 --              p.CURRENT_PERSON_ID,
 -- MAX(bi.CREATION_DATETIME) INIZIO,
 -- ADD_MONTHS(TO_DATE (CREATION_DATETIME,'YYYY-MM-DD HH24:MI:SS'), 12) SCADENZA
                 MAX(js.EXPIRATION_DATE) SCADENZA
 from BI_DOCUMENT bi
 left outer join PERSONS p ON bi."PERSON_ID" = p.EXTERNAL_ID
 LEFT JOIN
 JOURNALENTRIES js
 ON p.CURRENT_PERSON_CENTER = js.PERSON_CENTER AND p.CURRENT_PERSON_ID = js.PERSON_ID
 WHERE "CENTER_ID" = '105'
 AND "TYPE" = 'HEALTH_CERTIFICATE'
 GROUP BY bi."PERSON_ID"
                 -- p.CURRENT_PERSON_CENTER,
                 -- p.CURRENT_PERSON_ID
 --ORDER BY TO_DATE (CREATION_DATETIME,'YYYY-MM-DD HH24:MI:SS')
