  SELECT
     rel.STATUS RELATION_STATUS,
     rel.CENTER || 'p' || rel.ID PRIMARY_PID,
     pp.FIRSTNAME PRIMARY_FIRSTNAME,
     pp.LASTNAME PRIMARY_LASTNAME,
     cp.NAME PRIMARY_HOME_CLUB,
     rel.RELATIVECENTER || 'p' || rel.RELATIVEID SECONDARY_PID,
     ps.FIRSTNAME SECONDARY_FIRSTNAME,
     ps.LASTNAME SECONDARY_LASTNAME,
     cs.NAME SECONDARY_HOME_CLUB
 
 
 FROM
     RELATIVES rel
 join PERSONS pp on pp.CENTER = rel.CENTER and pp.ID  = rel.ID
 join PERSONS ps on ps.CENTER = rel.RELATIVECENTER and ps.ID  = rel.RELATIVEID
 join CENTERS cp on cp.ID = pp.CENTER
 join CENTERS cs on cs.ID = ps.CENTER
 JOIN SUBSCRIPTIONS ssec
 ON
     ssec.OWNER_CENTER = rel.CENTER
     AND ssec.OWNER_ID = rel.ID
     AND ssec.STATE IN (2,4,8)
 LEFT JOIN ACTIVITY_GROUP ag
 ON
     ag.id = act.ACTIVITY_GROUP_ID
 LEFT JOIN COLOUR_GROUPS cg
 ON
     cg.ID = act.COLOUR_GROUP_ID
 LEFT JOIN ACTIVITY_STAFF_CONFIGURATIONS asconf
 ON
     asconf.ACTIVITY_ID = act.ID
 LEFT JOIN STAFF_GROUPS sg
 ON
     sg.ID = asconf.STAFF_GROUP_ID
 LEFT JOIN BOOKING_TIME_CONFIGS btc
 ON
     btc.ID = act.TIME_CONFIG_ID
 LEFT JOIN ACTIVITY_RESOURCE_CONFIGS arc
 ON
     arc.ACTIVITY_ID = act.ID
 LEFT JOIN BOOKING_RESOURCE_GROUPS brg
 ON
     brg.ID = arc.BOOKING_RESOURCE_GROUP_ID
 LEFT JOIN PARTICIPATION_CONFIGURATIONS pc
 ON
     pc.ACTIVITY_ID = act.ID
     and pc.NAME in ('Class','Participants')
 LEFT JOIN BOOKING_PRIVILEGE_GROUPS bpg
 ON
     bpg.ID = pc.ACCESS_GROUP_ID
          
WHERE
ACT.ID ='10601'
     
     
     