-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 
	PEA3.TXTVALUE as Email
FROM 
	PERSONS P 
LEFT join 
	PERSON_EXT_ATTRS PEA3 
	ON PEA3.PERSONCENTER = P.CURRENT_PERSON_CENTER 
	AND PEA3.PERSONID = P.CURRENT_PERSON_ID 
	AND PEA3.NAME = '_eClub_Email'  
JOIN 
	CENTERS C 
	ON p.CENTER = C.ID
WHERE c.ID in ($$scope$$)
GROUP BY PEA3.TXTVALUE HAVING COUNT(PEA3.TXTVALUE) > 1