-- The extract is extracted from Exerp on 2026-02-08
--  
select distinct
	p.center ||'p'|| p.id as person_id, 
	c.shortname as club,
	p.fullname as full_name,
	prod2.name AS subscription_name,
	s.CENTER || 'ss' || s.ID AS subscription_id,
	sp.PRICE AS subscription_price,
	TO_TIMESTAMP(cl.valid_from / 1000) as data_validita_clipcard,
	TO_TIMESTAMP(cl.valid_until / 1000) as data_scadenza_clipcard,
	prod.name as nome_clipcard,
	cl.clips_initial as clips_vendute,
	cl.clips_left as clips_left,
	cl.cancelled
	FROM
		clipcards cl 
	join 
		products prod 
		on cl.id = prod.id
		and prod.blocked = 0
		and prod.PTYPE = 4
	JOIN
		PRODUCT_GROUP pg
		ON pg.ID = prod.PRIMARY_PRODUCT_GROUP_ID
	LEFT JOIN
		PRODUCT_AND_PRODUCT_GROUP_LINK pgLink
		ON pgLink.PRODUCT_CENTER = prod.CENTER
		AND pgLink.PRODUCT_ID = prod.ID
	LEFT JOIN
		PRODUCT_GROUP pgAll
		ON pgAll.ID = pgLink.PRODUCT_GROUP_ID
	JOIN 
		PERSONS p 
		ON p.CENTER = cl.OWNER_CENTER 
		AND p.ID = cl.OWNER_ID
	join 
		centers c
		on c.id = p.center 
		and c.country = 'IT'
	left JOIN SUBSCRIPTIONS S
	    ON s.OWNER_CENTER = p.CENTER
    	AND s.OWNER_ID = p.ID 
		and s.state in (2,4,8)
	LEFT JOIN PRODUCTS prod2
 	 	ON prod2.CENTER = s.SUBSCRIPTIONTYPE_CENTER
     	AND prod2.ID = s.SUBSCRIPTIONTYPE_ID
		and prod2.blocked = 0
		and prod2.PTYPE = 10
	LEFT JOIN SUBSCRIPTION_PRICE sp
	 	ON sp.SUBSCRIPTION_CENTER = s.CENTER
     	AND sp.SUBSCRIPTION_ID = s.ID
     	AND sp.FROM_DATE <= CURRENT_TIMESTAMP
    	 AND (
        	 sp.TO_DATE IS NULL
         	OR sp.TO_DATE > CURRENT_TIMESTAMP)
    	 AND sp.APPLIED = 1
    	 --AND sp.CANCELLED = 0 
	where 
		p.center in ($$scope$$)
	and 
		TO_TIMESTAMP(cl.valid_from / 1000) >= ($$data_validita_clipcard_da$$)
	and 
		TO_TIMESTAMP(cl.valid_from / 1000) <= ($$data_validita_clipcard_fino_a$$)
	and pgAll.id in ('53601')
	and prod2.name not in ('Active Break Life Metro',
	'3 Month Amazon Collection',
	'3 Month Amazon Life',
	'3 Month Amazon Premium',
	'A -Junior Pool 12 Mesi Global App Test Cash',
	'ACADEMY Antigravity Fundamentals',
	'ACADEMY Antigravity Refresh ',
	'ACADEMY Antigravity upgrade ',
	'ACADEMY Percorso Yoga',
	'ACADEMY Percorso Yoga online',
	'Accompagnatore Junior',
	'Accompagnatore Junior Cash ',
	'Active Break Collection',
	'Active Break Collection CASH',
	'Active Break Free',
	'Active Break Free Cash',
	'Active Break Free Matrice',
	'Active Break Life Metro',
	'Active Break Life Metro CASH',
	'Active Break Life Province',
	'Active Break Life Province CASH',
	'Active Break Premium',
	'Active Break Premium CASH',
	'Active Break Premium Plus',
	'Active Break Premium Plus CASH',
	'Alter Ego',
	'Alter Ego Collection',
	'Alter Ego Premium',
	'Alter Ego Premium Plus',
	'Away All Member',
	'Away Collection Member',
	'Cambio Merce',
	'Cambio Merce Corporate Cash',
	'Cambio Merce Corporate Flexi CASH',
	'Cambio Merce Locale',
	'CARNET 10 INGRESSI Collection',
	'CARNET 10 INGRESSI COLLECTION BOCCONI',
	'CARNET 10 INGRESSI Life Metro',
	'CARNET 10 INGRESSI Life Province',
	'CARNET 10 INGRESSI P.PLUS BOCCONI',
	'CARNET 10 INGRESSI Premium',
	'CARNET 10 INGRESSI Premium Plus',
	'Carnet 10 partite Padel NON SOCIO',
	'Carnet 10 partite Padel SOCIO',
	'CARNET 15 INGRESSI Collection',
	'CARNET 15 INGRESSI COLLECTION BOCCONI',
	'CARNET 15 INGRESSI Life Metro',
	'CARNET 15 INGRESSI Life Province',
	'CARNET 15 INGRESSI P.PLUS BOCCONI',
	'CARNET 15 INGRESSI Premium',
	'CARNET 15 INGRESSI Premium Plus',
	'CARNET 20 INGRESSI Collection',
	'CARNET 20 INGRESSI COLLECTION BOCCONI',
	'CARNET 20 INGRESSI Life Metro',
	'CARNET 20 INGRESSI Life Province',
	'CARNET 20 INGRESSI P.PLUS BOCCONI',
	'CARNET 20 INGRESSI Premium',
	'CARNET 20 INGRESSI Premium Plus',
	'Carnet 5 lezioni Padel NON SOCIO',
	'Carnet 5 lezioni Padel SOCIO',
	'Carnet 5 lezioni Padel SOCIO Collection',
	'Carnet 5 lezioni Padel SOCIO OPEN 12/24',
	'Corporate Digitale 1 mese CASH',
	'Corporate Digitale 12 mesi CASH',
	'Corporate Digitale 3 mesi CASH',
	'Corporate Digitale Outdoor 1 mese CASH',
	'Corporate Digitale Outdoor 12  mesi CASH',
	'Corporate Digitale Outdoor 3 mesi CASH',
	'Corporate One Month',
	'Corporate One Month Collection',
	'Corporate Open Mese',
	'Corporate Open Mese  CASH',
	'Corsista',
	'Digital Free',
	'Digitale Annuale',
	'Digitale Annuale Omaggio ',
	'Digitale Bimestrale',
	'Digitale Integrato',
	'Digitale Integrato Omaggio 12 Mesi',
	'Digitale Mensile ',
	'Digitale Mensile CASH',
	'Digitale Mensile Omaggio',
	'Digitale Mensile Promo ',
	'Digitale Outdoor Annuale Omaggio',
	'Digitale Outdoor Semestrale',
	'Digitale Outdoor Trimestrale',
	'Dipendente',
	'Ditte Esterne',
	'E - PT Fee 12 mesi Collection Global App Test CASH',
	'Executive',
	'F - Open 12 Mesi Collection Global App Test',
	'F - Open 12 Mesi Collection Global App Test CASH',
	'Freelance',
	'Freelance Cash',
	'JOIN 10',
	'JOIN 3',
	'JOIN 5',
	'JOIN ACTIVE',
	'JOIN COLLECTION',
	'JOIN LIFE',
	'JOIN OFF PEAK DAY',
	'JOIN OFF PEAK NIGHT',
	'JOIN PREMIUM',
	'JOIN PREMIUM PLUS',
	'JOIN PROMO',
	'JOIN WEEK END',
	'Junior Omaggio',
	'Junior Omaggio Cash',
	'Junior Open 12 10A-13A',
	'Junior Open 12 18M-9A',
	'Junior Pool ',
	'Junior Pool 12 Mesi',
	'Junior Pool 12 Mesi Cash',
	'Junior Pool Cash',
	'NS Nuoto 4 Mesi Mono',
	'Nuoto Legacy',
	'One Month Amazon Collection',
	'One Month Amazon Premium',
	'One Month Huawei',
	'Ospite Corsi',
	'Ospite Padel',
	'Ospite Parking',
	'Ospite Pilates - Yoga',
	'Ospite Pranzo',
	'Ospite Pranzo Collection',
	'Ospite Pranzo Gift',
	'Ospite Pranzo Special Time Free',
	'Outdoor Digital Free',
	'PT Ex GI 11 mesi Collection',
	'PT Ex GI 11 mesi Life Metro',
	'PT Ex GI 11 mesi Life Province',
	'PT Ex GI 11 mesi Premium',
	'PT Ex GI 11 mesi Premium Plus',
	'PT Ex GI 12 mesi Collection',
	'PT Ex GI 12 mesi Collection CASH',
	'PT Ex GI 12 mesi Life Metro',
	'PT Ex GI 12 mesi Life Metro CASH',
	'PT Ex GI 12 mesi Life Province',
	'PT Ex GI 12 mesi Life Province CASH',
	'PT Ex GI 12 mesi Premium',
	'PT Ex GI 12 mesi Premium CASH',
	'PT Ex GI 12 mesi Premium Plus',
	'PT Ex GI 12 mesi Premium Plus CASH',
	'PT Ex GI Fee 11 Mesi ',
	'PT Ex GI Fee 12 Mesi ',
	'PT Ex GI Fee Reformer 11 Mesi ',
	'PT Ex GI Fee Reformer 12 Mesi ',
	'PT Fee 11 mesi Collection',
	'PT Fee 11 mesi Life Metro',
	'PT Fee 11 mesi Life Province',
	'PT Fee 11 mesi Premium',
	'PT Fee 11 mesi Premium Plus',
	'PT Fee 12 Mesi Collection',
	'PT Fee 12 mesi Collection CASH',
	'PT Fee 12 mesi Life Metro',
	'PT Fee 12 mesi Life Metro CASH',
	'PT Fee 12 mesi Life Province',
	'PT Fee 12 mesi Life Province CASH',
	'PT Fee 12 mesi Premium',
	'PT Fee 12 mesi Premium CASH',
	'PT Fee 12 mesi Premium Plus',
	'PT Fee 12 mesi Premium Plus CASH',
	'PT Fee Reformer 11 Mesi ',
	'PT Fee Reformer 12 Mesi ',
	'PT Fee Reformer Cash',
	'PT Fee WeekEnd +1 Collection',
	'PT Fee WeekEnd +1 Collection CASH',
	'PT Fee WeekEnd +1 Life Metro',
	'PT Fee WeekEnd +1 Life Metro CASH',
	'PT Fee WeekEnd +1 Life Province',
	'PT Fee WeekEnd +1 Life Province CASH',
	'PT Fee WeekEnd +1 Premium',
	'PT Fee WeekEnd +1 Premium CASH',
	'PT Fee WeekEnd +1 Premium Plus',
	'PT Fee WeekEnd +1 Premium Plus CASH',
	'PT Fee WeekEnd +6 Collection',
	'PT Fee WeekEnd +6 Collection CASH',
	'PT Fee WeekEnd +6 Life Metro',
	'PT Fee WeekEnd +6 Life Metro CASH',
	'PT Fee WeekEnd +6 Life Province',
	'PT Fee WeekEnd +6 Life Province CASH',
	'PT Fee WeekEnd +6 Premium',
	'PT Fee WeekEnd +6 Premium CASH',
	'PT Fee WeekEnd +6 Premium Plus',
	'PT Fee WeekEnd +6 Premium Plus CASH',
	'Revolution Socio Collection',
	'SMART Break Collection',
	'SMART Break Collection CASH',
	'SMART Break Life Metro',
	'SMART Break Life Metro CASH',
	'SMART Break Life Province',
	'SMART Break Life Province CASH',
	'SMART Break Matrice Life Metro CASH',
	'SMART Break Matrice Premium CASH',
	'SMART Break Premium',
	'SMART Break Premium CASH',
	'SMART Break Premium Plus',
	'SMART Break Premium Plus CASH',
	'Special Adult ',
	'Special Junior Semestrale CASH',
	'Speciale Junior',
	'Speciale Junior Cash',
	'Specialist Academy',
	'Staff Family',
	'Staff Family Senior ',
	'Staff Family Young',
	'Tessera Adulto 10 Ingressi',
	'Titolare',
	'Vip',
	'Vip Classic',
	'Vip Premium',
	'Vip Senior',
	'Vip Senior Collection',
	'Vip Young',
	'Vip Young Collection',
	'Virgin Fibra',
	'W - SMART Open Flexi Collection Global App Test CASH')