SELECT
	MPR.CACHED_PRODUCTNAME "Product Name",
	MPR.GLOBALID "Global Product ID",
	C.NAME "Club Name"
FROM 
	PRODUCT_AVAILABILITY PA
JOIN
	MASTERPRODUCTREGISTER MPR 
ON 
	MPR.DEFINITION_KEY = PA.PRODUCT_MASTER_KEY
JOIN
	CENTERS C 
ON 
	PA.SCOPE_ID = C.ID AND PA.SCOPE_TYPE = 'C' -- Overide is specified at club level  
WHERE
	MPR.STATE = 'ACTIVE'
AND
	MPR.PRODUCT_ACCOUNT_CONFIG_ID IN (406,476,404,405,408,409) -- Membership Revenue
AND
	C.ID In (76,29,33,35,51,56,407,400) -- Classic Clubs