SELECT
    *
FROM
    (
        SELECT
            s.center                                                                                  AS "Home Center" ,
            pr.name                                                                                   AS "Subscription",
            COUNT (DISTINCT p.center||'p'||p.id)                                                      AS Members_with_Sub,
            SUM(DECODE(c.shortname,'Aldersgate',1,0))                                                 AS "Aldersgate",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Aldersgate',p.center||'p'||p.id,NULL))                AS "Aldersgate_unq",
            SUM(DECODE(c.shortname,'Bank',1,0))                                                       AS "Bank",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Bank',p.center||'p'||p.id,NULL))                      AS "Bank_unq",
            SUM(DECODE(c.shortname,'Barbican',1,0))                                                   AS "Barbican",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Barbican',p.center||'p'||p.id,NULL))                  AS "Barbican_unq",
            SUM(DECODE(c.shortname,'Belfast',1,0))                                                    AS "Belfast",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Belfast',p.center||'p'||p.id,NULL))                   AS "Belfast_unq",
            SUM(DECODE(c.shortname,'Birmingham',1,0))                                                 AS "Birmingham",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Birmingham',p.center||'p'||p.id,NULL))                AS "Birmingham_unq",
            SUM(DECODE(c.shortname,'Bolton',1,0))                                                     AS "Bolton",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Bolton',p.center||'p'||p.id,NULL))                    AS "Bolton_unq",
            SUM(DECODE(c.shortname,'Borehamwood',1,0))                                                AS "Borehamwood",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Borehamwood',p.center||'p'||p.id,NULL))               AS "Borehamwood_unq",
            SUM(DECODE(c.shortname,'Bradford',1,0))                                                   AS "Bradford",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Bradford',p.center||'p'||p.id,NULL))                  AS "Bradford_unq",
            SUM(DECODE(c.shortname,'Bridgend',1,0))                                                   AS "Bridgend",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Bridgend',p.center||'p'||p.id,NULL))                  AS "Bridgend_unq",
            SUM(DECODE(c.shortname,'Brighton',1,0))                                                   AS "Brighton",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Brighton',p.center||'p'||p.id,NULL))                  AS "Brighton_unq",
            SUM(DECODE(c.shortname,'Bristol',1,0))                                                    AS "Bristol",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Bristol',p.center||'p'||p.id,NULL))                   AS "Bristol_unq",
            SUM(DECODE(c.shortname,'Broadgate',1,0))                                                  AS "Broadgate",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Broadgate',p.center||'p'||p.id,NULL))                 AS "Broadgate_unq",
            SUM(DECODE(c.shortname,'Bromley',1,0))                                                    AS "Bromley",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Bromley',p.center||'p'||p.id,NULL))                   AS "Bromley_unq",
            SUM(DECODE(c.shortname,'Canary Riverside',1,0))                                           AS "Canary Riverside",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Canary Riverside',p.center||'p'||p.id,NULL))          AS "Canary Riverside_unq",
            SUM(DECODE(c.shortname,'Chelmsford',1,0))                                                 AS "Chelmsford",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Chelmsford',p.center||'p'||p.id,NULL))                AS "Chelmsford_unq",
            SUM(DECODE(c.shortname,'Chelsea',1,0))                                                    AS "Chelsea",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Chelsea',p.center||'p'||p.id,NULL))                   AS "Chelsea_unq",
            SUM(DECODE(c.shortname,'Chigwell',1,0))                                                   AS "Chigwell",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Chigwell',p.center||'p'||p.id,NULL))                  AS "Chigwell_unq",
            SUM(DECODE(c.shortname,'Chislehurst',1,0))                                                AS "Chislehurst",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Chislehurst',p.center||'p'||p.id,NULL))               AS "Chislehurst_unq",
            SUM(DECODE(c.shortname,'Chiswick Park',1,0))                                              AS "Chiswick Park",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Chiswick Park',p.center||'p'||p.id,NULL))             AS "Chiswick Park_unq",
            SUM(DECODE(c.shortname,'Chiswick Riverside',1,0))                                         AS "Chiswick Riverside",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Chiswick Riverside',p.center||'p'||p.id,NULL))        AS "Chiswick Riverside_unq",
            SUM(DECODE(c.shortname,'Clapham',1,0))                                                    AS "Clapham",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Clapham',p.center||'p'||p.id,NULL))                   AS "Clapham_unq",
            SUM(DECODE(c.shortname,'Clearview',1,0))                                                  AS "Clearview",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Clearview',p.center||'p'||p.id,NULL))                 AS "Clearview_unq",
            SUM(DECODE(c.shortname,'Crawley',1,0))                                                    AS "Crawley",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Crawley',p.center||'p'||p.id,NULL))                   AS "Crawley_unq",
            SUM(DECODE(c.shortname,'Cricklewood',1,0))                                                AS "Cricklewood",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Cricklewood',p.center||'p'||p.id,NULL))               AS "Cricklewood_unq",
            SUM(DECODE(c.shortname,'Crouch End',1,0))                                                 AS "Crouch End",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Crouch End',p.center||'p'||p.id,NULL))                AS "Crouch End_unq",
            SUM(DECODE(c.shortname,'Croydon',1,0))                                                    AS "Croydon",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Croydon',p.center||'p'||p.id,NULL))                   AS "Croydon_unq",
            SUM(DECODE(c.shortname,'Cwmbran',1,0))                                                    AS "Cwmbran",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Cwmbran',p.center||'p'||p.id,NULL))                   AS "Cwmbran_unq",
            SUM(DECODE(c.shortname,'Denton',1,0))                                                     AS "Denton",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Denton',p.center||'p'||p.id,NULL))                    AS "Denton_unq",
            SUM(DECODE(c.shortname,'Derby',1,0))                                                      AS "Derby",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Derby',p.center||'p'||p.id,NULL))                     AS "Derby_unq",
            SUM(DECODE(c.shortname,'Devonshire',1,0))                                                 AS "Devonshire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Devonshire',p.center||'p'||p.id,NULL))                AS "Devonshire_unq",
            SUM(DECODE(c.shortname,'Dorset',1,0))                                                     AS "Dorset",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Dorset',p.center||'p'||p.id,NULL))                    AS "Dorset_unq",
            SUM(DECODE(c.shortname,'Ealing',1,0))                                                     AS "Ealing",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Ealing',p.center||'p'||p.id,NULL))                    AS "Ealing_unq",
            SUM(DECODE(c.shortname,'Edinburgh Fountain Park',1,0))                                    AS "Edinburgh Fountain Park",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Edinburgh Fountain Park',p.center||'p'||p.id,NULL))   AS "Edinburgh Fountain Park_unq",
            SUM(DECODE(c.shortname,'Edinburgh Omni',1,0))                                             AS "Edinburgh Omni",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Edinburgh Omni',p.center||'p'||p.id,NULL))            AS "Edinburgh Omni_unq",
            SUM(DECODE(c.shortname,'Enfield',1,0))                                                    AS "Enfield",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Enfield',p.center||'p'||p.id,NULL))                   AS "Enfield_unq",
            SUM(DECODE(c.shortname,'Farnborough',1,0))                                                AS "Farnborough",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Farnborough',p.center||'p'||p.id,NULL))               AS "Farnborough_unq",
            SUM(DECODE(c.shortname,'Friern Barnet',1,0))                                              AS "Friern Barnet",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Friern Barnet',p.center||'p'||p.id,NULL))             AS "Friern Barnet_unq",
            SUM(DECODE(c.shortname,'Fulham Pools',1,0))                                               AS "Fulham Pools",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Fulham Pools',p.center||'p'||p.id,NULL))              AS "Fulham Pools_unq",
            SUM(DECODE(c.shortname,'Glamorgan',1,0))                                                  AS "Glamorgan",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Glamorgan',p.center||'p'||p.id,NULL))                 AS "Glamorgan_unq",
            SUM(DECODE(c.shortname,'Glasgow ',1,0))                                                   AS "Glasgow ",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Glasgow ',p.center||'p'||p.id,NULL))                  AS "Glasgow _unq",
            SUM(DECODE(c.shortname,'Gloucester',1,0))                                                 AS "Gloucester",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Gloucester',p.center||'p'||p.id,NULL))                AS "Gloucester_unq",
            SUM(DECODE(c.shortname,'Gloucestershire',1,0))                                            AS "Gloucestershire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Gloucestershire',p.center||'p'||p.id,NULL))           AS "Gloucestershire_unq",
            SUM(DECODE(c.shortname,'Guildford',1,0))                                                  AS "Guildford",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Guildford',p.center||'p'||p.id,NULL))                 AS "Guildford_unq",
            SUM(DECODE(c.shortname,'Hammersmith',1,0))                                                AS "Hammersmith",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Hammersmith',p.center||'p'||p.id,NULL))               AS "Hammersmith_unq",
            SUM(DECODE(c.shortname,'Hampshire',1,0))                                                  AS "Hampshire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Hampshire',p.center||'p'||p.id,NULL))                 AS "Hampshire_unq",
            SUM(DECODE(c.shortname,'Harlow',1,0))                                                     AS "Harlow",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Harlow',p.center||'p'||p.id,NULL))                    AS "Harlow_unq",
            SUM(DECODE(c.shortname,'Hemel Hempstead',1,0))                                            AS "Hemel Hempstead",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Hemel Hempstead',p.center||'p'||p.id,NULL))           AS "Hemel Hempstead_unq",
            SUM(DECODE(c.shortname,'Hendon',1,0))                                                     AS "Hendon",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Hendon',p.center||'p'||p.id,NULL))                    AS "Hendon_unq",
            SUM(DECODE(c.shortname,'Humberston',1,0))                                                 AS "Humberston",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Humberston',p.center||'p'||p.id,NULL))                AS "Humberston_unq",
            SUM(DECODE(c.shortname,'Ilford',1,0))                                                     AS "Ilford",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Ilford',p.center||'p'||p.id,NULL))                    AS "Ilford_unq",
            SUM(DECODE(c.shortname,'Islington Angel',1,0))                                            AS "Islington Angel",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Islington Angel',p.center||'p'||p.id,NULL))           AS "Islington Angel_unq",
            SUM(DECODE(c.shortname,'Islington Essex Road',1,0))                                       AS "Islington Essex Road",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Islington Essex Road',p.center||'p'||p.id,NULL))      AS "Islington Essex Road_unq",
            SUM(DECODE(c.shortname,'Kensington',1,0))                                                 AS "Kensington",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Kensington',p.center||'p'||p.id,NULL))                AS "Kensington_unq",
            SUM(DECODE(c.shortname,'Kingston Richmond Road',1,0))                                     AS "Kingston Richmond Road",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Kingston Richmond Road',p.center||'p'||p.id,NULL))    AS "Kingston Richmond Road_unq",
            SUM(DECODE(c.shortname,'Lanarkshire',1,0))                                                AS "Lanarkshire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Lanarkshire',p.center||'p'||p.id,NULL))               AS "Lanarkshire_unq",
            SUM(DECODE(c.shortname,'Lancashire',1,0))                                                 AS "Lancashire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Lancashire',p.center||'p'||p.id,NULL))                AS "Lancashire_unq",
            SUM(DECODE(c.shortname,'Leeds Kirkstall Road',1,0))                                       AS "Leeds Kirkstall Road",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Leeds Kirkstall Road',p.center||'p'||p.id,NULL))      AS "Leeds Kirkstall Road_unq",
            SUM(DECODE(c.shortname,'Leeds Light',1,0))                                                AS "Leeds Light",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Leeds Light',p.center||'p'||p.id,NULL))               AS "Leeds Light_unq",
            SUM(DECODE(c.shortname,'Lichfield',1,0))                                                  AS "Lichfield",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Lichfield',p.center||'p'||p.id,NULL))                 AS "Lichfield_unq",
            SUM(DECODE(c.shortname,'Manchester Didsbury',1,0))                                        AS "Manchester Didsbury",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Manchester Didsbury',p.center||'p'||p.id,NULL))       AS "Manchester Didsbury_unq",
            SUM(DECODE(c.shortname,'Manchester Printworks',1,0))                                      AS "Manchester Printworks",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Manchester Printworks',p.center||'p'||p.id,NULL))     AS "Manchester Printworks_unq",
            SUM(DECODE(c.shortname,'Mayfair',1,0))                                                    AS "Mayfair",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Mayfair',p.center||'p'||p.id,NULL))                   AS "Mayfair_unq",
            SUM(DECODE(c.shortname,'Medway',1,0))                                                     AS "Medway",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Medway',p.center||'p'||p.id,NULL))                    AS "Medway_unq",
            SUM(DECODE(c.shortname,'Merchant Sq',1,0))                                                AS "Merchant Sq",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Merchant Sq',p.center||'p'||p.id,NULL))               AS "Merchant Sq_unq",
            SUM(DECODE(c.shortname,'Merton Abbey',1,0))                                               AS "Merton Abbey",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Merton Abbey',p.center||'p'||p.id,NULL))              AS "Merton Abbey_unq",
            SUM(DECODE(c.shortname,'Mill Hill',1,0))                                                  AS "Mill Hill",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Mill Hill',p.center||'p'||p.id,NULL))                 AS "Mill Hill_unq",
            SUM(DECODE(c.shortname,'Milngavie',1,0))                                                  AS "Milngavie",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Milngavie',p.center||'p'||p.id,NULL))                 AS "Milngavie_unq",
            SUM(DECODE(c.shortname,'Milton Keynes',1,0))                                              AS "Milton Keynes",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Milton Keynes',p.center||'p'||p.id,NULL))             AS "Milton Keynes_unq",
            SUM(DECODE(c.shortname,'Moorgate',1,0))                                                   AS "Moorgate",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Moorgate',p.center||'p'||p.id,NULL))                  AS "Moorgate_unq",
            SUM(DECODE(c.shortname,'Norfolk',1,0))                                                    AS "Norfolk",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Norfolk',p.center||'p'||p.id,NULL))                   AS "Norfolk_unq",
            SUM(DECODE(c.shortname,'Northampton Collingtree P',1,0))                                  AS "Northampton Collingtree P",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Northampton Collingtree P',p.center||'p'||p.id,NULL)) AS "Northampton Collingtree P_unq",
            SUM(DECODE(c.shortname,'Northampton Riverside Par',1,0))                                  AS "Northampton Riverside Par",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Northampton Riverside Par',p.center||'p'||p.id,NULL)) AS "Northampton Riverside Par_unq",
            SUM(DECODE(c.shortname,'Northwood Riverside',1,0))                                        AS "Northwood Riverside",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Northwood Riverside',p.center||'p'||p.id,NULL))       AS "Northwood Riverside_unq",
            SUM(DECODE(c.shortname,'Notting Hill',1,0))                                               AS "Notting Hill",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Notting Hill',p.center||'p'||p.id,NULL))              AS "Notting Hill_unq",
            SUM(DECODE(c.shortname,'Nottingham',1,0))                                                 AS "Nottingham",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Nottingham',p.center||'p'||p.id,NULL))                AS "Nottingham_unq",
            SUM(DECODE(c.shortname,'Oxfordshire',1,0))                                                AS "Oxfordshire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Oxfordshire',p.center||'p'||p.id,NULL))               AS "Oxfordshire_unq",
            SUM(DECODE(c.shortname,'Preston',1,0))                                                    AS "Preston",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Preston',p.center||'p'||p.id,NULL))                   AS "Preston_unq",
            SUM(DECODE(c.shortname,'Putney',1,0))                                                     AS "Putney",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Putney',p.center||'p'||p.id,NULL))                    AS "Putney_unq",
            SUM(DECODE(c.shortname,'Repton Park',1,0))                                                AS "Repton Park",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Repton Park',p.center||'p'||p.id,NULL))               AS "Repton Park_unq",
            SUM(DECODE(c.shortname,'Romford',1,0))                                                    AS "Romford",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Romford',p.center||'p'||p.id,NULL))                   AS "Romford_unq",
            SUM(DECODE(c.shortname,'Royal Berkshire',1,0))                                            AS "Royal Berkshire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Royal Berkshire',p.center||'p'||p.id,NULL))           AS "Royal Berkshire_unq",
            SUM(DECODE(c.shortname,'Rugby',1,0))                                                      AS "Rugby",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Rugby',p.center||'p'||p.id,NULL))                     AS "Rugby_unq",
            SUM(DECODE(c.shortname,'Rustington',1,0))                                                 AS "Rustington",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Rustington',p.center||'p'||p.id,NULL))                AS "Rustington_unq",
            SUM(DECODE(c.shortname,'Salford Quays',1,0))                                              AS "Salford Quays",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Salford Quays',p.center||'p'||p.id,NULL))             AS "Salford Quays_unq",
            SUM(DECODE(c.shortname,'Sheffield Broadfield Park',1,0))                                  AS "Sheffield Broadfield Park",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Sheffield Broadfield Park',p.center||'p'||p.id,NULL)) AS "Sheffield Broadfield Park_unq",
            SUM(DECODE(c.shortname,'Sheffield Millhouses',1,0))                                       AS "Sheffield Millhouses",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Sheffield Millhouses',p.center||'p'||p.id,NULL))      AS "Sheffield Millhouses_unq",
            SUM(DECODE(c.shortname,'Solihull',1,0))                                                   AS "Solihull",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Solihull',p.center||'p'||p.id,NULL))                  AS "Solihull_unq",
            SUM(DECODE(c.shortname,'Stafford',1,0))                                                   AS "Stafford",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Stafford',p.center||'p'||p.id,NULL))                  AS "Stafford_unq",
            SUM(DECODE(c.shortname,'Staines',1,0))                                                    AS "Staines",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Staines',p.center||'p'||p.id,NULL))                   AS "Staines_unq",
            SUM(DECODE(c.shortname,'Stockley Park',1,0))                                              AS "Stockley Park",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Stockley Park',p.center||'p'||p.id,NULL))             AS "Stockley Park_unq",
            SUM(DECODE(c.shortname,'Strand',1,0))                                                     AS "Strand",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Strand',p.center||'p'||p.id,NULL))                    AS "Strand_unq",
            SUM(DECODE(c.shortname,'Streatham',1,0))                                                  AS "Streatham",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Streatham',p.center||'p'||p.id,NULL))                 AS "Streatham_unq",
            SUM(DECODE(c.shortname,'Sunbury',1,0))                                                    AS "Sunbury",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Sunbury',p.center||'p'||p.id,NULL))                   AS "Sunbury_unq",
            SUM(DECODE(c.shortname,'Surrey',1,0))                                                     AS "Surrey",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Surrey',p.center||'p'||p.id,NULL))                    AS "Surrey_unq",
            SUM(DECODE(c.shortname,'Swiss Cottage',1,0))                                              AS "Swiss Cottage",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Swiss Cottage',p.center||'p'||p.id,NULL))             AS "Swiss Cottage_unq",
            SUM(DECODE(c.shortname,'Taunton',1,0))                                                    AS "Taunton",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Taunton',p.center||'p'||p.id,NULL))                   AS "Taunton_unq",
            SUM(DECODE(c.shortname,'Thorpe Wood',1,0))                                                AS "Thorpe Wood",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Thorpe Wood',p.center||'p'||p.id,NULL))               AS "Thorpe Wood_unq",
            SUM(DECODE(c.shortname,'Thundersley',1,0))                                                AS "Thundersley",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Thundersley',p.center||'p'||p.id,NULL))               AS "Thundersley_unq",
            SUM(DECODE(c.shortname,'Tower Bridge',1,0))                                               AS "Tower Bridge",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Tower Bridge',p.center||'p'||p.id,NULL))              AS "Tower Bridge_unq",
            SUM(DECODE(c.shortname,'Tunbridge Wells',1,0))                                            AS "Tunbridge Wells",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Tunbridge Wells',p.center||'p'||p.id,NULL))           AS "Tunbridge Wells_unq",
            SUM(DECODE(c.shortname,'Twickenham ',1,0))                                                AS "Twickenham ",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Twickenham ',p.center||'p'||p.id,NULL))               AS "Twickenham _unq",
            SUM(DECODE(c.shortname,'VA UK Head Office',1,0))                                          AS "VA UK Head Office",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'VA UK Head Office',p.center||'p'||p.id,NULL))         AS "VA UK Head Office_unq",
            SUM(DECODE(c.shortname,'Walbrook',1,0))                                                   AS "Walbrook",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Walbrook',p.center||'p'||p.id,NULL))                  AS "Walbrook_unq",
            SUM(DECODE(c.shortname,'Wandsworth Smugglers Way',1,0))                                   AS "Wandsworth Smugglers Way",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wandsworth Smugglers Way',p.center||'p'||p.id,NULL))  AS "Wandsworth Smugglers Way_unq",
            SUM(DECODE(c.shortname,'Wandsworth Southside',1,0))                                       AS "Wandsworth Southside",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wandsworth Southside',p.center||'p'||p.id,NULL))      AS "Wandsworth Southside_unq",
            SUM(DECODE(c.shortname,'Warwickshire',1,0))                                               AS "Warwickshire",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Warwickshire',p.center||'p'||p.id,NULL))              AS "Warwickshire_unq",
            SUM(DECODE(c.shortname,'Wearside',1,0))                                                   AS "Wearside",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wearside',p.center||'p'||p.id,NULL))                  AS "Wearside_unq",
            SUM(DECODE(c.shortname,'West London',1,0))                                                AS "West London",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'West London',p.center||'p'||p.id,NULL))               AS "West London_unq",
            SUM(DECODE(c.shortname,'Weston',1,0))                                                     AS "Weston",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Weston',p.center||'p'||p.id,NULL))                    AS "Weston_unq",
            SUM(DECODE(c.shortname,'Wimbledon North Road',1,0))                                       AS "Wimbledon North Road",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wimbledon North Road',p.center||'p'||p.id,NULL))      AS "Wimbledon North Road_unq",
            SUM(DECODE(c.shortname,'Wimbledon Worple Road',1,0))                                      AS "Wimbledon Worple Road",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wimbledon Worple Road',p.center||'p'||p.id,NULL))     AS "Wimbledon Worple Road_unq",
            SUM(DECODE(c.shortname,'Wokingham',1,0))                                                  AS "Wokingham",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wokingham',p.center||'p'||p.id,NULL))                 AS "Wokingham_unq",
            SUM(DECODE(c.shortname,'Wolverhampton',1,0))                                              AS "Wolverhampton",
            COUNT (DISTINCT DECODE(c.SHORTNAME,'Wolverhampton',p.center||'p'||p.id,NULL))             AS "Wolverhampton_unq"
        FROM
            SUBSCRIPTIONS s
        JOIN
            PERSONS p
        ON
            s.OWNER_CENTER = p.CENTER
            AND s.OWNER_ID = p.ID
        LEFT JOIN
            ATTENDS att
        ON
            att.PERSON_CENTER = p.center
            AND att.PERSON_ID = p.id
        LEFT JOIN
            BOOKING_RESOURCES br
        ON
            br.CENTER = att.BOOKING_RESOURCE_CENTER
            AND br.id = att.BOOKING_RESOURCE_ID
            AND br.NAME='Gym Floor'
        LEFT JOIN
            centers c
        ON
            c.id = br.center
        JOIN
            PRODUCTS pr
        ON
            pr.center = s.SUBSCRIPTIONTYPE_CENTER
            AND pr.id = s.SUBSCRIPTIONTYPE_ID
        WHERE
            p.persontype <>2
            AND s.STATE = 2
            AND s.center = $$home_center$$
            AND att.START_TIME BETWEEN $$from_date$$ AND $$to_date$$
            AND NOT EXISTS
            (
                SELECT
                    1
                FROM
                    ATTENDS att2
                WHERE
                    att2.PERSON_CENTER = att.PERSON_CENTER
                    AND att2.PERSON_ID = att.PERSON_ID
                    AND att2.BOOKING_RESOURCE_CENTER = att.BOOKING_RESOURCE_CENTER
                    AND att2.START_TIME BETWEEN att.START_TIME - 1000*60*60*3 AND att.START_TIME-1)
        GROUP BY
            s.center,
            pr.name) 