-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
    p.EXTERNAL_ID::VARCHAR AS "EXTERNALID",
    p.ZIPCODE AS "POSTALCODE",  
    pea.TXTVALUE AS "EMAIL",
    p.CENTER::VARCHAR AS "GYMID",
    CASE  p.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE' 
                       WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' WHEN 8 THEN  'ANONYMIZED'  WHEN 9 THEN  'CONTACT'  ELSE 'UNKNOWN' END AS "PERSONSTATUS",
    CASE  p.BLACKLISTED  WHEN 0 THEN  'NONE'  WHEN 1 THEN  'BLACKLISTED'  WHEN 2 THEN  'SUSPENDED'  WHEN 3 THEN  'BLOCKED' END AS "BLACKLISTED",
    TO_CHAR(longtodatec(p.LAST_MODIFIED,p.CENTER),'YYYY-MM-DD HH24:MI:SS') AS "EXERPLASTMODIFIEDDATE"
FROM
    PERSONS p
LEFT JOIN PERSON_EXT_ATTRS pea ON pea.PERSONCENTER = p.CENTER AND pea.PERSONID = p.ID AND pea.NAME = '_eClub_Email'
WHERE
        p.CENTER IN (:Scope)
        AND p.EXTERNAL_ID IS NOT NULL
        AND p.SEX != 'C'
        AND pea.TXTVALUE IS NULL