with 
     params as materialized 
     (   
        select
				c.id AS CENTERID,

                datetolongC(TO_CHAR(CAST(:From AS DATE), 'YYYY-MM-dd HH24:MI'),c.id) AS FromDate,
                
                CAST((datetolongC(TO_CHAR((CAST(:To AS DATE) + INTERVAL '1 day'), 'YYYY-MM-dd HH24:MI'),c.id) - 1) AS BIGINT) AS ToDate         
        
                    
        from centers c        
        where c.id in (:scope)    
     )

SELECT DISTINCT 
    S.CENTER AS CENTER, 
    S.ID AS ID, 
    CASE S.STATE WHEN 2 THEN 'ACTIVE' WHEN 3 THEN 'ENDED' WHEN 4 THEN 'FROZEN' WHEN 7 THEN 'WINDOW' WHEN 8 THEN 'CREATED' ELSE 'UNKNOWN' END AS
    STATE, 
    CASE S.SUB_STATE WHEN 1 THEN 'NONE' WHEN 2 THEN 'AWAITING ACTIVATION' WHEN 3 THEN 'UPGRADED' WHEN 4 THEN 'DOWNGRADED' WHEN 5 THEN 'EXTENDED' 
        WHEN 6 THEN 'TRANSFERRED' WHEN 7 THEN 'REGRETTED' WHEN 8 THEN 'CANCELLED' WHEN 9 THEN 'BLOCKED' WHEN 10 THEN 'CHANGED' ELSE 'UNKNOWN' END AS
    SUBSTATE, 
    S.SUBSCRIPTIONTYPE_CENTER AS SUBSCRIPTIONTYPE_CENTER,
    S.SUBSCRIPTIONTYPE_ID AS SUBSCRIPTIONTYPE_ID, 
    S.OWNER_CENTER AS OWNER_CENTER, 
    S.OWNER_ID AS OWNER_ID, 
    CURPERS.EXTERNAL_ID AS EXTERNAL_ID, 
    S.BINDING_END_DATE AS BINDING_END_DATE,
    S.BINDING_PRICE AS BINDING_PRICE, 
    S.INDIVIDUAL_PRICE AS INDIVIDUAL_PRICE, 
    S.SUBSCRIPTION_PRICE AS SUBSCRIPTION_PRICE,
    S.START_DATE AS START_DATE, 
    S.END_DATE AS END_DATE,
    S.BILLED_UNTIL_DATE AS BILLED_UNTIL_DATE, 
    S.REFMAIN_CENTER AS REFMAIN_CENTER, 
    S.REFMAIN_ID AS REFMAIN_ID, 
    S.CREATION_TIME AS CREATION_TIME, 
    S.CREATOR_CENTER AS CREATION_CENTER,
    S.CREATOR_ID AS CREATION_ID, 
    S.SAVED_FREE_DAYS AS SAVED_FREE_DAYS, 
    S.SAVED_FREE_MONTHS AS SAVED_FREE_MONTHS,
    S.INVOICELINE_CENTER AS INVOICELINE_CENTER, 
    S.INVOICELINE_ID AS INVOICELINE_ID, 
    S.INVOICELINE_SUBID AS INVOICE_SUBID,
    S.TRANSFERRED_CENTER AS TRANSFERRED_CENTER, 
    S.TRANSFERRED_ID AS TRANSFERRED_ID, 
    S.SUB_COMMENT AS SUB_COMMENT,
    S.EXTENDED_TO_CENTER AS EXTENDED_TO_CENTER, 
    S.EXTENDED_TO_ID AS EXTENDED_TO_ID, 
    S.RENEWAL_REMINDER_SENT AS RENEWAL_REMINDER_SENT, 
    S.RENEWAL_POLICY_OVERRIDE AS RENEWAL_POLICY_OVERRIDE, 
    S.ADMINFEE_INVOICELINE_SUBID AS ADMINFEE_INVOICELINE_SUBID, 
    S.CAMPAIGN_CODE_ID AS CAMPAIGN_CODE_ID, 
    S.IS_PRICE_UPDATE_EXCLUDED AS IS_PRICE_UPDATE_EXCLUDED, 
    PR.NAME AS NAME, 
    PR.GLOBALID AS GLOBAL_ID
FROM SUBSCRIPTIONS AS S 
join params on s.center = params.centerid
LEFT JOIN PERSONS AS P ON ( 
        P.CENTER = S.OWNER_CENTER 
        AND P.ID = S.OWNER_ID)
LEFT JOIN PRODUCTS AS PR ON ( 
        PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER 
        AND PR.ID = S.SUBSCRIPTIONTYPE_ID) 
LEFT JOIN PERSONS AS CURPERS ON ( 
        CURPERS.CENTER = P.CURRENT_PERSON_CENTER
        AND CURPERS.ID = P.CURRENT_PERSON_ID)
WHERE 1=1
    AND P.CENTER IN (:scope)
    AND S.CREATION_TIME between params.fromdate and params.todate
    AND 
    (S.SUBSCRIPTIONTYPE_CENTER, S.SUBSCRIPTIONTYPE_ID) 
    IN
    (   SELECT 
            center, 
            id
        FROM PRODUCTS
        WHERE 
            PTYPE = 10
    --AND GLOBALID IN ( :global_sub_id )
    AND center IN (S.CENTER))