WITH
     PARAMS AS materialized
    (
        SELECT
				TRUNC(to_date(getcentertime(c.id), 'YYYY-MM-DD HH24:MI')+30) AS cutDate,
				TRUNC(to_date(getcentertime(c.id), 'YYYY-MM-DD HH24:MI')) AS todaysDate,
                c.ID AS CenterID
        FROM CENTERS c
        JOIN COUNTRIES co ON c.COUNTRY = co.ID
    )
SELECT 
	cen.EXTERNAL_ID 								AS Cost,
	cen.ID 											AS CenterId,
	sub.OWNER_CENTER || 'p' || sub.OWNER_ID 		AS PersonId,
	CAST(EXTRACT('year' FROM age(per.birthdate)) AS VARCHAR) AS Age,
    CASE  sub.STATE  WHEN 2 THEN 'ACTIVE'  WHEN 3 THEN 'ENDED'  WHEN 4 THEN 'FROZEN'  WHEN 7 THEN 'WINDOW'  WHEN 8 THEN 'CREATED' ELSE 'UNKNOWN' END AS subscription_STATE,
    CASE  sub.SUB_STATE  WHEN 1 THEN 'NONE'  WHEN 2 THEN 'AWAITING_ACTIVATION'  WHEN 3 THEN 'UPGRADED'  WHEN 4 THEN 'DOWNGRADED'  WHEN 5 THEN 'EXTENDED'  WHEN 6 THEN  'TRANSFERRED' WHEN 7 THEN 'REGRETTED' WHEN 8 THEN 'CANCELLED' WHEN 9 THEN 'BLOCKED' ELSE 'UNKNOWN' END  AS SUBSCRIPTION_SUB_STATE,
	CASE  st.ST_TYPE  WHEN 0 THEN 'CASH'  WHEN 1 THEN 'EFT' END 			AS St_Type,
	TO_CHAR(sub.START_DATE, 'YYYY-MM-DD') 			AS start_DATE,	
	TO_CHAR(sub.BINDING_END_DATE, 'YYYY-MM-DD') 	AS binding_END_DATE,
	TO_CHAR(sub.END_DATE, 'YYYY-MM-DD')				AS end_DATE,
	sub.BINDING_PRICE,
	sub.EXTENDED_TO_CENTER
FROM 
	SUBSCRIPTIONS sub
JOIN PARAMS params ON params.CenterID = sub.CENTER
LEFT JOIN SUBSCRIPTIONTYPES st
ON
    st.CENTER = sub.SUBSCRIPTIONTYPE_CENTER
    AND st.ID = sub.SUBSCRIPTIONTYPE_ID
LEFT JOIN PERSONS per
ON
	sub.OWNER_CENTER = per.CENTER
	AND sub.OWNER_ID = per.ID
LEFT JOIN CENTERS cen
ON
	sub.OWNER_CENTER = cen.ID
WHERE 
	sub.CENTER IN (:ChosenScope)
	AND sub.END_DATE >= params.todaysDate
	AND sub.END_DATE < params.cutDate
