SELECT
    per.center || 'p' || per.id personid,
	per.FIRSTNAME,
	per.LASTNAME,
    CASE  per.PERSONTYPE  WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN 'CORPORATE'  WHEN 5 THEN 'ONEMANCORPORATE'  WHEN 6 THEN 'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST' ELSE 'UNKNOWN' END PERSONTYPE, 
    CASE  per.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE'  WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' ELSE 'UNKNOWN' END PERSONSTATUS,
	pa.CREDITOR_ID,
	pa.BANK_REGNO,
	pa.BANK_ACCNO,
	pa.IBAN,
	pa.BIC,
	pa.REF,
	pa.PAYMENT_CYCLE_CONFIG_ID,
    CASE  pa.STATE  WHEN 1 THEN 'Created'  WHEN 2 THEN 'Sent'  WHEN 3 THEN 'Incorrect Account'  WHEN 4 THEN 'Ok'  WHEN 5 THEN 'Account closed'  WHEN 6 THEN 'Cancelled' ELSE 'UNKNOWN' END AGREEMENTSTATE,
	TO_CHAR(longToDate(pa.CREATION_TIME), 'YYYY-MM-DD')		AS PA_CreationTime,
    prod.NAME PRODUCTNAME,
    sub.SUBSCRIPTION_PRICE currentMemberPrice,
	TO_CHAR(sub.START_DATE, 'YYYY-MM-DD') start_DATE,
	TO_CHAR(sub.END_DATE, 'YYYY-MM-DD') end_DATE,
    CASE subType.ST_TYPE  WHEN 0 THEN  'CASH'  WHEN 1 THEN  'EFT' END currenttype,
	TO_CHAR(TRUNC(current_timestamp), 'YYYY-MM-DD') todays_date


FROM
	PERSONS per
LEFT JOIN SUBSCRIPTIONS sub
ON
	sub.OWNER_CENTER = per.CENTER
	AND sub.OWNER_ID = per.ID
	AND sub.STATE IN (2,8)
LEFT JOIN SUBSCRIPTIONTYPES subType
ON
    subType.CENTER = sub.SUBSCRIPTIONTYPE_CENTER
    AND subType.ID = sub.SUBSCRIPTIONTYPE_ID
JOIN PRODUCTS prod
ON
    subType.CENTER = prod.CENTER
    AND subType.ID = prod.ID
LEFT JOIN ACCOUNT_RECEIVABLES ar
ON
	per.CENTER = ar.CUSTOMERCENTER
	AND per.ID = ar.CUSTOMERID
	
LEFT JOIN PAYMENT_ACCOUNTS pacc
ON
	pacc.CENTER = ar.CENTER
	AND pacc.ID = ar.ID

JOIN PAYMENT_AGREEMENTS pa
ON
	pa.CENTER = pacc.ACTIVE_AGR_CENTER
	AND pa.ID = pacc.ACTIVE_AGR_ID
	AND pa.SUBID = pacc.ACTIVE_AGR_SUBID

WHERE
    per.center in (:Scope)
	AND per.STATUS = 1
ORDER BY
	per.CENTER,
	per.ID
