SELECT
	cen.EXTERNAL_ID AS Cost,
	cen.NAME AS Center,
	prod.NAME,
	inv1.BALANCE_QUANTITY,
	inv1.UNIT_VALUE,
	inv1.BALANCE_VALUE,
	TO_CHAR(TRUNC(current_timestamp), 'YYYY-MM-DD') todays_date

FROM
	INVENTORY_TRANS inv1
	
LEFT JOIN PRODUCTS prod
ON
	inv1.PRODUCT_CENTER = prod.CENTER
	AND inv1.PRODUCT_ID = prod.ID
	
INNER JOIN 
	(
		SELECT
			inv.PRODUCT_CENTER,
			inv.PRODUCT_ID,
			MAX(inv.ENTRY_TIME) AS MAXENTRY_TIME
		FROM
			INVENTORY_TRANS inv
		GROUP BY
			inv.PRODUCT_CENTER,
			inv.PRODUCT_ID
	) inv2
ON
	inv1.PRODUCT_CENTER = inv2.PRODUCT_CENTER
	AND inv1.PRODUCT_ID = inv2.PRODUCT_ID
	AND inv1.ENTRY_TIME = inv2.MAXENTRY_TIME
	
LEFT JOIN CENTERS cen
ON
	inv1.PRODUCT_CENTER = cen.ID

WHERE
	inv1.PRODUCT_CENTER IN (:ChosenScope)
	AND inv1.PRODUCT_CENTER NOT IN (100)
	AND inv1.BALANCE_QUANTITY > 0
ORDER BY
	inv1.PRODUCT_CENTER,
	prod.NAME
