SELECT
	cen.SHORTNAME AS Center,
	COUNT(CASE WHEN per.STATUS = 0 THEN per.ID END) AS Lead,
	COUNT(CASE WHEN per.STATUS = 1 THEN per.ID END) AS Active,
	COUNT(CASE WHEN per.STATUS = 2 THEN per.ID END) AS Inactive,
	COUNT(CASE WHEN per.STATUS = 3 THEN per.ID END) AS TempInactive,
	COUNT(*) AS TotalDB
	
FROM
	PERSONS per
LEFT JOIN CENTERS cen
ON
	per.CENTER = cen.ID

WHERE
	per.CENTER IN (:ChosenScope)
	AND per.PERSONTYPE != 2
	AND per.CENTER != 100
GROUP BY cen.SHORTNAME
ORDER BY cen.SHORTNAME