-- The extract is extracted from Exerp on 2026-02-08
-- Used for drafts or other testing
/* Vi läser in tex 639440944 men de vill ha 806886694 i filen. 
 * För att göra detta ska följande göras:
 * -Convert the number you’ve read to hex
 * -reverse it
 * -make it a decimal number again
 * NUMBER: 639440944
 * HEX:   261D1830
 * REVERSE: 0381D162 - WRONG!
 *
 * NUMBER: 4263318670
 * HEX: FE1D148E
 * REVERSE: 8E141DFE
 * LITTLE_END: 2383683070
 *

 * NUMBER should be converted from Big Endian to Little endian byte swapping bytes in hex
*/

SELECT DISTINCT
    E.IDENTITY AS CHIPID,
	TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) AS HEX,
	--TO_NUMBER('30181D26', LPAD('X',LENGTH(E.IDENTITY),'X')) AS REVERSED_NUMBER,
	
	TO_NUMBER(
		CONCAT(
			CONCAT(
				SUBSTR( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ,7, 2),
				SUBSTR( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ,5, 2)
			),
			CONCAT(
				SUBSTR( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ,3, 2),
				SUBSTR( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ,1, 2)
			)
		),
		LPAD('X',LENGTH(E.IDENTITY),'X')
	) AS REVERSED_CONCAT,

CONCAT(
	CASE
		MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
		WHEN 1 THEN '0'
		WHEN 0 THEN ''
	END,
	TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
) AS PADDED_HEX,

CONCAT(
	CONCAT(
		SUBSTR(
			CONCAT(
				CASE
					MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
					WHEN 1 THEN '0'
					WHEN 0 THEN ''
				END,
				TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
			), 7, 2
		),
		SUBSTR(
			CONCAT(
				CASE
					MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
					WHEN 1 THEN '0'
					WHEN 0 THEN ''
				END,
				TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
			), 5, 2
		)
	),
	CONCAT(
		SUBSTR(
			CONCAT(
				CASE
					MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
					WHEN 1 THEN '0'
					WHEN 0 THEN ''
				END,
				TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
			), 3, 2
		),
		SUBSTR(
			CONCAT(
				CASE
					MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
					WHEN 1 THEN '0'
					WHEN 0 THEN ''
				END,
				TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
			), 1, 2
		)
	)
) AS PADDED_REVERSE_HEX,

TO_NUMBER(
	CONCAT(
		CONCAT(
			SUBSTR(
				CONCAT(
					CASE
						MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
						WHEN 1 THEN '0'
						WHEN 0 THEN ''
					END,
					TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
				), 7, 2
			),
			SUBSTR(
				CONCAT(
					CASE
						MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
						WHEN 1 THEN '0'
						WHEN 0 THEN ''
					END,
					TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
				), 5, 2
			)
		),
		CONCAT(
			SUBSTR(
				CONCAT(
					CASE
						MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
						WHEN 1 THEN '0'
						WHEN 0 THEN ''
					END,
					TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
				), 3, 2
			),
			SUBSTR(
				CONCAT(
					CASE
						MOD(LENGTH( TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X'))) ), 2 )
						WHEN 1 THEN '0'
						WHEN 0 THEN ''
					END,
					TRIM(TO_CHAR(E.IDENTITY, LPAD('X',LENGTH(E.IDENTITY),'X')))
				), 1, 2
			)
		)
	),
	LPAD('X',LENGTH(E.IDENTITY),'X')
) AS PADDED_REVERSED_NUMBER,

	'END' AS lastcol

FROM ENTITYIDENTIFIERS E
JOIN PERSONS P ON  (E.REF_CENTER = P.CENTER AND E.REF_ID = P.ID AND E.REF_TYPE = 1 AND E.IDMETHOD = 1 AND E.ENTITYSTATUS = 1)
WHERE E.IDENTITY = '183607392' OR E.IDENTITY = '639440944'


