SELECT
		p.CENTER,
	c.SHORTNAME AS CenterName,
	p.CENTER || 'p' || p.ID AS PersonId,
	pea_comment.TXTVALUE AS Old_Id,
    DECODE (p.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') PERSONTYPE, 
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED', 9,'CONTACT', 'UNKNOWN') PERSONSTATUS,
    DECODE (sub.STATE, 2,'ACTIVE', 3,'ENDED', 4,'FROZEN', 7,'WINDOW', 8,'CREATED','UNKNOWN') subscription_STATE,
    DECODE (sub.SUB_STATE, 1,'NONE', 2,'AWAITING_ACTIVATION', 3,'UPGRADED', 4,'DOWNGRADED', 5,'EXTENDED', 6, 'TRANSFERRED',7,'REGRETTED',8,'CANCELLED',9,'BLOCKED','UNKNOWN')  SUBSCRIPTION_SUB_STATE,
	p.FIRSTNAME,
	p.LASTNAME,
	--p.SSN,
	TO_CHAR(TRUNC(exerpsysdate()), 'YYYY-MM-DD') todays_date
FROM PERSONS p

LEFT JOIN
	(
		SELECT 
			s.OWNER_CENTER,
			s.OWNER_ID,
			MAX(s.ID) AS maxid
		FROM SUBSCRIPTIONS s
		GROUP BY
			s.OWNER_CENTER,
			s.OWNER_ID
	) max_sub
ON
	p.CENTER = max_sub.OWNER_CENTER
	AND p.ID = max_sub.OWNER_ID

LEFT JOIN SUBSCRIPTIONS sub
ON
	max_sub.OWNER_CENTER = sub.OWNER_CENTER
	AND max_sub.OWNER_ID = sub.OWNER_ID
	AND max_sub.maxid = sub.ID


LEFT JOIN CENTERS c
ON
	p.CENTER = c.ID

LEFT JOIN PERSON_EXT_ATTRS pea_comment
ON
    pea_comment.PERSONCENTER = p.center
	AND pea_comment.PERSONID = p.id
	AND pea_comment.NAME = '_eClub_OldSystemPersonId'

WHERE
	p.CENTER IN (:Scope)
	AND p.sex != 'C'