SELECT DISTINCT              
        E.IDENTITY AS CHIPID,
        TO_CHAR(E.REF_ID) AS cusstomernumbers,
        P.FIRSTNAME AS NAME,
        P.LASTNAME,
        P.ADDRESS1 AS ADDRESS,
        P.ZIPCODE,
        P.CITY
FROM ENTITYIDENTIFIERS E
JOIN PERSONS P ON  (E.REF_CENTER = P.CENTER AND E.REF_ID = P.ID AND E.REF_TYPE = 1 AND E.IDMETHOD = 1 AND E.ENTITYSTATUS = 1)
LEFT JOIN SUBSCRIPTIONS S ON (E.REF_CENTER = S.OWNER_CENTER AND E.REF_ID = S.OWNER_ID AND S.STATE IN (2,8) AND S.SUB_STATE != 9)
WHERE (S.CENTER IS NOT NULL AND s.CENTER = 728) OR (E.REF_CENTER = 728 AND (longToDate(E.START_TIME) >= (exerpsysdate() - 30)))