-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT P.CENTER AS CENTER, P.ID AS ID, P.FULLNAME AS FULLNAME, 
        CE.NAME AS CENTER, PE1.LASTNAME AS COMPANYNAME, PE2.EXTERNAL_ID 
        AS EXTERNAL_ID, CASE P.STATUS WHEN 0 THEN 'LEAD' WHEN 1 THEN 
        'ACTIVE' WHEN 2 THEN 'INACTIVE' WHEN 3 THEN 'TEMPORARY 
        INACTIVE' WHEN 4 THEN 'TRANSFERRED' WHEN 5 THEN 'DUPLICATE' 
        WHEN 6 THEN 'PROSPECT' WHEN 7 THEN 'DELETED' WHEN 8 THEN 
        'ANONIMIZED' WHEN 9 THEN 'CONTACT' ELSE 'UNKNOWN' END AS 
        STATUS, CASE P.PERSONTYPE WHEN 0 THEN 'PRIVATE' WHEN 1 THEN 
        'STUDENT' WHEN 2 THEN 'STAFF' WHEN 3 THEN 'FRIEND' WHEN 4 THEN 
        'CORPORATE' WHEN 5 THEN 'ONE MAN CORPORATE' WHEN 6 THEN 
        'FAMILY' WHEN 7 THEN 'SENIOR' WHEN 8 THEN 'GUEST' ELSE 
        'UNKNOWN' END AS PERSONTYPE, P.FIRSTNAME AS FIRSTNAME, 
        P.LASTNAME AS LASTNAME, P.SEX AS SEX, P.BLACKLISTED AS 
        BLACKLISTED, P.ADDRESS1 AS ADDRESS1, P.ADDRESS2 AS ADDRESS2, 
        P.COUNTRY AS COUNTRY, P.ZIPCODE AS ZIPCODE, P.BIRTHDATE AS 
        BIRTHDATE, P.PINCODE AS PINCODE, P.FRIENDS_ALLOWANCE AS 
        FRIENDS_ALLOWANCE, P.CITY AS CITY, PEA1.TXTVALUE AS PHONEHOME, 
        PEA2.TXTVALUE AS PHONEMOBILE, PEA3.TXTVALUE AS EMAIL, 
		PEA5.TXTVALUE as Mafis,

        P.MIDDLENAME AS MIDDLENAME, P.FIRST_ACTIVE_START_DATE AS 
        FIRST_ACTIVE_START_DATE, P.LAST_ACTIVE_START_DATE AS 
        LAST_ACTIVE_START_DATE, P.LAST_ACTIVE_END_DATE AS 
        LAST_ACTIVE_END_DATE, P.MEMBERDAYS AS MEMBERDAYS, 
        P.ACCUMULATED_MEMBERDAYS AS ACCUMULATED_MEMBERDAYS, CASE WHEN 
        P.LAST_ACTIVE_START_DATE IS NULL THEN 0 WHEN 
        P.LAST_ACTIVE_END_DATE IS NULL THEN TRUNC(TO_DATE('2018-02-27', 
        'YYYY-MM-DD') - P.LAST_ACTIVE_START_DATE) + 1 ELSE P.MEMBERDAYS 
        END AS UNBROKEN_MEMBER_DAYS, CASE WHEN P.LAST_ACTIVE_END_DATE 
        IS NULL THEN TRUNC(TO_DATE('2018-02-27', 'YYYY-MM-DD') - 
        P.LAST_ACTIVE_START_DATE) + 1 + P.ACCUMULATED_MEMBERDAYS ELSE 
        P.MEMBERDAYS + P.MEMBERDAYS END AS BROKEN_MEMBER_DAYS, 
        EI1.IDENTITY AS BARCODE, EI2.IDENTITY AS MAGNETICCARD, 
        EI3.IDENTITY AS RFCARD, EI4.IDENTITY AS PIN 
    from PERSONS P LEFT 
    join SUBSCRIPTIONS S ON (P.CENTER = S.OWNER_CENTER AND P.ID = 
        S.OWNER_ID) LEFT 
    join CENTERS CE ON P.CENTER = CE.ID LEFT 
    join ENTITYIDENTIFIERS EI1 ON (P.CENTER = EI1.REF_CENTER AND P.ID = 
        EI1.REF_ID AND EI1.IDMETHOD = 1 AND EI1.ENTITYSTATUS = 1) LEFT 
    join ENTITYIDENTIFIERS EI2 ON (P.CENTER = EI2.REF_CENTER AND P.ID = 
        EI2.REF_ID AND EI2.IDMETHOD = 2 AND EI2.ENTITYSTATUS = 1) LEFT 
    join ENTITYIDENTIFIERS EI3 ON (P.CENTER = EI3.REF_CENTER AND P.ID = 
        EI3.REF_ID AND EI3.IDMETHOD = 4 AND EI3.ENTITYSTATUS = 1) LEFT 
    join ENTITYIDENTIFIERS EI4 ON (P.CENTER = EI4.REF_CENTER AND P.ID = 
        EI4.REF_ID AND EI4.IDMETHOD = 5 AND EI4.ENTITYSTATUS = 1) LEFT 
    join RELATIVES RL ON (P.CENTER = RL.RELATIVECENTER AND P.ID = 
        RL.RELATIVEID AND RL.RTYPE = 2 AND RL.STATUS <> 3) LEFT 
    join PERSONS PE1 ON (PE1.CENTER = RL.CENTER AND PE1.ID = RL.ID) LEFT 
    join PERSONS PE2 ON (PE2.CENTER = P.CURRENT_PERSON_CENTER AND PE2.ID = 
        P.CURRENT_PERSON_ID) LEFT 
    join PERSON_EXT_ATTRS PEA1 ON (PEA1.PERSONCENTER = P.CENTER AND 
        PEA1.PERSONID = P.ID AND PEA1.NAME = '_eClub_PhoneHome') LEFT 
    join PERSON_EXT_ATTRS PEA2 ON (PEA2.PERSONCENTER = 
        P.CURRENT_PERSON_CENTER AND PEA2.PERSONID = P.CURRENT_PERSON_ID 
        AND PEA2.NAME = '_eClub_PhoneSMS') LEFT 
    join PERSON_EXT_ATTRS PEA3 ON (PEA3.PERSONCENTER = 
        P.CURRENT_PERSON_CENTER AND PEA3.PERSONID = P.CURRENT_PERSON_ID 
		AND PEA3.NAME = '_eClub_Email') 
 
LEFT join PERSON_EXT_ATTRS PEA5 ON (PEA5.PERSONCENTER = P.CENTER AND 
        PEA5.PERSONID = P.ID AND PEA5.NAME = 'tarifmafisat')

         WHERE P.CENTER IN (:Scope) 