SELECT 
	p.CENTER || 'p' || p.ID AS PersonId,
    DECODE (p.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') PERSONTYPE, 
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED', 9,'CONTACT', 'UNKNOWN') PERSONSTATUS,
	p.FIRSTNAME,
	p.LASTNAME,  
	p.BLACKLISTED

FROM PERSONS p

WHERE p.center IN (:Scope)
AND p.BLACKLISTED = 1