SELECT
    ACT.CENTER,
    TO_CHAR(LONGTODATE(ACT.TRANS_TIME),'YYYY-MM-DD')       AS BOOK_DATE,
    B.BILL_NO                                              AS VOUCHER_ID,
    ACT.TEXT                                               AS VOUCHER_LINE,
    REPLACE(ACT.AMOUNT,'.',',')                            AS AMOUNT,
    DEB_ACC.EXTERNAL_ID                                    AS DEBET_EXT_ID,
    CRED_ACC.EXTERNAL_ID                                   AS CREDIT_EXT_ID,
    AGG_TRANS.CENTER || 'agt' || AGG_TRANS.ID              AS AGGR_TRANS_ID,
    TO_CHAR(LONGTODATE(ACT.ENTRY_TIME),'YYYY-MM-DD HH:MM') AS ENTRY_TIME,
    B.EMPLOYEE_CENTER || 'emp' || B.EMPLOYEE_ID            AS EMPLOYEE
FROM
    ECLUB2.ACCOUNT_TRANS ACT
JOIN ECLUB2.BILLLINES BL
ON
    BL.ACCOUNT_TRANS_CENTER = ACT.CENTER
    AND BL.ACCOUNT_TRANS_ID = ACT.ID
    AND BL.ACCOUNT_TRANS_SUBID = ACT.SUBID
JOIN BILLS B
ON
    B.CENTER = BL.CENTER
    AND B.ID = BL.ID
JOIN ECLUB2.ACCOUNTS DEB_ACC
ON
    DEB_ACC.CENTER = ACT.DEBIT_ACCOUNTCENTER
    AND DEB_ACC.ID = ACT.DEBIT_ACCOUNTID
JOIN ECLUB2.ACCOUNTS CRED_ACC
ON
    CRED_ACC.CENTER = ACT.CREDIT_ACCOUNTCENTER
    AND CRED_ACC.ID = ACT.CREDIT_ACCOUNTID
LEFT JOIN ECLUB2.AGGREGATED_TRANSACTIONS AGG_TRANS
ON
    AGG_TRANS.CENTER = ACT.CENTER
    AND AGG_TRANS.ID = ACT.ID
WHERE
    ACT.TRANS_TIME >= :FromDate
    AND ACT.TRANS_TIME <= :ToDate
AND BL.CENTER in (:Scope)
ORDER BY
    ACT.CENTER,
    TO_CHAR(LONGTODATE(ACT.TRANS_TIME),'YYYY-MM-DD')
