-- The extract is extracted from Exerp on 2026-02-08
-- List the bookings made by the Twiik User
SELECT 
	per.CENTER, 
	per.ID,
	per.FULLNAME,
	per.PERSONTYPE,
	par.STATE,
	b.NAME,
	LONGTODATE(b.STARTTIME) AS STARTTIME,
	LONGTODATE(par.CREATION_TIME) AS CREATED,
	employee.FULLNAME AS CREATING_USER
FROM PARTICIPATIONS par
JOIN PERSONS per ON
	per.CENTER = par.PARTICIPANT_CENTER
	AND per.ID = PARTICIPANT_ID
JOIN BOOKINGS b ON
	par.BOOKING_CENTER = b.CENTER
	AND par.BOOKING_ID = b.ID
JOIN PERSONS employee ON
	par.CREATION_BY_CENTER = employee.CENTER
	AND par.CREATION_BY_ID = employee.ID
JOIN ACTIVITY act ON
	b.ACTIVITY = act.ID
WHERE 
	per.PERSONTYPE != 2
	AND act.ACTIVITY_TYPE = 2
	AND par.CREATION_TIME > :fromDate
	AND par.CREATION_TIME < :toDate + 3600 * 1000 * 24
	AND par.BOOKING_CENTER IN (:scope)
	AND employee.FULLNAME IN (:employeeName)