SELECT AR.CENTER AS AR_CENTER, AR.ID AS AR_ID, AR.AR_TYPE AS 
        AR_AR_TYPE, PE.CENTER AS PE_CENTER, PE.ID AS PE_ID, PE.SEX AS 
        PE_SEX, PE.FIRSTNAME AS PE_FIRSTNAME, PE.MIDDLENAME AS 
        PE_MIDDLENAME, PE.LASTNAME AS PE_LASTNAME, PE.EXTERNAL_ID AS 
        PE_EXTERNAL_ID, PE.PERSONTYPE AS PE_PERSONTYPE 
    from ACCOUNT_RECEIVABLES AS AR INNER 
    join PERSONS AS PE ON (AR.CUSTOMERCENTER = PE.CENTER AND AR.CUSTOMERID 
        = PE.ID) 
    where (AR.CENTER IN (1) AND (AR.BALANCE <> 0 OR AR.LAST_ENTRY_TIME >= 
        GETENDOFDAY(:date))) 
 