SELECT DISTINCT s.OWNER_CENTER||'p'||s.OWNER_ID,s.OWNER_CENTER, s.BINDING_PRICE, s.INDIVIDUAL_PRICE,s.SUBSCRIPTION_PRICE, sp.PRICE, s.START_DATE, s.END_DATE,sp.FROM_DATE,sp.TO_DATE, p.FIRSTNAME,p.LASTNAME,p.CENTER FROM
SUBSCRIPTIONS s LEFT JOIN PERSONS p ON
P.CENTER = S.OWNER_CENTER  AND P.ID = S.OWNER_ID
LEFT JOIN SUBSCRIPTION_PRICE sp ON
 sp.SUBSCRIPTION_CENTER = s.CENTER
    AND sp.SUBSCRIPTION_ID = s.id
    AND sp.CANCELLED = 0
WHERE (s.OWNER_CENTER||'p'||s.OWNER_ID) IN(
'170p259',
'170p266'
)
AND sp.FROM_DATE > SYSDATE - 30