-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
    cen.NAME CLUB,
	per.center,
    per.center || 'p' || per.id personid,
	per.birthdate,
    CASE  per.PERSONTYPE  WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN 'CORPORATE'  WHEN 5 THEN 'ONEMANCORPORATE'  WHEN 6 THEN 'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST' ELSE 'UNKNOWN' END PERSONTYPE, 
    CASE  per.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE'  WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' ELSE 'UNKNOWN' END PERSONSTATUS,
    per.FIRSTNAME,
    per.LASTNAME,
    per.CITY,
	sub.END_DATE AS Sub_ENDDATE,
    CASE  sub.STATE  WHEN 2 THEN 'ACTIVE'  WHEN 3 THEN 'ENDED'  WHEN 4 THEN 'FROZEN'  WHEN 7 THEN 'WINDOW'  WHEN 8 THEN 'CREATED' ELSE 'UNKNOWN' END subscription_STATE,
    CASE  sub.SUB_STATE  WHEN 1 THEN 'NONE'  WHEN 2 THEN 'AWAITING_ACTIVATION'  WHEN 3 THEN 'UPGRADED'  WHEN 4 THEN 'DOWNGRADED'  WHEN 5 THEN 'EXTENDED'  WHEN 6 THEN  'TRANSFERRED' WHEN 7 THEN 'REGRETTED' WHEN 8 THEN 'CANCELLED' WHEN 9 THEN 'BLOCKED' ELSE 'UNKNOWN' END  SUBSCRIPTION_SUB_STATE,
	pcl.NEW_VALUE AS NewPersonId,
	newper.center AS NewCenter,
	TO_CHAR(longtodate(pcl.ENTRY_TIME), 'YYYY-MM-DD') AS TransferDate,
	CASE  newper.STATUS  WHEN 0 THEN 'LEAD'  WHEN 1 THEN 'ACTIVE'  WHEN 2 THEN 'INACTIVE'  WHEN 3 THEN 'TEMPORARYINACTIVE'  WHEN 4 THEN 'TRANSFERED'  WHEN 5 THEN 'DUPLICATE'  WHEN 6 THEN 'PROSPECT'  WHEN 7 THEN 'DELETED' ELSE 'UNKNOWN' END NewPersonStatus,
--    DECODE(subType.ST_TYPE, 0, 'KONTANT', 1, 'AUTOGIRO') currenttype,
	TO_CHAR(TRUNC(current_timestamp), 'YYYY-MM-DD') todays_date
FROM
    PERSONS per

LEFT JOIN PERSON_CHANGE_LOGS pcl
ON
	per.CENTER = pcl.PERSON_CENTER
	AND per.ID = pcl.PERSON_ID

LEFT JOIN
	(
		SELECT
			per2.CENTER || 'p' || per2.ID AS pid,
			per2.STATUS,
			per2.center
		FROM
			PERSONS per2
 
	) newper
ON
	pcl.NEW_VALUE = newper.pid

JOIN centers cen
ON
    cen.ID = per.CENTER
LEFT JOIN SUBSCRIPTIONS sub
ON
	sub.OWNER_CENTER = per.CENTER
	AND sub.OWNER_ID = per.ID
/*
LEFT JOIN SUBSCRIPTIONTYPES subType
ON
    subType.CENTER = sub.SUBSCRIPTIONTYPE_CENTER
    AND subType.ID = sub.SUBSCRIPTIONTYPE_ID
*/
WHERE
	per.CENTER IN (:ChosenScope) --scope
	AND pcl.CHANGE_ATTRIBUTE = '_eClub_TransferredToId'
	AND newper.STATUS = 1
	AND pcl.ENTRY_TIME BETWEEN :From_date AND :To_date --longdate


				
ORDER BY sub.END_DATE
