-- The extract is extracted from Exerp on 2026-02-08
-- Bla
SELECT
	je.PERSON_CENTER ||'p'||PERSON_ID AS MEMBER_ID,
	je.NAME AS NOTE,
	c.NAME AS EMPLOYEE_CENTER,
	p.FULLNAME AS EMPLOYEE,
	je.TEXT,
	longtodate(je.CREATION_TIME)
FROM JOURNALENTRIES je
JOIN EMPLOYEES e ON
	e.CENTER = je.CREATORCENTER
	AND e.ID = je.CREATORID
JOIN PERSONS p ON
	p.CENTER = e.PERSONCENTER
	AND p.ID = e.PERSONID
JOIN CENTERS c ON
	c.ID = e.CENTER
WHERE 
	je.TEXT LIKE ('TerminationCancel%')
	AND e.CENTER IN ($$scope$$)
	AND je.CREATION_TIME >= $$startDate$$
	AND je.CREATION_TIME < $$toDate$$ + (24 * 60 * 60 * 1000)