/*select p.NAME,p.CENTER,p.ID,pg.NAME,pg.ID from PRODUCTS p 
left join PRODUCT_GROUP pg on
	p.PRIMARY_PRODUCT_GROUP_ID = pg.ID*/
--GROUP BY p.NAME,pg.NAME,pg.ID

/*SELECT 
	cfg.ID,
	cfg.NAME,
	cfg.PRODUCT_ACCOUNT_TYPE,
	cfg.BLOCKED,
	cfg.SCOPE_TYPE,
	cfg.SCOPE_ID,
	cfg.SALES_ACCOUNT_GLOBALID,
	cfg.EXPENSES_ACCOUNT_GLOBALID,
	cfg.REFUND_ACCOUNT_GLOBALID,
	cfg.WRITE_OFF_ACCOUNT_GLOBALID,
	cfg.DEFER_REV_ACCOUNT_GLOBALID
FROM 
	PRODUCT_ACCOUNT_CONFIGURATIONS cfg
JOIN ACCOUNTS acc ON
	cfg.*/

--SELECT * FROM ACCOUNTS

--SELECT * FROM ACCOUNTGROUPS
/*SELECT 
	p.CENTER,
	p.ID,
	p.NAME,
	p.PRODUCT_ACCOUNT_CONFIG_ID,
	cfg.NAME,
	cfg.SCOPE_TYPE,
	cfg.SCOPE_ID,
	cfg.SALES_ACCOUNT_GLOBALID

FROM 
	PRODUCTS p
JOIN PRODUCT_ACCOUNT_CONFIGURATIONS cfg ON
	cfg.ID = p.PRODUCT_ACCOUNT_CONFIG_ID*/

--SELECT * FROM masteraccountregister
SELECT 
	mpr.SCOPE_TYPE AS "PRODUCT_SCOPE_TYPE",
	mpr.SCOPE_ID AS "PRODUCT_SCOPE_ID",
	product_parent.NAME AS "PARENT_NAME",
	product_areas.NAME AS "SCOPE_NAME",
	mpr.CACHED_PRODUCTNAME AS "PRODUCT_NAME",
	mpr.CACHED_PRODUCTPRICE AS "PRODUCT_PRICE",
	mpr.GLOBALID AS "PRODUCT_GLOBALID",
	
	cfg.NAME AS "CFG_NAME",
	cfg.PRODUCT_ACCOUNT_TYPE AS "ACCOUNT_TYPE",
	cfg.SALES_ACCOUNT_GLOBALID AS "SALES_GLOBAL_ID",
	cfg.REFUND_ACCOUNT_GLOBALID  AS "REFUND_GLOBALID",
	cfg.WRITE_OFF_ACCOUNT_GLOBALID AS "WRITE_OFF",
	cfg.defer_lia_account_globalid AS "defer_lia_account_globalid",
	cfg.defer_rev_account_globalid AS "defer_rev_account_globalid",
	cfg.expenses_account_globalid AS "expenses_account_globalid",


	mar.GLOBALID AS "ACCOUNT_GLOBALID",
	mar.NAME AS "ACCOUNT_NAME",	
	mar.EXTERNAL_ID AS "ACCOUNT_EXTERNAL_ID",
	mar.SCOPE_TYPE AS "ACCOUNT_SCOPE_TYPE",
	mar.SCOPE_ID AS "ACCOUNT_SCOPE_ID",
	account_parent.NAME AS "ACCOUNT_PARENT_NAME",
	account_areas.NAME AS "ACCOUNT_SCOPE_NAME"

FROM MASTERPRODUCTREGISTER mpr

JOIN PRODUCT_ACCOUNT_CONFIGURATIONS cfg ON
	cfg.ID = mpr.PRODUCT_ACCOUNT_CONFIG_ID

JOIN MASTERACCOUNTREGISTER mar ON
	mar.GLOBALID = cfg.SALES_ACCOUNT_GLOBALID
JOIN AREAS product_areas ON
	mpr.SCOPE_ID = product_areas.ID
JOIN AREAS product_parent ON
	product_areas.PARENT = product_parent.ID
JOIN AREAS account_areas ON
	mar.SCOPE_ID = account_areas.ID
JOIN AREAS account_parent ON
	account_areas.PARENT = account_parent.ID
WHERE mpr.STATE = 'ACTIVE'

--SELECT * FROM AREAS