select  
	distinct p.CENTER ||'p'||p.ID AS MEMBER_ID,
	p.EXTERNAL_ID,
	p.FULLNAME,
	p.LASTNAME ||','||p.FIRSTNAME AS MERGED_NAME,
	p.SSN AS SSN,
	emp.CENTER EMPLOYEE_CENTER,
	emp.ID EMPLOYEE_ID,
	p.ID,
	p.CENTER,
	emp.LAST_LOGIN AS LAST_LOGIN,
	DECODE (p.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') PERSONTYPE, 
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED','UNKNOWN') PERSONSTATUS,
	c.NAME AS CENTER_NAME,
	DECODE (emp.BLOCKED,0,'EJ BLOCKERAD', 1, 'BLOCKERAD','UNKNOWN') BLOCKED
from EMPLOYEES emp
join PERSONS p on 
	p.CENTER = emp.PERSONCENTER
    and p.ID = emp.PERSONID
join CENTERS c on
	emp.CENTER = c.ID
where 
	emp.CENTER in ($$scope$$)
order by c.NAME

