select  
	distinct p.CENTER ||'p'||p.ID AS MEMBER_ID,
	p.EXTERNAL_ID,
	p.FULLNAME,
	p.LASTNAME ||','||p.FIRSTNAME AS MERGED_NAME,
	p.SSN AS SSN,
	p.ID,
	p.CENTER,
	DECODE (p.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') PERSONTYPE, 
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED','UNKNOWN') PERSONSTATUS,
	c.NAME,
	DECODE (emp.BLOCKED,0,'EJ BLOCKERAD', 1, 'BLOCKERAD','UNKNOWN') BLOCKED,
	emp.CENTER AS EMPLOYEE_CENTER,
	emp.ID AS EMPLOYEE_ID
from PERSONS p 
left join EMPLOYEES emp on 
	p.CENTER = emp.PERSONCENTER
    and p.ID = emp.PERSONID
join CENTERS c on
	p.CENTER = c.ID
where 
	p.CENTER in ($$scope$$)
	and p.persontype=2
order by c.NAME
