-- The extract is extracted from Exerp on 2026-02-08
-- Simplified IK-report that display the IK-values transaction by transaction.

SELECT
	INV0.CENTER AS SALES_CENTER
	,TO_CHAR(longtodate(INV0.ENTRY_TIME), 'YYYY-MM-DD HH24:MI') AS SALES_DATE
	, CASE
		WHEN IL.PERSON_CENTER IS NOT NULL
			THEN IL.PERSON_CENTER || 'p' || IL.PERSON_ID
		ELSE NULL
	END AS MEDLEMS_NUMMER
	, CASE
		WHEN IL.PERSON_CENTER IS NOT NULL
			THEN CASE  PER.PERSONTYPE  WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN  'CORPORATE'  WHEN 5 THEN  'ONEMANCORPORATE'  WHEN 6 THEN  'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST' ELSE 'UNKNOWN' END
		ELSE NULL
	END AS PERSONTYP
	, INV0.TEXT AS INVOICE_TEXT
	, TO_CHAR(s.START_DATE, 'YYYY-MM-DD') AS START_DATE
	, TO_CHAR(s.BILLED_UNTIL_DATE, 'YYYY-MM-DD') AS BILLED_UNTIL_DATE
	, (IL.TEXT) || '...' AS PRODUKT
	, (ROUND(CRT.AMOUNT, 2)) AS SUMMA
,CASE prod.PTYPE  WHEN 1 THEN  'Retail'  WHEN 2 THEN  'Service'  WHEN 4 THEN  'Clipcard'  WHEN 5 THEN  'Subscription creation'  WHEN 6 THEN  'Transfer'  WHEN 7 THEN  'Freeze period'  WHEN 8 THEN  'Gift card'  WHEN 9 THEN  'Free gift card'  WHEN 10 THEN  'Subscription'  WHEN 12 THEN  'Subscription pro-rata'  WHEN 13 THEN  'Subscription add-on'  WHEN 14 THEN  'Access product' END AS PROD_TYPE_NAME
, CASE CRT.CRTTYPE  WHEN 1 THEN  'CASH'  WHEN 6 THEN  'CARD'  WHEN 7 THEN  'CARD'  WHEN 8 THEN  'CARD'  WHEN 5 THEN  'AR_CASH'  WHEN 2 THEN  'CHANGE'  WHEN 9 THEN  'GIFTCARD'  WHEN 13 THEN  'CUSTOM' END AS BETALMEDEL
--,periodFrom AS PERIODFROM
--,periodTo AS PERIODTO
FROM
	INVOICELINES IL
	--CROSS JOIN PARAMS params
	JOIN
		PRODUCTS prod
	ON
		prod.CENTER = IL.PRODUCTCENTER
		AND prod.ID = IL.PRODUCTID
		-- To get the Share municipality link
	LEFT JOIN PRODUCT_AND_PRODUCT_GROUP_LINK spl
	ON
		spl.PRODUCT_CENTER = prod.CENTER
		AND spl.PRODUCT_ID = prod.ID
		AND spl.PRODUCT_GROUP_ID = 8825
	INNER JOIN INVOICES INV0
	ON
		IL.CENTER = INV0.CENTER
		AND IL.ID = INV0.ID
	LEFT JOIN CASHREGISTERREPORTS CRR
	ON
		CRR.CENTER = INV0.CASHREGISTER_CENTER
		AND CRR.ID = INV0.CASHREGISTER_ID
		AND CRR.STARTTIME <= INV0.ENTRY_TIME
		AND CRR.REPORTTIME > INV0.ENTRY_TIME
	LEFT JOIN PERSONS PER
	ON
		IL.PERSON_CENTER = PER.center
		AND IL.PERSON_ID = PER.id
	LEFT JOIN AR_TRANS ART
	ON
		ART.REF_CENTER = INV0.CENTER
		AND ART.REF_ID = INV0.ID
		AND ART.REF_TYPE = 'INVOICE'
	LEFT JOIN ACCOUNT_RECEIVABLES AR
	ON
		ART.CENTER = AR.CENTER
		AND ART.ID = AR.ID
	JOIN CASHREGISTERTRANSACTIONS CRT
	ON
		CRT.CENTER = INV0.CASHREGISTER_CENTER
		AND CRT.ID = INV0.CASHREGISTER_ID
		AND CRT.PAYSESSIONID = INV0.PAYSESSIONID
	LEFT JOIN SUBSCRIPTIONS s
	ON
		s.OWNER_CENTER = per.CENTER
		AND s.OWNER_ID = per.ID
		AND s.STATE = 2
WHERE
	INV0.CASHREGISTER_CENTER = $$center$$
	AND IL.TOTAL_AMOUNT <> 0
	AND prod.PTYPE IN (:productType)
	AND CRT.CRTTYPE NOT IN(5,12)
	AND INV0.ENTRY_TIME >= :periodFromLong --params.periodFromLong
	AND INV0.ENTRY_TIME < :periodToLong + (60 * 60 * 1000) --params.periodToLong
	OR(
		INV0.CASHREGISTER_CENTER = 100 and per.center = $$center$$
		AND prod.PTYPE IN(:productType)
		AND CRT.CRTTYPE NOT IN(5,12)
		AND IL.TOTAL_AMOUNT <> 0
		AND INV0.ENTRY_TIME >= :periodFromLong -- params.periodFromLong
		AND INV0.ENTRY_TIME < :periodToLong + (60 * 60 * 1000) 
	)
	AND NOT EXISTS (
		SELECT * FROM PRODUCT_AND_PRODUCT_GROUP_LINK pgl
		JOIN PRODUCT_GROUP pg
		ON
			pgl.PRODUCT_GROUP_ID = pg.ID
		WHERE
			prod.CENTER = pgl.PRODUCT_CENTER
			AND prod.ID = pgl.PRODUCT_ID
			AND pg.NAME = 'Excluded subscriptions'
	)


/*UNION ON THE CREDITTRANSACTIONS AS WELL*/
UNION ALL
SELECT
	CN.CENTER AS SALES_CENTER
	, TO_CHAR(longtodate(CN.ENTRY_TIME), 'YYYY-MM-DD HH24:MI') AS SALES_DATE
	, CASE
		WHEN CNL.PERSON_CENTER IS NOT NULL
			THEN CNL.PERSON_CENTER || 'p' || CNL.PERSON_ID
		ELSE NULL
		END AS MEDLEMS_NUMMER
	, CASE
		WHEN CNL.PERSON_CENTER IS NOT NULL
			THEN CASE  PER.PERSONTYPE  WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN  'CORPORATE'  WHEN 5 THEN  'ONEMANCORPORATE'  WHEN 6 THEN  'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST' ELSE 'UNKNOWN' END
		ELSE NULL
	END AS PERSONTYP
	, CN.TEXT AS INVOICE_TEXT
	, TO_CHAR(s.START_DATE, 'YYYY-MM-DD') AS START_DATE
	, TO_CHAR(s.END_DATE, 'YYYY-MM-DD') AS END_DATE
	, (CNL.TEXT) || '...' AS PRODUKT
	, (ROUND(CNL.TOTAL_AMOUNT, 2)) AS SUMMA
	,CASE prod.PTYPE  WHEN 1 THEN  'Retail'  WHEN 2 THEN  'Service'  WHEN 4 THEN  'Clipcard'  WHEN 5 THEN  'Subscription creation'  WHEN 6 THEN  'Transfer'  WHEN 7 THEN  'Freeze period'  WHEN 8 THEN  'Gift card'  WHEN 9 THEN  'Free gift card'  WHEN 10 THEN  'Subscription'  WHEN 12 THEN  'Subscription pro-rata'  WHEN 13 THEN  'Subscription add-on'  WHEN 14 THEN  'Access product' END AS PROD_TYPE_NAME
	, CASE CRT.CRTTYPE  WHEN 1 THEN  'CASH'  WHEN 6 THEN  'CARD'  WHEN 7 THEN  'CARD'  WHEN 8 THEN  'CARD'  WHEN 5 THEN  'AR_CASH'  WHEN 2 THEN  'CHANGE'  WHEN 9 THEN  'GIFTCARD'  WHEN 13 THEN  'CUSTOM' END AS BETALMEDEL
--,periodFrom AS PERIODFROM
--,periodTo AS PERIODTO
FROM
	CREDIT_NOTE_LINES CNL
	--CROSS JOIN PARAMS params
	JOIN PRODUCTS prod
	ON
		prod.CENTER = CNL.PRODUCTCENTER
		AND prod.id = CNL.PRODUCTID
	LEFT JOIN PRODUCT_AND_PRODUCT_GROUP_LINK spl
	ON
		spl.PRODUCT_CENTER = prod.CENTER
		AND spl.PRODUCT_ID = prod.ID
		AND spl.PRODUCT_GROUP_ID = 8825
	INNER JOIN CREDIT_NOTES CN
	ON
		CNL.CENTER = CN.CENTER
		AND CNL.ID = CN.ID
	LEFT JOIN CASHREGISTERREPORTS CRR
	ON
		CRR.CENTER = CN.CASHREGISTER_CENTER
		AND CRR.ID = CN.CASHREGISTER_ID
		AND CRR.STARTTIME <= CN.ENTRY_TIME
		AND CRR.REPORTTIME > CN.ENTRY_TIME
	LEFT JOIN PERSONS PER
	ON
		CNL.PERSON_CENTER = PER.center
		AND CNL.PERSON_ID = PER.id
	LEFT JOIN AR_TRANS ART
	ON
		ART.REF_CENTER = CN.CENTER
		AND ART.REF_ID = CN.ID
		AND ART.REF_TYPE = 'CREDIT_NOTE'
	LEFT JOIN ACCOUNT_RECEIVABLES AR
	ON
		ART.CENTER = AR.CENTER
		AND ART.ID = AR.ID
	LEFT JOIN CASHREGISTERTRANSACTIONS CRT
	ON
		CRT.CENTER = CN.CASHREGISTER_CENTER
		AND CRT.ID = CN.CASHREGISTER_ID
		AND CRT.PAYSESSIONID = CN.PAYSESSIONID
	LEFT JOIN SUBSCRIPTIONS s
	ON
		s.OWNER_CENTER = per.CENTER
		AND s.OWNER_ID = per.ID
		AND s.STATE = 2
WHERE
	CN.CASHREGISTER_CENTER = $$center$$
	AND prod.PTYPE IN(:productType) -- 5,10
	AND CNL.TOTAL_AMOUNT <> 0
	AND CN.ENTRY_TIME >= :periodFromLong --params.periodFromLong
	AND CN.ENTRY_TIME < :periodToLong + (60 * 60 * 1000) --params.periodToLong
	AND CRT.CRTTYPE NOT IN(5,12)
	OR (
		CN.CASHREGISTER_CENTER = 100
		AND CRT.CRTTYPE NOT IN (5, 12)
		AND prod.PTYPE IN(:productType)
		AND CNL.TOTAL_AMOUNT <> 0
		AND PER.CENTER = $$center$$
		AND CN.ENTRY_TIME >= :periodFromLong 
		AND CN.ENTRY_TIME < :periodToLong + (60 * 60 * 1000)
	)
	AND NOT EXISTS (
		SELECT * FROM PRODUCT_AND_PRODUCT_GROUP_LINK pgl
		JOIN PRODUCT_GROUP pg
		ON
			pgl.PRODUCT_GROUP_ID = pg.ID
		WHERE
			prod.CENTER = pgl.PRODUCT_CENTER
			AND prod.ID = pgl.PRODUCT_ID
			AND pg.NAME = 'Excluded subscriptions'
	)
