WITH
    PARAMS AS
    (
        SELECT
                /*+ materialize */
				TO_CHAR(TRUNC(ADD_MONTHS(LAST_DAY(to_date(getcentertime(100), 'YYYY-MM-DD HH24:MI'))+1,-2)),'YYYY-MM-DD') AS periodFrom,
				TO_CHAR(TRUNC(ADD_MONTHS(LAST_DAY(to_date(getcentertime(100), 'YYYY-MM-DD HH24:MI')),-1)),'YYYY-MM-DD') AS periodTo,
				datetolongTZ(TO_CHAR(TRUNC(ADD_MONTHS(LAST_DAY(to_date(getcentertime(100), 'YYYY-MM-DD HH24:MI'))+1,-2)), 'YYYY-MM-DD HH24:MI'),'Europe/Stockholm') AS periodFromLong,
				datetolongTZ(TO_CHAR(TRUNC(ADD_MONTHS(LAST_DAY(to_date(getcentertime(100), 'YYYY-MM-DD HH24:MI'))+1,-1)), 'YYYY-MM-DD HH24:MI'),'Europe/Stockholm') AS periodToLong,
				getcentertime(100) AS todaysDate
		FROM DUAL
    )
SELECT
	C1.NAME AS SALES_CENTER
	,SUM(ROUND(IL.TOTAL_AMOUNT, 2)) AS IL_SUMMA
FROM
	INVOICELINES IL
	CROSS JOIN PARAMS params
	JOIN
		PRODUCTS prod
	ON
		prod.CENTER = IL.PRODUCTCENTER
		AND prod.ID = IL.PRODUCTID
		-- To get the Share municipality link
	LEFT JOIN PRODUCT_AND_PRODUCT_GROUP_LINK spl
	ON
		spl.PRODUCT_CENTER = prod.CENTER
		AND spl.PRODUCT_ID = prod.ID
		AND spl.PRODUCT_GROUP_ID = 8825
	INNER JOIN INVOICES INV0
	ON
		IL.CENTER = INV0.CENTER
		AND IL.ID = INV0.ID
	LEFT JOIN CASHREGISTERREPORTS CRR
	ON
		CRR.CENTER = INV0.CASHREGISTER_CENTER
		AND CRR.ID = INV0.CASHREGISTER_ID
		AND CRR.STARTTIME <= INV0.ENTRY_TIME
		AND CRR.REPORTTIME > INV0.ENTRY_TIME
	LEFT JOIN PERSONS PER
	ON
		IL.PERSON_CENTER = PER.center
		AND IL.PERSON_ID = PER.id
	LEFT JOIN AR_TRANS ART
	ON
		ART.REF_CENTER = INV0.CENTER
		AND ART.REF_ID = INV0.ID
		AND ART.REF_TYPE = 'INVOICE'
	LEFT JOIN ACCOUNT_RECEIVABLES AR
	ON
		ART.CENTER = AR.CENTER
		AND ART.ID = AR.ID
	LEFT JOIN CASHREGISTERTRANSACTIONS CRT
	ON
		CRT.CENTER = INV0.CASHREGISTER_CENTER
		AND CRT.ID = INV0.CASHREGISTER_ID
		AND CRT.PAYSESSIONID = INV0.PAYSESSIONID
	LEFT JOIN CENTERS C1
	ON
		C1.ID = INV0.CENTER
WHERE
	INV0.CASHREGISTER_CENTER IN ($$scope$$)
	AND IL.TOTAL_AMOUNT <> 0
	AND INV0.ENTRY_TIME >= params.periodFromLong
	AND INV0.ENTRY_TIME < params.periodToLong
	OR(
		INV0.CASHREGISTER_CENTER = 100 AND PER.CENTER IN ($$scope$$)
		AND IL.TOTAL_AMOUNT <> 0
		AND INV0.ENTRY_TIME >= params.periodFromLong
		AND INV0.ENTRY_TIME < params.periodToLong
	)
	AND NOT EXISTS (
		SELECT * FROM PRODUCT_AND_PRODUCT_GROUP_LINK pgl
		JOIN PRODUCT_GROUP pg
		ON
			pgl.PRODUCT_GROUP_ID = pg.ID
		WHERE
			prod.CENTER = pgl.PRODUCT_CENTER
			AND prod.ID = pgl.PRODUCT_ID
			AND pg.NAME = 'Excluded subscriptions'
	)
GROUP BY C1.NAME




/*UNION ON THE CREDITTRANSACTIONS AS WELL*/
UNION ALL

SELECT
	C2.NAME AS SALES_CENTER
	,-SUM(ROUND(CNL.TOTAL_AMOUNT, 2)) AS IL_SUMMA
FROM
	CREDIT_NOTE_LINES CNL
	CROSS JOIN PARAMS params
	JOIN PRODUCTS prod
	ON
		prod.CENTER = CNL.PRODUCTCENTER
		AND prod.id = CNL.PRODUCTID
	LEFT JOIN PRODUCT_AND_PRODUCT_GROUP_LINK spl
	ON
		spl.PRODUCT_CENTER = prod.CENTER
		AND spl.PRODUCT_ID = prod.ID
		AND spl.PRODUCT_GROUP_ID = 8825
	INNER JOIN CREDIT_NOTES CN
	ON
		CNL.CENTER = CN.CENTER
		AND CNL.ID = CN.ID
	LEFT JOIN CASHREGISTERREPORTS CRR
	ON
		CRR.CENTER = CN.CASHREGISTER_CENTER
		AND CRR.ID = CN.CASHREGISTER_ID
		AND CRR.STARTTIME <= CN.ENTRY_TIME
		AND CRR.REPORTTIME > CN.ENTRY_TIME
	LEFT JOIN PERSONS PER
	ON
		CNL.PERSON_CENTER = PER.center
		AND CNL.PERSON_ID = PER.id
	LEFT JOIN AR_TRANS ART
	ON
		ART.REF_CENTER = CN.CENTER
		AND ART.REF_ID = CN.ID
		AND ART.REF_TYPE = 'CREDIT_NOTE'
	LEFT JOIN ACCOUNT_RECEIVABLES AR
	ON
		ART.CENTER = AR.CENTER
		AND ART.ID = AR.ID
	LEFT JOIN CASHREGISTERTRANSACTIONS CRT
	ON
		CRT.CENTER = CN.CASHREGISTER_CENTER
		AND CRT.ID = CN.CASHREGISTER_ID
		AND CRT.PAYSESSIONID = CN.PAYSESSIONID
	LEFT JOIN CENTERS C2
	ON 
		C2.ID = CN.CENTER
WHERE
	CN.CASHREGISTER_CENTER IN ($$scope$$)
	AND CN.ENTRY_TIME >= params.periodFromLong
	AND CN.ENTRY_TIME < params.periodToLong
	OR (
		CN.CASHREGISTER_CENTER = 100
		AND PER.CENTER IN ($$scope$$)
		AND CN.ENTRY_TIME >= params.periodFromLong
		AND CN.ENTRY_TIME < params.periodToLong
	)
	AND NOT EXISTS (
		SELECT * FROM PRODUCT_AND_PRODUCT_GROUP_LINK pgl
		JOIN PRODUCT_GROUP pg
		ON
			pgl.PRODUCT_GROUP_ID = pg.ID
		WHERE
			prod.CENTER = pgl.PRODUCT_CENTER
			AND prod.ID = pgl.PRODUCT_ID
			AND pg.NAME = 'Excluded subscriptions'
	)
GROUP BY C2.NAME