SELECT
        c.COUNTRY,
        p.EXTERNAL_ID AS SHOPPERREFERENCE,
        (CASE pag.STATE
                WHEN 4 THEN 'OK'
                ELSE 'UNKNOWN'
        END) AS PAYMENT_AGREEMENT_STATE,
        pag.CLEARINGHOUSE_REF AS ALIAS,
        pag.CLEARINGHOUSE_INIT_REF AS TOKEN,
        pag.CREDITOR_ID,
        ch.DATASUPPLIER_ID,
        ch.EXTERNAL_CLEARINGHOUSE_ID
FROM PERSONS p
JOIN ACCOUNT_RECEIVABLES ar ON p.CENTER = ar.CUSTOMERCENTER AND p.ID = ar.CUSTOMERID AND ar.AR_TYPE = 4
JOIN PAYMENT_ACCOUNTS pac ON ar.CENTER = pac.CENTER AND ar.ID = pac.ID
JOIN PAYMENT_AGREEMENTS pag ON pac.ACTIVE_AGR_CENTER = pag.CENTER AND pac.ACTIVE_AGR_ID = pag.ID AND pac.ACTIVE_AGR_SUBID = pag.SUBID
JOIN CENTERS c ON pag.CENTER = c.ID
JOIN CLEARINGHOUSES ch ON pag.CLEARINGHOUSE = ch.ID
WHERE
        ch.STATE = 'ACTIVE'
        AND ch.CTYPE = 173
        AND pag.STATE IN (4)
		AND c.COUNTRY IN (:Country)
