-- The extract is extracted from Exerp on 2026-02-08
-- ST-2369-ver2
SELECT 
	INV0.CENTER AS "SALES_CENTER"
	,TO_CHAR(longtodate(INV0.ENTRY_TIME), 'YYYY-MM-DD HH24:MI') AS "SALES_DATE"
	, CASE
		WHEN IL.PERSON_CENTER IS NOT NULL
			THEN IL.PERSON_CENTER || 'p' || IL.PERSON_ID
		ELSE NULL
	END AS "MEDLEMS_NUMMER"
	, CASE
		WHEN IL.PERSON_CENTER IS NOT NULL
			THEN CASE  PER.PERSONTYPE  WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN  'CORPORATE'  WHEN 5 THEN  'ONEMANCORPORATE'  WHEN 6 THEN  'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST' ELSE 'UNKNOWN' END
		ELSE NULL
	END AS "PERSONTYP"
	, TO_CHAR(s.START_DATE, 'YYYY-MM-DD') AS "START_DATE"
	, TO_CHAR(s.END_DATE, 'YYYY-MM-DD') AS "END_DATE"
	, (IL.TEXT) || '...' AS "PRODUKT"
	, (ROUND(IL.TOTAL_AMOUNT, 2)) AS "SUMMA"
	, ROUND(IL.TOTAL_AMOUNT - (IL.TOTAL_AMOUNT * (1 - (1 / (1 + IL.RATE)))),2) "NETTO"
    , ROUND(IL.TOTAL_AMOUNT * (1 - (1 / (1 + IL.RATE))),2)                     "MOMS"
,CASE prod.PTYPE  WHEN 1 THEN  'Retail'  WHEN 2 THEN  'Service'  WHEN 4 THEN  'Clipcard'  WHEN 5 THEN  'Subscription creation'  WHEN 6 THEN  'Transfer'  WHEN 7 THEN  'Freeze period'  WHEN 8 THEN  'Gift card'  WHEN 9 THEN  'Free gift card'  WHEN 10 THEN  'Subscription'  WHEN 12 THEN  'Subscription pro-rata'  WHEN 13 THEN  'Subscription add-on'  WHEN 14 THEN  'Access product' END AS "TYP"
, CASE CRT.CRTTYPE  WHEN 1 THEN  'CASH'  WHEN 6 THEN  'CARD'  WHEN 7 THEN  'CARD'  WHEN 8 THEN  'CARD'  WHEN 5 THEN  'AR_CASH'  WHEN 2 THEN  'CHANGE'  WHEN 9 THEN  'GIFTCARD'  WHEN 13 THEN  'CUSTOM' END AS "BETALMEDEL"
,c.NAME AS "CENTER_NAME"
,TO_CHAR(longtodate(:periodFromLong), 'YYYY-MM-DD') AS "PERIOD_FROM"
,TO_CHAR(longtodate(:periodToLong), 'YYYY-MM-DD') AS "PERIOD_TO"

,getcentertime(100) AS "TODAY"
,company.COMPANY_NAME AS "COMPANY_NAME"
,company.ADDRESS1 AS "ADDRESS1"
,company.ADDRESS2 AS "ADDRESS2"
,company.ZIPCODE AS "ZIPCODE"
,company.CITY AS "CITY"
,ROUND(company.SPLIT_RATE_COMMUNITY * (IL.TOTAL_AMOUNT - (IL.TOTAL_AMOUNT * (1 - (1 / (1 + IL.RATE))))),2) AS "COMMUNITY_PART"

FROM
	INVOICELINES IL
	JOIN
		PRODUCTS prod
	ON
		prod.CENTER = IL.PRODUCTCENTER
		AND prod.ID = IL.PRODUCTID
		-- To get the Share municipality link
	LEFT JOIN PRODUCT_AND_PRODUCT_GROUP_LINK spl
	ON
		spl.PRODUCT_CENTER = prod.CENTER
		AND spl.PRODUCT_ID = prod.ID
		AND spl.PRODUCT_GROUP_ID = 8825
	INNER JOIN INVOICES INV0
	ON
		IL.CENTER = INV0.CENTER
		AND IL.ID = INV0.ID
	LEFT JOIN CASHREGISTERREPORTS CRR
	ON
		CRR.CENTER = INV0.CASHREGISTER_CENTER
		AND CRR.ID = INV0.CASHREGISTER_ID
		AND CRR.STARTTIME <= INV0.ENTRY_TIME
		AND CRR.REPORTTIME > INV0.ENTRY_TIME
	LEFT JOIN PERSONS PER
	ON
		IL.PERSON_CENTER = PER.center
		AND IL.PERSON_ID = PER.id
	LEFT JOIN AR_TRANS ART
	ON
		ART.REF_CENTER = INV0.CENTER
		AND ART.REF_ID = INV0.ID
		AND ART.REF_TYPE = 'INVOICE'
	LEFT JOIN ACCOUNT_RECEIVABLES AR
	ON
		ART.CENTER = AR.CENTER
		AND ART.ID = AR.ID
	LEFT JOIN CASHREGISTERTRANSACTIONS CRT
	ON
		CRT.CENTER = INV0.CASHREGISTER_CENTER
		AND CRT.ID = INV0.CASHREGISTER_ID
		AND CRT.PAYSESSIONID = INV0.PAYSESSIONID
	LEFT JOIN SUBSCRIPTIONS s
	ON
		s.OWNER_CENTER = per.CENTER
		AND s.OWNER_ID = per.ID
		AND s.STATE = 2
	LEFT JOIN CENTERS c
		ON per.CENTER = c.ID
JOIN
    (
        SELECT
          p.LASTNAME                      COMPANY_NAME
          ,p.ADDRESS1
          ,p.ADDRESS2
          ,p.ZIPCODE
          ,p.CITY
          ,(atts.TXTVALUE)::decimal / 100 SPLIT_RATE_COMMUNITY
          ,c.NAME              CENTER_NAME
        FROM
            PERSONS p
        JOIN
            CENTERS c
        ON
            c.id = :center
        JOIN
            PERSON_EXT_ATTRS atts
        ON
            atts.PERSONCENTER = p.CENTER
            AND atts.PERSONID = p.ID
            AND atts.NAME = 'SPLIT_RATE_COMMUNITY'
        WHERE
            (
				p.LASTNAME LIKE '9' || REPLACE(lpad((:center)::varchar,3),' ','0') || ' %') 
				OR (p.LASTNAME LIKE '9' || REPLACE(lpad((:center)::varchar,4),' ','0') || ' %')
			) company
ON
    1 = 1
WHERE
	per.CENTER = :center
	AND (
		INV0.CASHREGISTER_CENTER = 100
		OR	(		
			(INV0.EMPLOYEE_CENTER = 100 AND INV0.EMPLOYEE_ID = 6204)
		    OR (INV0.EMPLOYEE_CENTER = 100 AND INV0.EMPLOYEE_ID = 49204)

		)
	)
	AND CRT.CRTTYPE NOT IN(5,12)
	AND IL.TOTAL_AMOUNT <> 0
	AND INV0.ENTRY_TIME >= :periodFromLong
	AND INV0.ENTRY_TIME < :periodToLong + (60 * 60 * 1000)
	AND NOT EXISTS (
		SELECT * FROM PRODUCT_AND_PRODUCT_GROUP_LINK pgl
		JOIN PRODUCT_GROUP pg
		ON
			pgl.PRODUCT_GROUP_ID = pg.ID
		WHERE
			prod.CENTER = pgl.PRODUCT_CENTER
			AND prod.ID = pgl.PRODUCT_ID
			AND pg.NAME = 'Excluded subscriptions'
	)



/*UNION ON THE CREDITTRANSACTIONS AS WELL*/
UNION ALL
SELECT
	CN.CENTER AS SALES_CENTER
	, TO_CHAR(longtodate(CN.ENTRY_TIME), 'YYYY-MM-DD HH24:MI') AS SALES_DATE
	, CASE
		WHEN CNL.PERSON_CENTER IS NOT NULL
			THEN CNL.PERSON_CENTER || 'p' || CNL.PERSON_ID
		ELSE NULL
		END AS MEDLEMS_NUMMER
	, CASE
		WHEN CNL.PERSON_CENTER IS NOT NULL
			THEN CASE  PER.PERSONTYPE  WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN  'CORPORATE'  WHEN 5 THEN  'ONEMANCORPORATE'  WHEN 6 THEN  'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST' ELSE 'UNKNOWN' END
		ELSE NULL
	END AS PERSONTYP
	, TO_CHAR(s.START_DATE, 'YYYY-MM-DD') AS START_DATE
	, TO_CHAR(s.END_DATE, 'YYYY-MM-DD') AS END_DATE
	, (CNL.TEXT) || '...' AS PRODUKT
	, (ROUND(CNL.TOTAL_AMOUNT, 2)) AS SUMMA
	, ROUND(CNL.TOTAL_AMOUNT - (CNL.TOTAL_AMOUNT * (1 - (1 / (1 + CNL.RATE)))),2) NETTO
    , ROUND(CNL.TOTAL_AMOUNT * (1 - (1 / (1 + CNL.RATE))),2)                     MOMS
	,CASE prod.PTYPE  WHEN 1 THEN  'Retail'  WHEN 2 THEN  'Service'  WHEN 4 THEN  'Clipcard'  WHEN 5 THEN  'Subscription creation'  WHEN 6 THEN  'Transfer'  WHEN 7 THEN  'Freeze period'  WHEN 8 THEN  'Gift card'  WHEN 9 THEN  'Free gift card'  WHEN 10 THEN  'Subscription'  WHEN 12 THEN  'Subscription pro-rata'  WHEN 13 THEN  'Subscription add-on'  WHEN 14 THEN  'Access product' END AS PROD_TYPE_NAME
	, CASE CRT.CRTTYPE  WHEN 1 THEN  'CASH'  WHEN 6 THEN  'CARD'  WHEN 7 THEN  'CARD'  WHEN 8 THEN  'CARD'  WHEN 5 THEN  'AR_CASH'  WHEN 2 THEN  'CHANGE'  WHEN 9 THEN  'GIFTCARD'  WHEN 13 THEN  'CUSTOM' END AS BETALMEDEL
,c.NAME AS CENTER_NAME
,TO_CHAR(longtodate(:periodFromLong), 'YYYY-MM-DD HH24:MI') AS PERIOD_FROM
,TO_CHAR(longtodate(:periodFromLong), 'YYYY-MM-DD HH24:MI') AS PERIOD_TO
,getcentertime(100) AS TODAY
,company.COMPANY_NAME AS COMPANY_NAME
,company.ADDRESS1 AS ADDRESS1
,company.ADDRESS2 AS ADDRESS2
,company.ZIPCODE AS ZIPCODE
,company.CITY AS CITY
,ROUND(company.SPLIT_RATE_COMMUNITY * (CNL.TOTAL_AMOUNT - (CNL.TOTAL_AMOUNT * (1 - (1 / (1 + CNL.RATE))))),2) AS COMMUNITY_PART

FROM
	CREDIT_NOTE_LINES CNL
	JOIN PRODUCTS prod
	ON
		prod.CENTER = CNL.PRODUCTCENTER
		AND prod.id = CNL.PRODUCTID
	LEFT JOIN PRODUCT_AND_PRODUCT_GROUP_LINK spl
	ON
		spl.PRODUCT_CENTER = prod.CENTER
		AND spl.PRODUCT_ID = prod.ID
		AND spl.PRODUCT_GROUP_ID = 8825
	INNER JOIN CREDIT_NOTES CN
	ON
		CNL.CENTER = CN.CENTER
		AND CNL.ID = CN.ID
	LEFT JOIN CASHREGISTERREPORTS CRR
	ON
		CRR.CENTER = CN.CASHREGISTER_CENTER
		AND CRR.ID = CN.CASHREGISTER_ID
		AND CRR.STARTTIME <= CN.ENTRY_TIME
		AND CRR.REPORTTIME > CN.ENTRY_TIME
	LEFT JOIN PERSONS PER
	ON
		CNL.PERSON_CENTER = PER.center
		AND CNL.PERSON_ID = PER.id
	LEFT JOIN AR_TRANS ART
	ON
		ART.REF_CENTER = CN.CENTER
		AND ART.REF_ID = CN.ID
		AND ART.REF_TYPE = 'CREDIT_NOTE'
	LEFT JOIN ACCOUNT_RECEIVABLES AR
	ON
		ART.CENTER = AR.CENTER
		AND ART.ID = AR.ID
	LEFT JOIN CASHREGISTERTRANSACTIONS CRT
	ON
		CRT.CENTER = CN.CASHREGISTER_CENTER
		AND CRT.ID = CN.CASHREGISTER_ID
		AND CRT.PAYSESSIONID = CN.PAYSESSIONID
	LEFT JOIN SUBSCRIPTIONS s
	ON
		s.OWNER_CENTER = per.CENTER
		AND s.OWNER_ID = per.ID
		AND s.STATE = 2
	LEFT JOIN CENTERS c
		ON per.CENTER = c.ID
JOIN
    (
        SELECT
          p.LASTNAME                      COMPANY_NAME
          ,p.ADDRESS1
          ,p.ADDRESS2
          ,p.ZIPCODE
          ,p.CITY
          ,(atts.TXTVALUE)::decimal / 100 SPLIT_RATE_COMMUNITY
          ,c.NAME              CENTER_NAME
        FROM
            PERSONS p
        JOIN
            CENTERS c
        ON
            c.id = :center
        JOIN
            PERSON_EXT_ATTRS atts
        ON
            atts.PERSONCENTER = p.CENTER
            AND atts.PERSONID = p.ID
            AND atts.NAME = 'SPLIT_RATE_COMMUNITY'
        WHERE
            (
				p.LASTNAME LIKE '9' || REPLACE(lpad((:center)::varchar,3),' ','0') || ' %') 
				OR (p.LASTNAME LIKE '9' || REPLACE(lpad((:center)::varchar,4),' ','0') || ' %')
				OR (p.LASTNAME LIKE '9239%' AND $$center$$ = 9239)
			) company
ON
    1 = 1
WHERE
	CN.CASHREGISTER_CENTER = 100
	AND CRT.CRTTYPE NOT IN(5,12)
	AND CNL.TOTAL_AMOUNT <> 0
	AND PER.CENTER = :center
	AND CN.ENTRY_TIME >= :periodFromLong
	AND CN.ENTRY_TIME < :periodToLong + (60 * 60 * 1000)
	
	AND NOT EXISTS (
		SELECT * FROM PRODUCT_AND_PRODUCT_GROUP_LINK pgl
		JOIN PRODUCT_GROUP pg
		ON
			pgl.PRODUCT_GROUP_ID = pg.ID
		WHERE
			prod.CENTER = pgl.PRODUCT_CENTER
			AND prod.ID = pgl.PRODUCT_ID
			AND pg.NAME = 'Excluded subscriptions'
	)
