-- The extract is extracted from Exerp on 2026-02-08
-- Extract of debts during a period.
Contain information of active as well as historical debts.
SELECT 
	--cc.CENTER,	
	--cc.ID,
	--cc.PERSONCENTER, 
	--cc.PERSONID,
	c.NAME AS CENTERNAME,
	cc.PERSONCENTER ||'p'||cc.PERSONID AS PERSONKEY,
	cc.STARTDATE,
	cc.AMOUNT AS REMAINING_AMOUNT,
	pr.REQ_AMOUNT AS INITIAL_AMOUNT,
	TO_CHAR(longtodate(cc.CLOSED_DATETIME),'YYYY-MM-DD') AS DEBT_CLOSE_DATE
FROM CASHCOLLECTIONCASES cc
JOIN CASHCOLLECTION_REQUESTS cr ON
	cr.CENTER = cc.CENTER
	AND cr.ID = cc.ID
JOIN PAYMENT_REQUESTS pr ON
	pr.CENTER = cr.PAYMENT_REQUEST_CENTER
	AND pr.ID = cr.PAYMENT_REQUEST_ID
	AND pr.SUBID = cr.PAYMENT_REQUEST_SUBID
JOIN CENTERS c ON
	pr.CENTER = c.ID
WHERE
	cc.START_DATETIME > :startDate
	AND cc.START_DATETIME < :endDate
	AND cc.CENTER IN(:scope)
	--cc.PERSONCENTER = 733
	--AND cc.PERSONID = 31003
