SELECT
    p1.CENTER || 'p' || p1.ID p1_id,
    p1.SSN p1_SSn,
    DECODE ( p1.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') AS p1_PERSONTYPE,
    DECODE (p1.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED','UNKNOWN')         AS p1_STATUS,
    p2.CENTER || 'p' || p2.ID p2_id,
    DECODE ( p2.PERSONTYPE, 0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE', 6,'FAMILY', 7,'SENIOR', 8,'GUEST','UNKNOWN') AS p2_PERSONTYPE,
    DECODE (p2.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED','UNKNOWN')         AS p2_STATUS,
    p2.SSN p2_SSn
FROM
    PERSONS p1
JOIN PERSONS p2
ON
    p2.SSN = p1.SSN
    AND
    (
        p2.CENTER != p1.CENTER
        OR p2.ID != p1.ID
    )
WHERE
    p1.STATUS IN (0,1,2,3)
    AND p2.STATUS IN (0,1,2,3)
    AND p1.SEX != 'C'
    AND p2.SEX != 'C'