-- The extract is extracted from Exerp on 2026-02-08
-- Extract to fetch members with PT subscriptions that was ended within given period.
SELECT 
	sub.OWNER_CENTER || 'p'|| sub.OWNER_ID AS PersonKey,
	per.FULLNAME AS Namn,
	sub.INDIVIDUAL_PRICE,
	sub.SUBSCRIPTION_PRICE,
	sub.END_DATE,
	prod.NAME
FROM SUBSCRIPTIONS sub 
LEFT JOIN SUBSCRIPTIONTYPES st
	ON st.CENTER = sub.SUBSCRIPTIONTYPE_CENTER
    AND st.ID = sub.SUBSCRIPTIONTYPE_ID
LEFT JOIN PRODUCTS prod
	ON st.CENTER = prod.CENTER
    AND st.ID = prod.ID
LEFT JOIN CENTERS cen
	ON sub.OWNER_CENTER = cen.ID
LEFT JOIN PERSONS p
	ON sub.OWNER_CENTER = p.CENTER
	AND sub.OWNER_ID = p.ID
LEFT JOIN PRODUCT_GROUP pg
	ON pg.ID = prod.PRIMARY_PRODUCT_GROUP_ID
LEFT JOIN PERSONS per
	ON per.CENTER = sub.OWNER_CENTER
	AND per.ID = sub.OWNER_ID
WHERE 
	sub.OWNER_CENTER IN (:scope)
	AND prod.PRIMARY_PRODUCT_GROUP_ID IN(5424,1224,3625,7224,10824,14024)
	AND sub.END_DATE > :fromDate
	AND sub.END_DATE < :toDate
