SELECT
	p.CENTER,
	p.ID,
	p.CENTER || 'p'||p.ID,
	p.EXTERNAL_ID,
	p.FULLNAME,
	ext.TXTVALUE,
	p.STATUS,
	p.PERSONTYPE
FROM PERSONS p
JOIN PERSON_EXT_ATTRS ext ON
	p.CENTER = ext.PERSONCENTER
	AND p.ID = ext.PERSONID
WHERE 
	p.CENTER = 1
	AND ext.NAME = 'LEADTYPE'
	AND ext.TXTVALUE LIKE ('%contest|2022-10%')