/* List members that have purchased membership during period and used trainingstart*/
SELECT 
	p.FULLNAME AS NAME,
	p.CENTER ||'p'||p.ID AS MEMBER_ID,
	c.NAME AS CENTER_NAME,
	p.FIRST_ACTIVE_START_DATE AS BECAME_MEMBER,
	LONGTODATE(pt1.STARTTIME) AS TR1_BOOKED,
	LONGTODATE(pt1.PARTICIPATED) AS TR1_PARTICIPATED,
	pt1.INSTRUCTOR AS TR1_INSTRUCTOR,
	LONGTODATE(pt2.STARTTIME) AS TR2_BOOKED,
	LONGTODATE(pt2.PARTICIPATED) AS TR2_PARTICIPATED,
	pt2.INSTRUCTOR AS TR2_INSTRUCTOR,
	LONGTODATE(arena_walk.STARTTIME) AS ARENA_WALK_BOOKED,
	LONGTODATE(arena_walk.PARTICIPATED) AS ARENA_WALK_PARTICIPATED,
	arena_walk.INSTRUCTOR AS AW_INSTRUCTOR,
	LONGTODATE(guide1.STARTTIME) AS VEILEDNING_1_BOOKED,
	LONGTODATE(guide1.PARTICIPATED) AS VEILEDNING_1_PARTICIPATED,
	guide1.INSTRUCTOR AS GUIDE1_INSTRUCTOR,
	LONGTODATE(guide2.STARTTIME) AS VEILEDNING_2_BOOKED,
	LONGTODATE(guide2.PARTICIPATED) AS VEILEDNING_2_PARTICIPATED,
	guide2.INSTRUCTOR AS GUIDE1_INSTRUCTOR

FROM PERSONS p
JOIN CENTERS c ON
        p.CENTER = c.ID
FULL OUTER JOIN (
		SELECT 
			b.NAME,
			b.STARTTIME,
			b.OWNER_CENTER,
			b.OWNER_ID,
			pa.SHOWUP_TIME AS PARTICIPATED,
			ins.FULLNAME AS INSTRUCTOR
		FROM BOOKINGS b
		LEFT JOIN STAFF_USAGE st ON
	    	b.CENTER = st.BOOKING_CENTER
			AND b.ID = st.BOOKING_ID
		LEFT JOIN PERSONS ins ON
			st.PERSON_CENTER = ins.CENTER
			AND st.PERSON_ID = ins.ID
		FULL OUTER JOIN PARTICIPATIONS pa ON
			pa.BOOKING_CENTER = b.CENTER
			AND pa.BOOKING_ID = b.ID
		WHERE 
			b.NAME = 'Treningsstart 1 PT'			
			AND b.STATE = 'ACTIVE'
	) pt1 ON 
	pt1.OWNER_CENTER = p.CENTER
	AND pt1.OWNER_ID = p.ID 

FULL OUTER JOIN (
		SELECT 
			b.NAME,
			b.STARTTIME,
			b.OWNER_CENTER,
			b.OWNER_ID,
			pa.SHOWUP_TIME AS PARTICIPATED,
			ins.FULLNAME AS INSTRUCTOR
		FROM BOOKINGS b
		LEFT JOIN STAFF_USAGE st ON
	    	b.CENTER = st.BOOKING_CENTER
			AND b.ID = st.BOOKING_ID
		LEFT JOIN PERSONS ins ON
			st.PERSON_CENTER = ins.CENTER
			AND st.PERSON_ID = ins.ID
		FULL OUTER JOIN PARTICIPATIONS pa ON
			pa.BOOKING_CENTER = b.CENTER
			AND pa.BOOKING_ID = b.ID
		WHERE 
			b.NAME = 'Treningsstart 2 PT'			
			AND b.STATE = 'ACTIVE'
	) pt2 ON 
	pt2.OWNER_CENTER = p.CENTER
	AND pt2.OWNER_ID = p.ID 

FULL OUTER JOIN (
		SELECT 
			b.NAME,
			b.STARTTIME,
			b.OWNER_CENTER,
			b.OWNER_ID,
			pa.SHOWUP_TIME AS PARTICIPATED,
			ins.FULLNAME AS INSTRUCTOR
		FROM BOOKINGS b
		LEFT JOIN STAFF_USAGE st ON
	    	b.CENTER = st.BOOKING_CENTER
			AND b.ID = st.BOOKING_ID
		LEFT JOIN PERSONS ins ON
			st.PERSON_CENTER = ins.CENTER
			AND st.PERSON_ID = ins.ID
		FULL OUTER JOIN PARTICIPATIONS pa ON
			pa.BOOKING_CENTER = b.CENTER
			AND pa.BOOKING_ID = b.ID
		WHERE 
			b.NAME = 'Arena Walk'			
			AND b.STATE = 'ACTIVE'
	) arena_walk ON 
	arena_walk.OWNER_CENTER = p.CENTER
	AND arena_walk.OWNER_ID = p.ID 

FULL OUTER JOIN (
		SELECT 
			b.NAME,
			b.STARTTIME,
			b.OWNER_CENTER,
			b.OWNER_ID,
			pa.SHOWUP_TIME AS PARTICIPATED,
			ins.FULLNAME AS INSTRUCTOR
		FROM BOOKINGS b
		LEFT JOIN STAFF_USAGE st ON
	    	b.CENTER = st.BOOKING_CENTER
			AND b.ID = st.BOOKING_ID
		LEFT JOIN PERSONS ins ON
			st.PERSON_CENTER = ins.CENTER
			AND st.PERSON_ID = ins.ID
		FULL OUTER JOIN PARTICIPATIONS pa ON
			pa.BOOKING_CENTER = b.CENTER
			AND pa.BOOKING_ID = b.ID
		WHERE 
			b.NAME = 'Veiledning 1'			
			AND b.STATE = 'ACTIVE'
	) guide1 ON 
	guide1.OWNER_CENTER = p.CENTER
	AND guide1.OWNER_ID = p.ID 

FULL OUTER JOIN (
		SELECT 
			b.NAME,
			b.STARTTIME,
			b.OWNER_CENTER,
			b.OWNER_ID,
			pa.SHOWUP_TIME AS PARTICIPATED,
			ins.FULLNAME AS INSTRUCTOR
		FROM BOOKINGS b
		LEFT JOIN STAFF_USAGE st ON
	    	b.CENTER = st.BOOKING_CENTER
			AND b.ID = st.BOOKING_ID
		LEFT JOIN PERSONS ins ON
			st.PERSON_CENTER = ins.CENTER
			AND st.PERSON_ID = ins.ID
		FULL OUTER JOIN PARTICIPATIONS pa ON
			pa.BOOKING_CENTER = b.CENTER
			AND pa.BOOKING_ID = b.ID
		WHERE 
			b.NAME = 'Veiledning 2'			
			AND b.STATE = 'ACTIVE'
	) guide2 ON 
	guide2.OWNER_CENTER = p.CENTER
	AND guide2.OWNER_ID = p.ID 
WHERE
	p.FIRST_ACTIVE_START_DATE >= cast(:fromDate as date)
	AND p.FIRST_ACTIVE_START_DATE < TRUNC(CAST(:toDate AS DATE))+1
	AND p.CENTER IN (:scope)
--AND b.STATE = 'ACTIVE'
--ORDER BY 
--	p.CENTER,
--	p.ID,
--	b.STARTTIME
