-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
	per.EXTERNAL_ID AS "EXTERNAL_ID",
	per.CENTER ||'p'|| per.ID AS "MEMBERNUMER",
	per.FIRSTNAME AS "FIRST_NAME",
	per.LASTNAME AS "LAST_NAME",
	bk.NAME AS "CLASS_NAME",
	TO_CHAR(MIN(longtodate(bk.STARTTIME)),'YYYY-MM-DD HH24:MI') AS "STARTTIME",
	TO_CHAR(MAX(longtodate(bk.STARTTIME)),'YYYY-MM-DD HH24:MI') AS "ENDTIME"
	

FROM PERSONS per 

JOIN PARTICIPATIONS par ON
	par.PARTICIPANT_CENTER = per.CENTER
	AND par.PARTICIPANT_ID = per.ID
JOIN BOOKINGS bk ON
	par.BOOKING_CENTER = bk.CENTER
	AND par.BOOKING_ID = bk.ID
JOIN ACTIVITY act ON
	bk.ACTIVITY = act.ID
JOIN CENTERS c ON
	par.CENTER = c.ID
FULL JOIN RELATIVES rel ON 
	per.CENTER = rel.CENTER 
	AND per.ID = rel.ID
WHERE 
	act.ACTIVITY_TYPE = 9
	AND bk.CENTER IN (:center)
	AND rel.CENTER IS NULL
	AND rel.ID IS NULL
GROUP BY 
	per.EXTERNAL_ID,
	per.FIRSTNAME,
	per.LASTNAME,
	per.CENTER,
	per.ID,
	bk.NAME
ORDER BY 
	bk.NAME,
	per.FULLNAME,
	per.EXTERNAL_ID