-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
    distinct p.GLOBALID, pg.NAME
FROM
    MASTERPRODUCTREGISTER p
JOIN PRODUCT_ACCOUNT_CONFIGURATIONS pg
ON
    p.PRODUCT_ACCOUNT_CONFIG_ID = pg.ID
WHERE
    pg.NAME = :Name