-- The extract is extracted from Exerp on 2026-02-08
-- Extract to show used campaigncodes for Twiik Rewards
SELECT 
	us.PERSON_CENTER||'p'||us.PERSON_ID,
	us.TARGET_SERVICE,
	cc.CODE,
	LONGTODATE(us.USE_TIME),
	invl.PRODUCTCENTER,
	invl.PRODUCTID
FROM PRIVILEGE_USAGES us

LEFT JOIN INVOICELINES invl ON
    invl.CENTER = us.TARGET_CENTER
    AND invl.ID = us.TARGET_ID
    AND invl.SUBID = us.TARGET_SUBID    
LEFT JOIN CAMPAIGN_CODES cc ON
   	us.CAMPAIGN_CODE_ID = cc.ID
LEFT JOIN PERSONS per ON
	us.PERSON_CENTER = per.CENTER
	AND us.PERSON_ID = per.ID	
WHERE 
	cc.CODE IS NOT NULL
	AND us.TARGET_SERVICE = 'InvoiceLine'
	AND per.EXTERNAL_ID = $$externalId$$
	AND LONGTODATE(us.USE_TIME) > NOW() :: DATE
ORDER BY us.USE_TIME DESC