/**
* List courseparticipants by date with startdate on a given date.
*
*/
SELECT
	per.EXTERNAL_ID AS "EXTERNAL_ID",
	per.CENTER ||'p'|| per.ID AS "MEMBER_ID",
	per.FIRSTNAME AS "FIRST_NAME",
	per.LASTNAME AS "LAST_NAME",
	c.NAME AS "CENTER",
	bk.NAME AS "CLASS_NAME",
	TO_CHAR(MIN(longtodate(bk.STARTTIME)),'YYYY-MM-DD HH24:MI') AS "STARTTIME"
	
FROM PERSONS per 

JOIN PARTICIPATIONS par ON
	par.PARTICIPANT_CENTER = per.CENTER
	AND par.PARTICIPANT_ID = per.ID
JOIN BOOKINGS bk ON
	par.BOOKING_CENTER = bk.CENTER
	AND par.BOOKING_ID = bk.ID
JOIN ACTIVITY act ON
	bk.ACTIVITY = act.ID
JOIN CENTERS c ON
	par.CENTER = c.ID
WHERE 
	par.STATE IN ('BOOKED','PARTICIPATION')
	AND act.ACTIVITY_TYPE = 9
	AND bk.CENTER IN (:scope)
	AND bk.STARTTIME >= :fromDate
	AND bk.STARTTIME <= (:toDate)+(60 * 60 * 24 * 1000)
	AND (par.CANCELATION_REASON IS NULL OR par.CANCELATION_REASON NOT IN('USER', 'CENTER'))
GROUP BY 
	per.EXTERNAL_ID,
	per.FIRSTNAME,
	per.LASTNAME,
	per.CENTER,
	per.ID,
	bk.NAME,
	c.NAME
ORDER BY 
	bk.NAME,
	per.FULLNAME,
	per.EXTERNAL_ID