SELECT 
	payer.EXTERNAL_ID,
	payer.FULLNAME,
	e.IDENTITY,
	e.ENTITYSTATUS,
	gc.AMOUNT,
	gc.AMOUNT_REMAINING,
	e.REF_TYPE,
	e.IDMETHOD,
	TO_CHAR(TO_TIMESTAMP(gc.PURCHASE_TIME / 1000), 'YYYY-MM-DD HH24:MI') AS PURCHASE_TIME,
	gc.EXPIRATIONDATE
FROM GIFT_CARDS gc 
JOIN ENTITYIDENTIFIERS e ON 
	gc.CENTER = e.REF_CENTER
JOIN PERSONS payer ON
	payer.CENTER = gc.PAYER_CENTER
	AND payer.ID = gc.PAYER_ID
AND gc.ID = e.REF_ID
	
WHERE 
	gc.PURCHASE_TIME >  CAST(:eventTime AS BIGINT)
	AND e.ENTITYSTATUS = 1
	AND payer.CENTER IN (
		SELECT c.ID FROM CENTERS c WHERE c.COUNTRY IN ('SE','NO')
	)
	AND payer.EXTERNAL_ID = :externalId
	AND e.REF_TYPE = 5
ORDER BY gc.PURCHASE_TIME DESC