-- The extract is extracted from Exerp on 2026-02-08
--  
-- First part: Retrieve persons with defined cd.codes
SELECT DISTINCT
    p.CENTER || 'p' || p.id AS MEMBERID,
    curr_p.EXTERNAL_ID,
    CASE p.STATUS
     WHEN 0 THEN 'LEAD'
        WHEN 1 THEN 'ACTIVE'
        WHEN 2 THEN 'INACTIVE'
        WHEN 3 THEN 'TEMPORARY INACTIVE'
        WHEN 4 THEN 'TRANSFERRED'
        WHEN 5 THEN 'DUPLICATE'
        WHEN 6 THEN 'PROSPECT'
        WHEN 7 THEN 'DELETED'
        WHEN 8 THEN 'ANONYMIZED'
        WHEN 9 THEN 'CONTACT'
        ELSE 'Undefined'
    END AS "MEMBER STATUS",
    pr.NAME AS SUBSCRIPTION,
    pr.price AS Default_price,
    sp.price AS Reduced_Price,
    CASE s.STATE
        WHEN 2 THEN 'ACTIVE'
        WHEN 3 THEN 'ENDED'
        WHEN 4 THEN 'FROZEN'
        WHEN 7 THEN 'WINDOW'
        WHEN 8 THEN 'CREATED'
        ELSE 'OTHER'
    END AS "SUBSCRIPTION STATE",
    s.START_DATE AS STARTDATE,
    CD.CODE,
    s.END_DATE AS ENDDATE,
    TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YYYY HH24:MI:SS') AS CREATIONTIME
FROM
    PERSONS p
JOIN SUBSCRIPTIONS s ON s.OWNER_CENTER = p.CENTER AND s.OWNER_ID = p.ID
JOIN SUBSCRIPTION_PRICE sp ON sp.SUBSCRIPTION_CENTER = s.CENTER AND sp.SUBSCRIPTION_ID = s.ID
JOIN PRIVILEGE_USAGES pu ON pu.PERSON_CENTER = p.CENTER AND pu.PERSON_ID = p.ID
JOIN CAMPAIGN_CODES cd ON cd.ID = pu.CAMPAIGN_CODE_ID
JOIN PRODUCTS pr ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER AND pr.ID = s.SUBSCRIPTIONTYPE_ID
JOIN PERSONS curr_p ON p.CURRENT_PERSON_CENTER = curr_p.CENTER AND p.CURRENT_PERSON_ID = curr_p.ID
WHERE
    pr.GLOBALID = 'PLUS_UNLIMITED'
    AND cd.code IN ('STUDIEPRIS','STUDIERABAT', 'Studiepris','Studierabat','studiepris','studierabat')
    AND SP.PRICE = 239
    AND p.center IN (:Scope)
	AND curr_p.EXTERNAL_ID != '2532759'

UNION

-- Second part: Retrieve persons with cd.code IS NULL
SELECT DISTINCT
    p.CENTER || 'p' || p.id AS MEMBERID,
    curr_p.EXTERNAL_ID,
    CASE p.STATUS
        WHEN 0 THEN 'LEAD'
        WHEN 1 THEN 'ACTIVE'
        WHEN 2 THEN 'INACTIVE'
        WHEN 3 THEN 'TEMPORARY INACTIVE'
        WHEN 4 THEN 'TRANSFERRED'
        WHEN 5 THEN 'DUPLICATE'
        WHEN 6 THEN 'PROSPECT'
        WHEN 7 THEN 'DELETED'
        WHEN 8 THEN 'ANONYMIZED'
        WHEN 9 THEN 'CONTACT'
        ELSE 'Undefined'
    END AS "MEMBER STATUS",
    pr.NAME AS SUBSCRIPTION,
    pr.price AS Default_price,
    sp.price AS Reduced_Price,
    CASE s.STATE
        WHEN 2 THEN 'ACTIVE'
        WHEN 3 THEN 'ENDED'
        WHEN 4 THEN 'FROZEN'
        WHEN 7 THEN 'WINDOW'
        WHEN 8 THEN 'CREATED'
        ELSE 'OTHER'
    END AS "SUBSCRIPTION STATE",
    s.START_DATE AS STARTDATE,
    CD.CODE,
    s.END_DATE AS ENDDATE,
    TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YYYY HH24:MI:SS') AS CREATIONTIME
FROM
    PERSONS p
JOIN SUBSCRIPTIONS s ON s.OWNER_CENTER = p.CENTER AND s.OWNER_ID = p.ID
JOIN SUBSCRIPTION_PRICE sp ON sp.SUBSCRIPTION_CENTER = s.CENTER AND sp.SUBSCRIPTION_ID = s.ID
JOIN PRIVILEGE_USAGES pu ON pu.PERSON_CENTER = p.CENTER AND pu.PERSON_ID = p.ID
LEFT JOIN CAMPAIGN_CODES cd ON cd.ID = pu.CAMPAIGN_CODE_ID
JOIN PRODUCTS pr ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER AND pr.ID = s.SUBSCRIPTIONTYPE_ID
JOIN PERSONS curr_p ON p.CURRENT_PERSON_CENTER = curr_p.CENTER AND p.CURRENT_PERSON_ID = curr_p.ID
WHERE
    pr.GLOBALID = 'PLUS_UNLIMITED'
    AND cd.code IS NULL
    AND SP.PRICE = 239
    AND p.center IN (:Scope)
	AND curr_p.EXTERNAL_ID != '2532759'

ORDER BY CREATIONTIME;