-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT 
    p.CENTER || 'p' || p.id AS MEMBERID,
    p.FULLNAME AS Full_Name,
    curr_p.EXTERNAL_ID,
    CASE p.STATUS 
        WHEN 0 THEN 'LEAD' 
        WHEN 1 THEN 'ACTIVE' 
        WHEN 2 THEN 'INACTIVE' 
        WHEN 3 THEN 'TEMPORARY INACTIVE' 
        WHEN 4 THEN 'TRANSFERRED' 
        WHEN 5 THEN 'DUPLICATE' 
        WHEN 6 THEN 'PROSPECT' 
        WHEN 7 THEN 'DELETED' 
        WHEN 8 THEN 'ANONYMIZED' 
        WHEN 9 THEN 'CONTACT' 
        ELSE 'Undefined' 
    END AS "MEMBER STATUS",
    pr.NAME AS SUBSCRIPTION,
    pr.price AS subscriptionPrice,
    CASE s.STATE  
        WHEN 2 THEN 'ACTIVE'  
        WHEN 3 THEN 'ENDED'  
        WHEN 4 THEN 'FROZEN'  
        WHEN 7 THEN 'WINDOW'  
        WHEN 8 THEN 'CREATED' 
        ELSE 'OTHER' 
    END AS "SUBSCRIPTION STATE",
    s.START_DATE AS STARTDATE,
    s.END_DATE AS ENDDATE,
    TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YYYY HH24:MM:SS') AS CREATIONTIME
FROM PERSONS p
JOIN SUBSCRIPTIONS s
    ON s.OWNER_CENTER = p.CENTER
    AND s.OWNER_ID = p.ID
JOIN PRODUCTS pr
    ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER
    AND pr.ID = s.SUBSCRIPTIONTYPE_ID
JOIN PRIVILEGE_USAGES pu
    ON pu.PERSON_CENTER = p.CENTER
    AND pu.PERSON_ID = p.ID
JOIN CAMPAIGN_CODES cd
    ON cd.ID = pu.CAMPAIGN_CODE_ID
JOIN PERSONS curr_p
    ON p.CURRENT_PERSON_CENTER = curr_p.CENTER 
    AND p.CURRENT_PERSON_ID = curr_p.ID
WHERE
TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YYYY') = TO_CHAR(longtodate(pu.USE_TIME), 'DD-MM-YYYY')
    AND extract(year from age(P.BIRTHDATE)) BETWEEN 0 AND 17 -- Filter for under 18
--AND pr.GLOBALID LIKE 'PLUS%'
AND s.CREATION_TIME >= (:Oprettelses_efter)
AND s.CREATION_TIME <= (:Oprettelse_for)
--AND s.STATE = 2
ORDER BY CREATIONTIME;
