-- This is the version from 2026-02-05
--  
WITH temp AS (
  SELECT 
    s.OWNER_CENTER || 'p' || s.OWNER_ID AS MEMBERID,
    pr.NAME,
    pr.GLOBALID,
    p1.FULLNAME AS MEMBERNAME,
    s.CREATOR_CENTER || 'emp' || s.CREATOR_ID AS SALESPERSONID,
    p2.FULLNAME AS SALESPERSON,
    s.CREATION_TIME,  -- Ensure CREATION_TIME is selected
    LAG(s.CREATION_TIME, 1) OVER (PARTITION BY s.OWNER_ID ORDER BY s.CREATION_TIME) AS lagged_date
  FROM SUBSCRIPTIONS s
  JOIN PERSONS p1 
    ON s.OWNER_CENTER = p1.CENTER 
    AND s.OWNER_ID = p1.ID
  JOIN EMPLOYEES e 
    ON s.CREATOR_CENTER = e.CENTER 
    AND s.CREATOR_ID = e.ID
  JOIN PERSONS p2 
    ON e.PERSONCENTER = p2.CENTER 
    AND e.PERSONID = p2.ID
  LEFT JOIN PRODUCTS pr 
    ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER 
    AND pr.ID = s.SUBSCRIPTIONTYPE_ID
  WHERE
    (s.CREATOR_CENTER || 'emp' || s.CREATOR_ID) = '114emp40220'
    AND EXTRACT(YEAR FROM AGE(p1.BIRTHDATE)) BETWEEN 11 AND 17
    AND s.CREATION_TIME >= :Creation_Date_From 
    AND s.CREATION_TIME < :Creation_Date_To
)

SELECT *
FROM temp
WHERE lagged_date <= temp.CREATION_TIME;  -- Explicit alias reference
