-- This is the version from 2026-02-05
--  
SELECT 
    I.Center, 
    CI.NAME AS SALES_CENTER, 
    longtodateC(I.trans_time, I.center) AS SALES_DAY,
    P.NAME AS PRODUCT, 
    P.PRICE AS PRICE,
    E.external_id AS Staff_ID,
    PE.External_id AS Emp_ExternalID,
    PP.CENTER || 'p' || PP.ID AS CUSTOMER_ID,
    PP.External_id AS Member_ExternalID,
    FLOOR(EXTRACT(YEAR FROM AGE(
        TO_TIMESTAMP(I.TRANS_TIME / 1000),  -- Convert if stored in milliseconds
        PP.BIRTHDATE
    ))) AS AGE_AT_PURCHASE

FROM 
    INVOICES I 
JOIN INVOICELINES IL ON I.CENTER = IL.CENTER AND I.ID = IL.ID 
JOIN PRODUCTS P ON IL.PRODUCTCENTER = P.CENTER AND IL.PRODUCTID = P.ID 
JOIN EMPLOYEES E ON I.EMPLOYEE_CENTER = E.CENTER AND I.EMPLOYEE_ID = E.ID
JOIN PERSONS PE ON E.PERSONCENTER = PE.CENTER AND E.PERSONID = PE.ID
JOIN CENTERS CE ON PE.CENTER = CE.ID
JOIN CLIPCARDS C ON IL.CENTER = C.INVOICELINE_CENTER AND IL.ID = C.INVOICELINE_ID AND IL.SUBID = C.INVOICELINE_SUBID
JOIN PERSONS PP ON C.OWNER_CENTER = PP.CENTER AND C.OWNER_ID = PP.ID
JOIN CENTERS CP ON PP.CENTER = CP.ID
JOIN CENTERS CI ON I.CENTER = CI.ID
WHERE 
    I.TRANS_TIME >= :From_date
    AND I.TRANS_TIME < :To_date_exclusive
    AND I.Center IN (:scope)
	AND P.NAME = 'Dagspas til fitness og holdtræning'
    AND FLOOR(EXTRACT(YEAR FROM AGE(
        TO_TIMESTAMP(I.TRANS_TIME / 1000), 
        PP.BIRTHDATE
    ))) BETWEEN 14 AND 17;

