-- The extract is extracted from Exerp on 2026-02-08
-- Drop off/Churning
SELECT
    s.CENTER,
    c.SHORTNAME,
    COUNT(*)
FROM
    FW.SUBSCRIPTIONS s

JOIN FW.CENTERS c
ON
    s.CENTER = c.ID
JOIN FW.PERSONS p
ON
    s.OWNER_CENTER = p.center
    AND s.OWNER_ID = p.ID
JOIN SUBSCRIPTIONTYPES ST
ON
    (
        S.SUBSCRIPTIONTYPE_CENTER = ST.CENTER
        AND S.SUBSCRIPTIONTYPE_ID = ST.ID
    )
JOIN PRODUCTS PR
ON
    (
        S.SUBSCRIPTIONTYPE_CENTER = PR.CENTER
        AND S.SUBSCRIPTIONTYPE_ID = PR.ID
    )
JOIN FW.PRODUCT_GROUP PG
ON
    (
        PG.ID = PR.PRIMARY_PRODUCT_GROUP_ID
    )
WHERE
	s.CENTER in (:Scope)
    AND s.END_DATE >= :FromDate
    AND s.END_DATE <= :ToDate
    AND p.PERSONTYPE <> 2
    AND PR.PRIMARY_PRODUCT_GROUP_ID IN (6,7)
    AND s.SUB_STATE NOT IN (3,5,6)
GROUP BY
    s.CENTER,
    c.SHORTNAME
ORDER BY s.CENTER

