-- This is the version from 2026-02-05
--  
SELECT 
S.OWNER_CENTER || 'p'|| S.OWNER_ID AS PersonKey, 
P.NAME, 
SC.EFFECT_DATE, 
SC.EMPLOYEE_CENTER || 'emp' || SC.EMPLOYEE_ID AS EmployeeKey 
FROM 
SUBSCRIPTION_CHANGE SC 
JOIN SUBSCRIPTIONS S 
ON 
SC.NEW_SUBSCRIPTION_CENTER = S.CENTER 
AND SC.NEW_SUBSCRIPTION_ID = S.ID 
JOIN PRODUCTS P 
ON 
P.CENTER = S.SUBSCRIPTIONTYPE_CENTER 
AND P.ID = S.SUBSCRIPTIONTYPE_ID 
WHERE 
SC.TYPE = 'TYPE' 
AND SC.CHANGE_TIME > :fromdatetimelong 
AND SC.CHANGE_TIME <= :todatetimelong 
AND P.GLOBALID IN ('EFT_NORMAL_BEAUTY_ANGEL', 'EFT_CORPORATE_BEAUTY_ANGEL', 
'EFT_LOCAL_1_FREE_CLASS', 'EFT_LOCAL_1_FREE_CLASS_UNDER18', 'EFT_LOCAL_FW149', 'EFT_LOCAL_FW149_WEEKEND', 'EFT_NORMAL_BUDDY', 'EFT_NORMAL_HEAT_WAVE', 'EFT_CORPORATE_NORMAL_HEATWAVE') 
ORDER BY 
SC.CHANGE_TIME ASC