-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
    PERSONS.FIRSTNAME,
    COUNT(PERSONS.SSN),
    PERSONS.SSN
FROM
    PERSONS
WHERE
    PERSONS.STATUS IN (0,2,6,9)
    and PERSONS.FIRSTNAME is not null
GROUP BY
    PERSONS.FIRSTNAME,
    PERSONS.SSN
HAVING
    (
        COUNT(PERSONS.SSN) > 1 )
