-- This is the version from 2026-02-05
--  
WITH
    params AS
    (
        SELECT
            CASE $$offset$$ WHEN -1 THEN 0 ELSE (TRUNC(current_timestamp)-$$offset$$-to_date('01-01-1970','DD-MM-YYYY'))*24*3600*1000::bigint END AS FROMDATE,
            (TRUNC(current_timestamp+1)-to_date('01-01-1970','DD-MM-YYYY'))*24*3600*1000::bigint                                 AS TODATE
        
    )
SELECT
    CAST ( ss.ID AS VARCHAR(255))                                    AS "SUBSCRIPTION_SALES_ID",
    ss.SUBSCRIPTION_CENTER || 'ss' || ss.SUBSCRIPTION_ID             AS "SUBSCRIPTION_ID",
    CAST ( ss.SUBSCRIPTION_CENTER AS VARCHAR(255))                   AS "SUBSCRIPTION_CENTER",
    ss.SUBSCRIPTION_TYPE_CENTER || 'prod' || ss.SUBSCRIPTION_TYPE_ID AS "PRODUCT_ID",
    BI_DECODE_FIELD('SUBSCRIPTION_SALES','TYPE',ss.TYPE)             AS "SALES_TYPE",
    TO_CHAR(longtodateC(s.creation_time,s.center), 'YYYY-MM-DD')     AS "SALES_DATE",
    TO_CHAR(ss.START_DATE, 'YYYY-MM-DD')                             AS "START_DATE",
    TO_CHAR(ss.END_DATE, 'YYYY-MM-DD')                               AS "END_DATE",
    p.EXTERNAL_ID                                                    AS "SALES_PERSON_ID",
    -- JOINING FEE
    TO_CHAR(ss.PRICE_NEW + ss.PRICE_NEW_DISCOUNT, 'FM99999999999999')                                                                           AS "JF_NORMAL_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_NEW_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                           AS "JF_DISCOUNT",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_NEW, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                                    AS "JF_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_NEW_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                          AS "JF_SPONSORED",
    TO_CHAR(ss.PRICE_NEW - ss.PRICE_NEW_SPONSORED, 'FM99999999999999')                                                                           AS "JF_MEMBER",
    -- PRO RATA PERIOD
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_PRORATA + ss.PRICE_PRORATA_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')   AS "PRO_RATA_PERIOD_NORMAL_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_PRORATA_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                      AS "PRORATA_PERIOD_DISCOUNT",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_PRORATA, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                               AS "PRORATA_PERIOD_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_PRORATA_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                     AS "PRORATA_PERIOD_SPONSORED",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_PRORATA - ss.PRICE_PRORATA_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')  AS "PRORATA_PERIOD_MEMBER",
    -- INITIAL PERIOD
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_INITIAL + ss.PRICE_INITIAL_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')   AS "INIT_PERIOD_NORMAL_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_INITIAL_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                      AS "INIT_PERIOD_DISCOUNT",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_INITIAL, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                               AS "INIT_PERIOD_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_INITIAL_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                     AS "INIT_PERIOD_SPONSORED",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_INITIAL - ss.PRICE_INITIAL_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')  AS "INIT_PERIOD_MEMBER",
    -- ADMIN FEE
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_ADMIN_FEE + ss.PRICE_ADMIN_FEE_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')   AS "ADMIN_FEE_NORMAL_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_ADMIN_FEE_DISCOUNT, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                        AS "ADMIN_FEE_DISCOUNT",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_ADMIN_FEE, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                                 AS "ADMIN_FEE_PRICE",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_ADMIN_FEE_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')                       AS "ADMIN_FEE_SPONSORED",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.PRICE_ADMIN_FEE - ss.PRICE_ADMIN_FEE_SPONSORED, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')  AS "ADMIN_FEE_MEMBER",
    REPLACE(TO_CHAR(ss.BINDING_DAYS,'FM999G999G999G999G999'),',','.')  AS "BINDING_DAYS",
    CASE
        WHEN s.INVOICELINE_CENTER IS NULL
        THEN s2.INVOICELINE_CENTER||'inv'||s2.INVOICELINE_ID
        ELSE s.INVOICELINE_CENTER||'inv'||s.INVOICELINE_ID
    END                           AS "SALE_ID",
    REPLACE(REPLACE(REPLACE(TO_CHAR(ss.CONTRACT_INCLUDING_SPONSOR, 'FM999G999G999G999G990D00'), '.', '|'), ',', '.'),'|',',')  AS "INIT_CONTRACT_VALUE",
    CASE
        WHEN ss.CANCELLATION_DATE IS NULL
        THEN 'ACTIVE'
        ELSE 'CANCELLED'
    END AS "STATE",
    CASE
        WHEN s.INVOICELINE_CENTER IS NULL
        THEN s2.INVOICELINE_CENTER||'inv'||s2.INVOICELINE_ID||'ln'||s2.INVOICELINE_SUBID
        ELSE s.INVOICELINE_CENTER||'inv'||s.INVOICELINE_ID||'ln'||s.INVOICELINE_SUBID
    END      AS      "JF_SALES_LINE_ID",
    s.center AS      "CENTER_ID",
    REPLACE(TO_CHAR(ss.LAST_MODIFIED,'FM999G999G999G999G999'),',','.') AS "ETS"
FROM
    PARAMS, SUBSCRIPTION_SALES ss
JOIN
    SUBSCRIPTIONS s
ON
    s.CENTER = ss.SUBSCRIPTION_CENTER
    AND s.ID = ss.SUBSCRIPTION_ID
JOIN
    EMPLOYEES emp
ON
    emp.CENTER = ss.EMPLOYEE_CENTER
    AND emp.ID = ss.EMPLOYEE_ID
JOIN
    PERSONS p
ON
    p.CENTER = emp.PERSONCENTER
    AND p.ID = emp.PERSONID
LEFT JOIN
    SUBSCRIPTIONS s2
ON
    s2.center = s.TRANSFERRED_CENTER
    AND s2.id = s.TRANSFERRED_ID
WHERE
    ss.LAST_MODIFIED BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
