-- This is the version from 2026-02-05
--  
SELECT 
    AR.CUSTOMERCENTER          AS PersonCenter,
    AR.CUSTOMERID              AS PersonId,
    longtodate(ART.TRANS_TIME) AS dato,
    ART.TEXT,
    ART.AMOUNT,
    ART.CENTER,
    ART.ID,
    ART.SUBID
FROM
    AR_TRANS ART
JOIN ACCOUNT_TRANS ACT
ON
    ART.REF_CENTER = ACT.CENTER
AND ART.REF_ID = ACT.ID
AND ART.REF_SUBID = ACT.SUBID
JOIN ACCOUNTS CRED
ON
    CRED.CENTER = ACT.CREDIT_ACCOUNTCENTER AND CRED.ID = ACT.CREDIT_ACCOUNTID JOIN ACCOUNTS DEB ON
    DEB.CENTER = ACT.DEBIT_ACCOUNTCENTER AND DEB.ID = ACT.DEBIT_ACCOUNTID JOIN ACCOUNT_RECEIVABLES AR ON
    AR.CENTER = ART.CENTER
AND AR.ID = ART.ID
WHERE
    ART.EMPLOYEECENTER = 109
AND ART.EMPLOYEEID = 9
AND ART.TRANS_TIME > datetolong('2009-09-01 00:00') AND ART.REF_TYPE ='ACCOUNT_TRANS'
AND
    (
        CRED.GLOBALID = 'UNPLACED_PAYMENTS'
     OR DEB.GLOBALID = 'UNPLACED_PAYMENTS'
    )
