-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT PERSON_LOGIN_TOKENS.PERSON_CENTER, CENTERS.NAME ,PERSON_LOGIN_TOKENS.PERSON_ID, PERSONS.FULLNAME
FROM PERSON_LOGIN_TOKENS, CENTERS, PERSONS
WHERE CENTERS.ID = PERSON_LOGIN_TOKENS.PERSON_CENTER AND PERSONS.ID = PERSON_LOGIN_TOKENS.PERSON_ID and PERSONS.CENTER = PERSON_LOGIN_TOKENS.PERSON_CENTER