-- This is the version from 2026-02-05
--  
SELECT 
CAST ( a.ID AS VARCHAR(255)) AS "ACTIVITY_ID",
    a.NAME                       AS "NAME",
    a.STATE                      AS "STATE",
    --DECODE(a.ACTIVITY_TYPE, 1,'GENERAL', 2,'CLASS_BOOKING', 3,'RESOURCE_BOOKING', 4,'STAFF_BOOKING', 5,'MEETING', 6,'STAFF_AVAILABILITY', 7,'RESOURCE_AVAILABILITY', 8,'CHILD_CARE', 9,'COURSES', 'UNKNOWN' ) AS "ACTIVITY_TYPE",
    BI_DECODE_FIELD('ACTIVITY','ACTIVITY_TYPE',a.ACTIVITY_TYPE) AS "ACTIVITY_TYPE",
    CAST ( a.ACTIVITY_GROUP_ID AS VARCHAR(255))                 AS "ACTIVITY_GROUP_ID",
    cg.NAME                                                     AS "COLOR",
    CASE
        WHEN COALESCE(a.MAX_PARTICIPANTS,0) <= 0
        THEN 0
        ELSE a.MAX_PARTICIPANTS
    END AS "MAX_PARTICIPANTS",
    CASE
        WHEN COALESCE(a.MAX_WAITING_LIST_PARTICIPANTS,0) <= 0
        THEN 0
        ELSE a.MAX_WAITING_LIST_PARTICIPANTS
    END           AS "MAX_WAITING_LIST_PARTICIPANTS",
    a.EXTERNAL_ID AS "ACTIVITY_EXTERNAL_ID"
FROM
    ACTIVITY a
LEFT JOIN
    COLOUR_GROUPS cg
ON
    a.COLOUR_GROUP_ID = cg.ID
    AND a.COLOUR_GROUP_ID IS NOT NULL
LEFT JOIN
    ACTIVITY_GROUP ag
ON
    a.ACTIVITY_GROUP_ID = ag.ID
    AND a.ACTIVITY_GROUP_ID IS NOT NULL
WHERE
    a.STATE != 'DRAFT'
    AND a.TOP_NODE_ID IS NULL

