-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT -- BI_ACCEPTED_MATERIALS
    'ACCEPTED_MATERIALS' AS "TABLE_NAME",
    COUNT(*)             AS "ROW_COUNT"
FROM
    PERSONS p
LEFT JOIN
    PERSON_EXT_ATTRS acceptedMaterial
ON
    p.center=acceptedMaterial.PERSONCENTER
    AND p.id=acceptedMaterial.PERSONID
    AND acceptedMaterial.name IN('_eClub_IsAcceptingThirdPartyOffers',
                                 '_eClub_IsAcceptingEmailNewsLetters')
WHERE
    p.SEX != 'C'
    -- Exclude Transferred
    AND p.STATUS NOT IN (4)
UNION ALL
SELECT -- BI_ACTIVITY
    'ACTIVITY' AS "TABLE_NAME",
    COUNT(*)   AS "ROW_COUNT"
FROM
    ACTIVITY a
WHERE
    a.STATE != 'DRAFT'
    AND a.TOP_NODE_ID IS NULL
UNION ALL
SELECT -- BI_ACTIVITY_GROUP
    'ACTIVITY_GROUP' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    ACTIVITY_GROUP ag
WHERE
    ag.TOP_NODE_ID IS NULL
    AND ag.STATE != 'DRAFT'
UNION ALL
SELECT -- BI_AGREEMENT_CASES
    'AGREEMENT_CASES' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    CASHCOLLECTIONCASES cc
WHERE
    cc.MISSINGPAYMENT = 0
UNION ALL
SELECT -- BI_AREA_CENTERS
    'AREA_CENTERS' AS "TABLE_NAME",
    COUNT(*)       AS "ROW_COUNT"
FROM
    AREA_CENTERS
UNION ALL
SELECT -- BI_AREAS
    'AREAS'  AS "TABLE_NAME",
    COUNT(*) AS "ROW_COUNT"
FROM
    BI_AREAS biview
UNION ALL
SELECT -- BI_BOOKING_RESOURCE_USAGE
    'BOOKING_RESOURCE_USAGE' AS "TABLE_NAME",
    COUNT(*)                 AS "ROW_COUNT"
FROM
    BOOKING_RESOURCE_USAGE biview
UNION ALL
SELECT -- BI_BOOKINGS
    'BOOKINGS' AS "TABLE_NAME",
    COUNT(*)   AS "ROW_COUNT"
FROM
    BOOKINGS biview
UNION ALL
SELECT -- BI_CAMPAIGNS
    'CAMPAIGNS' AS "TABLE_NAME",
    SUM(COUNT)  AS "ROW_COUNT"
FROM
    (
        SELECT
            COUNT(*) AS COUNT
        FROM
            STARTUP_CAMPAIGN st
        UNION ALL
        SELECT
            COUNT(*) AS COUNT
        FROM
            PRIVILEGE_RECEIVER_GROUPS prg)
UNION ALL
SELECT -- BI_CENTER_EXT_ATTR
    'CENTER_EXT_ATTR' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    CENTER_EXT_ATTRS cea
UNION ALL
SELECT -- BI_CENTERS
    'CENTERS' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM
    CENTERS biview
UNION ALL
SELECT -- BI_CLIPCARD_USAGE
    'CLIPCARD_USAGE' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    CARD_CLIP_USAGES biview
UNION ALL
SELECT -- BI_CLIPCARDS
    'CLIPCARDS' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    CLIPCARDS biview
UNION ALL
SELECT -- BI_COMPANIES
    'COMPANIES' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    PERSONS p
WHERE
    p.SEX = 'C'
UNION ALL
SELECT -- BI_COUNTRIES
    'COUNTRIES' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    COUNTRIES biview
UNION ALL
SELECT -- BI_DAILY_MEMBER_STATE
    'DAILY_MEMBER_STATE' AS "TABLE_NAME",
    COUNT(*)             AS "ROW_COUNT"
FROM
    DAILY_MEMBER_STATUS_CHANGES dms
WHERE
    dms.ENTRY_STOP_TIME IS NULL
UNION ALL
SELECT -- BI_DEBT_CASES
    'DEBT_CASES' AS "TABLE_NAME",
    COUNT(*)     AS "ROW_COUNT"
FROM
    CASHCOLLECTIONCASES cc
WHERE
    cc.MISSINGPAYMENT = 1
UNION ALL
SELECT -- BI_FREEZES
    'FREEZES' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM
    SUBSCRIPTION_FREEZE_PERIOD f
UNION ALL
SELECT -- BI_INVENTORY_TRANSACTIONS_LOG
    'INVENTORY_TRANSACTIONS_LOG' AS "TABLE_NAME",
    COUNT(*)                     AS "ROW_COUNT"
FROM
    INVENTORY_TRANS
UNION ALL
SELECT
    'KPI_LOG' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM -- BI_KPI_LOG
    KPI_DATA kd
JOIN
    KPI_FIELDS kf
ON
    kf.id = kd.FIELD
WHERE
    kf.EXTERNAL_ID LIKE 'BI_%'
UNION ALL
SELECT -- BI_MASTER_PRODUCTS
    'MASTER_PRODUCTS' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    MASTERPRODUCTREGISTER mp
WHERE
    ID = DEFINITION_KEY
UNION ALL
SELECT -- BI_PARTICIPATIONS
    'PARTICIPATIONS' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    PARTICIPATIONS biview
UNION ALL
SELECT -- BI_PERSON_DETAILS
    'PERSON_DETAILS' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    PERSONS p
WHERE
    p.SEX != 'C'
    -- Exclude Transferred
    AND p.center = p.TRANSFERS_CURRENT_PRS_CENTER
    AND p.id = p.TRANSFERS_CURRENT_PRS_ID
UNION ALL
SELECT -- BI_PERSON_EXT_ATTR
    'PERSON_EXT_ATTR' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    PERSONS p
JOIN
    PERSON_EXT_ATTRS pea
ON
    pea.PERSONCENTER = p.center
    AND pea.PERSONID =p.id
WHERE
    p.SEX != 'C'
    -- Exclude Transferred
    AND p.center = p.TRANSFERS_CURRENT_PRS_CENTER
    AND p.id = p.TRANSFERS_CURRENT_PRS_ID
    AND instr(pea.NAME,'_eClub_') =0
    AND pea.NAME != 'CREATION_DATE'
UNION ALL
SELECT -- BI_ACCESS_PRIVILEGE_USAGE
    'ACCESS_PRIVILEGE_USAGE' AS "TABLE_NAME",
    COUNT(*)                 AS "ROW_COUNT"
FROM
    PRIVILEGE_USAGES pu
JOIN
    PRIVILEGE_GRANTS pg
ON
    pg.ID = pu.GRANT_ID
WHERE
    pu.TARGET_SERVICE IN ('Participation',
                          'Attend',
                          'Booking')
    AND pg.GRANTER_SERVICE IN ('GlobalCard',
                               'GlobalSubscription',
                               'Access product',
                               'Addon')
UNION ALL
SELECT -- BI_PERSONS
    'PERSONS' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM
    PERSONS p
WHERE
    p.SEX != 'C'
    -- Exclude Transferred
    AND p.center = p.TRANSFERS_CURRENT_PRS_CENTER
    AND p.id = p.TRANSFERS_CURRENT_PRS_ID
UNION ALL
SELECT -- BI_PRODUCT_GROUPS
    'PRODUCT_GROUPS' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    PRODUCT_GROUP pg
WHERE
    pg.TOP_NODE_ID IS NULL
UNION ALL
SELECT -- BI_PRODUCT_PRIVILEGE_USAGE
    'PRODUCT_PRIVILEGE_USAGE' AS "TABLE_NAME",
    COUNT(*)                  AS "ROW_COUNT"
FROM
    PRIVILEGE_USAGES pu
WHERE
    pu.TARGET_SERVICE IN ('InvoiceLine',
                          'SubscriptionPrice')
UNION ALL
SELECT -- BI_PRODUCT_PRODUCT_GROUPS
    'PRODUCT_PRODUCT_GROUPS' AS "TABLE_NAME",
    COUNT(*)                 AS "ROW_COUNT"
FROM
    PRODUCT_AND_PRODUCT_GROUP_LINK ppgl
UNION ALL
SELECT -- BI_PRODUCTS
    'PRODUCTS' AS "TABLE_NAME",
    COUNT(*)   AS "ROW_COUNT"
FROM
    PRODUCTS biview
UNION ALL
SELECT -- BI_RESOURCES
    'RESOURCES' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    BOOKING_RESOURCES
UNION ALL
SELECT -- BI_SALES_LOG
    'SALES_LOG' AS "TABLE_NAME",
    SUM(cnt)    AS "ROW_COUNT"
FROM
    (
        SELECT
            COUNT(*) AS cnt
        FROM
            invoice_lines_mt il
        UNION ALL
        SELECT
            COUNT(*) AS cnt
        FROM
            credit_note_lines_mt cl )
UNION ALL
SELECT -- BI_STAFF_USAGE
    'STAFF_USAGE' AS "TABLE_NAME",
    COUNT(*)      AS "ROW_COUNT"
FROM
    STAFF_USAGE s
UNION ALL
SELECT -- BI_SUBSCRIPTION_ADDONS
    'SUBSCRIPTION_ADDONS' AS "TABLE_NAME",
    COUNT(*)              AS "ROW_COUNT"
FROM
    SUBSCRIPTION_ADDON sa
UNION ALL
SELECT -- BI_SUBSCRIPTION_PERIODS
    'SUBSCRIPTION_PERIODS' AS "TABLE_NAME",
    COUNT(*)               AS "ROW_COUNT"
FROM
    SPP_INVOICELINES_LINK biview
UNION ALL
SELECT -- BI_SUBSCRIPTION_SALES
    'SUBSCRIPTION_SALES' AS "TABLE_NAME",
    COUNT(*)             AS "ROW_COUNT"
FROM
    SUBSCRIPTION_SALES ss
UNION ALL
SELECT -- BI_SUBSCRIPTION_STATE_LOG
    'SUBSCRIPTION_STATE_LOG' AS "TABLE_NAME",
    COUNT(*)                 AS "ROW_COUNT"
FROM
    STATE_CHANGE_LOG
WHERE
    ENTRY_TYPE = 2
UNION ALL
SELECT -- BI_VISITS_LOG
    'VISITS_LOG' AS "TABLE_NAME",
    COUNT(*)     AS "ROW_COUNT"
FROM
    CHECKINS
UNION ALL
SELECT -- BI_VISITS_LOG
    'ATTENDS' AS "TABLE_NAME",
    COUNT(*)     AS "ROW_COUNT"
FROM
    ATTENDS