-- This is the version from 2026-02-05
--  
SELECT DISTINCT
    ar.CUSTOMERCENTER||'p'||ar.CUSTOMERID AS MEMBER_ID,
    prs.REQUESTED_AMOUNT,
    prs.PAID_STATE
FROM
    FW.AR_TRANS art
JOIN
    FW.ACCOUNT_RECEIVABLES ar
ON
    ar.center = art.CENTER
    AND ar.id = art.id
    AND ar.AR_TYPE = 4
JOIN
    FW.PAYMENT_REQUEST_SPECIFICATIONS prs
ON
    prs.CENTER = art.PAYREQ_SPEC_CENTER
    AND prs.id= art.PAYREQ_SPEC_ID
    AND prs.SUBID = art.PAYREQ_SPEC_SUBID
WHERE
    art.DUE_DATE IS NOT NULL
    AND prs.ORIGINAL_DUE_DATE = to_date('2018-03-03','YYYY-MM-DD')
    AND art.ENTRY_TIME < 1516503635000
    AND art.ENTRY_TIME > 1513555235000
    AND ar.CUSTOMERCENTER = 107
    AND prs.REQUESTED_AMOUNT <> 0