-- This is the version from 2026-02-05
--  
SELECT 
C.LASTNAME AS CompanyName , 
C.CENTER || 'p' || C.ID AS CompanyId, 
C.SSN AS VATNumber, 
longtodate(ART.ENTRY_TIME) AS DATETIME, 
ART.AMOUNT, 
ART.TEXT, 
ART.EMPLOYEECENTER || 'emp' || ART.EMPLOYEEID AS EmployeeId, 
S.FULLNAME as EmployeeName, 
ART.REF_TYPE, 
ART.DUE_DATE, 
ART.INFO, 
AR.BALANCE AS accountBalance 
FROM 
AR_TRANS ART 
JOIN ACCOUNT_RECEIVABLES AR 
ON 
ART.CENTER = AR.CENTER 
AND ART.ID = AR.ID 
JOIN PERSONS C 
ON 
C.CENTER = AR.CUSTOMERCENTER 
AND C.ID = AR.CUSTOMERID 
JOIN EMPLOYEES E 
ON 
E.CENTER = ART.EMPLOYEECENTER 
AND E.ID = ART.EMPLOYEEID 
JOIN PERSONS S 
ON 
E.PERSONCENTER = S.CENTER 
AND E.PERSONID = S.ID 
WHERE 
s.center = 103
and 
s.id = 2980

