-- This is the version from 2026-02-05
--  
SELECT DISTINCT P.CENTER ||'p'|| P.ID AS MEMBERID, P.EXTERNAL_ID,
 P.FULLNAME AS FULLNAME, 
        CE.NAME AS CENTER, CASE P.STATUS WHEN 0 THEN 'LEAD' WHEN 1 THEN 
        'ACTIVE' WHEN 2 THEN 'INACTIVE' WHEN 3 THEN 'TEMPORARY 
        INACTIVE' WHEN 4 THEN 'TRANSFERRED' WHEN 5 THEN 'DUPLICATE' 
        WHEN 6 THEN 'PROSPECT' WHEN 7 THEN 'DELETED' WHEN 8 THEN 
        'ANONIMIZED' WHEN 9 THEN 'CONTACT' ELSE 'UNKNOWN' END AS 
        STATUS, CASE P.PERSONTYPE WHEN 0 THEN 'PRIVATE' WHEN 1 THEN 
        'STUDENT' WHEN 2 THEN 'STAFF' WHEN 3 THEN 'FRIEND' WHEN 4 THEN 
        'CORPORATE' WHEN 5 THEN 'ONE MAN CORPORATE' WHEN 6 THEN 
        'FAMILY' WHEN 7 THEN 'SENIOR' WHEN 8 THEN 'GUEST' ELSE 
        'UNKNOWN' END AS PERSONTYPE

    from PERSONS P LEFT 
    join SUBSCRIPTIONS S ON (P.CENTER = S.OWNER_CENTER AND P.ID = 
        S.OWNER_ID) LEFT 
    join CENTERS CE ON P.CENTER = CE.ID
    where P.CENTER IN (111,180,183,214,230,606,611,622)  AND S.STATE IN (2,4,8)
	AND P.STATUS NOT IN (4,5,7,8)
	ORDER BY
	MEMBERID