-- This is the version from 2026-02-05
--  
SELECT
ar.CUSTOMERCENTER ||'p'|| ar.CUSTOMERID as MEMBERID,
P.FULLNAME,
p.EXTERNAL_ID,
CASE p.STATUS WHEN 0 THEN 'LEAD' WHEN 1 THEN 'ACTIVE' WHEN 2 THEN 'INACTIVE' WHEN 3 THEN 'TEMPORARY INACTIVE' WHEN 4 THEN 'TRANSFERRED' WHEN 5 THEN 'DUPLICATE' WHEN 6 THEN 'PROSPECT' WHEN 7 THEN 'DELETED' WHEN 8 THEN 'ANONYMIZED' WHEN 9 THEN 'CONTACT' ELSE 'Undefined' END AS STATUS,
CASE  p.PERSONTYPE
 WHEN 0 THEN 'PRIVATE'  WHEN 1 THEN 'STUDENT'  WHEN 2 THEN 'STAFF'  WHEN 3 THEN 'FRIEND'  WHEN 4 THEN 'CORPORATE'  WHEN 5 THEN 'ONEMANCORPORATE'
 WHEN 6 THEN  'FAMILY'  WHEN 7 THEN 'SENIOR'  WHEN 8 THEN 'GUEST'  WHEN 10 THEN  'EXTERNAL STAFF' ELSE 'UNKNOWN' END AS "PERSON TYPE",
ar.BALANCE,
CASE ar.AR_TYPE WHEN 1 THEN 'CASH ACCOUNT' WHEN 4 THEN 'PAYMENT ACCOUNT' WHEN 5 THEN 'DEBT ACCOUNT' ELSE 'Undefined' END AS "ACCOUNT TYPE"
FROM
ACCOUNT_RECEIVABLES ar
JOIN
persons p
ON
ar.customercenter = p.center
AND ar.customerid = p.id
WHERE
ar.BALANCE < 0
AND ar.AR_TYPE in (1,4,5)
And p.center in (:scope)
AND p.sex != 'C'
ORDER BY memberid
