-- This is the version from 2026-02-05
--  
SELECT
COUNT(*) AS CLIPCARD_SALES_COUNT,
prod.NAME
--invl.TOTAL_AMOUNT,
--invl.QUANTITY,
--TO_CHAR(longtodate(inv.TRANS_TIME), 'DD-MM-YYYY') AS "DATE"
FROM
CLIPCARDS cc
JOIN INVOICELINES invl
ON
invl.CENTER = cc.INVOICELINE_CENTER
AND invl.ID = cc.INVOICELINE_ID
AND invl.SUBID = cc.INVOICELINE_SUBID
JOIN PRODUCTS prod
ON
prod.CENTER = invl.PRODUCTCENTER
AND prod.ID = invl.PRODUCTID
JOIN INVOICES inv
ON
inv.CENTER = invl.CENTER
AND inv.ID = invl.ID
WHERE
inv.TRANS_TIME >= :dateFrom 
AND inv.TRANS_TIME <:dateTo
AND cc.INVOICELINE_CENTER in (:scope)
GROUP BY
prod.NAME
