-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT p.CENTER ||'p'|| p.id as MEMBERID,
cd.CODE as CAMPAIGNCODE,
pr.NAME as SUBSCRIPTION,
s.START_DATE AS STARTDATE,
s.END_DATE as ENDDATE,
TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YY HH24:MM:SS') AS CREATIONTIME
FROM PERSONS p
JOIN SUBSCRIPTIONS s
ON s.OWNER_CENTER = p.CENTER
AND s.OWNER_ID = p.ID
JOIN PRODUCTS pr
ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER
AND pr.ID = s.SUBSCRIPTIONTYPE_ID
JOIN PRIVILEGE_USAGES pu
ON pu.PERSON_CENTER = p.CENTER
AND pu.PERSON_ID = p.ID
JOIN CAMPAIGN_CODES cd
ON cd.ID = pu.CAMPAIGN_CODE_ID
WHERE
(p.CENTER, p.ID) in (:MEMBER)
AND s.STATE = 2
