-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT p.CENTER || 'prod' || p.ID AS PRODUCT_ID,
	   p.GLOBALID AS PRODUCT_GLOBALID,
	   sales_acc.GLOBALID AS SALES_ACC_GLOBALID
FROM
    PRODUCTS p
LEFT JOIN FW.CENTERS c
ON
    c.ID = p.CENTER
LEFT JOIN FW.PRODUCT_ACCOUNT_CONFIGURATIONS pac
ON
    pac.ID = p.PRODUCT_ACCOUNT_CONFIG_ID
LEFT JOIN FW.ACCOUNTS sales_acc
ON
    sales_acc.GLOBALID = pac.SALES_ACCOUNT_GLOBALID
    AND sales_acc.CENTER = c.ID