-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT
	PR.NAME AS NAVE,
	PR.GLOBALID AS "GLOBAL ID",
	count(*) AS "ANTAL MEDLEMMER" 
FROM SUBSCRIPTIONS S
	LEFT join PRODUCTS PR 
	ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID
    where s.CENTER IN (:scope)
	AND S.STATE IN (2,4,8)
GROUP BY
	PR.NAME,
	PR.GLOBALID
