-- This is the version from 2026-02-05
--  
SELECT s.OWNER_CENTER ||'p'|| s.OWNER_ID AS MEMBERID,
p1.FULLNAME AS MEMBERNAME,
s.CREATOR_CENTER ||'emp'|| CREATOR_ID AS SALESPERSONID,
p2.FULLNAME AS SALESPERSON
FROM
SUBSCRIPTIONS s
JOIN PERSONS p1
ON s.OWNER_CENTER = p1.CENTER AND s.OWNER_ID = p1.ID
JOIN EMPLOYEES e
ON s.CREATOR_CENTER = e.CENTER AND s.CREATOR_ID = e.ID
JOIN PERSONS p2
ON e.PERSONCENTER = p2.CENTER AND e.PERSONID = p2.ID
WHERE
(s.CENTER ||'ss'|| s.ID) in (:Sub_ID)