-- The extract is extracted from Exerp on 2026-02-08
--  
select *
from CHECKINS c
JOIN PERSONS P
ON p.CENTER = c.PERSON_CENTER AND p.ID = c.PERSON_ID
WHERE
c.CHECKIN_CENTER in (:CENTER)
AND c.CHECKIN_TIME >= (:CHECKIN_TIME_FROM)
AND c.CHECKIN_TIME <= (:CHECKIN_TIME_TO)
--AND c.CHECKIN_RESULT = 3