-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 
--Count(SHOWUP_INTERFACE_TYPE),
DECODE(SHOWUP_INTERFACE_TYPE, 0, 'Automatisk', 1, 'Klient', 2, 'App', 3, 'Kiosk'),
PARTICIPANT_CENTER ||'p'|| PARTICIPANT_ID,
SHOWUP_INTERFACE_TYPE,
TO_CHAR(longtodate(SHOWUP_TIME), 'DD-MM-YYYY HH24:MI'),
TO_CHAR(longtodate(START_TIME), 'DD-MM-YYYY HH24:MI')
FROM PARTICIPATIONS
WHERE
SHOWUP_TIME >= (:SHOWUP_START)
--AND SHOWUP_TIME <= (SHOWUP_END)
AND CENTER in (:SCOPE)
--GROUP BY
--SHOWUP_INTERFACE_TYPE