-- This is the version from 2026-02-05
--  
SELECT s.OWNER_CENTER ||'p'|| s.OWNER_ID,
pr.NAME,
pr.GLOBALID,
--sa.ADDON_PRODUCT_ID,
il.TOTAL_AMOUNT,
il.PRODUCT_NORMAL_PRICE,
il.TEXT
FROM SUBSCRIPTIONS s
JOIN PRODUCTS pr ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER AND pr.ID = 
        s.SUBSCRIPTIONTYPE_ID
--JOIN SUBSCRIPTION_ADDON sa
--ON sa.SUBSCRIPTION_CENTER = s.CENTER AND sa.SUBSCRIPTION_ID = s.ID
JOIN INVOICELINES il
ON s.INVOICELINE_CENTER = il.CENTER
AND s.INVOICELINE_ID = il.ID
AND INVOICELINE_SUBID = il.SUBID

WHERE (s.OWNER_CENTER ||'p'|| s.OWNER_ID) IN (:Member)