-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT 
s.OWNER_CENTER ||'p'|| s.OWNER_ID,
CASE s.STATE  WHEN 2 THEN  'ACTIVE'  WHEN 3 THEN  'ENDED'  WHEN 4 THEN  'FROZEN'  WHEN 7 THEN  'WINDOW'  WHEN 8 THEN  'CREATED'  ELSE 'UNKNOWN' END,
s.CENTER ||'ss'|| s.ID,
s.START_DATE SUB_START,
s.END_DATE SUB_END,
s.SUBSCRIPTION_PRICE,
sfp.START_DATE FREEZE_START,
TO_CHAR(longtodate(sfp.ENTRY_TIME), 'dd-MM-YYYY HH24:MI') AS "Freeze creation",
sfp.END_DATE FREEZE_END,
sfp.TYPE
FROM SUBSCRIPTION_FREEZE_PERIOD sfp
JOIN SUBSCRIPTIONS s
on s.CENTER = sfp.SUBSCRIPTION_CENTER
AND s.ID = sfp.SUBSCRIPTION_ID
WHERE sfp.END_DATE >= (s.END_DATE - 31)
AND sfp.START_DATE BETWEEN (:Freeze_start) AND (:Freeze_end)
AND sfp.STATE != 'CANCELLED'
