-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT
invl.PERSON_CENTER || 'p' || invl.PERSON_ID person_id,
to_char(longtodate(inv.TRANS_TIME),'DD-MM-YYYY HH24:MI') TRANSACTION_TIME,
prod.NAME "FEE_NAME",
p.FIRST_ACTIVE_START_DATE FIRST_START_DATE,
s.START_DATE "SUB_STARTDATE",
pr.NAME SUB_NAME,
CASE
WHEN p.FIRST_ACTIVE_START_DATE < s.START_DATE THEN 'Tidligere/eksisterende medlem'
ELSE 'Nyt medlem'
END AS MEMBER_TYPE
FROM
FW.INVOICELINES invl
JOIN FW.INVOICES inv
ON
inv.CENTER = invl.CENTER
AND inv.ID = invl.ID
JOIN FW.PRODUCTS prod
ON
    prod.CENTER = invl.PRODUCTCENTER
    AND prod.ID = invl.PRODUCTID
JOIN PERSONS p
ON invl.PERSON_CENTER = p.CENTER AND invl.PERSON_ID = p.ID
JOIN SUBSCRIPTIONS s
ON s.OWNER_CENTER = p.CENTER AND s.OWNER_ID = p.ID
JOIN PRODUCTS pr ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER AND pr.ID = s.SUBSCRIPTIONTYPE_ID 
WHERE
prod.GLOBALID IN ('NON_LOCAL_CHECKIN_FEE', 'CLUB_CHECKIN_FEE', 'VP_CLASS_BOOKING_FEE', 'VP_CLUB_CHECKIN_FEE')
AND inv.TRANS_TIME between (:StartDate) and (:EndDate)
AND inv.PAYER_CENTER in (:Person_homecenter)
AND s.START_DATE > (:Sub_startdate)
ORDER BY
(invl.PERSON_CENTER || 'p' || invl.PERSON_ID)