-- This is the version from 2026-02-05
--  
SELECT DISTINCT p.CENTER ||'p'|| p.id as MEMBERID,
curr_p.EXTERNAL_ID,
		DECODE(p.STATUS,0,'LEAD',1,'ACTIVE',2,'INACTIVE',3,'TEMPORARY INACTIVE',4,'TRANSFERRED',5,'DUPLICATE',6,'PROSPECT',7,'DELETED',8,'ANONYMIZED',9,'CONTACT','Undefined') AS "MEMBER STATUS",
cd.CODE as CAMPAIGNCODE,
pr.NAME as SUBSCRIPTION,
DECODE(s.STATE, 2, 'ACTIVE', 3, 'ENDED', 4, 'FROZEN', 7, 'WINDOW', 8, 'CREATED','OTHER') AS "SUBSCRIPTION STATE",
s.START_DATE AS STARTDATE,
s.END_DATE as ENDDATE,
TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YY HH24:MM:SS') AS CREATIONTIME
FROM PERSONS p
JOIN SUBSCRIPTIONS s
ON s.OWNER_CENTER = p.CENTER
AND s.OWNER_ID = p.ID
JOIN PRODUCTS pr
ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER
AND pr.ID = s.SUBSCRIPTIONTYPE_ID
JOIN PRIVILEGE_USAGES pu
ON pu.PERSON_CENTER = p.CENTER
AND pu.PERSON_ID = p.ID
JOIN CAMPAIGN_CODES cd
ON cd.ID = pu.CAMPAIGN_CODE_ID
JOIN PERSONS curr_p
ON p.CURRENT_PERSON_CENTER = curr_p.CENTER AND p.CURRENT_PERSON_ID = curr_p.ID
WHERE
cd.CODE like 'Nuuday%'
--AND s.CREATION_TIME >= (Oprettelses_efter)
--AND s.CREATION_TIME <= (Oprettelse_for)
--AND s.STATE = 2
ORDER BY
CREATIONTIME