-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
p.CENTER ||'p'|| p.ID AS "PERSON_ID",
s.CENTER AS "SUBSCRIPTION_CENTER",
pr.NAME AS "SUBSCRIPTION_NAME",
pr.GLOBALID AS "SUBSCRIPTION_GLOBAL_ID",
Current_price.FROM_DATE AS "CURRENT_PRICE_FROM_DATE",
Current_price.TO_DATE AS "CURRENT_PRICE_TO_DATE",
Current_price.PRICE AS "CURRENT_PRICE",
sp.FROM_DATE AS "NEW_CAMPAIGN_PRICE_FROM_DATE",
sp.TO_DATE AS "NEW_CAMPAIGN_PRICE_TO_DATE",
sp.PRICE AS "NEW_CAMPAIGN_PRICE",
New_price.FROM_DATE AS "NORMAL_PRICE_PRICE_FROM_DATE",
New_price.TO_DATE AS "NORMAL_PRICE_PRICE_TO_DATE",
New_price.PRICE AS "NORMAL_PRICE"
FROM 
SUBSCRIPTION_PRICE sp
JOIN
SUBSCRIPTIONS s
ON sp.SUBSCRIPTION_CENTER = s.CENTER
AND sp.SUBSCRIPTION_ID = s.ID
JOIN PERSONS p
ON p.CENTER = s.OWNER_CENTER
AND p.ID = s.OWNER_ID
JOIN SUBSCRIPTION_PRICE Current_price
ON Current_price.SUBSCRIPTION_CENTER = s.CENTER
AND Current_price.SUBSCRIPTION_ID = s.ID
JOIN SUBSCRIPTION_PRICE New_price
ON New_price.SUBSCRIPTION_CENTER = s.CENTER
AND New_price.SUBSCRIPTION_ID = s.ID
JOIN PRODUCTS pr 
ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER
AND pr.ID = s.SUBSCRIPTIONTYPE_ID
WHERE
--sp.SUBSCRIPTION_CENTER = 608
--AND sp.SUBSCRIPTION_ID = 134011
sp.FROM_DATE = :Dato
AND sp.TO_DATE = :Dato2
AND sp.TYPE = 'CAMPAIGN'
AND sp.CANCELLED = 0
AND s.CENTER in (:Scope)
AND Current_price.TO_DATE < :Dato3
AND New_price.FROM_DATE > :Dato4