-- This is the version from 2026-02-05
--  
Select
scf.TYPE,
cfp.CACHED_PRODUCTNAME,
scf.STATE,
mpr.GLOBALID,
mpr.CACHED_PRODUCTNAME
from SUBSCRIPTION_CHANGE_FEES scf
JOIN MASTERPRODUCTREGISTER mpr
ON mpr.ID = scf.SUBSCR_TYPE_FROM
JOIN MASTERPRODUCTREGISTER cfp
ON cfp.ID = scf.CHANGE_FEE_PRODUCT
WHERE scf.STATE != 'DELETED'
ORDER BY
mpr.GLOBALID
