-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT
sp.PRICE,
CASE s.STATE WHEN 2 THEN 'ACTIVE' WHEN 4 THEN 'FROZEN' END AS STATUS,
p.CENTER ||'p'|| p.ID as MemberID,
p.CENTER,
p.sex as Gender,
current_timestamp as Run_time,
PR.NAME AS NAME,
PR.GLOBALID AS GLOBAL_ID,
CASE P.PERSONTYPE WHEN 0 THEN 'PRIVATE' WHEN 1 THEN 
        'STUDENT' WHEN 2 THEN 'STAFF' WHEN 3 THEN 'FRIEND' WHEN 4 THEN 
        'CORPORATE' WHEN 5 THEN 'ONE MAN CORPORATE' WHEN 6 THEN 
        'FAMILY' WHEN 7 THEN 'SENIOR' WHEN 8 THEN 'GUEST' ELSE 
        'UNKNOWN' END AS PERSONTYPE
FROM SUBSCRIPTIONS s
JOIN SUBSCRIPTION_PRICE sp
ON sp.SUBSCRIPTION_CENTER = s.CENTER
AND sp.SUBSCRIPTION_ID = s.ID
LEFT join PRODUCTS PR 
	ON PR.CENTER = S.SUBSCRIPTIONTYPE_CENTER AND PR.ID = S.SUBSCRIPTIONTYPE_ID
JOIN PERSONS p
ON p.CENTER = s.OWNER_CENTER
AND p.ID = s.OWNER_ID
WHERE
sp.FROM_DATE <= current_date
AND (sp.TO_DATE is null or sp.TO_DATE > current_date)
AND sp.CANCELLED = 0
AND s.STATE in (2,4)
AND s.CENTER in (:scope)
GROUP BY
sp.PRICE,
s.state,
p.CENTER,
PR.NAME,
current_timestamp,
p.sex,
PR.GLOBALID,
(p.CENTER ||'p'|| p.ID),
P. PERSONTYPE
ORDER BY
(p.CENTER ||'p'|| p.ID)
