-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
pa.ref,
ar.CUSTOMERCENTER ||'p'|| ar.CUSTOMERID,
pa.EXPIRATION_DATE
FROM
PAYMENT_AGREEMENTS pa
JOIN ACCOUNT_RECEIVABLES ar
ON pa.CENTER = ar.CENTER
AND pa.ID = ar.ID
WHERE
pa.EXPIRATION_DATE	BETWEEN :EXPIRY_DATE_FROM AND :EXPIRY_DATE_TO
AND pa.CREDITOR_ID = 'FW_ADYEN'
AND pa.STATE = 4
AND pa.ACTIVE = 1
