-- This is the version from 2026-02-05
-- REQ0016137
SELECT DISTINCT p.CENTER ||'p'|| p.id as MEMBERID,
curr_p.EXTERNAL_ID,
		CASE p.STATUS WHEN 0 THEN 'LEAD' WHEN 1 THEN 'ACTIVE' WHEN 2 THEN 'INACTIVE' WHEN 3 THEN 'TEMPORARY INACTIVE' WHEN 4 THEN 'TRANSFERRED' WHEN 5 THEN 'DUPLICATE' WHEN 6 THEN 'PROSPECT' WHEN 7 THEN 'DELETED' WHEN 8 THEN 'ANONYMIZED' WHEN 9 THEN 'CONTACT' ELSE 'Undefined' END AS "MEMBER STATUS",
cd.CODE as CAMPAIGNCODE,
pr.NAME as SUBSCRIPTION,
CASE s.STATE  WHEN 2 THEN  'ACTIVE'  WHEN 3 THEN  'ENDED'  WHEN 4 THEN  'FROZEN'  WHEN 7 THEN  'WINDOW'  WHEN 8 THEN  'CREATED' ELSE 'OTHER' END AS "SUBSCRIPTION STATE",
s.START_DATE AS STARTDATE,
s.END_DATE as ENDDATE,
TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YYYY HH24:MM:SS') AS CREATIONTIME
FROM PERSONS p
JOIN SUBSCRIPTIONS s
ON s.OWNER_CENTER = p.CENTER
AND s.OWNER_ID = p.ID
JOIN PRODUCTS pr
ON pr.CENTER = s.SUBSCRIPTIONTYPE_CENTER
AND pr.ID = s.SUBSCRIPTIONTYPE_ID
JOIN PRIVILEGE_USAGES pu
ON pu.PERSON_CENTER = p.CENTER
AND pu.PERSON_ID = p.ID
JOIN CAMPAIGN_CODES cd
ON cd.ID = pu.CAMPAIGN_CODE_ID
JOIN PERSONS curr_p
ON p.CURRENT_PERSON_CENTER = curr_p.CENTER AND p.CURRENT_PERSON_ID = curr_p.ID
WHERE
cd.CODE like 'Arla%' OR
cd.CODE like 'ARLAPG15' OR
cd.CODE like 'B2B%' OR
cd.CODE like 'Cheval%' OR
cd.CODE like 'Domea%' OR
cd.CODE like 'Imerco%' OR
cd.CODE like 'JYSKFW2022%' OR
cd.CODE like 'Nuuday%' OR
cd.CODE like 'Q8FW2022%' OR
cd.CODE like 'Sanistål%' OR
cd.CODE like 'Verisure%' OR
cd.CODE like 'Alliance%' OR
cd.CODE like '3SHAPEFW2022' OR
cd.CODE like 'AllianceFW2022' OR  
cd.CODE like 'AKAFW20' OR
cd.CODE like 'BBFW15' OR
cd.CODE like '5RPFW15' OR
cd.CODE like 'BDOFW15' OR
cd.CODE like 'BESTSELLERFW2022' OR
cd.CODE like 'BKPG10' OR
cd.CODE like 'CHFW15' OR
cd.CODE like 'CLEVERFWPLUS' OR
cd.CODE like 'CONVATECFW2022' OR
cd.CODE like 'COOPFW15' OR
cd.CODE like 'COOPFW20' OR
cd.CODE like 'DAGROFAFW15' OR
cd.CODE like 'DHLFW2022' OR
cd.CODE like 'DKLFW20' OR
cd.CODE like 'DTFW15' OR
cd.CODE like 'EPICOFW15' OR
cd.CODE like 'EUROFINSFW15' OR
cd.CODE like 'FALCKFW15' OR
cd.CODE like 'FKFW15' OR
cd.CODE like 'GLSFW15' OR
cd.CODE like 'GOFW15' OR
cd.CODE like 'GSFW15' OR
cd.CODE like 'IKEAFW2022' OR
cd.CODE like 'JFFW15' OR
cd.CODE like 'JYSKFW2022' OR
cd.CODE like 'KODEXGFW15' OR
cd.CODE like 'LIDLFW15' OR
cd.CODE like 'LLGFW15' OR
cd.CODE like 'LOUISE15PG' OR
cd.CODE like 'LOXAMFW15' OR
cd.CODE like 'LPFW15' OR
cd.CODE like 'MADKLUBBENFW15' OR
cd.CODE like 'MILJØMFW15' OR
cd.CODE like 'MPFW15' OR
cd.CODE like 'NICGFW15' OR
cd.CODE like 'NKFW15' OR
cd.CODE like 'NICGFW15' OR
cd.CODE like 'NORDISKFILMFW15' OR
cd.CODE like 'NORDSTERNFW2022' OR
cd.CODE like 'NorlysFW2022' OR
cd.CODE like 'NREPFW15' OR
cd.CODE like 'NTFW15' OR
cd.CODE like 'ORDNUNGFW15' OR
cd.CODE like 'PSYKIATRIFW15' OR
cd.CODE like 'Q8FW2022' OR
cd.CODE like 'REKOMFW15' OR
cd.CODE like 'REKOMFW20' OR
cd.CODE like 'NICGFW15' OR
cd.CODE like 'RITUALSFW15' OR
cd.CODE like 'SIFW15' OR
cd.CODE like 'SNTFW15' OR
cd.CODE like 'SWECOFW15' OR
cd.CODE like 'TAMIGOFW15' OR
cd.CODE like 'TDCFWPLUS' OR
cd.CODE like 'TERMAFW2022' OR
cd.CODE like 'TIETOEVRYFW15' OR
cd.CODE like 'TVMIDTVESTFW15' OR
cd.CODE like 'VILLAFW10' OR
cd.CODE like 'VILLAFW15' OR
cd.CODE like 'VMSGFW15' OR
cd.CODE like 'WOAFW15
'
AND TO_CHAR(longtodate(s.CREATION_TIME), 'DD-MM-YYYY') = TO_CHAR(longtodate(pu.USE_TIME), 'DD-MM-YYYY')
--AND pr.GLOBALID like 'PLUS%' 
--AND pr.GLOBALID like 'Core%
--AND s.CREATION_TIME >= (Oprettelses_efter)
--AND s.CREATION_TIME <= (Oprettelse_for)
--AND s.STATE = 2
ORDER BY
CREATIONTIME
