-- This is the version from 2026-02-05
--  
SELECT
	p.CENTER ||'p'|| p.ID,
	decode(p.status,0,'Lead',1,'Active',2,'Inactive',3,'TemporaryInactive',4,'Transferred',5,'Duplicate',6,'Prospect',7,'Deleted',8,'Anonymized',9,'Contact','Undefined') AS "Person status",
	DECODE(p.PERSONTYPE,0,'PRIVATE', 1,'STUDENT', 2,'STAFF', 3,'FRIEND', 4,'CORPORATE', 5,'ONEMANCORPORATE',6, 'FAMILY', 7,'SENIOR', 8,'GUEST', 10, 'EXTERNAL STAFF','UNKNOWN') AS "PERSON TYPE",
	ch.NAME,
	DECODE(pr.STATE,1,'NEW',2,'SENT',3,'DONE',4,'DONE MANUALLY',5,'FAILED, REJECTED BY CLEARINGHOUSE',6,'FAILED, BANK REJECTED',7,'FAILED,REJECTED BY DEBTOR',8,'CANCELLED',12,'FAILED, COULD NOT BE SENT',17,'FAILED, PAYMENT REVOKED',18,'DONE PARTIALLY',19,'FAILED, NOT SUPPORTED','UNKNOWN') AS PAYMENT_REQUEST_STATE,
	pr.REQ_AMOUNT,
	pr.REQ_DATE
	
FROM
	PAYMENT_REQUESTS pr

JOIN
	ACCOUNT_RECEIVABLES ar
ON
	ar.center = pr.center
AND ar.id = pr.id
AND ar.AR_TYPE = 4

JOIN
	PERSONS p
ON
	p.CENTER = ar.CUSTOMERCENTER
AND p.id = ar.CUSTOMERID
AND p.SEX != 'C'

JOIN
	CLEARINGHOUSES ch
ON
	pr.CLEARINGHOUSE_ID = ch.ID
AND	ch.ID != 2

WHERE
	pr.CENTER in (:scope)
AND TO_CHAR(pr.REQ_DATE, 'MM-YYYY') = TO_CHAR(sysdate, 'MM-YYYY')
AND pr.REQ_AMOUNT > 0