-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
cc.OWNER_CENTER || 'p' || cc.OWNER_ID pid,
cc.INVOICELINE_CENTER as Sold_in_Center,
cc.CLIPS_INITIAL,
cc.CLIPS_LEFT,
prod.NAME,
invl.TOTAL_AMOUNT,
invl.QUANTITY
FROM
CLIPCARDS cc
JOIN INVOICELINES invl
ON
invl.CENTER = cc.INVOICELINE_CENTER
AND invl.ID = cc.INVOICELINE_ID
AND invl.SUBID = cc.INVOICELINE_SUBID
JOIN PRODUCTS prod
ON
prod.CENTER = invl.PRODUCTCENTER
AND prod.ID = invl.PRODUCTID
JOIN INVOICES inv
ON
inv.CENTER = invl.CENTER
AND inv.ID = invl.ID
WHERE
inv.TRANS_TIME BETWEEN :dateFrom AND :dateTo
AND prod.GLOBALID = 'BASIS_PROGRAM_PT'
and cc.INVOICELINE_CENTER in (:Scope)