-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT DISTINCT
qa.CENTER ||'p'|| qa.ID AS MemberID,
TO_CHAR(longtodate(qa.LOG_TIME), 'dd-MM-YYYY HH24:MI:SS') ANSWER_TIME,
curr_p1.EXTERNAL_ID,
qar.TEXT_ANSWER
FROM
QUESTIONNAIRE_ANSWER qa
JOIN
QUESTION_ANSWER qar
ON qa.CENTER = qar.ANSWER_CENTER AND qa.ID = qar.ANSWER_ID AND qa.SUBID = qar.ANSWER_SUBID
JOIN QUESTIONNAIRE_CAMPAIGNS qc
ON qa.QUESTIONNAIRE_CAMPAIGN_ID = qc.ID
JOIN PERSONS p1
ON qa.CENTER = p1.CENTER AND qa.ID = p1.ID
JOIN PERSONS curr_p1
ON p1.CURRENT_PERSON_CENTER = curr_p1.CENTER AND p1.CURRENT_PERSON_ID = curr_p1.ID
WHERE qc.type = 3
-- qc.ID in (1802, 2202)
--AND qa.RESULT_CODE = '0800'
--AND qar.QUESTION_ID = 2
AND longtodate(qa.LOG_TIME) >= current_date - 90
AND longtodate(qa.LOG_TIME) < current_date
ORDER BY
ANSWER_TIME
