SELECT
    p.CENTER || 'p' || p.ID pid,
    p.CENTER,
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED',8, 'ANONYMIZED', 9, 'CONTACT', 'UNKNOWN') AS STATUS,
    s.CENTER || 'ss' || s.ID ssid,
	s.BINDING_PRICE SUB_PRICE,
    DECODE (s.STATE, 2,'ACTIVE', 3,'ENDED', 4,'FROZEN', 7,'WINDOW', 8,'CREATED','UNKNOWN') as SUB_STATUS,
    prod.NAME SUB_TYPE,
    pg.NAME SUB_GROUP_NAME,
    sa.ID ADDON_ID,
    mpr.CACHED_PRODUCTNAME ADDON_NAME,
    mpr.GLOBALID ADDON_GLOBAL_ID,
    longToDate(sa.CREATION_TIME) addon_created,
    sa.START_DATE addon_start_date,
    sa.END_DATE addon_end_date,
    sa.INDIVIDUAL_PRICE_PER_UNIT addon_price
FROM
    SUBSCRIPTION_ADDON sa
join SUBSCRIPTIONS s on s.CENTER = sa.SUBSCRIPTION_CENTER and s.id = sa.SUBSCRIPTION_ID
join PRODUCTS prod on prod.CENTER = s.SUBSCRIPTIONTYPE_CENTER and  prod.ID = s.SUBSCRIPTIONTYPE_ID
join PRODUCT_GROUP pg on pg.ID = prod.PRIMARY_PRODUCT_GROUP_ID
join PERSONS p on p.CENTER = s.OWNER_CENTER and p.ID = s.OWNER_ID 
join MASTERPRODUCTREGISTER mpr on mpr.ID = sa.ADDON_PRODUCT_ID    
WHERE
    sa.CANCELLED = 0
    AND (
        sa.END_DATE IS NULL
        OR sa.END_DATE > exerpsysdate())
        and sa.USE_INDIVIDUAL_PRICE = $$price_type$$