SELECT
    p.CENTER || 'p' || p.ID pid
  , p.FULLNAME
  , longToDate(art.TRANS_TIME) TRANSACTION_TIME
  , art.AMOUNT
  , art.TEXT
FROM
    ACCOUNT_TRANS act
LEFT JOIN
    AR_TRANS art
ON
    art.REF_TYPE = 'ACCOUNT_TRANS'
    AND ( (
            art.REF_CENTER = act.DEBIT_TRANSACTION_CENTER
            AND art.REF_ID = act.DEBIT_TRANSACTION_ID
            AND art.REF_SUBID = act.DEBIT_TRANSACTION_SUBID)
        OR (
            art.REF_CENTER = act.CENTER
            AND art.REF_ID = act.ID
            AND art.REF_SUBID = act.SUBID ))
LEFT JOIN
    ACCOUNT_RECEIVABLES ar
ON
    ar.CENTER = art.CENTER
    AND ar.ID = art.ID
LEFT JOIN
    PERSONS p
ON
    p.CENTER = ar.CUSTOMERCENTER
    AND p.ID = ar.CUSTOMERID
WHERE
    act.AGGREGATED_TRANSACTION_CENTER = $$AGGREGATED_TRANSACTION_CENTER$$
    AND act.AGGREGATED_TRANSACTION_ID = $$AGGREGATED_TRANSACTION_ID$$