SELECT
    COUNT(*),
    DECODE (STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 6,'PROSPECT', 7,'DELETED','UNKNOWN') AS STATUS,
    p.CENTER
FROM
    JOURNALENTRIES je
JOIN PERSONS p
ON
    p.CENTER = je.CENTER
    AND p.id = je.ID
WHERE
    je.NAME = 'Import note'
GROUP BY
    p.STATUS,
    p.CENTER