SELECT
    ID AS "ID",
    ACCESS_CODE AS "ACCESS_CODE",
    ACCESS_TIME AS "ACCESS_DATETIME",
    USAGE_POINT_CENTER || 'br' || USAGE_POINT_ID  AS "RESOURCE_ID",
    USAGE_POINT_CENTER AS "CENTER_ID",
    ACCESS_TIME AS "ETS"
FROM
    ACCESS_CODE     
