SELECT
    ID                     AS "ID",
    TASK_ACTION_ID         AS "TASK_ACTION_ID",
    TASK_STEP_ID           AS "TASK_STEP_ID",
    TRANSITION_TO_STEP_ID  AS "TRANSITION_TO_STEP_ID",
    TASK_USER_CHOICE_ID    AS "TASK_USER_CHOICE_ID",
    NEW_TASK_STATUS        AS "NEW_TASK_STATUS" ,
    POST_TRANSITION_ACTION AS "POST_TRANSITION_ACTION" 
FROM
    TASK_STEP_TRANSITIONS