SELECT
    ID                         AS "ID",
    NAME                       AS "NAME",
    EXTERNAL_ID                AS "EXTERNAL_ID",
    PARENT_PRODUCT_GROUP_ID    AS "PARENT_PRODUCT_GROUP_ID",
    CAST(DIMENSION_PRODUCT_GROUP_ID AS INTEGER) AS "DIMENSION_PRODUCT_GROUP_ID"
FROM
    PRODUCT_GROUP
WHERE
    TOP_NODE_ID IS NULL