SELECT
    p.CENTER || 'p' || p.ID AS Pref,
    cen.NAME as CLUB_NAME,
    ext.TXTVALUE AS Salutation,
    p.SEX,
    p.FIRSTNAME,
    p.LASTNAME,
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,
    'DUPLICATE', 6,'PROSPECT', 7,'DELETED',8, 'ANONYMIZED', 9, 'CONTACT', 'UNKNOWN') AS PERSON_STATUS,
    p.LAST_ACTIVE_START_DATE AS LAST_JOIN_DATE
FROM
    PUREGYM.PERSONS p
JOIN
    PUREGYM.PERSON_EXT_ATTRS ext
ON
    p.CENTER = ext.PERSONCENTER
    AND p.ID = ext.PERSONID
    AND ext.NAME = '_eClub_Salutation'
    AND ext.TXTVALUE = 'DR'
JOIN PUREGYM.CENTERS cen
on p.CENTER = cen.ID    
    