SELECT
    PUREGYM.Persons.EXTERNAL_ID       AS "External ID",
    PUREGYM.Person_ext_attrs.TXTVALUE AS "Car Reg",
    PUREGYM.Centers.NAME              AS "Center"
FROM
    PUREGYM.PERSONS
Left JOIN
    PUREGYM.PERSON_EXT_ATTRS
ON
    PUREGYM.persons.CENTER = PUREGYM.PERSON_EXT_ATTRS.PERSONCENTER
AND 
	PUREGYM.persons.ID = PUREGYM.PERSON_EXT_ATTRS.PERSONID

Left JOIN
    PUREGYM.CENTERS
ON
    PUREGYM.persons.CENTER = PUREGYM.centers.ID
WHERE
    PUREGYM.person_ext_attrs.TXTVALUE IS NOT NULL
AND 
	PUREGYM.Persons.EXTERNAL_ID IS NOT NULL
AND 
	PUREGYM.PERSON_EXT_ATTRS.NAME = 'carreg'