-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
        COUNT (*) REPETITIONS,
        atr.TXTVALUE
FROM PUREGYM.PERSONS P
JOIN PUREGYM.PERSON_EXT_ATTRS ATR ON p.CENTER = atr.PERSONCENTER AND p.ID = atr.PERSONID AND atr.NAME = '_eClub_Email' AND atr.TXTVALUE IS NOT NULL
WHERE
        p.STATUS = 1
        AND p.PERSONTYPE NOT IN (2,8)
GROUP BY
        atr.TXTVALUE
HAVING COUNT (*) > 1
ORDER BY
        COUNT (*) DESC