SELECT -- BI_SUBSCRIPTION_STATE_LOG
    KEY
FROM
    STATE_CHANGE_LOG
WHERE
    ENTRY_TYPE = 2
    AND (
        ENTRY_END_TIME > ENTRY_START_TIME
        OR ENTRY_END_TIME IS NULL )
    AND (
        COALESCE(ENTRY_END_TIME,ENTRY_START_TIME) > 1483228800000
        AND COALESCE(ENTRY_END_TIME,ENTRY_START_TIME) < 1509494400000)