-- The extract is extracted from Exerp on 2026-02-08
-- https://clublead.atlassian.net/browse/ST-3281
 SELECT PIN, SUM(PURCHASED) AS "Yanga Water Bolt On"
 FROM
 (
 SELECT DISTINCT
   e.IDENTITY AS PIN,
   (CASE
         WHEN sa.CENTER_ID IS NULL THEN 0
         ELSE 1
   END) AS PURCHASED
 FROM
   PERSONS p
 JOIN
   SUBSCRIPTIONS s
   ON
         s.OWNER_CENTER = p.CENTER
         AND s.OWNER_ID = p.ID
 LEFT JOIN
   SUBSCRIPTION_ADDON sa
   ON
         s.CENTER = sa.SUBSCRIPTION_CENTER
         AND s.ID = sa.SUBSCRIPTION_ID
         AND sa.ADDON_PRODUCT_ID = 58402
         AND sa.START_DATE <= CURRENT_TIMESTAMP
         AND (sa.END_DATE IS NULL or sa.END_DATE >= CURRENT_TIMESTAMP)
 JOIN
   ENTITYIDENTIFIERS e
 ON
   p.CENTER = e.REF_CENTER
   AND p.ID = e.REF_ID
   AND e.ENTITYSTATUS = 1
   AND e.IDMETHOD = 5
   AND e.REF_TYPE = 1
 WHERE
   p.STATUS = 1
   AND p.CENTER IN (1,9,95,96,147,175)
 ) x
 GROUP BY PIN
