WITH
    params AS
    (
        SELECT
            DECODE(:offset,-1,0,(TRUNC(SYSDATE)-:offset-to_date('1-1-1970 00:00:00','MM-DD-YYYY HH24:Mi:SS'))*24*3600*1000) AS FROMDATE,
            (TRUNC(SYSDATE+1)-to_date('1-1-1970 00:00:00','MM-DD-YYYY HH24:Mi:SS'))*24*3600*1000                                  AS TODATE
        FROM
            dual
    )

SELECT -- BI_ACTIVITY
    'ACTIVITY' AS "TABLE_NAME",
    COUNT(*)   AS "ROW_COUNT"
FROM
    BI_ACTIVITY biview
UNION ALL
SELECT -- BI_ACTIVITY_GROUP
    'ACTIVITY_GROUP' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    BI_ACTIVITY_GROUP biview
UNION ALL
SELECT -- BI_AGREEMENT_CASES
    'AGREEMENT_CASES' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    params,
    BI_AGREEMENT_CASES biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT -- BI_AREA_CENTERS
    'AREA_CENTERS' AS "TABLE_NAME",
    COUNT(*)       AS "ROW_COUNT"
FROM
    BI_AREA_CENTERS biview
UNION ALL
SELECT -- BI_AREAS
    'AREAS'  AS "TABLE_NAME",
    COUNT(*) AS "ROW_COUNT"
FROM
    BI_AREAS biview
UNION ALL
SELECT -- BI_BOOKINGS
    'BOOKINGS' AS "TABLE_NAME",
    COUNT(*)   AS "ROW_COUNT"
FROM
    params,
    BI_BOOKINGS biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT -- BI_CENTER_EXT_ATTR
    'CENTER_EXT_ATTR' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    params,
    BI_CENTER_EXT_ATTR biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT -- BI_CENTERS
    'CENTERS' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM
    BI_CENTERS biview
UNION ALL
SELECT -- BI_CLIPCARD_USAGE
    'CLIPCARD_USAGE' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    params,
    BI_CLIPCARD_USAGE biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT -- BI_CLIPCARDS
    'CLIPCARDS' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    params,
    BI_CLIPCARDS biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT -- BI_COMPANIES
    'COMPANIES' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    params,
    BI_COMPANIES biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT -- BI_COUNTRIES
    'COUNTRIES' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    BI_COUNTRIES biview
UNION ALL
SELECT -- BI_DAILY_MEMBER_STATE
    'DAILY_MEMBER_STATE' AS "TABLE_NAME",
    COUNT(*)             AS "ROW_COUNT"
FROM
    params,
    BI_DAILY_MEMBER_STATE biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'DEBT_CASES' AS "TABLE_NAME",
    COUNT(*)     AS "ROW_COUNT"
FROM
    params,
    BI_DEBT_CASES biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'KPI_LOG' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM
    params,
    BI_KPI_LOG biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'MASTER_PRODUCTS' AS "TABLE_NAME",
    COUNT(*)          AS "ROW_COUNT"
FROM
    BI_MASTER_PRODUCTS biview
UNION ALL
SELECT
    'PARTICIPATIONS' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    params,
    BI_PARTICIPATIONS biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'PERSONS' AS "TABLE_NAME",
    COUNT(*)  AS "ROW_COUNT"
FROM
    params,
    BI_PERSONS biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'PRODUCT_GROUPS' AS "TABLE_NAME",
    COUNT(*)         AS "ROW_COUNT"
FROM
    BI_PRODUCT_GROUPS biview
UNION ALL
SELECT
    'PRODUCT_PRODUCT_GROUPS' AS "TABLE_NAME",
    COUNT(*)                 AS "ROW_COUNT"
FROM
    params,
    BI_PRODUCT_PRODUCT_GROUPS biview
UNION ALL
SELECT
    'PRODUCTS' AS "TABLE_NAME",
    COUNT(*)   AS "ROW_COUNT"
FROM
    params,
    BI_PRODUCTS biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'SALES_LOG' AS "TABLE_NAME",
    COUNT(*)    AS "ROW_COUNT"
FROM
    params,
    BI_SALES_LOG biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'STAFF_USAGE' AS "TABLE_NAME",
    COUNT(*)      AS "ROW_COUNT"
FROM
    params,
    BI_STAFF_USAGE biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'SUBSCRIPTION_ADDONS' AS "TABLE_NAME",
    COUNT(*)              AS "ROW_COUNT"
FROM
    params,
    BI_SUBSCRIPTION_ADDONS biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'SUBSCRIPTION_SALES' AS "TABLE_NAME",
    COUNT(*)             AS "ROW_COUNT"
FROM
    params,
    BI_SUBSCRIPTION_SALES biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'SUBSCRIPTION_STATE_LOG' AS "TABLE_NAME",
    COUNT(*)                 AS "ROW_COUNT"
FROM
    params,
    BI_SUBSCRIPTION_STATE_LOG biview
WHERE
    biview.ets BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE
UNION ALL
SELECT
    'PERSON_COMPANY_AGREEMENT_LOG' AS "TABLE_NAME",
    COUNT(*)                       AS "ROW_COUNT"
FROM
    params,
    STATE_CHANGE_LOG scl
JOIN
    RELATIVES r
ON
    r.center = scl.center
    AND r.id = scl.id
    AND r.SUBID = scl.SUBID
    AND r.rtype = 2
WHERE
    r.rtype = 2
    AND (
        scl.ENTRY_END_TIME-scl.ENTRY_START_TIME > 1000
        OR scl.ENTRY_END_TIME IS NULL)
    AND scl.ENTRY_START_TIME BETWEEN PARAMS.FROMDATE AND PARAMS.TODATE