SELECT
    s.CENTER||'ss'||s.ID            AS SUBSCRIPTION_ID,
    s.OWNER_CENTER||'p'||s.OWNER_ID AS MEMBER_ID
FROM
    PUREGYM.SUBSCRIPTIONS s
JOIN
    PUREGYM.SUBSCRIPTIONTYPES st
ON
    st.CENTER = s.SUBSCRIPTIONTYPE_CENTER
    AND st.ID = s.SUBSCRIPTIONTYPE_ID
JOIN
    PUREGYM.PRODUCTS p
ON
    st.PRODUCTNEW_CENTER = p.center
    AND st.PRODUCTNEW_ID = p.id
WHERE
    s.STATE = 2
    AND p.BLOCKED = 1
    AND st.ST_TYPE = 1
    AND st.FREEZEPERIODPRODUCT_CENTER IS NOT NULL