SELECT
        inv.PAYER_CENTER || 'p' || inv.PAYER_ID AS CompanyId,
        pr.REQ_AMOUNT,
        pr.REQ_DATE,
        pr.DUE_DATE,
        pr.CLEARINGHOUSE_ID,
        inv.text,
        il.PERSON_CENTER || 'p' || il.PERSON_ID AS PersonId,
        il.text,
        il.TOTAL_AMOUNT,
		c.ID,
        c.INVOICE_COUNT
        /*art.REF_TYPE,
        count(*)*/
FROM PUREGYM.CLEARING_OUT c
JOIN PUREGYM.PAYMENT_REQUESTS pr ON pr.REQ_DELIVERY = c.ID
JOIN PUREGYM.PAYMENT_REQUEST_SPECIFICATIONS prs ON prs.CENTER = pr.INV_COLL_CENTER AND prs.ID = pr.INV_COLL_ID AND prs.SUBID = pr.INV_COLL_SUBID
JOIN PUREGYM.AR_TRANS art ON art.PAYREQ_SPEC_CENTER = prs.CENTER AND art.PAYREQ_SPEC_ID = prs.ID AND art.PAYREQ_SPEC_SUBID = prs.SUBID
JOIN PUREGYM.INVOICES inv ON inv.CENTER = art.REF_CENTER AND inv.ID = art.REF_ID AND art.REF_TYPE = 'INVOICE'
JOIN PUREGYM.INVOICE_LINES_MT il ON il.CENTER = inv.CENTER AND il.ID = inv.ID
JOIN PUREGYM.ACCOUNT_RECEIVABLES ar ON ar.CENTER = pr.CENTER AND ar.ID = pr.ID
WHERE c.ID IN (:ExportFileId)