-- The extract is extracted from Exerp on 2026-02-08
-- https://clublead.atlassian.net/browse/ST-5497
SELECT
    TO_CHAR(p.EXTERNAL_ID) AS "EXTERNALID",
    p.ZIPCODE AS "POSTALCODE",  
    pea.TXTVALUE AS "EMAIL",
    TO_CHAR(p.CENTER) AS "GYMID",
    DECODE (p.STATUS, 0,'LEAD', 1,'ACTIVE', 2,'INACTIVE', 3,'TEMPORARYINACTIVE', 4,'TRANSFERED', 5,'DUPLICATE', 
                      6,'PROSPECT', 7,'DELETED',8, 'ANONYMIZED', 9, 'CONTACT', 'UNKNOWN') AS "PERSONSTATUS",
    DECODE (p.BLACKLISTED, 0, 'NONE', 1, 'BLACKLISTED', 2, 'SUSPENDED', 3, 'BLOCKED') AS "BLACKLISTED",
    TO_CHAR(longtodatetz(p.LAST_MODIFIED,'Europe/London'),'YYYY-MM-DD HH24:MI:SS') AS "EXERPLASTMODIFIEDDATE"
FROM
    PERSONS p
LEFT JOIN PERSON_EXT_ATTRS pea ON pea.PERSONCENTER = p.CENTER AND pea.PERSONID = p.ID AND pea.NAME = '_eClub_Email'
WHERE
        p.CENTER IN (:Scope)
        AND p.EXTERNAL_ID IS NOT NULL
        AND p.SEX != 'C'
        AND pea.TXTVALUE IS NULL