SELECT 
  qc.ID AS "QUESTIONNAIRE_CAMPAIGN_ID",  
  qc.QUESTIONNAIRE "QUESTIONNAIRE_ID",
  qc.NAME AS "QUESTIONNAIRE_CAMPAIGN_NAME",
  q.NAME AS "QUESTIONNAIRE_NAME",
  to_char(qc.STARTDATE,'YYYY-MM-DD') AS "QUESTIONNAIRE_CAMPAIGN_START",
  to_char(qc.STOPDATE,'YYYY-MM-DD') AS "QUESTIONNAIRE_CAMPAIGN_END"
FROM 
  QUESTIONNAIRE_CAMPAIGNS qc
JOIN
  QUESTIONNAIRES q
ON
  q.ID = qc.QUESTIONNAIRE
ORDER BY
  q.ID
