-- The extract is extracted from Exerp on 2026-02-08
--  
SELECT
        s.OWNER_CENTER || 'p' || s.OWNER_ID AS PERSON_ID,
        s.CENTER || 'ss' || s.ID AS SUBSCRIPTION_ID,
        s.START_DATE AS SUB_START_DATE,
        s.END_DATE AS SUB_END_DATE,
        s.BILLED_UNTIL_DATE,
        pea.TXTVALUE AS PUREGYMATHOME,
        srp.*
FROM SUBSCRIPTIONS s
JOIN SUBSCRIPTIONTYPES st ON s.SUBSCRIPTIONTYPE_CENTER = st.CENTER AND s.SUBSCRIPTIONTYPE_ID = st.ID 
JOIN SUBSCRIPTION_REDUCED_PERIOD srp ON srp.SUBSCRIPTION_CENTER = s.CENTER AND srp.SUBSCRIPTION_ID = s.ID AND  srp.STATE = 'ACTIVE'
LEFT JOIN PERSON_EXT_ATTRS pea ON pea.PERSONCENTER = s.OWNER_CENTER AND pea.PERSONID = s.OWNER_ID AND pea.NAME = 'PUREGYMATHOME'
WHERE
        /* EFT Subscriptions */
        st.ST_TYPE = 1
        AND s.CENTER IN (:Scope)
        AND srp.END_DATE = TO_DATE('2020-07-20','YYYY-MM-DD') 
AND srp.TEXT IS NULL