SELECT
TO_CHAR(p.EXTERNAL_ID) AS "EXTERNALID",
DECODE(pea.DISABLEDACCESS_TXTVALUE,'true',1,0)                                                                                                                                AS "DISABLEDACCESS"
FROM
PERSONS p
LEFT JOIN
(
SELECT
*
FROM
(
SELECT
p.TRANSFERS_CURRENT_PRS_CENTER,
p.TRANSFERS_CURRENT_PRS_ID,
pea.NAME,
pea.TXTVALUE,
pea.LAST_EDIT_TIME
FROM
PUREGYM.PERSON_EXT_ATTRS pea
JOIN
PERSONS p
ON
p.center = pea.PERSONCENTER
AND p.id = pea.PERSONID
WHERE
pea.NAME IN (
'DISABLED_ACCESS'
) ) PIVOT ( MAX(LAST_EDIT_TIME) AS LAST_EDIT_TIME, MAX(TXTVALUE) AS TXTVALUE FOR NAME IN (  'DISABLED_ACCESS'                    AS DISABLEDACCESS) ) ) pea
ON
pea.TRANSFERS_CURRENT_PRS_CENTER = p.TRANSFERS_CURRENT_PRS_CENTER
AND pea.TRANSFERS_CURRENT_PRS_ID = p.TRANSFERS_CURRENT_PRS_ID
WHERE
p.CENTER IN (:Scope)
AND p.EXTERNAL_ID IS NOT NULL
AND p.SEX != 'C'