 SELECT
     CASE  WHEN c.id::varchar IS NULL THEN 'total' ELSE c.id::varchar END                                                                                                  AS "Center ID",
     c.name                                                                                                                          AS "Center Name",
     a.name                                                                                                                          AS "Regional Manager",
     TO_CHAR(c.STARTUPDATE,'yyyy-MM-dd')                                                                                             AS "STARTUPDATE",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 1 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1   AS "1st Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 1 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "1st Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 1 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "1st Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 2 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1   AS "2nd Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 2 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "2nd Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 2 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "2nd Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 3 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1  AS "3rd Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 3 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "3rd Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 3 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "3rd Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 4 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1  AS "4th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 4 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "4th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 4 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "4th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 5 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1  AS "5th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 5 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "5th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 5 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "5th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 6 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1   AS "6th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 6 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "6th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 6 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "6th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 7 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1   AS "7th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 7 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "7th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 7 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "7th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 8 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1   AS "8th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 8 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "8th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 8 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "8th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 9 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1   AS "9th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 9 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "9th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 9 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)      AS "9th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 10 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "10th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 10 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "10th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 10 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "10th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 11 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "11th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 11 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "11th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 11 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "11th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 12 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "12th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 12 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "12th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 12 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "12th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 13 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "13th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 13 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "13th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 13 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "13th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 14 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "14th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 14 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "14th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 14 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "14th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 15 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "15th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 15 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "15th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 15 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "15th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 16 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "16th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 16 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "16th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 16 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "16th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 17 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "17th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 17 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "17th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 17 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "17th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 18 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "18th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 18 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "18th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 18 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "18th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 19 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "19th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 19 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "19th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 19 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "19th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 20 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "20th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 20 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "20th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 20 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "20th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 21 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "21st Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 21 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "21st Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 21 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "21st Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 22 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "22nd Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 22 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "22nd Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 22 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "22nd Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 23 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END) *-1 AS "23rd Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 23 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "23rd Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 23 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "23rd Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 24 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "24th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 24 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "24th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 24 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "24th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 25 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "25th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 25 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "25th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 25 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "25th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 26 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "26th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 26 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "26th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 26 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "26th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 27 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "27th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 27 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "27th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 27 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "27th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 28 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "28th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 28 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "28th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 28 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "28th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 29 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "29th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 29 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "29th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 29 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "29th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 30 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "30th Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 30 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "30th Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 30 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "30th Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 31 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)*-1  AS "31st Leavers diff",
     SUM(CASE kd4.field WHEN 615 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 31 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "31st Total Joiners diff",
     SUM(CASE kd4.field WHEN 604 THEN CASE extract(DAY FROM kd4.FOR_DATE) WHEN 31 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END ELSE NULL END)     AS "31st Net Gain diff",
     SUM(CASE kd4.field WHEN 618 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END)*-1                                                 AS "total Leavers MTD diff",
     SUM(CASE kd4.field WHEN 615 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END)                                                    AS "total Joiners MTD diff",
     SUM(CASE kd4.field WHEN 604 THEN kd4.VALUE-CASE  WHEN kd3.VALUE IS NULL THEN 0 ELSE kd3.value END ELSE NULL END)                                                    AS "total Net Gain MTD diff"
 FROM
     KPI_DATA kd4
 LEFT JOIN
     KPI_DATA kd3
 ON
     kd3.FIELD = kd4.FIELD
     AND kd3.CENTER = kd4.CENTER
     AND add_months(kd3.FOR_DATE,12)=kd4.FOR_DATE
 JOIN
     CENTERS c
 ON
     kd4.center = c.id and c.id !=100
 JOIN
     AREA_CENTERS AC
 ON
     C.ID = AC.CENTER
 JOIN
     AREAS A
 ON
     A.ID = AC.AREA
     AND A.PARENT = 61
 WHERE
     kd4.FIELD IN (615,618,604)
     AND extract(MONTH FROM kd4.FOR_DATE) = extract(MONTH FROM TRUNC(CURRENT_TIMESTAMP) -1 -$$offset$$)
     AND extract(DAY FROM kd4.FOR_DATE) <= extract(DAY FROM TRUNC(CURRENT_TIMESTAMP) -1 -$$offset$$)
     AND extract(YEAR FROM kd4.FOR_DATE) = extract(YEAR FROM TRUNC(CURRENT_TIMESTAMP) -1 -$$offset$$)-- and c.id != 8
 GROUP BY
     grouping sets ( (c.id,c.name,a.name,c.STARTUPDATE), () )
 ORDER BY
     4
