-- The extract is extracted from Exerp on 2026-02-08
--  
 (
 SELECT
     ' Center Name'                                  AS "Center Name",
     'Startup Date'                                 AS "Startup Date",
     'Regional Manager'                             AS "Regional Manager",
     'Status'                                       AS "Status",
     'From Price £'                                 AS "From Price £",
     'Center Name'                                  AS "To Price £",
     TO_CHAR(TRUNC(SYSDATE,'MM'),'DD/MM/YYYY')      AS "Day-1",
     TO_CHAR(TRUNC(SYSDATE,'MM')+1,'DD/MM/YYYY')  AS "Day-2",
     TO_CHAR(TRUNC(SYSDATE,'MM')+2,'DD/MM/YYYY')  AS "Day-3",
     TO_CHAR(TRUNC(SYSDATE,'MM')+3,'DD/MM/YYYY')  AS "Day-4",
     TO_CHAR(TRUNC(SYSDATE,'MM')+4,'DD/MM/YYYY')  AS "Day-5",
     TO_CHAR(TRUNC(SYSDATE,'MM')+5,'DD/MM/YYYY')  AS "Day-6",
     TO_CHAR(TRUNC(SYSDATE,'MM')+6,'DD/MM/YYYY')  AS "Day-7",
     TO_CHAR(TRUNC(SYSDATE,'MM')+7,'DD/MM/YYYY')  AS "Day-8",
     TO_CHAR(TRUNC(SYSDATE,'MM')+8,'DD/MM/YYYY')  AS "Day-9",
     TO_CHAR(TRUNC(SYSDATE,'MM')+9,'DD/MM/YYYY') AS "Day-10",
     TO_CHAR(TRUNC(SYSDATE,'MM')+10,'DD/MM/YYYY') AS "Day-11",
     TO_CHAR(TRUNC(SYSDATE,'MM')+11,'DD/MM/YYYY') AS "Day-12",
     TO_CHAR(TRUNC(SYSDATE,'MM')+12,'DD/MM/YYYY') AS "Day-13",
     TO_CHAR(TRUNC(SYSDATE,'MM')+13,'DD/MM/YYYY') AS "Day-14",
     TO_CHAR(TRUNC(SYSDATE,'MM')+14,'DD/MM/YYYY') AS "Day-15",
     TO_CHAR(TRUNC(SYSDATE,'MM')+15,'DD/MM/YYYY') AS "Day-16",
     TO_CHAR(TRUNC(SYSDATE,'MM')+16,'DD/MM/YYYY') AS "Day-17",
     TO_CHAR(TRUNC(SYSDATE,'MM')+17,'DD/MM/YYYY') AS "Day-18",
     TO_CHAR(TRUNC(SYSDATE,'MM')+18,'DD/MM/YYYY') AS "Day-19",
     TO_CHAR(TRUNC(SYSDATE,'MM')+19,'DD/MM/YYYY') AS "Day-20",
     TO_CHAR(TRUNC(SYSDATE,'MM')+20,'DD/MM/YYYY') AS "Day-21",
     TO_CHAR(TRUNC(SYSDATE,'MM')+21,'DD/MM/YYYY') AS "Day-22",
     TO_CHAR(TRUNC(SYSDATE,'MM')+22,'DD/MM/YYYY') AS "Day-23",
     TO_CHAR(TRUNC(SYSDATE,'MM')+23,'DD/MM/YYYY') AS "Day-24",
     TO_CHAR(TRUNC(SYSDATE,'MM')+24,'DD/MM/YYYY') AS "Day-25",
     TO_CHAR(TRUNC(SYSDATE,'MM')+25,'DD/MM/YYYY') AS "Day-26",
     TO_CHAR(TRUNC(SYSDATE,'MM')+26,'DD/MM/YYYY') AS "Day-27",
     TO_CHAR(TRUNC(SYSDATE,'MM')+27,'DD/MM/YYYY') AS "Day-28",
     TO_CHAR(TRUNC(SYSDATE,'MM')+28,'DD/MM/YYYY') AS "Day-29",
     TO_CHAR(TRUNC(SYSDATE,'MM')+29,'DD/MM/YYYY') AS "Day-30",
     TO_CHAR(TRUNC(SYSDATE,'MM')+30,'DD/MM/YYYY') AS "Day-31",
      TO_CHAR(TRUNC(SYSDATE,'MM')+31,'DD/MM/YYYY') AS "Day-32",
     TO_CHAR(TRUNC(SYSDATE,'MM')+32,'DD/MM/YYYY') AS "Day-33",
     TO_CHAR(TRUNC(SYSDATE,'MM')+33,'DD/MM/YYYY') AS "Day-34",
     TO_CHAR(TRUNC(SYSDATE,'MM')+34,'DD/MM/YYYY') AS "Day-35",
     TO_CHAR(TRUNC(SYSDATE,'MM')+35,'DD/MM/YYYY') AS "Day-36",
     TO_CHAR(TRUNC(SYSDATE,'MM')+36,'DD/MM/YYYY') AS "Day-37",
     TO_CHAR(TRUNC(SYSDATE,'MM')+37,'DD/MM/YYYY') AS "Day-38",
     TO_CHAR(TRUNC(SYSDATE,'MM')+38,'DD/MM/YYYY') AS "Day-39",
     TO_CHAR(TRUNC(SYSDATE,'MM')+39,'DD/MM/YYYY') AS "Day-40",
     TO_CHAR(TRUNC(SYSDATE,'MM')+40,'DD/MM/YYYY') AS "Day-41",
     TO_CHAR(TRUNC(SYSDATE,'MM')+41,'DD/MM/YYYY')  AS "Day-42",
     TO_CHAR(TRUNC(SYSDATE,'MM')+42,'DD/MM/YYYY')  AS "Day-43",
     TO_CHAR(TRUNC(SYSDATE,'MM')+43,'DD/MM/YYYY')  AS "Day-44",
     TO_CHAR(TRUNC(SYSDATE,'MM')+44,'DD/MM/YYYY')  AS "Day-45",
     TO_CHAR(TRUNC(SYSDATE,'MM')+45,'DD/MM/YYYY')  AS "Day-46",
     TO_CHAR(TRUNC(SYSDATE,'MM')+46,'DD/MM/YYYY')  AS "Day-47",
     TO_CHAR(TRUNC(SYSDATE,'MM')+47,'DD/MM/YYYY')  AS "Day-48",
     TO_CHAR(TRUNC(SYSDATE,'MM')+48,'DD/MM/YYYY')  AS "Day-49",
     TO_CHAR(TRUNC(SYSDATE,'MM')+49,'DD/MM/YYYY') AS "Day-50",
     TO_CHAR(TRUNC(SYSDATE,'MM')+50,'DD/MM/YYYY')      AS "Day-51",
     TO_CHAR(TRUNC(SYSDATE,'MM')+51,'DD/MM/YYYY')  AS "Day-52",
     TO_CHAR(TRUNC(SYSDATE,'MM')+52,'DD/MM/YYYY')  AS "Day-53",
     TO_CHAR(TRUNC(SYSDATE,'MM')+53,'DD/MM/YYYY')  AS "Day-54",
     TO_CHAR(TRUNC(SYSDATE,'MM')+54,'DD/MM/YYYY')  AS "Day-55",
     TO_CHAR(TRUNC(SYSDATE,'MM')+55,'DD/MM/YYYY')  AS "Day-56",
     TO_CHAR(TRUNC(SYSDATE,'MM')+56,'DD/MM/YYYY')  AS "Day-57",
     TO_CHAR(TRUNC(SYSDATE,'MM')+57,'DD/MM/YYYY')  AS "Day-58",
     TO_CHAR(TRUNC(SYSDATE,'MM')+58,'DD/MM/YYYY')  AS "Day-59",
     TO_CHAR(TRUNC(SYSDATE,'MM')+59,'DD/MM/YYYY') AS "Day-60",
     TO_CHAR(TRUNC(SYSDATE,'MM')+60,'DD/MM/YYYY')      AS "Day-61",
     TO_CHAR(TRUNC(SYSDATE,'MM')+61,'DD/MM/YYYY')  AS "Day-62",
     TO_CHAR(TRUNC(SYSDATE,'MM')+62,'DD/MM/YYYY')  AS "Day-63",
     TO_CHAR(TRUNC(SYSDATE,'MM')+63,'DD/MM/YYYY')  AS "Day-64",
     TO_CHAR(TRUNC(SYSDATE,'MM')+64,'DD/MM/YYYY')  AS "Day-65",
     TO_CHAR(TRUNC(SYSDATE,'MM')+65,'DD/MM/YYYY')  AS "Day-66",
     TO_CHAR(TRUNC(SYSDATE,'MM')+66,'DD/MM/YYYY')  AS "Day-67",
     TO_CHAR(TRUNC(SYSDATE,'MM')+67,'DD/MM/YYYY')  AS "Day-68",
     TO_CHAR(TRUNC(SYSDATE,'MM')+68,'DD/MM/YYYY')  AS "Day-69",
     TO_CHAR(TRUNC(SYSDATE,'MM')+69,'DD/MM/YYYY') AS "Day-70",
     TO_CHAR(TRUNC(SYSDATE,'MM')+70,'DD/MM/YYYY')      AS "Day-71",
     TO_CHAR(TRUNC(SYSDATE,'MM')+71,'DD/MM/YYYY')  AS "Day-72",
     TO_CHAR(TRUNC(SYSDATE,'MM')+72,'DD/MM/YYYY')  AS "Day-73",
     TO_CHAR(TRUNC(SYSDATE,'MM')+73,'DD/MM/YYYY')  AS "Day-74",
     TO_CHAR(TRUNC(SYSDATE,'MM')+74,'DD/MM/YYYY')  AS "Day-75",
     TO_CHAR(TRUNC(SYSDATE,'MM')+75,'DD/MM/YYYY')  AS "Day-76",
     TO_CHAR(TRUNC(SYSDATE,'MM')+76,'DD/MM/YYYY')  AS "Day-77",
     TO_CHAR(TRUNC(SYSDATE,'MM')+77,'DD/MM/YYYY')  AS "Day-78",
     TO_CHAR(TRUNC(SYSDATE,'MM')+78,'DD/MM/YYYY')  AS "Day-79",
     TO_CHAR(TRUNC(SYSDATE,'MM')+79,'DD/MM/YYYY') AS "Day-80",
     TO_CHAR(TRUNC(SYSDATE,'MM')+80,'DD/MM/YYYY')      AS "Day-81",
     TO_CHAR(TRUNC(SYSDATE,'MM')+81,'DD/MM/YYYY')  AS "Day-82",
     TO_CHAR(TRUNC(SYSDATE,'MM')+82,'DD/MM/YYYY')  AS "Day-83",
     TO_CHAR(TRUNC(SYSDATE,'MM')+83,'DD/MM/YYYY')  AS "Day-84",
     TO_CHAR(TRUNC(SYSDATE,'MM')+84,'DD/MM/YYYY')  AS "Day-85",
     TO_CHAR(TRUNC(SYSDATE,'MM')+85,'DD/MM/YYYY')  AS "Day-86",
     TO_CHAR(TRUNC(SYSDATE,'MM')+86,'DD/MM/YYYY')  AS "Day-87",
     TO_CHAR(TRUNC(SYSDATE,'MM')+87,'DD/MM/YYYY')  AS "Day-88",
     TO_CHAR(TRUNC(SYSDATE,'MM')+88,'DD/MM/YYYY')  AS "Day-89",
     TO_CHAR(TRUNC(SYSDATE,'MM')+89,'DD/MM/YYYY') AS "Day-90",
     'Total'                                        AS TOTAL
 FROM
     DUAL)
UNION
    (
SELECT
NVL(name,'_Grand Total') as Name,
STARTUPDATE,
                    General_Manager,
                    IsOpen,
                    From_Price,
                    To_Price,
           TO_CHAR( SUM("Day-1")) AS "Day-1",
           TO_CHAR( SUM("Day-2")) AS "Day-2",
           TO_CHAR( SUM("Day-3")) AS "Day-3",
           TO_CHAR( SUM("Day-4")) AS "Day-4",
           TO_CHAR( SUM("Day-5")) AS "Day-5",
           TO_CHAR( SUM("Day-6")) AS "Day-6",
           TO_CHAR( SUM("Day-7")) AS "Day-7",
           TO_CHAR( SUM("Day-8")) AS "Day-8",
           TO_CHAR( SUM("Day-9")) AS "Day-9",
           TO_CHAR( SUM("Day-10")) AS "Day-10",
           TO_CHAR( SUM("Day-11")) AS "Day-11",
           TO_CHAR( SUM("Day-12")) AS "Day-12",
           TO_CHAR( SUM("Day-13")) AS "Day-13",
           TO_CHAR( SUM("Day-14")) AS "Day-14",
           TO_CHAR( SUM("Day-15")) AS "Day-15",
           TO_CHAR( SUM("Day-16")) AS "Day-16",
           TO_CHAR( SUM("Day-17")) AS "Day-17",
           TO_CHAR( SUM("Day-18")) AS "Day-18",
           TO_CHAR( SUM("Day-19")) AS "Day-19",
           TO_CHAR( SUM("Day-20")) AS "Day-20",
           TO_CHAR( SUM("Day-21")) AS "Day-21",
           TO_CHAR( SUM("Day-22")) AS "Day-22",
           TO_CHAR( SUM("Day-23")) AS "Day-23",
           TO_CHAR( SUM("Day-24")) AS "Day-24",
           TO_CHAR( SUM("Day-25")) AS "Day-25",
           TO_CHAR( SUM("Day-26")) AS "Day-26",
           TO_CHAR( SUM("Day-27")) AS "Day-27",
           TO_CHAR( SUM("Day-28")) AS "Day-28",
           TO_CHAR( SUM("Day-29")) AS "Day-29",
           TO_CHAR( SUM("Day-30")) AS "Day-30",
           TO_CHAR( SUM("Day-31")) AS "Day-31",
           TO_CHAR( SUM("Day-32")) AS "Day-32",
           TO_CHAR( SUM("Day-33")) AS "Day-33",
           TO_CHAR( SUM("Day-34")) AS "Day-34",
           TO_CHAR( SUM("Day-35")) AS "Day-35",
           TO_CHAR( SUM("Day-36")) AS "Day-36",
           TO_CHAR( SUM("Day-37")) AS "Day-37",
           TO_CHAR( SUM("Day-38")) AS "Day-38",
           TO_CHAR( SUM("Day-39")) AS "Day-39",
           TO_CHAR( SUM("Day-40")) AS "Day-40",
           TO_CHAR( SUM("Day-41")) AS "Day-41",
           TO_CHAR( SUM("Day-42")) AS "Day-42",
           TO_CHAR( SUM("Day-43")) AS "Day-43",
           TO_CHAR( SUM("Day-44")) AS "Day-44",
           TO_CHAR( SUM("Day-45")) AS "Day-45",
           TO_CHAR( SUM("Day-46")) AS "Day-46",
           TO_CHAR( SUM("Day-47")) AS "Day-47",
           TO_CHAR( SUM("Day-48")) AS "Day-48",
           TO_CHAR( SUM("Day-49")) AS "Day-49",
           TO_CHAR( SUM("Day-50")) AS "Day-50",
           TO_CHAR( SUM("Day-51")) AS "Day-51",
           TO_CHAR( SUM("Day-52")) AS "Day-52",
           TO_CHAR( SUM("Day-53")) AS "Day-53",
           TO_CHAR( SUM("Day-54")) AS "Day-54",
           TO_CHAR( SUM("Day-55")) AS "Day-55",
           TO_CHAR( SUM("Day-56")) AS "Day-56",
           TO_CHAR( SUM("Day-57")) AS "Day-57",
           TO_CHAR( SUM("Day-58")) AS "Day-58",
           TO_CHAR( SUM("Day-59")) AS "Day-59",
           TO_CHAR( SUM("Day-60")) AS "Day-60",
           TO_CHAR( SUM("Day-61")) AS "Day-61",
           TO_CHAR( SUM("Day-62")) AS "Day-62",
           TO_CHAR( SUM("Day-63")) AS "Day-63",
           TO_CHAR( SUM("Day-64")) AS "Day-64",
           TO_CHAR( SUM("Day-65")) AS "Day-65",
           TO_CHAR( SUM("Day-66")) AS "Day-66",
           TO_CHAR( SUM("Day-67")) AS "Day-67",
           TO_CHAR( SUM("Day-68")) AS "Day-68",
           TO_CHAR( SUM("Day-69")) AS "Day-69",
           TO_CHAR( SUM("Day-70")) AS "Day-70",
           TO_CHAR( SUM("Day-71")) AS "Day-71",
           TO_CHAR( SUM("Day-72")) AS "Day-72",
           TO_CHAR( SUM("Day-73")) AS "Day-73",
           TO_CHAR( SUM("Day-74")) AS "Day-74",
           TO_CHAR( SUM("Day-75")) AS "Day-75",
           TO_CHAR( SUM("Day-76")) AS "Day-76",
           TO_CHAR( SUM("Day-77")) AS "Day-77",
           TO_CHAR( SUM("Day-78")) AS "Day-78",
           TO_CHAR( SUM("Day-79")) AS "Day-79",
           TO_CHAR( SUM("Day-80")) AS "Day-80",
           TO_CHAR( SUM("Day-81")) AS "Day-81",
           TO_CHAR( SUM("Day-82")) AS "Day-82",
           TO_CHAR( SUM("Day-83")) AS "Day-83",
           TO_CHAR( SUM("Day-84")) AS "Day-84",
           TO_CHAR( SUM("Day-85")) AS "Day-85",
           TO_CHAR( SUM("Day-86")) AS "Day-86",
           TO_CHAR( SUM("Day-87")) AS "Day-87",
           TO_CHAR( SUM("Day-88")) AS "Day-88",
           TO_CHAR( SUM("Day-89")) AS "Day-89",
           TO_CHAR( SUM("Day-90")) AS "Day-90",
           TO_CHAR( SUM(TOTAL)) as TOTAL
FROM
    (
        SELECT
            PV.*,
           NVL("Day-1",0)+ NVL("Day-2",0)+ NVL("Day-3",0)+ NVL("Day-4",0)+ NVL("Day-5",0)+ NVL("Day-6",0)+ NVL("Day-7",0)+ NVL("Day-8",0)+ NVL("Day-9",0)+NVL("Day-10",0)+NVL("Day-11",0)+ NVL("Day-12",0)+ NVL("Day-13",0)+ NVL("Day-14",0)+ NVL("Day-15",0)+ NVL("Day-16",0)+ NVL("Day-17",0)+ NVL("Day-18",0)+ NVL("Day-19",0)+ NVL("Day-20",0)+ NVL("Day-21",0)+ NVL("Day-22",0)+ NVL("Day-23",0)+ NVL("Day-24",0)+ NVL("Day-25",0)+ NVL("Day-26",0)+ NVL("Day-27",0)+ NVL("Day-28",0)+ NVL("Day-29",0)+ NVL("Day-30",0)+ NVL("Day-31",0)+ NVL("Day-32",0)+ NVL("Day-33",0)+ NVL("Day-34",0)+ NVL("Day-35",0)+ NVL("Day-36",0)+ NVL("Day-37",0)+ NVL("Day-38",0)+ NVL("Day-39",0)+NVL("Day-40",0)+NVL("Day-41",0)+ NVL("Day-42",0)+ NVL("Day-43",0)+ NVL("Day-44",0)+ NVL("Day-45",0)+ NVL("Day-46",0)+ NVL("Day-47",0)+ NVL("Day-48",0)+ NVL("Day-49",0)+ NVL("Day-50",0)+  NVL("Day-51",0)+ NVL("Day-52",0)+ NVL("Day-53",0)+ NVL("Day-54",0)+ NVL("Day-55",0)+ NVL("Day-56",0)+ NVL("Day-57",0)+ NVL("Day-58",0)+ NVL("Day-59",0)+ NVL("Day-60",0)+ NVL("Day-61",0)+ NVL("Day-62",0)+ NVL("Day-63",0)+ NVL("Day-64",0)+ NVL("Day-65",0)+ NVL("Day-66",0)+ NVL("Day-67",0)+ NVL("Day-68",0)+ NVL("Day-69",0)+NVL("Day-70",0)+NVL("Day-71",0)+ NVL("Day-72",0)+ NVL("Day-73",0)+ NVL("Day-74",0)+ NVL("Day-75",0)+ NVL("Day-76",0)+ NVL("Day-77",0)+ NVL("Day-78",0)+ NVL("Day-79",0)+ NVL("Day-80",0)+  NVL("Day-81",0)+ NVL("Day-82",0)+ NVL("Day-83",0)+ NVL("Day-84",0)+ NVL("Day-85",0)+ NVL("Day-86",0)+ NVL("Day-87",0)+ NVL("Day-88",0)+ NVL("Day-89",0)+ NVL("Day-90",0) AS TOTAL
        FROM
            (
                SELECT
                    NVL(name,'_Grand Total') as name,
                    STARTUPDATE,
                    General_Manager,
                    IsOpen,
                    TO_CHAR(From_Price) From_Price,
                    TO_CHAR(To_Price) To_Price,
                    TO_CHAR(case when "Day-1">10 then "Day-1" else null end) AS "Day-1",
                    TO_CHAR(case when "Day-2">10 then "Day-2" else null end) AS "Day-2",
                    TO_CHAR(case when "Day-3">10 then "Day-3" else null end) AS "Day-3",
                    TO_CHAR(case when "Day-4">10 then "Day-4" else null end) AS "Day-4",
                    TO_CHAR(case when "Day-5">10 then "Day-5" else null end) AS "Day-5",
                    TO_CHAR(case when "Day-6">10 then "Day-6" else null end) AS "Day-6",
                    TO_CHAR(case when "Day-7">10 then "Day-7" else null end) AS "Day-7",
                    TO_CHAR(case when "Day-8">10 then "Day-8" else null end) AS "Day-8",
                    TO_CHAR(case when "Day-9">10 then "Day-9" else null end) AS "Day-9",
                    TO_CHAR(case when "Day-10">10 then "Day-10" else null end) AS "Day-10",
                    TO_CHAR(case when "Day-11">10 then "Day-11" else null end) AS "Day-11",
                    TO_CHAR(case when "Day-12">10 then "Day-12" else null end) AS "Day-12",
                    TO_CHAR(case when "Day-13">10 then "Day-13" else null end) AS "Day-13",
                    TO_CHAR(case when "Day-14">10 then "Day-14" else null end) AS "Day-14",
                    TO_CHAR(case when "Day-15">10 then "Day-15" else null end) AS "Day-15",
                    TO_CHAR(case when "Day-16">10 then "Day-16" else null end) AS "Day-16",
                    TO_CHAR(case when "Day-17">10 then "Day-17" else null end) AS "Day-17",
                    TO_CHAR(case when "Day-18">10 then "Day-18" else null end) AS "Day-18",
                    TO_CHAR(case when "Day-19">10 then "Day-19" else null end) AS "Day-19",
                    TO_CHAR(case when "Day-20">10 then "Day-20" else null end) AS "Day-20",
                    TO_CHAR(case when "Day-21">10 then "Day-21" else null end) AS "Day-21",
                    TO_CHAR(case when "Day-22">10 then "Day-22" else null end) AS "Day-22",
                    TO_CHAR(case when "Day-23">10 then "Day-23" else null end) AS "Day-23",
                    TO_CHAR(case when "Day-24">10 then "Day-24" else null end) AS "Day-24",
                    TO_CHAR(case when "Day-25">10 then "Day-25" else null end) AS "Day-25",
                    TO_CHAR(case when "Day-26">10 then "Day-26" else null end) AS "Day-26",
                    TO_CHAR(case when "Day-27">10 then "Day-27" else null end) AS "Day-27",
                    TO_CHAR(case when "Day-28">10 then "Day-28" else null end) AS "Day-28",
                    TO_CHAR(case when "Day-29">10 then "Day-29" else null end) AS "Day-29",
                    TO_CHAR(case when "Day-30">10 then "Day-30" else null end) AS "Day-30",
                    TO_CHAR(case when "Day-31">10 then "Day-31" else null end) AS "Day-31",
                    TO_CHAR(case when "Day-32">10 then "Day-32" else null end) AS "Day-32",
                    TO_CHAR(case when "Day-33">10 then "Day-33" else null end) AS "Day-33",
                    TO_CHAR(case when "Day-34">10 then "Day-34" else null end) AS "Day-34",
                    TO_CHAR(case when "Day-35">10 then "Day-35" else null end) AS "Day-35",
                    TO_CHAR(case when "Day-36">10 then "Day-36" else null end) AS "Day-36",
                    TO_CHAR(case when "Day-37">10 then "Day-37" else null end) AS "Day-37",
                    TO_CHAR(case when "Day-38">10 then "Day-38" else null end) AS "Day-38",
                    TO_CHAR(case when "Day-39">10 then "Day-39" else null end) AS "Day-39",
                    TO_CHAR(case when "Day-40">10 then "Day-40" else null end) AS "Day-40",
                    TO_CHAR(case when "Day-41">10 then "Day-41" else null end) AS "Day-41",
                    TO_CHAR(case when "Day-42">10 then "Day-42" else null end) AS "Day-42",
                    TO_CHAR(case when "Day-43">10 then "Day-43" else null end) AS "Day-43",
                    TO_CHAR(case when "Day-44">10 then "Day-44" else null end) AS "Day-44",
                    TO_CHAR(case when "Day-45">10 then "Day-45" else null end) AS "Day-45",
                    TO_CHAR(case when "Day-46">10 then "Day-46" else null end) AS "Day-46",
                    TO_CHAR(case when "Day-47">10 then "Day-47" else null end) AS "Day-47",
                    TO_CHAR(case when "Day-48">10 then "Day-48" else null end) AS "Day-48",
                    TO_CHAR(case when "Day-49">10 then "Day-49" else null end) AS "Day-49",
                    TO_CHAR(case when "Day-50">10 then "Day-50" else null end) AS "Day-50",
                    TO_CHAR(case when "Day-51">10 then "Day-51" else null end) AS "Day-51",
                    TO_CHAR(case when "Day-52">10 then "Day-52" else null end) AS "Day-52",
                    TO_CHAR(case when "Day-53">10 then "Day-53" else null end) AS "Day-53",
                    TO_CHAR(case when "Day-54">10 then "Day-54" else null end) AS "Day-54",
                    TO_CHAR(case when "Day-55">10 then "Day-55" else null end) AS "Day-55",
                    TO_CHAR(case when "Day-56">10 then "Day-56" else null end) AS "Day-56",
                    TO_CHAR(case when "Day-57">10 then "Day-57" else null end) AS "Day-57",
                    TO_CHAR(case when "Day-58">10 then "Day-58" else null end) AS "Day-58",
                    TO_CHAR(case when "Day-59">10 then "Day-59" else null end) AS "Day-59",
                    TO_CHAR(case when "Day-60">10 then "Day-60" else null end) AS "Day-60",
                    TO_CHAR(case when "Day-61">10 then "Day-61" else null end) AS "Day-61",
                    TO_CHAR(case when "Day-62">10 then "Day-62" else null end) AS "Day-62",
                    TO_CHAR(case when "Day-63">10 then "Day-63" else null end) AS "Day-63",
                    TO_CHAR(case when "Day-64">10 then "Day-64" else null end) AS "Day-64",
                    TO_CHAR(case when "Day-65">10 then "Day-65" else null end) AS "Day-65",
                    TO_CHAR(case when "Day-66">10 then "Day-66" else null end) AS "Day-66",
                    TO_CHAR(case when "Day-67">10 then "Day-67" else null end) AS "Day-67",
                    TO_CHAR(case when "Day-68">10 then "Day-68" else null end) AS "Day-68",
                    TO_CHAR(case when "Day-69">10 then "Day-69" else null end) AS "Day-69",
                    TO_CHAR(case when "Day-70">10 then "Day-70" else null end) AS "Day-70",
                    TO_CHAR(case when "Day-71">10 then "Day-71" else null end) AS "Day-71",
                    TO_CHAR(case when "Day-72">10 then "Day-72" else null end) AS "Day-72",
                    TO_CHAR(case when "Day-73">10 then "Day-73" else null end) AS "Day-73",
                    TO_CHAR(case when "Day-74">10 then "Day-74" else null end) AS "Day-74",
                    TO_CHAR(case when "Day-75">10 then "Day-75" else null end) AS "Day-75",
                    TO_CHAR(case when "Day-76">10 then "Day-76" else null end) AS "Day-76",
                    TO_CHAR(case when "Day-77">10 then "Day-77" else null end) AS "Day-77",
                    TO_CHAR(case when "Day-78">10 then "Day-78" else null end) AS "Day-78",
                    TO_CHAR(case when "Day-79">10 then "Day-79" else null end) AS "Day-79",
                    TO_CHAR(case when "Day-80">10 then "Day-80" else null end) AS "Day-80",
                    TO_CHAR(case when "Day-81">10 then "Day-81" else null end) AS "Day-81",
                    TO_CHAR(case when "Day-82">10 then "Day-82" else null end) AS "Day-82",
                    TO_CHAR(case when "Day-83">10 then "Day-83" else null end) AS "Day-83",
                    TO_CHAR(case when "Day-84">10 then "Day-84" else null end) AS "Day-84",
                    TO_CHAR(case when "Day-85">10 then "Day-85" else null end) AS "Day-85",
                    TO_CHAR(case when "Day-86">10 then "Day-86" else null end) AS "Day-86",
                    TO_CHAR(case when "Day-87">10 then "Day-87" else null end) AS "Day-87",
                    TO_CHAR(case when "Day-88">10 then "Day-88" else null end) AS "Day-88",
                    TO_CHAR(case when "Day-89">10 then "Day-89" else null end) AS "Day-89",
                    TO_CHAR(case when "Day-90">10 then "Day-90" else null end) AS "Day-90"
                FROM
                    (
                        SELECT
                            c.name,
                            TO_CHAR(c.STARTUPDATE, 'yyyy-MM-dd')    STARTUPDATE ,
                            a.name                                  General_Manager,
                            p.center||'p'||p.id                     memberID,
                            s.SUBSCRIPTION_PRICE                    From_Price,
                            sp.PRICE                                To_Price,
                            sp.FROM_DATE - TRUNC(SYSDATE,'MM')+1       AS DAY_OF,
                            CASE
                                WHEN c.STARTUPDATE>SYSDATE
                                THEN 'Pre-Join'
                                ELSE 'Open'
                            END AS IsOpen,
                            0   AS TOTAL
                        FROM
                            persons p
                        JOIN
                            PUREGYM.SUBSCRIPTIONS s
                        ON
                            s.OWNER_CENTER = p.CENTER
                            AND s.OWNER_ID = p.ID
                            AND s.STATE IN (2,4)
                        JOIN
                            PUREGYM.SUBSCRIPTION_PRICE sp
                        ON
                            sp.SUBSCRIPTION_CENTER = s.CENTER
                            AND sp.SUBSCRIPTION_ID = s.id
                            AND sp.FROM_DATE > SYSDATE
                            AND SP.FROM_DATE< TRUNC(SYSDATE,'MM') + 90
                            AND sp.CANCELLED = 0
                        JOIN
                            PUREGYM.CENTERS c
                        ON
                            c.id = p.center
                        JOIN
                            AREA_CENTERS AC
                        ON
                            C.ID = AC.CENTER
                        JOIN
                            AREAS A
                        ON
                            A.ID = AC.AREA
                            AND A.PARENT = 61
                        WHERE
                            p.STATUS IN (1,3)
                            AND c.id IN($$scope$$)) pivot (( COUNT(memberID)) FOR DAY_OF IN ( 1 AS "Day-1" ,
                                                                                               2  AS "Day-2" ,
                                                                                               3  AS "Day-3" ,
                                                                                               4  AS "Day-4" ,
                                                                                               5  AS "Day-5" ,
                                                                                               6  AS "Day-6" ,
                                                                                               7  AS "Day-7" ,
                                                                                               8  AS "Day-8" ,
                                                                                               9  AS "Day-9" ,
                                                                                               10 AS "Day-10" ,
                                                                                               11 AS "Day-11" ,
                                                                                               12 AS "Day-12" ,
                                                                                               13 AS "Day-13" ,
                                                                                               14 AS "Day-14" ,
                                                                                               15 AS "Day-15" ,
                                                                                               16 AS "Day-16" ,
                                                                                               17 AS "Day-17" ,
                                                                                               18 AS "Day-18" ,
                                                                                               19 AS "Day-19" ,
                                                                                               20 AS "Day-20" ,
                                                                                               21 AS "Day-21" ,
                                                                                               22 AS "Day-22" ,
                                                                                               23 AS "Day-23" ,
                                                                                               24 AS "Day-24" ,
                                                                                               25 AS "Day-25" ,
                                                                                               26 AS "Day-26" ,
                                                                                               27 AS "Day-27" ,
                                                                                               28 AS "Day-28" ,
                                                                                               29 AS "Day-29" ,
                                                                                               30 AS "Day-30" ,
                                                                                               31 AS "Day-31",
                                                                                               32  AS "Day-32" ,
                                                                                               33  AS "Day-33" ,
                                                                                               34  AS "Day-34" ,
                                                                                               35  AS "Day-35" ,
                                                                                               36  AS "Day-36" ,
                                                                                               37  AS "Day-37" ,
                                                                                               38  AS "Day-38" ,
                                                                                               39  AS "Day-39" ,
                                                                                               40  AS "Day-40" ,
                                                                                                41 AS "Day-41" ,
                                                                                               42  AS "Day-42" ,
                                                                                               43  AS "Day-43" ,
                                                                                               44  AS "Day-44" ,
                                                                                               45  AS "Day-45" ,
                                                                                               46  AS "Day-46" ,
                                                                                               47  AS "Day-47" ,
                                                                                               48  AS "Day-48" ,
                                                                                               49  AS "Day-49" ,
                                                                                               50 AS "Day-50" ,
                                                                                               51 AS "Day-51" ,
                                                                                               52  AS "Day-52" ,
                                                                                               53  AS "Day-53" ,
                                                                                               54  AS "Day-54" ,
                                                                                               55  AS "Day-55" ,
                                                                                               56  AS "Day-56" ,
                                                                                               57  AS "Day-57" ,
                                                                                               58  AS "Day-58" ,
                                                                                               59  AS "Day-59" ,
                                                                                               60 AS "Day-60" ,
                                                                                               61 AS "Day-61" ,
                                                                                               62  AS "Day-62" ,
                                                                                               63  AS "Day-63" ,
                                                                                               64  AS "Day-64" ,
                                                                                               65  AS "Day-65" ,
                                                                                               66  AS "Day-66" ,
                                                                                               67  AS "Day-67" ,
                                                                                               68  AS "Day-68" ,
                                                                                               69  AS "Day-69" ,
                                                                                               70 AS "Day-70" ,
                                                                                               71 AS "Day-71" ,
                                                                                               72  AS "Day-72" ,
                                                                                               73  AS "Day-73" ,
                                                                                               74  AS "Day-74" ,
                                                                                               75  AS "Day-75" ,
                                                                                               76  AS "Day-76" ,
                                                                                               77  AS "Day-77" ,
                                                                                               78  AS "Day-78" ,
                                                                                               79  AS "Day-79" ,
                                                                                               80 AS "Day-80" ,
                                                                                               81 AS "Day-81" ,
                                                                                               82  AS "Day-82" ,
                                                                                               83  AS "Day-83" ,
                                                                                               84  AS "Day-84" ,
                                                                                               85  AS "Day-85" ,
                                                                                               86  AS "Day-86" ,
                                                                                               87  AS "Day-87" ,
                                                                                               88  AS "Day-88" ,
                                                                                               89  AS "Day-89" ,
                                                                                               90 AS "Day-90" 
                                                                                              
                                                                                               )) ) PV
        WHERE
            NVL("Day-1",0)+ NVL("Day-2",0)+ NVL("Day-3",0)+ NVL("Day-4",0)+ NVL("Day-5",0)+ NVL("Day-6",0)+ NVL("Day-7",0)+ NVL("Day-8",0)+ NVL("Day-9",0)+NVL("Day-10",0)+NVL("Day-11",0)+ NVL("Day-12",0)+ NVL("Day-13",0)+ NVL("Day-14",0)+ NVL("Day-15",0)+ NVL("Day-16",0)+ NVL("Day-17",0)+ NVL("Day-18",0)+ NVL("Day-19",0)+ NVL("Day-20",0)+ NVL("Day-21",0)+ NVL("Day-22",0)+ NVL("Day-23",0)+ NVL("Day-24",0)+ NVL("Day-25",0)+ NVL("Day-26",0)+ NVL("Day-27",0)+ NVL("Day-28",0)+ NVL("Day-29",0)+ NVL("Day-30",0)+ NVL("Day-31",0)+ NVL("Day-32",0)+ NVL("Day-33",0)+ NVL("Day-34",0)+ NVL("Day-35",0)+ NVL("Day-36",0)+ NVL("Day-37",0)+ NVL("Day-38",0)+ NVL("Day-39",0)+NVL("Day-40",0)+NVL("Day-41",0)+ NVL("Day-42",0)+ NVL("Day-43",0)+ NVL("Day-44",0)+ NVL("Day-45",0)+ NVL("Day-46",0)+ NVL("Day-47",0)+ NVL("Day-48",0)+ NVL("Day-49",0)+ NVL("Day-50",0)+  NVL("Day-51",0)+ NVL("Day-52",0)+ NVL("Day-53",0)+ NVL("Day-54",0)+ NVL("Day-55",0)+ NVL("Day-56",0)+ NVL("Day-57",0)+ NVL("Day-58",0)+ NVL("Day-59",0)+ NVL("Day-60",0)+ NVL("Day-61",0)+ NVL("Day-62",0)+ NVL("Day-63",0)+ NVL("Day-64",0)+ NVL("Day-65",0)+ NVL("Day-66",0)+ NVL("Day-67",0)+ NVL("Day-68",0)+ NVL("Day-69",0)+NVL("Day-70",0)+NVL("Day-71",0)+ NVL("Day-72",0)+ NVL("Day-73",0)+ NVL("Day-74",0)+ NVL("Day-75",0)+ NVL("Day-76",0)+ NVL("Day-77",0)+ NVL("Day-78",0)+ NVL("Day-79",0)+ NVL("Day-80",0)+  NVL("Day-81",0)+ NVL("Day-82",0)+ NVL("Day-83",0)+ NVL("Day-84",0)+ NVL("Day-85",0)+ NVL("Day-86",0)+ NVL("Day-87",0)+ NVL("Day-88",0)+ NVL("Day-89",0)+ NVL("Day-90",0) > 10)
GROUP BY
    rollup( (name,STARTUPDATE,IsOpen,General_Manager,From_Price,To_Price,TOTAL)))