SELECT
    CCC.CENTER                  AS CCC_CENTER,
    CCC.ID                      AS CCC_ID,
    CCC.PERSONCENTER            AS CCC_PERSONCENTER,
    CCC.PERSONID                AS CCC_PERSONID,
    CCC.AR_CENTER               AS CCC_AR_CENTER,
    CCC.AR_ID                   AS CCC_AR_ID,
    CCC.CLOSED                  AS CCC_CLOSED,
    CCC.SUCCESSFULL             AS CCC_SUCCESSFULL,
    CCC.HOLD                    AS CCC_HOLD,
    CCC.AMOUNT                  AS CCC_AMOUNT,
    CCC.CC_AGENCY_AMOUNT        AS CCC_CC_AGENCY_AMOUNT,
    CCC.CC_AGENCY_UPDATE_SOURCE AS CCC_CC_AGENCY_UPDATE_SOURCE,
    CCC.CC_AGENCY_UPDATE_TIME   AS CCC_CC_AGENCY_UPDATE_TIME,
    CCC.CASHCOLLECTIONSERVICE   AS CCC_CASHCOLLECTIONSERVICE,
    CCC.EXT_REF                 AS CCC_EXT_REF,
    CCC.STARTDATE               AS CCC_STARTDATE,
    CCC.CURRENTSTEP             AS CCC_CURRENTSTEP,
    CCC.CURRENTSTEP_TYPE        AS CCC_CURRENTSTEP_TYPE,
    CCC.CURRENTSTEP_DATE        AS CCC_CURRENTSTEP_DATE,
    CCC.NEXTSTEP_DATE           AS CCC_NEXTSTEP_DATE,
    CCC.NEXTSTEP_TYPE           AS CCC_NEXTSTEP_TYPE,
    CCC.SETTINGS                AS CCC_SETTINGS,
    CCC.MISSINGPAYMENT          AS CCC_MISSINGPAYMENT,
    CCC.BELOW_MINIMUM_AGE       AS CCC_BELOW_MINIMUM_AGE,
    PE.FIRSTNAME                AS PE_FIRSTNAME,
    PE.LASTNAME                 AS PE_LASTNAME,
    PAG1.STATE                   AS PAG_STATE,
    PAG1.CREDITOR_ID             AS PAG_CREDITOR_ID
FROM
    CASHCOLLECTIONCASES CCC
INNER JOIN
    PERSONS PE
ON
    (
        CCC.PERSONCENTER = PE.CENTER
        AND CCC.PERSONID = PE.ID)
INNER JOIN
    ACCOUNT_RECEIVABLES AR
ON
    (
        AR.CUSTOMERCENTER = PE.CENTER
        AND AR.CUSTOMERID = PE.ID
        AND AR.AR_TYPE = 4)
LEFT JOIN
    PAYMENT_ACCOUNTS PAA
ON
    (
        PAA.CENTER = AR.CENTER
        AND PAA.ID = AR.ID)
LEFT JOIN
    PAYMENT_AGREEMENTS PAG1
ON
    (
        PAA.ACTIVE_AGR_CENTER = PAG1.CENTER
        AND PAA.ACTIVE_AGR_ID = PAG1.ID
        AND PAA.ACTIVE_AGR_SUBID = PAG1.SUBID)
WHERE
    (
        CCC.MISSINGPAYMENT = 1
        AND CCC.STARTDATE >= to_date(:date1)
        AND CCC.STARTDATE <= to_date(:date2)
        AND PE.SEX <> 'C'
        AND CCC.CENTER IN (:scope)
        AND CCC.CLOSED = 0
        AND CCC.CASHCOLLECTIONSERVICE IS NULL)